### ISSUE TITLE
Grant Application - ChainEducation

### ISSUE THREAD

**Issue by muskanmarwah1** [onflow/developer-grants#102]
# ChainEducation

# Grant category

Please select one:

- Educational material

# Description

ChainEducation is a decentralized platform where anyone can upgrade their web3 skills with hands-on tutorials.
<br />
They will be able to earn certificates as NFT once they complete a course.
<br />
The platform will also create their profile so that they can showcase it to the community.
<br />
They can add their projects and achievements too.
<br />
Educators can create their classrooms. They can upload as many courses in a classroom.
<br />
Students can get enrolled in a classroom.
<br />
For every achievement, they will earn achievement NFT.
<br />
Students can rate and review the courses too.

## Problem statement

- Target audience
  Users who want to get into web3 development are our target audience. Companies who wish to promote their technical product are welcome too. They can write a technical blog mentioning their product/service.
- Evidence for the need
 As of now, the information is completely disorganized. We want to organize this information so that anyone can access it easily. We will also be working on a powerful indexer, and all our blogs in our platform will be SEO optimized by default.

## Proposed solution

Our solution is to build a platform where an instructor can publish her blogs. As of now, we will be hacking **Ghost platform** to get started. We will be hosting this platform on our servers. Articles will be pushed inside our backend as well as IPFS.

## Impact

- Our tutorials will focus on Flow too. More and more developers can learn to build on top of the flow. Personally, our team will write a lot of articles on flow and will touch nearly all the products Flow ecosystem has.

# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

### Milestone 1

* **Estimated Duration:** 5 weeks 
* **Costs:** 10,000 USD

| Number | Deliverable | Specification | 
| ------------- | ------------- | ------------- |
| 0. | Creation of smart contracts using Solidity. | These smart contracts will be responsible for distributing tokens to users once they unlock and achievements. Also, they will be accountable for mint achievement, milestones, and course completion NFTs. Smart contracts will also store key attributes of a user profile. We will be using erc20 and erc721 smart contracts. Two more smart contracts would be required, one to store user information and another to send achievements to NFT who complete the course. |

### Milestone 2

* **Estimated Duration:** 3 weeks 
* **Costs:** 10,000 USD

| Number | Deliverable | Specification | 
| ------------- | ------------- | ------------- |
| 0. | UI development | We will be using **NextJS**, which is on top of **React**, to develop frontend of our educational platform. It will be served via Netlify. |
| 1. | Ghost platform development | We will use Ghost as our blog platform where instructors will write the blogs. |

### Milestone 3

* **Estimated Duration:** 3 weeks 
* **Costs:** 10,000 USD

| Number | Deliverable | Specification |
| ------------- | ------------- | ------------- |
| 0. | Database Modelling | Database modelling of all the first class entities.|
| 1. | API Design | High level API design.|
| 2. | User Authentication and Authorization | Building auth for the backend.|
| 3. | Course upload system | Development of course upload system and infra so that instructors can create and upload the course.|
| 4. | Student rating and review system | Development of review and rating system so that students can review a course.|
| 5. | API and Infrastructure | We are building our backend using Django which is written in **Python** due to it's strong ORM support. We will be using DRF(Django Rest Framework) to build the API layer.|

Total funding proposed: 30,000 USD
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Muskan Marwah | Smart Contract Developer | Worked as a flight attendent in indigo airlines close to 6 years. Now hacking inside Solidity and Rust. | marwahmuskan330@gmail.com |
| Aviraj Khare | Full-Stack Developer | Worked in Gojek for close to 2 and half years. I was in the Web3 space from 2016 to 2019. | avirajkhare00@gmail.com |

**Comment by chrisackermann** [comment]
Hi @muskanmarwah1, thanks so much for your proposal!  We're reviewing and will get back to you shortly.

**Comment by chrisackermann** [comment]
Hi @muskanmarwah1 - thanks again for submitting your proposal.

We've reviewed in detail and have decided to pass since the impact on the Flow developer ecosystem is not clear enough.

Feel free to reach out on Discord in case you have further questions: chrisa#6592
