### ISSUE TITLE
Infinity Wallet - A one-stop DeFi, NFT & Web3 Wallet, with first ever Web3 Browser!

### ISSUE THREAD

**Issue by InfinityWallet** [onflow/developer-grants#106]
# Infinity Wallet

# Grant category
Developer tools / services

# Description
Infinity Wallet is the first non-browser-extension, all-in-one non-custodial wallet ecosystem of its kind on desktop, supporting over 170,000 users within August. Providing a one-stop solution for seamless usability of DeFi, NFTs and easy cross-border payments, with a gateway to the world of Web3/DApps directly within the wallet’s Web3 browser. Fulfilling all a user's needs, while removing the complexities of decentralized finance and enabling economic freedom for everyone globally!

From day one, we have focused on enhancing and providing the best possible user experience and lowering the barrier to entry, to allow for streamlined and secure adoption of DeFi and Web3. Providing a world-class user experience with a seamless user interface, and a full spectrum of constantly growing features and services as a one-stop hub, delivering a more curated in-wallet experience. Making Infinity Wallet the complete solution for all crypto users’ needs, while making adoption and usage of cross-border payments, DeFi and Web3 easier than ever before.

Infinity Wallet is also the first desktop platform to provide users with access to the entire Web3 and DApp space without needing to leave their wallet, with the first Web3 browser and Web3/DApp store directly within the platform (https://docs.infinitywallet.io/infinity-wallet/features-and-notable-advancements/browser-less-dapps-and-web3). Finally removing the need to ever use unintuitive browser extension wallets again! Providing a far superior, safer and more natural user experience, with a range of unique advantages/benefits for users, DApps and chains alike, while enabling easier use and adoption.

We believe Flow will make a great addition to the Infinity Wallet and will be well received by both our and the Flow ecosystem’s users, which is why we have reached out to cooperate on this integration. As a multi-chain ecosystem we look to integrate and collaborate with chains that are innovating the space, to provide users (of Web3, DApps, DeFi, NFTs, etc.) with access to all of their crypto needs. Integrating chains across our wide range of features/services and supporting their web3 ecosystems (DApps & Tokens) is a consuming task however, hence why we can only integrate/support chains that are able to collaborate with us on supporting the integration via an integration grant.

A further introduction can also be found in our docs at[ https://docs.infinitywallet.io/](https://docs.infinitywallet.io/)

![Infinity Wallet](https://i.gyazo.com/e1a68afab6f7150a2baecacb06868a88.png)

You can download the live Infinity Wallet for desktop (with mobile in the works), supporting Windows, Linux and Mac : https://infinitywallet.io/download  

Link to our information deck, which will provide further information on the Infinity Wallet and its features and future plans.[ https://infinitywallet.io/docs/Infinity%20Wallet%20Deck.pdf](https://infinitywallet.io/docs/Infinity%20Wallet%20Deck.pdf)

Link to our docs which will explain more in-depth certain features and our roadmap: https://docs.infinitywallet.io/ and mobile sneak peak https://docs.infinitywallet.io/infinity-wallet/devices/mobile-wallet-sneak-peaks 

Link to more information along with a video on Browser-less Web3, allowing users to use any DApp directly within the Infinity Wallet, allowing for easier DApp discoverability/adoption:  https://docs.infinitywallet.io/infinity-wallet/features-and-notable-advancements/browser-less-dapps-and-web3

## Problem/Solution statement
The problem today is that while wallets are the most fundamental component required for usage and adoption of DeFi, Web3, crypto payments, a chain and its ecosystem, they are one of the least well developed applications in the crypto ecosystem. Wallets currently act mainly as an interface, serving primarily as a transaction signing layer, with very limited functionality or direct features/services/protocols (users generally have to search, find, learn and interact with many different applications and services), and are generally lacking in basic UX, while providing very unprofessional, hard to use and aesthetically poor user interfaces. This has been sufficient for the early adopters in crypto, however, for the next billion users to onboard to DeFi and Web3, a more curated and high quality user experience is required.

Infinity Wallet steps in to fill this need, as a one-stop hub for all payment, DeFi, NFT and Web3 activity. Providing a unique solution with a full spectrum of services, features and protocols in a premium platform, with a focus on delivering a seamless decentralized user experience and a user centric interface. Streamlining accessibility and lowering the barrier to entry, to allow for true adoption of DeFi, crypto payments & Web 3.0 globally.

Currently Flow greatly lacks a premium quality platform of our kind, delivering an all-in-one ecosystem that provides multiple unique services/protocols, along with a premium user interface and high end user experience that we deliver, which is generally lacking within most ecosystems today and holding back global adoption.

Additionally, as the first ever desktop Web3 browser, we bring a unique more natural user experience and value to any chain integrated when accessing DApps and Web3 (compared to browser-extensions), along with all our other unique features and services, hundreds of thousands of users and constantly growing user base.

## Impact
Infinity Wallet will benefit the Flow ecosystem and holders by providing a unique all-in-one wallet & ecosystem solution on Desktop (with mobile to come in the future), with a focus on premium quality. Delivering a seamless user experience and a user-centric interface, along with access to current and a wide range of constantly growing features/services. Providing Flow  access to the many advancements we have, bringing much needed value (infrastructure, features/services and a premium quality platform) to Flow.

Infinity Wallet will allow Flow and its ecosystem to be more easily adopted and used by the general public, in a unique crypto wallet, payment solution and Web3/DApp browser built for the masses, and used already by hundreds of thousands of users worldwide for easy cross-border payments, access to DeFi, NFTs and interacting with Web3/DApps directly within their wallet. As a one-stop platform for all users to directly access all their DeFi, Web3 and crypto needs, making adoption of the Flow ecosystem as easy and intuitive as possible and boosting awareness, usage and utility.

Below are some of the key features and services that chains are already benefiting from within Infinity Wallet and that could benefit and bring value to Flow:

- DeFi Wallet Solution;
![eth-wallet](https://user-images.githubusercontent.com/64919828/196939328-860eb632-d0bf-4920-be64-d72f4457740c.png)

- Portfolio and Analytics Monitoring/Dashboard;
![Portfolio](https://i.gyazo.com/72061265ce73936f53ad623a5bd507f8.png)

- Instant decentralized cross-border payments;
![wallet send amount](https://user-images.githubusercontent.com/64919828/196940156-f2d09991-f889-48a9-ba94-40dc6f56616d.png)

- Web3 browser and DApp store (One-click Connect to DApps, with the utmost discoverability and use of a chains’ ecosystem);
![DApps Store](https://i.gyazo.com/cb3413404fdff817e25b8d56d20af49c.png)
![Web3 Browser](https://i.gyazo.com/d5160e46f6048473e971b9e458c5a981.png)

- Cross-chain swap and bridge (Swap/Bridge between multiple supported chains);
![image](https://user-images.githubusercontent.com/64919828/196932419-0785e07c-e9c9-4236-bf52-3d64a147f551.png)

- NFT support to manage (view, send and receive) and trade NFTs;
![NFTs](https://i.gyazo.com/54988b611a034efc3e3d09ad4623446f.png)

- Advanced Transaction History and balance/value charts;
![Advanced Transactions](https://i.gyazo.com/7530eb3b49bedcf367a3ea506151954d.png)

- Custom Token Importing (Allowing any token to be imported, even if not default supported);
![image](https://user-images.githubusercontent.com/64919828/196932721-845babe3-b60d-418d-aff1-a59ea531defa.png)

For a more detailed look over our many current and future features/services please see our information deck available at https://infinitywallet.io/docs/Infinity%20Wallet%20Deck.pdf (pages 10-24 list core features/services and roadmap), or our docs here https://docs.infinitywallet.io/infinity-wallet/features-and-notable-advancements (detailing further information on core features/services and secondary features, as well as our roadmap)

# Milestones and funding
The goal of this grant would be the complete integration of Flow into Infinity Wallet, to allow users to easily interact with Flow and its ecosystem, while also providing access to a wide range of Infinity Wallet features/services/protocols that will support and drive utility and value to Flow. To provide unparalleled ease of use and adoption of Flow and access to a vast user base of over 170,000 users within August and growing, bringing constant free marketing, awareness and adoption.

We would be requesting $160,000 in FLOW (or alternatively USDC/USDT) as a single milestone, deliverable after the live launch of FLOW within the Infinity Wallet.

The timeline for integration/development/testing would take around 8 weeks from start to live launch. While ongoing expenses (future developments/features, maintenance, live chain support, ecosystem support, ongoing operational costs, marketing, and etc.) will be covered at our own expense, providing Flow with access to constant free resources and users.

We would negate all risk for FLOW by operating via a single milestone for the grant, which would be the complete integration and live launch of FLOW in the Infinity Wallet. This expedites the process and allows us to focus on fully completing the developments and launch, before receiving any payment.

While we operate via a single milestone, you can find our internal milestones/deliverables below to give a deeper insight into our process and to help describe what to expect:

**Milestone 1 -**
- Flow chain integration and core functions (balance tracking, send, receive, etc);
- Complete transaction history with advanced information;
- Integrate portfolio & analytics support;
- Ability to import/remove tokens;

**Milestone 2 -**
- Web3 Browser integration/development to allow for seamless one-click connecting to FLOW Web3 projects and DApps;
- Web3/DApp Store to allow for easy discoverability and adoption of FLOW ecosystem projects;
- Send/Receive NFTs;
- NFT Gallery to view all NFTs;
- Individual NFT viewing with stats and easy trading;

**Milestone 3 -**
- Cross-chain swap support for FLOW (Allowing users to directly onboard to FLOW from different chains “BTC, ETH, BSC and etc” within a single click);
- Contact/Address book;
- Payment requests;
- Desktop drag and drop QR scan;
- Live Market stats;
- Price Alerts;

**Milestone 4 -** 
- Internal testing of the integration;
- Internal auditing of the integration developments;
- Push the live release with the FLOW integration;
- Support FLOW as a default chain;
- Announcements across all social channels;
- Creation of a custom FLOW web page on the website;
- Announcement in the wallet of the integration of FLOW;

**Ecosystem Support**
- Collaborate with FLOW ecosystem projects on direct integration into the Infinity Wallet;
- Waive our usual yearly DApp fee that we would generally charge ecosystem projects (usually $5,000 a project, as an example 20 DApp integrations would usually be $100,000 in yearly fees.) to be integrated into the Infinity Wallet, we will integrate FLOW Web3 Project and DApps for free for the first year. Allowing them to be freely integrated into the Infinity Wallet Web3 Browser and DApp store, driving further awareness and growth to the Flow Ecosystem
- Integrate top FLOW tokens as default supported tokens, removing the need for users to manually import tokens;

On completion we will have free ongoing development support for FLOW into future available features/services on a case by case basis, as well as the free integration into our unique user focused mobile launch. Along with continued ecosystem collaboration/support for FLOW in the Infinity Wallet.

# Team
Information on our team, location, experience and goals can be found at the following link https://docs.google.com/document/d/19L9fGt241UVQlXxUtbx7BqkhCFxS6DzlFYu7svtUCi4/edit?usp=sharing 

# Contact Information
Contact Email: partner@infinitywallet.io
Telegram Contact: https://t.me/aron_infinity
 
 **Note**
We created this application as it seems the original application (https://github.com/onflow/developer-grants/issues/86) that we have now closed was missed along with other applicant's applications that were submitted at the same time, and we had not heard back after 1.5 months that the application was being reviewed as others had.

**Comment by chrisackermann** [comment]
@InfinityWallet Thanks for opening a new issue for your proposal!  I'm going to close this one out since I've re-opened #86 to keep that as the source of truth.
