### ISSUE TITLE
Grant to "UNCHAIN" for increasing the number of developers who can develop dApps on the Flow.

### ISSUE THREAD

**Issue by nack3827** [onflow/developer-grants#109]
# <Project name>
The Grant to "UNCHAIN" for increasing the number of developers who can develop dApps on the Flow.

# Grant category
Please select one:
- Educational material

# Description
## 🚀 Background
UNCHAIN is a community for engineers to learn web3 through practical development such as  NFT creation, dApps building, etc, created by [[shiftbase, inc.](https://shiftbase.xyz/)](https://shiftbase.xyz/)  This is the first educational developer program in Japan dedicated to web3.

UNCHAIN was established to solve the problem of a lack of information for Japanese engineers to practice web3 development. We are committed to contribute to the development of web3 technology in Japan by providing more people with quality information and equipping them with the right tools to give shape to their ideas.

### For this purpose, we will do the two approaches below:
**1️⃣ Making the learning content**
**Making learning content like the below for community members and converting web2 engineers to dApp developers on the Flow.**

**2️⃣ Distributing the grant to community members**
**Distributing the grant from  to community members who released the dapp on the XRPL on a first-come-first-served basis through the learning content.**

### Budget :
We request the budget for the Grant : $5K-6K worth of FLOW.

**How to use the budget?**
- Distributing $100 worth of FLOW to each community member who actually released the dapp on the Flow.
- The Grant will be distributed on a first-come-first-served basis through hosting the learning content created in  1️⃣ .

**Planned Release Date :**
We are planning to release the content regarding Flow at least one content around Dec　2022

## 👋  Past performance and track record
- web3 developer community with over 1,500 entries
    - Entry form: [https://www.unchain.tech/](https://www.unchain.tech/)
- Provide 18 contents to experience dApp development on a public blockchain
    - List of learning contents: [https://www.unchain.tech/learn]
    - supported networks: Astar, Avalanche, Ethereum, ICP, NEAR, Polygon, Solana        
　- More than 400 NFTs were issued to prove the development history of web3 products
    - OpenSea: [https://opensea.io/collection/unchain-passport]
- Provide our community with a P2P learning ecosystem for learning the web3 technology stack.

## 📚 Learning-contents
We provide project-based learning content to the community for free and open source. After joining the community, members will be expected to catch up and deepen their understanding of the web3 technology stack, such as Solidity, Rust, React, Typescript, Alchemy, and vercel.

### **[Overview of project-based learning contents]**
We provide 18 contents to experience dApp development for community members on a public blockchain.

### **[Details of project-based learning content]**
The content has several sections, from setting up a developing environment to hosting on a blockchain network.

### [**Proving one’s learning history with NFTs]**
A unique NFT will be issued as a learning certificate to community members who have completed the learning content.
  
# Team
The UNCHAIN developer community is managed by founders of  [[shiftbase Inc](https://www.shiftbase.xyz/en#)](https://www.shiftbase.xyz/en#).

🎷 [Yusuke Nakano](https://www.linkedin.com/in/yusuke-nakano-b47bba118/) / Co-founder & CEO of shiftbase Inc.

Yusuke moved to the Philippines at the age of 22 to launch an education business. After graduating from Hosei University, he joined Digital Garage, Inc. and was in charge of overseas expansion of CRM media business for financial institutions. 2018, he joined Empath, Inc. and promoted business development as COO, then co-founded shiftbase, inc.

What he wants to achieve in web3: to build a "learn-to-earn" ecosystem where all people, regardless of their status, geographic boundaries, or economic base, have equal access to quality education and support networks.

😊 [Yuki Shimura](https://www.linkedin.com/in/yuki-shimura-081738129/) / Co-founder & CCO of shiftbase Inc.

Yuki moved to the U.S. at the age of 16, graduated from the University of California, Los Angeles (UCLA), and spent two years at Harvard University doing interdisciplinary research in social psychology and brain science. In October 2020, he joined Empath, Inc. as Research Director, and in February 2022, he founded shiftbase, Inc. In February 2022, he will establish shiftbase, inc.

What she wants to achieve in web3: to create a protocol to donate a portion of the proceeds to housing assistance for young people in need of financial and social support, and eventually run a home for children without parents.

🕶 [Kenta Takase](https://www.linkedin.com/in/%E5%85%BC%E5%A4%AA-%E9%AB%98%E7%80%AC-a924b91a9/) / Co-founder & CSO of shiftbase Inc.

After graduating from Kindai University, Kenta was in charge of the back-office DX promotion project at the beauty appliance manufacturer "Ya-man", and experienced the launch of the new IT system department. He left the company to start an agricultural company and develop a D2C platform, and later co-founded shiftbase, inc.

What he wants to achieve in web3: to build a business model in the web3 domain that will enable a new generation of Japanese to be active globally.

🎧 [Sho Hihara](https://www.akxra.art/) / Co-founder & CTO of shiftbase Inc.

Sho moved to Canada at the age of 17 and received an IB Diploma from Lester B. Pearson College UWC. He received a scholarship from the Masayoshi Son Memorial Foundation to attend the University of Minerva, and has moved around the world while studying Computer Science. He is a full-stack engineer specializing in machine learning and blockchain development, and co-founder of shiftbase, inc.

What he wants to achieve in web3: to empower human ownership and decision-making processes on the Internet, creating a space where people can respect and appreciate culture and technology.

**Comment by chrisackermann** [comment]
Hi @nack3827 - thanks for sharing your proposal!  We will review and get back to you shortly.

**Comment by nack3827** [comment]
Hi @chrisackermann -thanks for your reply. I hope our proposals can contribute to the developer community for Flow ecosystem in Japan!

**Comment by Aliserag** [comment]
We appreciate your proposal and taking the time to fill it out. Given the time since this has been submitted I'm closing this down, please reach out to me if you'd like to share what you're working on now and explore potential opportunities ali.serag@flowfoundation.org.
