### ISSUE TITLE
 Footprint Analytics Grant Application

### ISSUE THREAD

**Issue by leoliew** [onflow/developer-grants#110]
# Footprint Analytics

# Grant category

Developer tools / services

# Description
Footprint Analytics provides API and visualization tools to uncover and visualize data across the blockchain, including NFT and GameFi data. It currently collects, parses and cleans data from 19 chains into structured and semantic tables. It lets users build charts and dashboards using a no-coding drag-and-drop interface as well as with SQL. 

## Problem statement

- Target audience: 
Flow team, developer and user on Flow. 
People who follow web3 development, including analysts, institutions, and developers.

- Evidence for the need
People believe that the data reflects the fact. Ethereum proves this. There are many [Ethereum Charts & Statistics](https://etherscan.io/charts) on etherscan that vividly represent the development of Ethereum. We believe Flow also needs to add these data to let the community feel the rapid development of Flow. Also the data can help analysts, writers to contribute contents about Flow by providing analysis dashboards, reports or articles, all of which will make Flow be widely known.

## Proposed solution

Our main target is to provide a cross-chain data analytics service.  Our data for Solana shows our ability to index Non-EVM compatible chains and this experience will help with our data indexing on Flow.
Another strategic move is NFT, which is growing fast on Flow. We have already indexed data of 3 chains and 13 NFT Marketplaces. We believe we can contribute to Flow's NFT ecosystem by providing data support for NFT projects.

The Detailed solution is written below:
- Provide the raw, full time period of data of the Flow chain.
- Parse the protocols on the Flow chain, starting with NFT.
- Provide abstract, normalized data and metrics. Create a "de facto standard" to simplify analysis across multiple protocols or chains.
- Provide the powerful analytics tool for flow users, analysts and developers to explore Flow data in a deeper level.
- Co-organize an online hackathon to attract analysts, developers to use and contribute to Flow's on-chain data analysis and insight.

## Impact

The benefits will be in the following 3 aspects:

1. Provide the Flow team with data on the ecosystem in order to monitor the development of the ecosystem.

- Data on user and developer participation, number of users, activity level, etc. This is good for discovering potential projects, monitoring the condition of the ecosystem, providing support and backing for the developers on the chain.

- Comparison between Flow chain and other chains to understand the situation of competing chains.

2. Providing data solutions for the developers on Flow 

- Help them understand project data so that they can better operate the project

- Attract more developers to build.

3. Brand awareness improvement: Data can show the strength and development of Flow and attract more developers and users

- With dashboards and reports, we can spread the word around about Flow's progress.
- Footprint can provide support on media channels: Columns on several million level media sites: [Cryptoslate ](https://cryptoslate.com/author/footprint-analytics/)and [CoinMarketCap](https://coinmarketcap.com/alexandria/author/footprint-analytics). Our contens could be reprinted by yahoo finance and many other media. Also other tens of social media platforms.

# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1- MVP - Synchronizing Flow Nodes to Footprint  | Flow full time period data on Footprint database | 1 week  | - | 2,000           |
|  2- MVP - Indexing Flow chain raw data   | Flow transactions and token_transfer data are available on Footprint | 1 weeks  | - | 3,000           |
| 3 - MVP - Flow chain data online on Footprint    | Flow chain overview dashboard | 1 week  | - | 3,000           |
| 4 - Adoption - Flow chain NFT data on Footprint   | Flow chain NFT overview dashboard & structured table | 1 month  | - | 8,000          |
| 5 - Adoption - Flow chain marketplace domain data in Footprint   |Flow chain Marketplace overview dashboard & structured table | 1 month  | - | 8,000          |
| 6 - Adoption - Flow chain GameFi data on Footprint   |Flow chain GameFi overview dashboard & structured table | 1 month  | - | 8,000          |
| 7 - Maintenance   |Resolving issues and fixing bugs | 6 month  | Contracts are missed, need Flow team to help contact developers | 10,000          |
| 8 - Hackathon Event | Co-organize an online hackathon to attract analysts, developers contribute to Flow | 1 month  | - | 20,000          |

Total funding proposed:  $62,000 
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Navy | CEO | CEO and Co-founder of Footprint Analytics. Full-stack developer and also a blockchain data analytics. Open Source Contributor on GitHub, which has over 32k stars| navy@footprint.network |

**Comment by chrisackermann** [comment]
Hi @leoliew - thanks so much for your proposal!  We will review and get back to you shortly.

**Comment by chrisackermann** [comment]
Hi @leoliew, happy new year!  

Thanks for your patience and for taking the time to submit your proposal.  We've reviewed in detail and have decided to pass since the impact on critical needs for the Flow developer ecosystem is not clear enough.

Feel free to reach out on Discord in case you have further questions: chrisa#6592
