### ISSUE TITLE
MAGNETIQ, Enabling Utility NFTs - Flow Developer Grant

### ISSUE THREAD

**Issue by ProfessorStam** [onflow/developer-grants#111]
# MAGNETIQ

# Grant category

Please select one:

Developer tools / services

# Description

MAGNETIQ is a platform that facilitates the creation, purchase, and activation of digital memberships by combining a familiar online experience with an advanced web3 back-end. Built on Flow, MAGNETIQ offers builders (e.g. brands, independent NFT projects) simple, no-code tools to create and maintain web3-enabled digital memberships that provide utility to their holders. Consumers are met with a familiar online experience for trading and interacting with their memberships.

In the process of development, we crystallized a pathway toward additional functionality that benefits the Flow ecosystem far more broadly. Specifically, we are building tools to integrate and activate “Magnets” as the functional conduit that delivers new utility layered onto historically more traditional “collectible” NFT projects. In our ecosystem, Magnets are what we call digital memberships, which are NFTs on the back-end. Along with starting new communities, Magnets can re-engage and reactivate communities formed around historical projects where the buzz has gone cold, roadmap has concluded, or the team may have been under-delivering.

Ultimately, we plan to create an open source system where any developer can create new tools that provide further activations for Magnet membership programs.  Developers of tools that go live will earn royalties for application usage. This will further incentivize new participants to join the Flow development ecosystem.

# Problem statement

## Target audience

- For what we call the “Legacy Project Level-Up,” anyone either already within the Flow ecosystem who has already launched a project in the space (perhaps with a light roadmap or low/no utility), or plans to to launch an NFT project, requiring tooling to quickly and easily deliver on promised utility to their NFT community and holders.
- For the “MAGNETIQ Platform,” the target audience is traditional, web2 brands and consumers, seeking to connect with each other through membership programs (as laid out more fully in our materials). Since this would onboard and convert so many new users, there would be great demand for a consistent, predictable experience that could be replicated across other projects in the Flow ecosystem.  These programs would be started from scratch on MAGNETIQ.
- For developers looking to create applications that further allow the activation of utility for Magnet membership programs.

## Evidence for the need

In the web3 space, we have seen countless examples of NFT projects and communities launching with roadmaps promising utility, but oftentimes falling flat or taking a long period of time to deliver.  Most projects have to take funds collected at drop to hire development teams and build each mechanism required to deliver promised utility to holders. This is very operationally intensive and often leads to prolonged delivery (or none at all), leading communities to get restless and either stop interacting with projects, or walk away from them entirely. These brands need to re-engage their audience, and start quickly and easily making good on their promises (hence our labeling it, the “Legacy Project Level-Up”).

In another vein, brands looking to build in web3 do not yet have a high enough level of sophistication and understanding to develop projects for themselves and regularly seek white-labeled solutions. Brands know they need to enter the space in the interest of remaining competitive, but relatedly, to forge new and deeper relationships with their customers. Web3 is an intimidating space for oft-bureaucratic organizations to navigate; and therefore, in order to deliver on promises of new projects borne out of more forward-thinking, experimental brands (that largely still operate natively in the web2 space), easy, no code tools are required to help them bring creative vision and utility to the space while minimizing the drawbacks of a still-maturing web3 infrastructure.

## Proposed solution

We are building a no-code tool with integrations for developers and projects on Flow to significantly reduce the time to market for applying activations to their current NFTs.

The first development track, the Legacy Program Level-Up solution allows project developers to connect existing projects and tokens built on Flow, to MAGNETIQ, to facilitate delivery of utility to their holders. Along with creation, we will be providing a full back-end dashboard to monitor progress, create additional ad hoc activations, and provide analytics on interaction from holders.

The second development track, the “MAGNETIQ Platform”, provides a seamless, dual-facing platform where brands meet their consumers and consumers get closer to their favorite brands. It is a simple, no-code solution to allow for easy creation of utility-based membership programs, paired with a consumer-friendly online experience for collecting utility and interacting with the memberships. The MAGNETIQ Platform allows for a brand to create an NFT membership program from scratch and sell it to consumers, all the while collecting valuable first-party data and insights based on both interactions with the smart contract and qualitative feedback from the tight-knit community. 

Ultimately, the system will be open source, where any developer can create new tools that provide further activations for programs from both development tracks.  Developers of tools that go live will earn royalties for application usage.

For both development tracks, we will be using Dapper Wallet as our primary wallet and payment solution.  Every NFT minted or purchased will initially be housed in a Dapper Wallet and presented to the user on a front-end MAGNETIQ-designed user profile.

See our pitch deck linked (https://docsend.com/view/qn3iandqy3hpf3s8) for further explanation and detailed design layouts and functionality.  

A demo of our initial prototype can be found linked (https://www.loom.com/share/46b5b0e8091a489e927c3a212624fc84).

# Impact

## In what ways does this benefit the broader Flow developer ecosystem?

Our platform will become a tool for projects on Flow to connect with so they can easily start to push utility through to their holders and users.  Instead of every project having to create bespoke applications for delivering utility, we will have mechanisms to read to the chain and provide their holders with NFTs which act as a key to claiming benefits.  We also seek to bring additional brands and users to Flow and Dapper Wallet, further helping to seed the ecosystem for future projects!

This enablement of tools for utilization of the NFTs makes it so they are not just traded but are used for a broader purpose. Our tool will significantly reduce the development effort for the brands to release the Magnet and correspondingly ensure the NFT utilization. In the future we would enable any NFT on the Flow blockchain to be converted to a utility-based NFT through a seamless integration. 

For developers on Flow, the open source system for the creation of new tooling provides an infrastructure base (the MAGNETIQ platform) enabling the ability to create bespoke new applications for membership program enablement.  Developers of tools that go live will also earn royalties for application usage.

# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| Onboarding|Creating the base platform for user and projects to onboard | 8wks | Delivery risk if there is a delay in requirements or excess bugs | $100K |
| MVP | Projects can assign applications to the NFT | 8wks | Delivery risk if there is a delay in requirements or excess bugs | $100K |
| Alpha Launch - MAGNETIQ | Formal public launch where projects can come and originate Flow NFTs and access utility features | 12wks | Risk the platform does not get enough brands and delays launch | $150K |
| Beta Launch - Legacy Project Level-Up | Other projects will be able to migrate to the platform, this is where we will open the platform to integrate with rest of the flow system | 24wks | Unseen complications in integrating with other projects on Flow | $100K |
| Maintenance | Resolving issues and fixing bugs and improving the platform | Ongoing | - | $50K |

Total funding proposed: <$500K>
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Tyler Stambaugh | Product Manager | 12+ years of experience as a business and technology consultant, designing and driving large scale technology development and integration. | tyler@magnetiq.xyz |
| Shashank Singla | Head of Engineering | 12+ years of experience in creating products, 2 exits in AI in US & India. Ex Goldman Sachs, IIT Delhi. | shashank.singla@hcode.tech |
| Harshit Garg | Program Manager | 6+ years of experience in program management, driving large scale digital transformation projects and worked with multiple startups | harshit.garg@hcode.tech |
| Gurdeep Singh | Blockchain | 5+ years of experience in development and 2+ years of experience in blockchain development ( solidity, cadence, polygon) | gurdeep.singh@hcode.tech |
| Jayant Pahuja| Front End | 3+ year of experience in frontend development  and 1 year as full stack( React, tailwind, | jayant.pahuja@hcode.tech |
| Ashish Gahlawat | Back End | 2+ years of experience | ashish.gahlawat@hcode.tech |
| Shantanu Bahadure | Designer | 5+ years of experience in UI/UX along with 2 year experience in graphics designing. | shantanu.bahadure@hcode.tech |

**Comment by chrisackermann** [comment]
Hey @ProfessorStam, thanks for checking back in!  We're working through our backlog and will have feedback in the next few days.  Thanks for your patience here!

**Comment by ProfessorStam** [comment]
Hi @chrisackermann, we did a slight addition to the grant proposal to highlight some of our plans of creating an open ecosystem for tool creation down the road.  Just giving you a heads up on some of the edits!

**Comment by chrisackermann** [comment]
Hi @ProfessorStam, thanks for your patience! 

The scope of this project is a bit large and I'd love to see if we could narrow the scope quite a bit to focus on delivering an MVP that could prove out some of the hypotheses around the impact on the Flow developer ecosystem.  It looks like the current proposal is that you're looking more for venture funding for the overall business/platform, so wanted to look more closely at the open source part of the product that you're building, since that will have the most potential for impact for the developer ecosystem.  Obviously, it's great if you build your primary product that will drive your business, but that just sits a bit outside of our focus with the program.

Please let me know if it makes sense to speak live to discuss some more and I'll reach out to find some time to chat.

**Comment by ProfessorStam** [comment]
@chrisackermann That sounds really great.  We would love to have a live conversation with you to discuss the grant, scope and how it all comes together.  We have also been interacting with other parts of the Flow ecosystem and Dapper partners, so would be great to also fill you in on how all of those are going so we can see how everything fits.

My email is tyler@magnetiq.xyz.  Let's connect there to coordinate time to meet!

**Comment by ProfessorStam** [comment]
Hey @chrisackermann, hope all is well.  Is there an email I can reach for connection to set up time with you to talk more about the scope of the MAGNETIQ grant application?  My email is tyler@magnetiq.xyz if its easier for you to reach out.

**Comment by Aliserag** [comment]
We appreciate your proposal and taking the time to fill it out. Given that things are stale with this grant submitted several years back I'm sure much of it is no longer relevant, closing it down. Don't hesitate to reach out at ali.serag@flowfoundation.org if you want to discuss potential upcoming synergies.
