### ISSUE TITLE
CLUBS

### ISSUE THREAD

**Issue by MaxMenshikov** [onflow/developer-grants#112]
# Grant category

Please select one:
Developer tools / DAO tooling/Educational material

# Core product - the 1st SocialFi metaverse with Talk & Earn monetization mode and an excellent way to Web3 from Web2 mechanics. We help to bring the communities to Web3 as an upgrade of the level of getting new knowledge, new business models, and managing of community with the engagement of each member from a passive role to the maximum contribution and reward with the tokens, NFTs, and many more.

## Problem statement
Creator economy development and the rapid evolution of metaverse concepts lead to significant changes in the relationship between creators and fans. Gen-Z doesn't want to communicate in the old way and expects new solutions from SocialFi. Content creators, bloggers, and artists want to own a community with their fans, receive a stable income from fans, customize and use web3 in relationships with fans, and be independent of the algorithms of web2 platforms. Gen-Z fans and followers want to be entertained, be social and involved, earn, own, and trade digital assets, get heart-to-heart talks with creators, and co-create content. 

- Target audience
9000 creators and 12M of their fans
- Evidence for the need
Lack of such solutions in Web3, there are only Web2 solutions with not-so-good functionality

## Proposed solution
We have a strong and very growing community, there are 1500+ creators/influencers with overall more than 160 000 000 of fans/community members. Our aim so to grow up to 9000+ creators/influencers with more than 12M+ MAU  of fans/community members in 2023. 
Our aim is to build a growing, stable, and very high level of engagement, in a few communities in the Flow ecosystem.

## Impact
We believe that we can give a lot of value to the Polygon ecosystem in a number of new engaged users, the revenue of Flow-based projects, dozens of thousands of new wallets in Flow, and priceless knowledge and experience from our managed communities. More experienced people can create new DAOs, and new projects, write code in Flow-based projects and develop new sustainable and effective products that make mass crypto adoption more real. 
Integrations - besides bringing value in general into the Flow ecosystem, we’re planning to work with all the relevant to us active Flow-based projects. 

- In what ways does this benefit the broader Flow developer ecosystem?
With our DAOs, we'll bring dozens of thousands of developers and will teach a lot of newcomers in Web3, check the numbers in milestones below.

# Milestones and funding
December 2022 - the first few integrations with Flow ecosystem products that we mentioned above and the start of the first 10 DAOs with 1000+ members each of them with the aim to learn the Web2 users to be active, well-skilled, and helpful members of the community of DAO with monthly payment from them on a start and later also on a monthly basis some rewards of them in form of tokens, payrolls, NFTs, etc
 
February 2023 - we’re integrated with the most suitable for us solutions in Flow, a total of started DAOs with 1000+ members is around 30+. We’re launching a boot camp for the most active members of our DAOs to make them influencers and help them to launch their own new DAOs in the Flow ecosystem. 
 
April 2023 - we’re integrating with the top relevant projects in Flow and other top NFT marketplaces for uniting auditories in Flow and enriching them by sharing an experience of our influencers and DAO members,  a total of started DAOs with 1000+ members is around 50+. We’re launching an accelerator program with other partners in the Flow ecosystem and 1st batch of a program “Build and develop your Flow DAO” on basis of our collected unique experience of using all the instruments that helped us to build and raise our first DAOs in Flow on our start. 

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - MVP   | Smart Contract | 6 weeks  | - | 15000         |
| X - Adoption   | 20 team using this project | 10 weeks  | - | 15000           |
| X - Maintenance   | Resolving issuing and fixing bugs | 4 months  | - | 25000           |

Total funding proposed: <55000 USD>
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
Max Menshikov, CEO: 16 years of entrepreneurial background. Startup Builder in corporate accelerator programs.
https://www.linkedin.com/in/maximmenshikov/

Pavel Voronin, CTO: 12 years in tech and product management.
https://www.linkedin.com/in/pavelvoronin/

Magdalina Bolotova, CMO: 17 years in strategic marketing Author of a methodology for building and managing communities. 
https://www.linkedin.com/in/magdalina-bolotova/

**Comment by chrisackermann** [comment]
Hi @MaxMenshikov - thanks for submitting your proposal!  We'll review and get back to you soon.

**Comment by MaxMenshikov** [comment]
Hi Chris,
I hope we gave all the necessary information in the application. If you
need more information about CLUBS let me know.

I look forward to hearing from you.

Best
Max

вт, 1 нояб. 2022 г. в 15:21, Chris Ackermann ***@***.***>:

**Comment by chrisackermann** [comment]
Hi @MaxMenshikov, thanks for your patience and taking the time to share your proposal here!

It's a bit unclear in terms of the specific solution that you are proposing here.  It sounds like you have a community of people on your platform, but could you please share more specific details on what your product/platform is and more specifics of how it will leverage Flow?

It's important that we get much more specific details as to what you're proposing to build through this grant and how it directly addresses pain points/gaps for the broader Flow ecosystem.   Thanks!

**Comment by alxflw** [comment]
@MaxMenshikov I'm closing this proposal due to inactivity. Please reopen with a response to the previous question if you want to proceed. thanks!
