### ISSUE TITLE
Flow Educational Video Encyclopedia on YouTube - Phase 1

### ISSUE THREAD

**Issue by ThisIsCodeXpert** [onflow/developer-grants#114]
# Flow Educational Video Encyclopedia on YouTube - Phase 1

# Grant category

Please select one:

- Educational material

# Description
Creation of one-stop platform for video based Flow educational content on YouTube which includes all Flow SDKs, libraries, Cadence language reference as well as real life examples tutorial series.

## Problem statement
YouTube is one of the major platform for web3 developers who want to learn about the technology. Flow doesn't have a good presence on YouTube to catch these developers. Even though there is some Flow educational material on YouTube, it doesn't have good audience as expected.

- Target audience
Thousands of developers who are eager to learn about web3.

## Proposed solution
We would like to create quality Flow educational content on YouTube and advertise it to the target audience. We propose creating following tutorial series on YouTube :

**Phase 1 - Real life examples of Flow**
* [Flow NFT DApp Tutorial Series](https://youtube.com/playlist?list=PLL5pYVd8AWtStx6jrAKKgJPjEznpqYbJh)
* Flow Fungible Tokens Creation Tutorial Series
* Flow Voting Smart Contract Creation Tutorial Series

**Phase 2 - References tutorial series**
* Flow Javascript SDK (FCL) Tutorial Series (Part -1/2/3)
* Build Smart Contracts on Flow With Cadence (Part - 1/2/3)
* Flow Command Line Interface (CLI) Tutorial Series
* Flow Go SDK Tutorial Series

In this proposal, we are applying only for Phase-1 grant.

Each tutorial series creation will be divided into two different parts : 1. Creation & Launch of series; 2. PR campaigns & advertising.
Each tutorial series will consist of 10-12 videos, each 8-12 minutes long.

## Impact

- At the end of this project we expect at least 75K-80K unique targeted developer audience.
- From which at least 4000-6000 (5%-7%) will be regular Flow content viewers and developers.
- YouTube web3 channels have growing audience which  will keep impacting Flow ecosystem in the future as well.

# Milestones and funding (Phase 1)

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1.1 - [Flow NFT DApp Tutorial Series](https://youtube.com/playlist?list=PLL5pYVd8AWtStx6jrAKKgJPjEznpqYbJh)   | Video series explaining creation of NFT smart contract and simple web3 integration | 0 days  | - | Free           |
| 1.2 - Flow NFT DApp Tutorial Series PR campaign   | Flow NFT DApp Tutorial Series will be advertised through various sources to get at least 25K-30K unique viewers. Budget will be spent for 1 month long period. Expected 25K-30K total views. (Around 1K viewers/day) | 7 days  | - | 1000           |
| 2.1 - Flow Fungible Tokens Creation Tutorial Series  | Video series will closely follow this example : https://developers.flow.com/cadence/tutorial/06-fungible-tokens | 10 days  | - | 750           |
| 2.2 - Flow Fungible Tokens Creation Tutorial Series PR campaign  | Flow Fungible Tokens Creation Tutorial Series will be advertised through various sources to get at least 25K-30K unique viewers. Budget will be spent for 1 month long period. Expected 25K-30K total views.  (Around 1K viewers/day) | 7 days  | - | 1000           |
| 3.1 - Flow Voting Smart Contract Creation Tutorial Series  | Video series will closely follow this example : https://developers.flow.com/cadence/tutorial/09-voting | 10 days  | - | 750           |
| 3.2 - Flow Voting Smart Contract Creation Tutorial Series PR campaign  | Flow Fungible Tokens Creation Tutorial Series will be advertised through various sources to get at least 25K-30K unique viewers. Budget will be spent for 1 month long period.  Expected 25K-30K total views. (Around 1K viewers/day) | 7 days  | - | 1000           |

Total funding proposed: 4500 USD 
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Krishna | Content creator | Owner of [CodeXpert](http://youtube.com/@CodeXpert) | officialcodexpert@gmail.com |

# Our previous collaboration
We were official community developers for Tron blockchain from 2018-2020. In that period, we created following tutorial series for Tron which is still the most popular educational source for Tron developers on YouTube with like/dislike rate of around 96%.
- [Best Tron (TRX) DApp Tutorial Series for Beginners](https://youtube.com/playlist?list=PLL5pYVd8AWtRDnTTKWzPpFcBT9nrPCQt6)
- [Create Tron (TRX) TRC20 Token - Tutorial Series](https://youtube.com/playlist?list=PLL5pYVd8AWtSh7lagrmq0G905yEcFWbow)
- [Tron (TRX) Dice Game DApp - Tutorial Series](https://youtube.com/playlist?list=PLL5pYVd8AWtTZAQFE_RBmqmAXOsWf707f)
- [Best Tron (TRX) Smart Contract beginner tutorial series](https://youtube.com/playlist?list=PLL5pYVd8AWtRTto_pFBxFFhG-S5dqC_O6)
- [Exclusive Interview With Tron Executive - Is Tron ‘The Ethereum Killer’ ?](https://youtu.be/C1Oz_PIORC4)

**Comment by ThisIsCodeXpert** [comment]
@chrisackermann Thanks for responding. Please let me know if you need any more information. Looking forward to it! :-)

**Comment by ThisIsCodeXpert** [comment]
@chrisackermann Is it possible to change the content of proposal? Actually I would like to add one more course here : Android application development using Flow blockchain. I think that will be really helpful for the developers. Thanks! :-)

**Comment by chrisackermann** [comment]
@ThisIsCodeXpert Sure thing, please go ahead and update!

**Comment by ThisIsCodeXpert** [comment]
@chrisackermann Thanks! I reached out to ChainSafe and Thirdweb teams yesterday and they told me they are still working on creating Flow based Unity3D SDKs. So For now, I think we have to wait a bit for android tutorials.

**Comment by ThisIsCodeXpert** [comment]
@chrisackermann Great news! Thanks a lot for trusting CodeXpert. I am very much excited to be a part of Flow team. Will do my best to meet the expectations. Looking forward for next steps..! :-)

Happy new year to you too!

**Comment by ThisIsCodeXpert** [comment]
@chrisackermann I was traveling last week but now I am back to my workplace and ready to start working on this project. Please let me know the next steps. Thanks again for giving us the opportunity to work with Flow team! :-)

**Comment by ThisIsCodeXpert** [comment]
Hi,

As promised above, I have completed all of the above milestones. I am listing the tutorial series links below : 

- Flow NFT DApp Tutorial Series : https://youtube.com/playlist?list=PLL5pYVd8AWtStx6jrAKKgJPjEznpqYbJh
- Flow Fungible Tokens Tutorial Series : https://youtube.com/playlist?list=PLL5pYVd8AWtRaVaOXUncz3Xzo4oRgblm4
- Flow Voting Smart Contract Tutorial Series : https://youtube.com/playlist?list=PLL5pYVd8AWtRVxHePnTEIFB3Y5QeHmwrO

I have also raised another proposal as I had written in this proposal itself, which will be part 2 of the Flow educational video encyclopaedia. Link here : https://github.com/onflow/developer-grants/issues/175

Looking forward to it!

Thanks! :-)

**Comment by ThisIsCodeXpert** [comment]
Hi Chris,

It's great connecting with you again.

I hope this email finds you well. I’m Krishna, CEO of VAKX, an IIT
Kharagpur alumni with previous experience at CERN. I’m excited to introduce
you to our newly launched startup, VAKX.

We specialize in providing AI-powered assistants designed to enhance open
documentation by delivering instant, contextual answers to users. This
solution is crucial in addressing the problem of navigating complex
documentation and reducing support queries.

One of our clients, Dapp World <https://dapp-world.com/>, has experienced
significant improvements in customer satisfaction and conversions since
using our AI assistant. *Priced at only $10*, it’s a cost-effective
solution with immense value.

To give you a taste of our platform, we offer free initial credits for
testing. You can explore the VAKX AI assistant and see it in action by
visiting our landing page <https://vakx.io/> and checking out the Integrate
VAKChat section. *Integration is straightforward—just 3 lines of
code!* Additionally,
if you deploy your AI assistant by the end of September 2024, we will
handle the entire onboarding process for you, so you won’t have to worry
about anything.

For a quick overview, you can watch our 5-minute YouTube demo video
<https://youtu.be/thsIbPIn3Dw> and review the attached brochure. If you’d
like a personalized demo, I’d be delighted to arrange a time that suits
you. Please use this Calendly link <https://calendly.com/krishna-vakx/30min> to
book a slot.

You can discover how VAKX AI assistant is enhancing user experiences at Dapp
World <https://dapp-world.com/>.

I look forward to a successful collaboration with Flow.
