### ISSUE TITLE
Nuxt-FCL module

### ISSUE THREAD

**Issue by vr1eva** [onflow/developer-grants#115]
# Nuxt-FCL

# Grant category
- Developer tools / services

# Description
I want to develop a Nuxt module that wraps the Flow Client Library. These provide comfort in the shape of shortcuts to methods of the most popular JavaScript libraries.

## Problem statement

There is a clear need for this tool, as evidenced by the fact that there are already several other projects that have created [similar modules](https://modules.nuxtjs.org/) (for other frameworks). I believe that I can create a high-quality module that is easy to use and that will have a positive impact on the Flow ecosystem.

## Proposed solution
The Flow Client Library is a tool that allows developers to interact with the Flow blockchain. By creating a Nuxt module that wraps the library, we would make it easier for developers to use Flow in their applications.

## Impact

The module will benefit the Flow ecosystem by making it easier for Vue developers to use Flow in their applications. This will make Flow more accessible to a wider range of developers, and ultimately lead to more adoption of the platform.

# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Feature selection   | Landing listing features to be included in the module | 2 weeks  | - | 1200           |
| 2 - Research and learn about Nuxt.js framework  | Capability to ship Nuxt.js modules  | 1 month | - | 1500           |
| 3 - Begin coding the module  | Module MVP  | 2 months | - | 3000           |
| 4 - Write tests for your module to ensure it works as intended.  | Test coverage  | 1 months | - | 1500           |
| 5 - Add documentation for the module so others can easily understand and use it. | Module documentation  | 1 month | - | 1500           |
| 6 - Publish module on npm so others can install and use it in their Nuxt.js projects   | Publication of the module in the Nuxt.js module directory + ad hoc support  | 2 month | - | 1500           |

Total amount requested: 10,200USD
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Bruno Gonzales (me) | Nuxt Developer | Vue Enthusiast | hivr1eva@gmail.com |

**Comment by chrisackermann** [comment]
Hi @vr1eva, thanks for submitting your proposal!  We're reviewing and will get back to you soon.

**Comment by alxflw** [comment]
Sorry for the delayed response @vr1eva! 

We reviewed your proposal in detail and decided to pass because it is unclear if the impact on the developer ecosystem will be high enough. We have yet to see broader NuxtJS adoption with Flow developers.

Thanks for taking the time to submit your proposal and feel free to reach me directly on Discord in case you have further questions: `alx-flw.find#6198`.
