### ISSUE TITLE
Flow Developer Content

### ISSUE THREAD

**Issue by CapnMB** [onflow/developer-grants#116]
# Flow Developer Content

# Grant category
Educational material

# Description

## Problem statement
Flow needs more developers - so onboarding new devs into the ecosystem is a priority. While there are over [18,000+ active monthly web3 developers](https://medium.com/electric-capital/electric-capital-developer-report-2021-f37874efea6d) (as of Jan 2022), less than 200 developers work in Flow/Cadence (compared to over 4000 in Ethereum/Solidity/Vyper). And while nearly 35,000 new developers joined or learned web3 in 2021, the number joining Ethereum was vastly larger (20-25% of all new devs) than any other ecosystem, including Flow.

In order for Flow to continue its growth, it needs to attract new developers.

However, there are a couple problems with onboarding these developers:

 * While new web3 developers are entering the space quickly (numbers nearly doubled from 2021 to 2022) most are introduced to web3 through Ethereum/Solidity - and stay there. Smart contract development is difficult, with a long learning curve, and devs are not incentivized to learn a new paradigm/chain/language.
 * For current Ethereum devs, even if they are interested in the Flow ecosystem, learning Flow/Cadence requires a paradigm shift (resource-oriented vs object-oriented) which makes onboarding difficult. This is a serious barrier to entry.
The ecosystem needs more paths for developers to enter Flow.

## Proposed solution
We want to bring more devs to Flow by creating technical content that helps devs understand why they should use Flow/Cadence, and then leads developers through the shift from their current stack to Flow. Our group, [Dev Spotlight](https://www.devspotlight.com/), is highly qualified to create these guides as we have deep experience both in technical content creation (including web3) and in similar projects for other ecosystems.

**Content Details**

We will create twelve articles, on a range of topics, that help developers reach that 'aha' moment with Flow/Cadence. Our content will lead them from the initial why, to the details of Cadence, to joining the ecosystem, to making a living, and beyond. 

Topics will be TBD and chosen by the Flow team on an ad-hoc basis over the coming 6 months. Topics can be diverse and range over subjects such as mobile native, on-chain logic, gaming, trust and transparency, and more. This ad-hoc model will allow us to react to market changes and trends with fresh content. All content will be produced independently without any work from the Flow team (we have a strong internal team of developers, writers, technical editors, code reviewers, and copy editors that work together to create a final draft of high quality).

All articles will be technically detailed and informative. The articles will include diagrams, screen shots, sample code, etc. The articles can be published on Flow properties and also syndicated to the 3rd party sites dev.to, DZone, Medium, Hacker Noon, and Hashnode. All articles will be available for review by the Flow team before publishing.

**Qualifications**

We have a proven track record of creating readable and digestible technical content around difficult topics. We have created many similar articles in different areas. We are experienced in web3 (our web3 client base is private but includes many top protocols and companies). Our web2 clients include some of the top developer-focused companies in the world such as Twilio, Salesforce, MongoDB, Cisco, and many more. While much of our work is ghostwritten and private, we are happy to provide examples to the Flow team upon request.

Over the past five years we have published over a thousand high-quality technical articles that have been read by tens of millions of developers. We are some of the most popular and followed writers on the above-mentioned 3rd party sites (such as DZone and dev.to) and can reach an audience that has not yet been introduced to Flow. We know this audience well and we know how to create successful technical content.

We are developers ourselves, and have a deep understanding of what developers want, what topics they most want to read, and what headlines get the views. We know how to write meaningful articles developers love to read.

We also [just completed a successful Flow developer grant ](https://github.com/onflow/developer-grants/issues/28)and met all of our milestones including target views.

## Impact

This series of technical guides will introduce a straightforward path to learning Flow/Cadence. This content should increase the number of developers in the ecosystem.

At the end of the project, we will publish a metrics report capturing the number of syndicated views and interactions. Please note that click-throughs/conversions will need to be measured by the Flow team as we don’t have access to this information.

# Milestones and funding

12 articles, topics created on-demand with a typical turnaround time of 3 weeks from topic to publishing. Cost is $4000 per article (payable in Flow tokens), with a $6000 bonus for every 50,000 views (also payable in Flow tokens), capped at 250,000 views ($30,000 bonus). Published over six months.

|Milestone | Est Publication Date | Cost
|-------------------------------|-----------------------|-----------
|Article 1-4 | 8 weeks from start | 16000 USD | 
|Article 5-8 | 16 weeks from start | 16000 USD | 
|Article 9-12 | 24 weeks from start | 16000 USD | 
|Cumulative 50k views | n/a | 6000 USD | 
|Cumulative 100k views | n/a | 6000 USD | 
|Cumulative 150k views | n/a | 6000 USD | 
|Cumulative 200k views | n/a | 6000 USD | 
|Cumulative 250k views | n/a | 6000 USD | 

Total funding proposed: 78000 USD
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Michael Bogan | Project Co-Lead | Founder. 25+ years of development and systems architecture experience. | michael@devspotlight.com |
| Paul McAviney | Project Co-Lead | Web3 lead. Core member of dev_dao. | paulie@devspotlight.com |
| Alvin Lee | Senior Editor | 20+ years of development and technical editing. | alvin@devspotlight.com |
| Various | Writers | We have a core group of ~10 web3 writers who will all contribute to the content. |  |

**Comment by chrisackermann** [comment]
Hi @CapnMB, thanks for submitting your proposal!  We're reviewing and will get back to you soon.

**Comment by chrisackermann** [comment]
Hi @CapnMB!  We just wanted to let you know that this proposal has been accepted.  We will be following up directly with next steps, thanks!

**Comment by Aliserag** [comment]
Closing as it's completed (I reviewed)!
