### ISSUE TITLE
Grant-Delivery Reasoning

### ISSUE THREAD

**Issue by jacob-tucker** [onflow/developer-grants#119]
# Grant-Delivery Reasoning

# Grant category

Please select one:

- Developer tools / services

# Description
This is a very small grant, however I would like to help make grant-delivery better for the recipient by having the grant team explain what the grant is for, and have that display in Flowscan under each transfer.

## Problem statement

- Target audience
The target audience is people who are completing grants in the Flow ecosystem, but this will be used by the Flow grant team.
- Evidence for the need
I have completed grants both individually, for Emerald City, and for other projects. Because of this, it became evident that it's hard to know why someone is receiving a $FLOW transfer. Is it for something I did from a grant? Is my friend transferring me $FLOW? Which grant is it for? I end up having to ping members of the Dapper/Flow team (which is probably really annoying for them) asking if payment has actually been delivered and what each transfer is for.

## Proposed solution
I want to design a simple contract that allows the sender to input a message, and it will emit an event with that message inside of it that describes why the recipient is receiving $FLOW.  Ideally, this would also be integrated into things like Flow Port in which you just add 1 extra input to type a message, and it will then be displayed on Flowscan.

## Impact

- In what ways does this benefit the broader Flow developer ecosystem?
It will allow people receiving $FLOW to understand why they are receiving it and for what grant it is for.

# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - MVP   | Smart Contract & Transaction | 1 week  | - | 500           |

Total funding proposed: 500 USD

# NOTE
The above is just for writing the smart contract & transaction. However, I am also happy to help integrate this into Flow Port and work with the Flow team to set up this technology through whatever platform they use to send out grants.
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Jacob Tucker | Smart Contract Engineer | ... | jacobtucker818@gmail.com |

**Comment by chrisackermann** [comment]
Hey @jacob-tucker, thanks for this!  Will get back to you shortly.

**Comment by chrisackermann** [comment]
Hey @jacob-tucker - are you considering this only for grants or are you thinking to build this in a way where could be used to help provide context on any sort of FLOW transfer if someone wanted to use?

**Comment by jacob-tucker** [comment]
Hi @chrisackermann - indeed. This would be used for any $FLOW transfer. Ideally this would be integrated directly into Flow Port, simply by adding 1 extra line to write a "reason" for the transfer. And it would show in Flowscan.

**Comment by chrisackermann** [comment]
Hi @jacob-tucker, we've approved this grant - thanks for your patience.

**Comment by jacob-tucker** [comment]
Hey there @chrisackermann !

I have completed the grant here: https://github.com/jacob-tucker/grant-reasoning

In order to use, we would have to:
1. Deploy `TokenDelivery.cdc` to mainnet
2. On Flow Port, simply update the transfer transaction code to `send_flow.cdc`
3. Add an (optional) input field when transferring to include a message

All files are included in the repository I sent along

**Comment by chrisackermann** [comment]
Hi @jacob-tucker, thanks - we've accepted this milestone and will make this grant as completed.  Will follow-up separately on getting this setup for Flow Port.
