### ISSUE TITLE
Funding Grants

### ISSUE THREAD

**Issue by Vadik-boom** [onflow/developer-grants#120]
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

Contact Info
--
CEO's LinkedIn: | https://www.linkedin.com/in/dmytrokutsenko/
CEO's Telegram: | https://t.me/DmytroKutsenko
CEO's Mail: | ceo@wzone.io
Team:
Team LinkedIn profiles: | https://www.linkedin.com/in/dmytrokutsenko/https://www.linkedin.com/in/nick-pop-senior-ux-designer/https://www.linkedin.com/in/ruslanpanchak/
Team size: | 13
PitchDeck: | https://wzone.io/data/upload/WLZ-Pitch_1.pdf
Project Info
Project Name: | WhiteList Zone
Project Mail: | business@wzone.io
Project Website: | wzone.io
Project Business Sector: | Marketplace
Current stage of the project: | MVP & Demo video availible
Project Mission: | WhiteList Zone mission is to make early-stage crypto investment accessible, efficient, and reliable.WhiteList Zone's main advantages over its competitors are: 1. The first Web 3.0 marketplace, with a user-friendly interface and automated buying/selling of whitelists. 2. You can buy and sell whitelists on any network. 3. fast and secure purchase 4. Buying whitelists directly from launchpads and project owners.
Advantages | WhiteList Zone mission is to make early-stage crypto investment accessible, efficient, and reliable.WhiteList Zone's main advantages over its competitors are: 1. The first Web 3.0 marketplace, with a user-friendly interface and automated buying/selling of whitelists. 2. You can buy and sell whitelists on any network. 3. fast and secure purchase 4. Buying whitelists directly from launchpads and project owners.
RoadMap: | https://wzone.io/roadmap
Whitepaper: | https://whitelist-zone.gitbook.io/whitelist-zone/whitelist-zone-introducing/whitelist-zone
PitchDeck: | https://wzone.io/data/upload/WLZ-Pitch_1.pdf
Description: | WhiteList Zoneis the first OTC marketplace where whitelist winners and owners can securely transfer access to unique investment opportunities and maximize their incomes hustle-free
Social media links:
Twitter: | https://twitter.com/wzone_io
Telegram: | https://t.me/WhiteListZone_Official
Medium: | https://medium.com/@WhiteListZone_Official
LinkeIn: | https://www.linkedin.com/company/wlz/

</body>
</html>Contact Info	
CEO's LinkedIn:	https://www.linkedin.com/in/dmytrokutsenko/
CEO's Telegram:	https://t.me/DmytroKutsenko
CEO's Mail:	[ceo@wzone.io](mailto:ceo@wzone.io#)
Team:	
Team LinkedIn profiles:	"https://www.linkedin.com/in/dmytrokutsenko/
https://www.linkedin.com/in/nick-pop-senior-ux-designer/
https://www.linkedin.com/in/ruslanpanchak/"
Team size:	13
PitchDeck:	https://wzone.io/data/upload/WLZ-Pitch_1.pdf
Project Info	
Project Name:	WhiteList Zone
Project Mail:	business@wzone.io
Project Website:	[wzone.io](http://wzone.io/)
Project Business Sector:	Marketplace
Current stage of the project:	MVP & Demo video availible
Project Mission:	"WhiteList Zone mission is to make early-stage crypto investment accessible, efficient, and reliable.

WhiteList Zone's main advantages over its competitors are: 

1. The first Web 3.0 marketplace, with a user-friendly interface and automated buying/selling of whitelists. 
2. You can buy and sell whitelists on any network. 
3. fast and secure purchase 
4. Buying whitelists directly from launchpads and project owners."
Advantages 	"WhiteList Zone mission is to make early-stage crypto investment accessible, efficient, and reliable.

WhiteList Zone's main advantages over its competitors are: 

1. The first Web 3.0 marketplace, with a user-friendly interface and automated buying/selling of whitelists. 
2. You can buy and sell whitelists on any network. 
3. fast and secure purchase 
4. Buying whitelists directly from launchpads and project owners."
RoadMap:	[https://wzone.io/roadmap](https://wzone.io/roadmap/#)
Whitepaper:	https://whitelist-zone.gitbook.io/whitelist-zone/whitelist-zone-introducing/whitelist-zone
PitchDeck:	https://wzone.io/data/upload/WLZ-Pitch_1.pdf
Description:	WhiteList Zoneis the first OTC marketplace where whitelist winners and owners can securely transfer access to unique investment opportunities and maximize their incomes hustle-free
Social media links:	
Twitter:	https://twitter.com/wzone_io
Telegram:	https://t.me/WhiteListZone_Official
Medium:	https://medium.com/@WhiteListZone_Official
LinkeIn:	https://www.linkedin.com/company/wlz/

**Comment by chrisackermann** [comment]
Hi @Vadik-boom, thanks for your proposal?  Would you mind updating to follow the format (and required information) that we've outlined in the submission template?  Thanks!

**Comment by chrisackermann** [comment]
Hi @Vadik-boom, just wanted follow-up re: previous comment about updating your proposal to follow the format and include the required information needed to properly review your submission.

Please let us know if you can update the proposal accordingly, thanks!
