### ISSUE TITLE
React Native x FCL Sample Starter

### ISSUE THREAD

**Issue by gregsantos** [onflow/developer-grants#121]
# FCL React Native Starter

# Grant category

Please select one or more of:

- [x] Open source maintenance
- [x] Developer tools / services
- [x] Educational material

# Description

There are several great FCL starters and sample apps for web frameworks like Next.js, Svelte, etc.
Many web developers use React Native to build cross platform and mobile native apps. A simple or full featured sample application built with React Native and FCL (fcl.js) would encourage more devs to create mobile apps for Flow.

## Problem statement

There is currently no FCL sample or harness app for React Native. In order to create one, some upgrades to the fcl.js library are required. For example, some current features of fcl.js and wallet discovery rely on the existence of a browser `window` object, iframes, and post messaging between windows. 

## Target audience
Javascript and React Native developers wishing to create mobile apps for Flow using the cross platform React Native framework and fcl.js

## Solution requirements
A service plugin (suggested) or other solution is needed which supports React Native web view method and uses an alternative for message passing between Discovery and wallet views.

## Submission requirements

- A simple or full featured sample app using fcl.js and React Native
- Upgrades to fcl.js to support an alternative to iframe/pop/tab methods and post messaging between discovery and wallet approval windows.

**Comment by JeffreyDoyle** [comment]
Closing, as there is an example fcl-react-native-scaffold by @jribbink available here: https://github.com/jribbink/fcl-react-native-scaffold/
