### ISSUE TITLE
Flowview: Account Inspection Tool #onFlow

### ISSUE THREAD

**Issue by LanfordCai** [onflow/developer-grants#122]
# Flowview

# Grant category

Please select one:

- **Open source maintenance**

# Description

[Flowview](https://flowview.app) is an account inspection tool on Flow, by using it you can:
- Check account information(.find and flowns domains supported) like available $FLOW balance and storage capacity
- List all the keys of the account, and create / revoke key if you are authed
- List all the FungibleTokens and the balance in your account
- List all the NFT collections in your account.
- Check the detail of specific NFT collection and NFT.
- List all the public / private paths in the account, show the interfaces and the target resource of the capability with good UI. And if you are authed, you can unlink them.
- List all the storage paths in the account, show the resources / structs in the path. You can check the details about the resources / structs, and destory resource if you are authed.
- Support mainnet, testnet and emulator, developers can easily use it to check the items in the account.

Now I'm going to add some features to Flowview, so I submit this to seek for support from grant program

## Problem statement

-   Target audience  

Developers and common users on Flow
   
-   Evidence for the need

I'm going to make flowview another flow-view-source with latest Flow/Cadence features and better UI. I like flow-view-source, it helps me a lot, but it's not actively maintained now. And I know now we have https://f.dnz.dev, a great flow-view-source fork, but just like some developers like vim, and some developers like VSCode, I want to make a viewer with better UI to make it both benefit the developers and common users. 

## Proposed solution

The main features I'm going to add are:

- `Contract`. A contract module with better syntax highlighting and dependencies list
- Transaction Viewer. Show the details of a transaction
- Block Viewer. Show the details of a block
- Integrate some new stuff on Flow, like Switchboard etc
- Support Sandbox net
- A bookmark function to make it easier to track multiple accounts during testing.

## Impact

- In what ways does this benefit the broader Flow developer ecosystem?
* Bring the developers and common users on Flow a well maintained and easy to use viewer, improve their experience.

# Milestones and funding

> Note: You can leave the USD proposal empty / "TBD". Please consider adoption and/or maintenance milestones at the end of your project.
> 

| Milestone | Deliverables   | Timeline | Risks                   | FLOW proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Contract module (Contract page, clickable dependants / dependencies, fork button etc) | Function available on website | 2 weeks |  | 6000 FLOW |
| 2 - Transaction Viewer and Block Viewer | Function available on website | 2 week |  | 6000 FLOW |
| 3 - Support Sandboxnet | sandbox.flowview.app launched | 3 days  |  | 500 FLOW    |
| 4 - Bookmark | Function available on website | 2 weeks  |  | 2500 FLOW  |
| 5 - Maintenance  | Support new features like Staking Info/Switchboard/ FTMetaviews/ Fix bugs/ Support / Cloud Service Maintenance | 6 months |  |  10000 FLOW |
| 6 - Adaption | More than 20 developers enabled Bookmark | 3 months after completion | | 4000 FLOW |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Lanford33 | Full-Stack Engineer | ... | email: lanfordcai@outlook.com <br /> discord: lanford33#2178 |

**Comment by chrisackermann** [comment]
Hi @LanfordCai!  Thanks for your patience, we've approved this grant and will be reaching out directly on next steps.  Thanks!
