### ISSUE TITLE
Sub DAO Emerald Brasil

### ISSUE THREAD

**Issue by diegofornalha** [onflow/developer-grants#123]
# EdTech Brasil

# Grant category

- Educational Material
https://academy.ecdao.org/pt
https://x.com/flowbrasilchain

# Description

## Problem statement

The situation in Brazil where there are a large number of developers who are interested in utilizing the flow blockchain and programming in cadence. However, the availability of English-only content is limiting their ability to do so. This suggests that there is a demand for resources in languages ​​other than English in order for these developers to fully utilize the flow blockchain. 

## Proposed solution

It is important to provide high-quality content to the Latin American (LATAM) community in order to support and enrich their learning and development. This can involve creating materials that are accurate, informative, and relevant to the needs and interests of the community. It may also involve ensuring that the content is presented in a clear and concise manner, and is accessible to individuals with varying levels of knowledge and expertise. By providing quality content to the LATAM community, individuals can improve their understanding and skills in a particular area, and have access to resources that can support their personal and professional growth.

## Impact

The goal of this proposal is to facilitate the transition of thousands of web2 developers to the web3 world, with a focus on utilizing flow solutions. Brazil, as the largest economy in Latin America, has a significant number of highly skilled developers who have the potential to create innovative solutions using the flow blockchain. These solutions have the potential to address a range of issues within Brazil, including green certification of agribusiness, environmental concerns related to forest devastation, and the distribution of wealth and hunger. This proposal is equivalent to six months of work, and its successful implementation could lead to significant benefits for Brazil and its developers.

# More about me:

I am an advocate for flow initiatives and have published articles and videos on social networks. In November 2022, I was selected from over 3300 applicants to be one of the first [16 ambassadors worldwide](https://twitter.com/flow_blockchain/status/1606042585763495936). In 2018, the launch of flow inspired me to open a company in Brazil called Coflow. Our company shares the same vision as Dapper Labs, which is to create industry-leading web3 experiences and develop dapps on the flow blockchain that provide users with a simple way to manage their assets and use the blockchain. Our mission is to make the world a more accessible and enjoyable place through consumer adoption of decentralized technologies.

# Milestones and funding

Deliverables : Production of content and posts on social networks LATAM 
https://discord.com/channels/613813861610684416/1049804829221978153 

# Team

Name | Role | Bio | Contact
-- | -- | -- | --
Diego Alcantara | Official Ambassador at Flow | Founder Coflow | diegofornalha@gmail.com
Bianca Lima | Head of Operations | CoFounder Coflow | bianca@coflow.com.br

**Comment by diegofornalha** [comment]
https://github.com/diegofornalha/Mais1Code/tree/master/content/pages/blog

I have prepared a platform for the OnFlowBR community and am in the process of expanding it to cover all of Latin America. I have migrated all of the content to the platform and will be using google analytics to allow others to monitor the real growth of the community. I am committed to fostering the growth of the community and will be allowing new flow advocates to post on the platform. As a reward for their contributions, I will be donating a portion of tokens. In addition to posting on the main blog, I will also be rewarding those who publish their posts on other content platforms and social networks with a flow token.

**Comment by diegofornalha** [comment]
@chrisackermann I will create targeted content for the hackathon participants, including the use of the emeraldBot to record and measure the engagement of advocates.

**Comment by Peixer** [comment]
@diegofornalha great idea! There are many people to reach in the LATAM space.

**Comment by diegofornalha** [comment]
@fotescodev The proposal update included the consideration of Spanish speakers, ensuring that they also have access to our content. In this way, we expand our audience and strengthen our LATAM presence. This inclusion reinforces our commitment to meet the needs of everyone.

**Comment by fotescodev** [comment]
Ok gents, let's give it a try!

**Comment by diegofornalha** [comment]
@fotescodev @alxflw Due to the restructuring of the grant program and delays in decision-making for proposal acceptance, the bilingual developer responsible for translating Spanish content accepted a new full-time job opportunity in another blockchain. As a result, we've chosen to reduce the amount of Flow tokens we are requesting, while still committing to deliver the Portuguese-translated content.

We are delighted to share that our community has been expanding and now includes about 200 developers, all members of the Emerald LATAM community, each one eager to participate in the Hackathon.

Moreover, we are excited to announce the launch of the BR token. Our goal is to add liquidity to this token and foster a token economy within regional projects.

Our target is to reach 6,000 members by the end of the year with this support. We are eager to accelerate our growth!

**Comment by diegofornalha** [comment]
@Aliserag 
<img width="859" alt="prt 2024-01-31 at 21 53 48" src="https://github.com/onflow/developer-grants/assets/37958057/149c5156-0aaf-454d-9ee1-266276e85116">

This is the amount held by the DAO. The strategy is straightforward: whenever the value of the Flow token drops, we secure a loan in dollars, which is then converted into Flow. We sell at a high to repay the loan. This method serves as a practical, educational example of DeFi in action. The profits enable us to increase our holdings of tokens from partner projects, such as the 236,000 DUST tokens we possess, viewable at https://www.flowdiver.io/account/diego.find?tab=tokens.

https://nft.flowverse.co/user/0x7bf07d719dcb8480?tab=sale
Additionally, we have Flovatar NFTs listed for sale, priced closely to their real market value, as can be seen at https://flov.dev/. This adds up to over 70,000 FLOW tokens in NFTs.

**Comment by chimpytuts** [comment]
@diegofornalha Hello Diego! If you need any help in the future, just tag me!

**Comment by Aliserag** [comment]
We appreciate your proposal and taking the time to fill it out. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
