### ISSUE TITLE
Bounty-based Flow Educational Content Creation

### ISSUE THREAD

**Issue by Randomacy** [onflow/developer-grants#124]
# <Project name>

# Grant category

Please select one:
- Educational material

# Description

## Problem statement

- Evidence for the need

There is a general need for blockchain ecosystems to create technical education content to onboard web2 developers. This is observed indirectly by traction from other ecosystems that produce educational content. For example, 75,000 developers signed up for an asynchronous academy that taught JavaScript, Ethereum, and project-based training. In another example, an L1 protocol launched a content bounty programme for its newly launched smart contract platform over 2 months. It generated 70+ high quality content, along with suggestions on improving it. Each content was rewarded an average of US$300-400, which was a high ROI. 

Additionally, a thriving ecosystem is not without community-generated content. Community-generated content are relatable to developers, and may fill knowledge gaps in existing documentation. On top of it, community members may use Flow for unexpected or novel use-cases.

- Target audience

Onboard will engage hunters to generate Flow technical education content. They will generally fall under two groups:

1. Experienced developers who enjoy creating educational content, i.e. similar to those who publish on Dev.to and Medium to help fellow developers
2. Developers who wish to document their experience learning an ecosystem

By offering the bounty, both groups of hunters are incentivized to create content to help others. The Onboard team will also review the submitted content and assist the hunters to polish their work for a smoother / improved reading experience.

## Proposed solution
Currently, Onboard is composed of two parts. The first part is a content bounty board that aggregates bounties from different ecosystems (https://onboard.super.site). The second part is a Discord community of hunters who discuss and support each other (https://discord.gg/RPwRWbajaz).

With the support of Flow ecosystem grant, we would like to host content bounties to get more technical and non-technical content into Flow ecosystem.

## Impact

- In what ways does this benefit the broader Flow developer ecosystem?

With more developer-generated content available in the Flow develop ecosystem, it is qualitatively easier for new developers to be onboarded onto using Flow. 

Additionally, with more developers who can write in Cadence, projects can launch faster and in greater quantity, leading to a more vibrant ecosystem. 

Additionally, having a corpus of content allows for additional downstream activities to engage developers, e.g., repurposing content for bootcamps, resources for hackathons, etc.

# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Launch of the bounty challenge   | Setting up the bounty challenge on the Onboard website and Discord group | 1 week  | - | 2000           |
| 2 - Submission of the content   | 10 technical and non-technical pieces, with a minimum of 3 technical piece, i.e. coding tutorial, sample project template | 2 months  | No hunters joining and subsequently no content creation<br><br>Mitigation<br>- Identify and collaborate with experienced members of the Flow community<br>- Manually curate and hunt for hunters who are competent in developing in Cadence<br>- Tap into the student blockchain research communities in Tier-1 universities around the world, e.g., National University of Singapore, Oxford, Cambridge, etc | 3000           |

Total funding proposed: USD5,000
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Jackie Tan | Head of Academy | Jackie is currently the Head of Academy at Tribe (https://tribex.co), where he leads developer bootcamps and education, e.g., curriculum development, running of bootcamps, etc. He is a passionate educator who has taught over 3,000 individuals in online and offline formats.<br><br>He am also in charge of launching new developer education initiatives and products to close the gap between web2 and web3. Prior to this, he ran and exited two startups in the education space - financial literacy and coding education in 2016 and 2019 respectively. <br><br>He also has a PhD from Nanyang Technological University, where he investigated proteins using machine and deep learning. <br><br>In his free time, he is a professor in Nanyang Technological University where he teaches data science, and in Singapore University of Social Sciences where he teaches entrepreneurship.<br><br>LinkedIn:<br>https://www.linkedin.com/in/jackietanyen | jackie@tribex.co |

**Comment by Randomacy** [comment]
Hope this message finds your team well! Wanted to follow up with an additional detail - we are collaborating with AngelHack, a community of 200k developers. We're trialling the bounty system with a small beta group, and results have been encouraging. 

Please do not hesitate to ask any questions that you might have!  Very excited to collaborate with your team to create awesome content.

**Comment by alxflw** [comment]
Sorry for the delayed response @Randomacy!

We reviewed your proposal in detail and decided to pass because it is unclear if the impact on the developer ecosystem will be high enough.

Thanks for taking the time to submit your proposal and feel free to reach me directly on Discord in case you have further questions: `alx-flw.find#6198`.
