### ISSUE TITLE
NFTikets(NFT Tickets) Marketplace

### ISSUE THREAD

**Issue by Jimmygodwin** [onflow/developer-grants#125]
# NFTikets(NFT Tickets) Marketplace
    

    

![](https://i.imgur.com/DuWPd9o.png)

# Website
https://nftikets.io/

# Grant category

Please select one or more of the:

- [ ] Open source maintenance
- [#] Developer tools/services
- [ ] Educational material

# Description
    
Nftikets has changed NFT minting narrative with our wallet-less minting architecture giving web2 users massive adoption of our e-ticketing Dapp. it is on this note we are moving forward to build the NFtikets marketplace where event organizers and ticket owners can add more value to their Tickets by adding videos, audio, and picture to these NFTs and reselling them in the marketplace if they wish or holding on to them for a later time.
It is also important to mention that the event organizer who originally sold these Tickets gets a Royalty of 5% every time the ticket is sold in the marketplace creating more value for the organizers even after the event. 
An entire economy of ticket trading will be birthed from this as individual tickets will maintain their value long after the events are over.

## Problem Statement
1. Tickets lose value post-event 
2. Reselling tickets is usually a difficult task as it has to be done offline. 
3. Event organizers have no control and make little to no profit over ticket Scalping.
4. Tickets have no beyond what has been printed.
5. Users are required to connect their wallets to an NFT marketplace (opensea, rarible and etc) before purchasing NFTs.

## Target audience
1. Event organizers looking to create, manage and sell tickets to a global audience without avoiding payment portal issues.
2. Ticket Scalpers looking to make a profit
3. Tickets holders looking to increase the value of their tickets

## Proposed solution
1. A user marketplace that allows the selling and buying of NFTs
2. Allow users to purchase tickets without going through the hassle of connecting their wallet, payments can be made via debit or credit cards and crypto.
3. Increase the value of Tickets for both attendees and event organizers - pre and post-event.
4. Give event organizers the opportunity of profiting from Ticket scalping.
5. Create an NFT marketplace with high adoption for web2 users as no wallet connection or technicality is needed to trade NFTs.

## Impact
1. Create a better profitability model for event organizers to make more revenue via ticket reselling.
2. Create accountability for Ticket scalpers
3. The marketplace will present a new opportunity for ticket trading
4. Reduce redundancy of tickets post events by giving real-world value to event ticketing via NFTs
5. Reduce carbon footprint due to less paper printing

## In what ways does this benefit the broader Flow developer ecosystem?
1. Increase the use case for the flow ecosystem 
2. More users interacting with the flow blockchain

# Milestones and funding

> Note: You can leave the USD proposal empty / "TBD". Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - MVP   | Marketplace build with Credit/Debit card checkout. Royalty on tickets sells  | 6 weeks  | - | 16850           |
| 2- Maintenance  | Resolving issuing and fixing bugs | 6 weeks  | - | 9270           |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Godwin Jimmy | Product Manager |  As a Product Manager, I have managed the development and deployment of various blockchain applications some of which are: Plutoswap (DEX), Dantown (https://www.dantownms.com/), Social Stack (https://www.socialstack.co), Cyrus NFT (https://www.cyruspahlavi.com/), Zoo NFT  (https://zoolabs.io/). | jimmygodwin371@gmail.com | 
  David Esser  | Advisor(Product) |  Chief Product Officer at Minterestt, Serial entrepreneur building blockchain, Defi, internet, mobile, and IoT applications Specialties: -- Product Management for enterprise blockchain, internet, and mobile applications.-- Strategy and implementation for complex technology products.-- Building & leading competent teams of technologists to deliver amazing quality and productivity results | Desser@tradewindsystems.com |
| Joseph Iroghama | Lead Frontend |  A frontend engineer with 3 years of experience in javascript, react, next, web3.js and threejs. | joseph@nftikets.io
| Helen  | UI/UX Designer |  UI/UX design with 4 years of experience in design. | Helen@nftikets.io
 |Gift Elenwo | Frontend Developer |  A computer science graduate with 6 months of experience in javascript and react |elenwogift2@nftikets.io
| Juliet Babatunde | Content Developer |  Content Developer and Copyright with 2 years experience. | babatundejuliet@nftikets.io

**Comment by alxflw** [comment]
Good to see the progress on the project and sorry for the delayed response @Jimmygodwin.

We reviewed this new proposal in detail and decided to pass because it is unclear if the impact on developer ecosystem will be high enough. We do recognize the need for use cases emerging as examples for developers. However, the deliverables aren't going to directly help developers become more productive on Flow.

Thanks for taking the time to submit your proposal and feel free to reach me directly on Discord in case you have further questions: `alx-flw.find#6198`.
