### ISSUE TITLE
Elements

### ISSUE THREAD

**Issue by namazu-sam** [onflow/developer-grants#127]
# Elements

# Grant category

- Developer tools / services

# Description
Elements is a cloud computing platform that provides a one-stop solution for app/game developers to develop and launch their properties in the Web3 market. Our platform is simple enough for novices with hardly any knowledge of Web3 to use, yet powerful enough to empower experienced teams to create their own complex marketplaces and ecosystems. We put powerful Web2 tools in developers’ hands to easily support single sign-on, account management, digital goods, and gamification, and more, while giving developers a gateway to embrace Web3 with tools for smart contracts, multi-blockchain support, decentralized storage, NFTs, and more. Elements allows businesses to get started with building a presence in Web3 and scale as large as they desire without needing to change systems or hire new teams

## Problem statement
The Web 3.0 Blockchain Market is estimated to grow to about $87 billion by 2030 and is anticipated to register a CAGR of 45.20% ([source](https://www.globenewswire.com/en/news-release/2022/05/05/2436993/0/en/Web-3-0-Blockchain-Market-is-estimated-to-be-US-87761-35-million-by-2030-with-a-CAGR-of-45-20-By-PMI.html)). Meanwhile, at the end of 2021, less than 20,000 developers were working in Web3. ([source](https://www.forbes.com/sites/ninabambysheva/2022/08/29/web3-growth-stymied-by-scarcity-of-programmers/?sh=25e3c0e7fa49)).

Creating a cloud infrastructure for an app with support for Web3 features is a daunting and expensive task for any developer. It can take months and costs hundreds of thousands of dollars to engineer. As the market grows, more indie developers will be interested in developing games that take advantage of the tech, but costs will be prohibitive, as will the time and effort required.

## Proposed solution
We believe our software simplifies the process of making a Web3 ecosystem so developers can focus on their apps and games rather than on backend setup and development. Instead of paying a team of server engineers for months to build an app’s backend, developers can sign up for the Elements SaaS solution and scale their platform in minutes. Our clients can enjoy up to a 50% reduction in development time from prototype to launch.

Elements has all the common web2 features developers need, such as single sign on, user profiles, digital inventory, leaderboards, achievements, and more. At the same time, it has web3 features such as smart contract management, generative minting, custodial wallets, and more - which all tie into the web2 side seamlessly.

Elements will be available in three tiers, including a free tier, and we will also offer white glove support for enterprise customers.

## Impact
We will incorporate Flow as part of our cross-chain support. Our goal is to make blockchain easy for developers and simple or invisible for their customers, and thus increase adoption on all sides. With better applications that focus on gameplay or experience first, which Elements facilitates, public perception of blockchain and NFTs will improve.

# Milestones and funding
We’re currently raising funds for productization of our platform. Elements currently works as a white glove solution in our consulting work, but we are now working on turning it into a truly one-click SaaS product. Funds will go towards these efforts as well as sales, customer success, and marketing. We will launch 6 months after completing our funding.

Our overall round is $4 million, but we’re seeking investments as low as $250,000 from strategic partners.
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Patrick Twohig | CEO | https://www.linkedin.com/in/patricktwohig/ | [patrickt@getelements.dev](mailto:patrickt@getelements.dev) |
| Samuel Kahn | COO | https://www.linkedin.com/in/samuel-kahn-ab4b8513/ | samk@getelements.dev |
| Keith Hudnall | CTO | https://www.linkedin.com/in/keith-hudnall-9415403/ | keithh@getelements.dev |
| Noah Kline | CSO | https://www.linkedin.com/in/noahdiskin/ | noahk@getelements.dev |
| Halsey Huth | Advisor | https://www.linkedin.com/in/halseyhuth/ | [halsey.huth@gmail.com](mailto:halsey.huth@gmail.com) |

**Comment by alxflw** [comment]
thanks for the submission @namazu-sam! this grants program isn't designed to support large investments. we're focused on tightly scoped projects. if you get to production and want to add Flow to your platform, please submit a new issue for us to review.

wishing you all the best!
