### ISSUE TITLE
DEX platform with Spot trading

### ISSUE THREAD

**Issue by spiros3p** [onflow/developer-grants#130]
# <Project name>

# Grant category

- Developer tools / services

# Description

People in crypto are used to trading their tokens in centralised exchanges (CEX) through spot markets (Binance, Kraken).  
Decentralised solutions on the other hand (DEX - Decentralised exchanges) rely mostly on swaps and Liquidity Pools for users to trade tokens.  
Spot trading on-chain is restricted to either only limit orders or it exists in networks with instant transaction execution (WAX, Solana) for market orders.

 For context:     
-   **Limit orders**: Limit orders make use of a pre-specified price to buy or sell a security.        
-   **Market orders**: Market orders are transactions meant to execute as quickly as possible at the current market price.

Spot trading allows users to trade with detailed information about the price history, volume, depth of orders and set their desired trading prices, along with every other benefit you have experienced trading BTC on Binance's spot platform.
Furthermore, it allows projects to support (defend price, provide liquidity, etc.) their tokens by only providing one side of the trading pair, unlike LPs.
The drawback is that trading is limited to the available pairs compared to LPs where there can be cascading swap between the desired tokens.

The inspiration:
Overall the WAX blockchain and my experience in it the past 2 years. WAX although a small mcap blockchain is blessed with Atomic hub (main marketplace) and Alcor exchange (main DEX) that have been major catalysts for builders to build projects (mainly games with FTs and NFTs) and users to trade NFTs and FTs, driving the WAX blockchain to the high transaction numbers we can see for a relatively small value chain.
[Alcor dex](https://wax.alcor.exchange/markets) on WAX blockchain is a great example of spot trading tokens on-chain. 
Alcor has been a significant part of all WAX projects launching, as it enables projects and users to easily list, monitor and support their tokens through the platform. 
It also serves as a place for users to discover new projects through finding their FT tokens and all relative information (volume, graph, price changes) provided in the DEX.
Therefore, most, if not all, NFT gaming projects have been building Dapps on WAX by utilising both NFTs and FTs, which has resulted in more engagement from users/communities.

As for me personally (Spiros), I have been a web2 developer for the past 2+ years, I have been close to FLOW since the TS boom and I always wanted to build a meaningful application on FLOW. 
Hence, I recently had the opportunity to complete the learnWeb3 FLOW course, following that, I have a already come up with a DApp idea to get some more hands on experience with Cadence and most importantly to better prepare me for building the suggested DEX platform, if you find the proposal meaningful and you get to offer us this opportunity through the grant.

## Problem statement

- Flow has no DEX that offers spot trading
- DeFi on FLOW is limited to a few options
- FLOW tokens' price history does not exist
- FLOW projects and their users have a hard time supporting token prices on LPs (it costs more to provide both tokens)

Another problem that we aim to address through the creation of the DEX platform is to enable users to initialise any FT contract, display and transfer all their owned FTs. 
This problem became apparent with the Blocto wallet situation, where they have stopped adding new tokens to their application for quite some time (SDM - DarkCountry, stFLOW - Increment).
In the meantime a few Dapps on FLOW (MotoGPI, DarkCountry, maybe others) only support Blocto Wallet to connect, 
hence, users do not have an interface to transfer their tokens between wallets.

## Proposed solution

Our main goal is to build a DEX platform on FLOW that offers spot trading and all its benefits for consumers and builders.  
First we will develop a smart contract for spot trading with limit orders, followed by the interface application.
Next, we will start onboarding existing FLOW projects on the platform and improving the platform based on users' feedback and in parallel we will upgrade the smart contract (or develop a new one) for users to easily list their desired trading pairs through a simple interface on the platform.
The longterm goal for the DEX platform is to offer market orders, through hybrid (on-chain/server) designs that will be explored in the future.

API endpoints will be provided, with the appropriate documentation, for third party tools to fetch market data.

In addition, we are aiming to build an interface for wallets to provide full control of their owned FTs (initialise, display, transfer, burn), regardless of the wallet application they use to connect on the platform.

Next, we will focus in the development of an IDO (initial DEX offering) service, where projects will be able to launch their tokens through the platform's simple interface for both the project owners and communities. 

Finally, an integration with a FIAT (CC) to Crypto (FLOW) service will be explored to make it quick and easy for users to acquire FLOW and trade for their desired tokens.

## Impact

- Spot trading is a more familiar way of trading tokens for the users due to them having previous experience with CEXs (like Binance)
- Spot trading offers more visual information for the user, making trading more interesting
- Users will discover new projects on FLOW through the use of the platform
- Enrich DeFi on FLOW by offering an alternative to the existing swap pools
- Projects will be one-click away from adding their desired trading pairs directly on-chain
- API endpoints will enable third-party tools to pull data from the markets
- Users will have full control of their owned FTs, regardless of the wallet application they use
- IDO service for projects to launch their tokens to their communities

# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Cadence MVP   | Develop smart contract for spot trading with limit orders | 4 weeks  | - | 2500         |
| 2 - Application MVP   | Design and develop the front end application | 8 weeks  | Require more time | 9000           |
| 3 - API  Endpoints | Develop API endpoints and Docs for third-party projects to pull market data | 3 weeks  | - | 3000           |
| 4 - Adoption   | Onboard existing FLOW projects, improve the application and upgrade the smart contract to easily add trading pairs | 6 weeks  | - | 4500           |
| 5 - FTs interface | Develop an interface for users to control their owned FTs  | 4 weeks  | - | 3000           |
| 6 - IDO service  | Design and develop an IDO service and smart contracts | 4 weeks  | Require more time | 4000           |
| 7 - Fiat2Crypto integration | Integrate with a fiat2crypto service to make acquiring of $FLOW simple and fast | 4 weeks  | Require more time | 4000           |
| 8 - Maintenance   | Resolving issues, fixing bugs, improving the application, push for adoption | 3 x 1 month  | - | 3 x 3000           |

Total funding proposed: 39000 USD
  
# Team

| Name | Role                | Bio | Contact         | Linkedin | Github |
| ---- | ------------------- | --- | --------------- |-------|-----|
| Spiros P. | Full-Stack Developer | DevOps engineer at Engie Impact, Electrical and Computer engineering graduate | [mail](spiros3p@gmail.com) | [Linkedin](https://www.linkedin.com/in/spiros3p/) | [Github](https://github.com/spiros3p) |
| Thimios G. | Backend engineer | Software engineer at Juniper | - | - | - |
| Periklis V. | Product owner | HV/HP engineer at GKN Fokker | - | - | - |

**Comment by franklywatson** [comment]
Hi @spiros3p i read over the proposal and we like the idea and are aware that the DeFi landscape on Flow has much to grow and evolve. Right now we're going to hold on this proposal since in order to help you and others succeed in this space we need first to agree on an Oracle specification that would be able provide the FLOW (and other) token pricing needed for spot trading. 

We would be interested to have you in the discussion for oracles and DeFi related which will help you in refining a more specific solution. 

Assuming that is of interest, we would then need to align on a high-level design and security specifics before proceeding to build. There is a very high bar for DeFI-centric projects given the value at stake and widely reported vulnerabilities that occur due to programming errors.

**Comment by spiros3p** [comment]
Hello @franklywatson, thank you for your reply. My response comes somewhat delayed, after we went through a team restructure, as interests of people change while time goes by. Anyway, after reconvening with my current partners, we decided to still pursue the project of this present submission for the flow blockchain. Let us know if it is still possible to take part in the working group related to our project, since submissions through the form is not possible anymore. Thank you and looking forward to get in touch!

**Comment by franklywatson** [comment]
Hi @spiros3p - thanks for reaching out and sorry for the delay on the response. At this time we're still pausing new grant proposals in the DeFi space to make sure that certain required primitives and standards are established before we re-start. Would you be open to discussing this in Q3? Thanks

**Comment by Aliserag** [comment]
We appreciate your proposal and taking the time to fill it out. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
