### ISSUE TITLE
Flow Twitter tipping Dapplet

### ISSUE THREAD

**Issue by Asp1ro** [onflow/developer-grants#133]
# <Flow Twitter tipping Dapplet>

# Grant category

Please select one:
- Developer tools / services

# Description
The purpose of this proposal is to develop an application that lays the foundation for enabling disintermediation between content creators and their fans which works on top of a familiar social network environments and using Flow for its core.

## Problem statement
One of the raison d'être of our project is to use augmentation as a tool to take back the freedom and control of your data and user experience from the owners of communities such as social networks. We can do this by adding decentralized layers at the front-end level on top of existing sites extending its capabilities. That is web augmentation. Thus, we believe that our solution is potentially interesting for any user who doesn't agree with their dependent role in the current "service provider" paradigm, or who simply lacks the functionality they are looking for in their usual interface. 

## Proposed solution
The Dapplets is versatile platform for building blockchain-rich application on top of existing websites augmenting them on the front-end level. Using the technical solutions developed by our team we plan to build extension for Twitter that will seamlessly connects it with Flow ecosystem. The proposal is to create several apps that organically work on top of Twitter. 
One of them allows you to create links between Flow addresses and Twitter accounts, making it possible to use the Twitter handler as the destination for Flow transactions. 
The second one adds the ability to send fungible tokens to any tweet augmenting Twitter UI, even if the user doesn't have a Flow account yet. Our user-end apps (we call them dapplets too) work through the browser Extension that downloads apps from a decentralized repository, so a special Flow dapplet need to be developed. 
We will also integrate the Flow wallet into the Extension.

We plan to expand the functionality of the platform which stores transactions in content units to work with other social networks. And also expand the functionality of these transactions to support other user scenarios, such as donation boxes, community tokenization, access to private content, and prediction markets.

## Impact

We assume that active users who encourage content creators with tokens lead to increase of user base, as there is interest from both sides: content creator looking for new sources of monetization, patrons interested in increasing number of new patrons which leads to improvement of content quality.
Since Dapplets Project is a platform, the developed application will also be a reference
implementation and will be described in our documentation. This will allow other developers to use the Flow + Dapplets bundle to create their own projects using Flow to enrich existing sites with web3 augmentations.

# Milestones and funding

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Flow wallet integration | Extension version supporting flow wallet and documentation to use Flow in dapplets | 6 weeks  | - | 10000           |
| 2 - Flow with Twitter Binding | Extension version augmenting Twitter profiles with Flow accounts | 4 weeks  | - | 6000           |
| 3 - Twitter Flow Tipping Dapplet | Reference Dapplet which allow user to send and claim Flow fungable tokens to any tweet + corresponding smart contract | 3 weeks  | - | 4000           |
| 4 - (Option) Send NFT to tweet  | Reference Dapplet which allow user to send and claim Flow NFTs to any tweet + corresponding smart contract | 6 weeks  | - | 10000           |
| X - Maintenance   | Resolving issuing and fixing bugs | 3 months  | - | 6000           |

Total funding proposed: 36000
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Dmitry Palchun | Founder | Software Engineer turned Project Manager turned Entrepreneur, Dmitry has a vast background in IT with 20+ years of experience and has been a driver and supporter of the blockchain community since the very beginning. He is a real crypto enthusiast and a firm believer in blockchain technology. Having initially worked as an Ethereum Smart Developer and Architect since 2014.| dima@ethernian.com |
| Coordinated Official Anaconda | CTO | Anaconda is a young and determined IT professional with 6+ years of experience who has worked with Dapplets Project from the very beginning. Anaconda has been engineering software since 2015 while serving in various roles from a developer, architect, project, and program manager to consultant, researcher, and technical director. Anaconda is a technology agnostic software craftsman who loves coding and blockchain technology, handles the development of Dapplets Platform, leads the technology team, and is personally responsible for solution architecture and the administration of the IT infrastructure.| - |
| Konstantin Yakovlev | Product Owner | Designer and entrepreneur and in the field of digital technologies. Konstantin has 15+ years of award-winning story of creating solutions for the corporate and mass market working with largest international brands and products. All the while, he has also been active in his academic career, training young designers. He is an assistant professor at the Institute of Culture and has a Ph.D. in computational linguistics.| knstntn.yakovlev@gmail.com |
The team also includes 4 developers and 2 designers.

**Comment by alxflw** [comment]
thanks for the submission @Asp1ro. While this is an interesting use case for users, it is unclear how/if this proposal would add direct & outsized impact to developers building applications and tools on Flow.
