### ISSUE TITLE
Verification Node For Emerald Latam

### ISSUE THREAD

**Issue by diegofornalha** [onflow/developer-grants#134]
# Grant category

To make the text more concise and avoid unnecessary repetitions, I will focus the information from Emerald Latam in this proposal below.
https://github.com/onflow/developer-grants/issues/157

Please select one:
- Educational material

We understand the importance of staking on the Flow network and request the minimum required amount of 135,000 FLOW tokens to operate a verification node.

As the Emerald Latam DAO community, we are proposing to become more active in the Flow Blockchain network by running a verification node. The **rewards earned** through this node will be used for the benefit of the community and audited to ensure its financial health. By participating in the verification network, we are contributing to the security and verifiability of the network, as well as becoming more involved in its operation.

We are currently leading all initiatives related to blockchain, Web 3, and cryptocurrencies events in Latin America, as well as developing hackathons for the creation of new products and services. Our next goal is to expand our participation in the Flow Blockchain network by running new nodes, following the order of Collection, Consensus, and Execution. By doing so, we will be contributing to the security and decentralization of the network, as well as positioning ourselves as an active and engaged community in the evolution of blockchain technology in Latin America.

We are using a point system similar to that of ambassadors to expand our community on Flow and, together with this community of developers, create our own integrated platform on Flow.

Currently, we use three main tools: Discord, Crew3, and DeWork. Through challenges, members earn points for engagement and participation. Check out the list of proposed activities for those who want to stand out beyond just being a developer:

Social media topic
Article/video (can earn more points depending on the quality and impact of the content)
Translated article
Translated video
Online/presential event (bonus points according to the number of participants)
Lecture on a topic from the Flow universe
Creation of projects/tools on Flow

Active members have access to various benefits such as payment for proof of work, curriculum profile for job referrals, extra invitations to local events, participation in private clubs, voting in decisions, access to our private channel, and early access to content.

# Milestones and funding

Marco | Entregas | Linha do tempo | Riscos | FLOW proposal
-- | -- | -- | -- | --
1 - Emerald Rewards LATAM | Verification Node  | 1 weeks | - | 135,000

![image](https://user-images.githubusercontent.com/37958057/225174447-b148bc3f-21fc-4039-bde2-5be2b4c8e786.png)

Total funding proposed: 135,000 FLOW
# Team

Name | Role | Bio | Contact
-- | -- | -- | --
Diego Alcantara | Official Ambassador at Flow | Founder Coflow | diegofornalha@gmail.com
Bianca Lima | Head of Operations | CoFounder Coflow | bianca@coflow.com.br
Andressa ANS | Head of Community | Member Emerald Latam | andressacabral272@gmail.com

**Comment by diegofornalha** [comment]
@fotescodev Our focus in the first moment will be to help form teams on our discord: https://discord.gg/hT8EpC5mUN

**Comment by alxflw** [comment]
@diegofornalha it looks like the description is for a platform but you changed the title to verification node. could you rework the whole description and follow the template (eg include detailed milestones and timelines and use USD as opposed to FLOW tokens)?

**Comment by diegofornalha** [comment]
To encourage the community to individually stake their token earnings in the protocol, we are requesting the distribution of Flow tokens.

![image](https://user-images.githubusercontent.com/37958057/225174542-acb55251-4f53-45d5-ac5c-1c3f8cdd33a0.png)

If this is an obstacle, I can change it to USD.

**Comment by franklywatson** [comment]
Hi @diegofornalha [diegofornalha](https://github.com/diegofornalha) - thanks for clarifying. What I think we are missing overall is a clearer understanding of how Emerald Latam DAO community operates, how much staking and other engagement (hackathons, educational outreach etc) would be taking place. 

135k FLOW is a considerable amount. It would be required to see the business case. Is there data you can provide around the events you are running, how many community members, numbers on the inflows of interest in staking nodes etc. Please help us understand more. Thanks

**Comment by diegofornalha** [comment]
Hi @franklywatson!
Here are some data about past and upcoming events, as well as details on community involvement and staking activities that we plan to implement.

We are strategically present in two communities, one of which is smaller and focused on the Flow blockchain, while the other is focused on web development.

Last month, we started a community that already has over 100 members, with more than 30 participating in the hackathon: https://discord.gg/hT8EpC5mUN

In the second community, Web3Dev, we offer Cadence courses and have monitors to support students. Currently, Web3Dev has over 5,000 members: https://discord.gg/M7M9CX2PXV

**Comment by andressa-ans** [comment]
@diegofornalha, está muito boa a proposta! Na minha opinião, se vc quiser melhorar mais, demostrar esse planejamento através de figuras como padrões ou tendências, ficaria top demais, ajudaria em uma visualização melhorada e ampla do projeto. EX:.                   

Sistema de pontos
Y=2022 (E+P= y membros)    X=2023 (E+P= x membros)

Sendo assim, fica nítido que houve mais efeito no X com esse projeto. ''Enfatizar os resultados''.

**Comment by diegofornalha** [comment]
@franklywatson This formula is quite simple and allows us to calculate the percentage variation in the number of members of Emerald Latam between 2022 and 2023. What's even better is that the higher the variation, the more points Emerald Latam will receive. It's an excellent way to encourage the growth of the number of members and reward those who strive to achieve this goal.

Taking Emerald Latam as an example, if it has 100 members in 2022 (Y=100) and increases to 120 members in 2023 (X=120), the points will be calculated as follows:

Points = (120 - 100) / 100 * 100
Points = 20%

In this case, Emerald Latam will receive 20 points for the 20% increase in the number of members.

It's worth remembering that this points system is a useful tool to evaluate the performance of Emerald Latam in relation to the number of members, but it should not be the only indicator used. It's important to consider other financial and non-financial factors to have a complete and accurate evaluation of the business's health.

**Comment by franklywatson** [comment]
Hi @diegofornalha - thanks for the follow up. It's hard to make the connection between the funding for Verification Node and the impact and engagement it may/could have. Also, our policy is that we don't provide grants for the running of nodes and unfortunately this is not something we make exceptions for. I think you would find more success in proposing smaller and specific grants, such your hackathon proposal https://github.com/onflow/developer-grants/issues/157.

**Comment by diegofornalha** [comment]
Hi @franklywatson - thank you for getting back to me, and I appreciate your explanation regarding your funding policy. Despite this, I remain committed to pursuing my hackathon proposal, and I am thrilled about the prospect of having support. Thank you once more!

**Comment by alxflw** [comment]
Hi @diegofornalha - I believe we're in a miscommunications loop, so I wanted to clarify: we have decided to pass on this grant request because it is not in line with the dev grant program goals. It sounds like you are going to pursue this without the grant funding; we're excited to see your progress and wish you all the best!

Thanks again for taking the time to submit your proposal and respond to our questions. Feel free to reach me directly on Discord in case you have further questions: `alx-flw.find#6198`.
