### ISSUE TITLE
Overflow follow up grant #2

### ISSUE THREAD

**Issue by bjartek** [onflow/developer-grants#136]
# Overflow

# Grant category

- Open source maintenance

# Description

This is a follow up grant 2 for  https://github.com/onflow/developer-grants/issues/12, and https://github.com/onflow/developer-grants/issues/87. 

## Continued supported. 
The initial grant saw alot of value and the follow up grant continued to give value. Overflow can already enable users to test secure-cadence and give feedback to dapper. Overflow also helped prevent an error in the recent test spork simply by keeping it up to date and alive and running an extensive test suite on the new version of flow. 

I would like to ask for a monthly fee to keep overflow a  float for another 3 month period for 10.000 a month for 3 aditional months.

# Milestones and funding

Only mainainance will be delivered this grant period.

> Note: You can leave the USD proposal empty / "TBD". Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Continued support   | Support | Every month  | I do not want overflow to grow unstable and want to be able to help its users. Each month for 3 months | 10000          |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Bjarte Karlsen | Code-monkey | I sling code and have fun and help some people too | bjarte@bjartek.org |

Fees can be discussed.

**Comment by chrisackermann** [comment]
Hi @bjartek, thanks for submitting your proposal!  We've accepted and will be following up directly on next steps.  Thanks!
