### ISSUE TITLE
Flowscore Developer Grant

### ISSUE THREAD

**Issue by proudlywashed** [onflow/developer-grants#139]
# <Flowscore>

# Developer tools / services

# Description
Flowscore is a ranking and rewards platform, defining digital identity for NFT Collectors.  What started as a request from our SNKRHUD Community has grown into a full-scale data behemoth, representing some of the best projects on Flow. We have more than 1.2M assets ranked from 7 projects, including Gamisodes Inspector Gadget, Rogue Bunnies, Driverz et al. We have grown to nearly 900 Collectors on the platform in only 4 months, who have a suite of features to showcase and flex their Collection. Highlights include a Trophy Room to show off their top 3 assets, a Snapshot to easily share their profile on Social, and a data-rich Collector Score that pulls both on chain and off chain info representing their value as a community member. We're now also offering data and insights to our Projects to better understand their community and convert more potential Holders.

## Problem statement
- Target audience
- Evidence for the need

Our platform is designed to increase value for both Projects and Collectors. Unfortunately, not everyone has or will survive this bear market. For Collectors, they've still invested time and money into these Communities. Our Collector Score grants scores to everyone, no matter whether your project is featured on our platform or not. We're validating their efforts. Once our rewards launch, we'll finish the engagement loop necessary to keep Collectors invested, no matter the status of the project. For those Projects that are able to survive, they're looking for tools to help them get connected to the core of their Community and continue to add Holders. We're able to provide data on the health of their project, including Top Holders, number of assets claimed on the platform, and realtime growth; however, we can also let them compare and contrast with other Projects on the platform and even see purchase intent and trends for those looking for more sophisticated insights. Our quick user growth and continued support from our Projects prove there is a need for what we continue to build.

## Proposed solution
Our next steps are to further build out our data offering. For Projects, we're going to tier the offering based on Projects' needs. Our lowest tier is a Project specific relatime data dashboard. The next tier will include ecosystem wide data to compare and contrast to other Projects also on Flowscore. Our global dashboard allows Projects to see the additional data we're collecting from Unranked Projects in user's inventories, including from other blockchains. Our final tier is for brand partners and bigger projects, giving them insights on purchase intent and trends to inform their decisions on and off chain. Overall, we're looking to better connect Projects to their Communities.
We're looking at increasing value for Collectors through Rewards. The more projects we have onboard, the more we can offer to Collectors. We'll open up Membership Card our top Collectors will be able to mint for free, solidifying their dominance on chain. This will be their access to free mints, giveaways, and IRL events. We'll be able to leverage this group to new Projects and new mints to get deals on upcoming Collections unavailable anywhere else that will ultimately enable us to guarantee minting out 10-30% of an overall Collection. 
We're always looking for a way to include Collectors who are heavily engaged on Social but maybe don't own as many assets for financial reasons. We want to expand our Chalenges, which is an extension of our Marketing efforts on on Twitter, asking users to share out their favorite Collections and tag their favorite projects. We want to continue to reward these users as well with giveaways and other rewards. Their involvement is equally as important as those who purchase.

## Impact
- In what ways does this benefit the broader Flow developer ecosystem?

We're literally giving Projects tools to succeed. We're bringing together the best Collectors on the front end and then providing exposure for every Project featured on our platform. Collectors are rewarded more points to their Collector Score for Ranked Projects vs Unranked. We reward for more diversity in your Collection. We encourage high floor prices to increase the value of your Collection. There is no other platform on Flow creating as much value as Flowscore, period. And that's before we launch the backend data opportunities! We are building the infrastructure needed when the mainstream audiences and markets return. It's incredible that we have Doodles and the NBA and Mattel, but what good is the chain if all Creators can't survive. We equalize the playing field, while incentivizing Collectors and benefiting Projects.

# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Data Tier Launch   | Backend Dashboard Launch | 3 weeks  | Getting Projects to Onboard | 15000           |
| 2 - Project Onboarding   | 1 Anchor and 10 additional Projects | 3 mos  | Costs | 25000          |
| 3 - User Onboarding   | 5K Registered Users | 3 months  | lack of Dapper support | 10000           |
| 4 - Rewards   | Launch Rewards platform | 2 months  | Crypto Markets | 25000           |

Total funding proposed: <75000>
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Brandon Martinez | CEO | Founded & Sold INDMUSIC, music admin platform behind "Harlem Shake" | bmart@flowscorenft.com
| Stefan Tauber | CXO | Creative Director, WPP Atticus Award Winner | stefan@flowscorenft.com
| HirayaMNL | Dev Team | Built & sold largest live-gaming app in SE Asia, Paydro

**Comment by alxflw** [comment]
thanks for the submission @proudlywashed. this developer grants program is designed to support developers building on Flow to become more productive. it seems this proposal isn't a good fit for the program. if you feel otherwise, please reopen and let us know how developers would be benefit directly from this. thanks!

wishing you all the best.
