### ISSUE TITLE
FindTruman Co-creation on Flow 

### ISSUE THREAD

**Issue by FT-Flow** [onflow/developer-grants#140]
# Project name 
- FindTruman

# Grant category
- Open source maintenance

# Description

## Deck link 
https://drive.google.com/file/d/1AvZ9lpqDH4nkzf3dnVf-kR3b2JYPlKH3/view?usp=sharing

## Problem statement

The story-gameplay (also known as Script-Murder) is becoming popular in recent years. Based on story, the player act as one of the story roles, and interact with others to achieve the ultimate goal from the first perspective. It is characterized by the strong immersion, content-based, social networking attributes, etc.

Our team starts story-gameplay Web2 project from 2017 and became one of the TOP brand in this category. We have accumulated 30 Million Web2 online users, nearly 100 offline studios which can give story-gameplay offline play service to customers in different cities.

The story-gameplay has its own ecosystem roles, including creator, publisher, service provider, player, pirate and Info platform. With the rapid growing, this industry encounters several issues which need to be solved urgently, for example:
1) The copyright problems;
2) The story price cannot be correlated with actual popularity;
3) The creators only get a small part of the story selling;
4) The players have no way to be profitable.

These issues limit the development of the whole industry. We believe that the content creators and players need to receive more incentives in the whole economic system as they contribute their innovative ideas and active participation to the whole system. We found that the Web3 and blockchain technology is very suitable to solve the problem and can give an explosive growth for the production of high quality contents through adequate incentive for the creators and players. This is the main motivation of our team to build this project.

### Target audience
Our main target audience includes the creators, the players and Story NFT investors:
- For creators, they will create story contents and issue story NFT to get the related supports and better create their contents.
- For players, they can enjoy the corresponding story games in FindTruman Platform. They can buy the membership, props, etc., and get the Role NFT and others rewards. 
- For Story NFT investors, they can buy the Story NFT to be deeply bound with the corresponding story, and get revelant profits with the development of the story. 

We also designed the first version of our economic system: https://drive.google.com/file/d/1zs7OgnLkfatH3jCT7qJbThDJCbI1ZroH/view?usp=sharing

### Evidence for the need
We have a profound experience in Web2 with our application with 30M users. During the development of this app, we have experienced a lot of drawbacks in the centralized system. For example, 
1) It is difficult to solicit users to join more actively in the community in the traditional business model. 
2) The creation of the stories is totally in a centralized way which hinders the generation of high-quality content as the creators are not sufficiently incentive. 
3) The problem of copyright. 

After deep research into the Web3 technology and ideology, we believe the Web3 economic system will bring a light into the traditional content creation model. This will help creators and players to join the creation and the build of the stories and games more actively.

## Proposed solution

We propose the  UGC Editor platform and Story-gameplay platform to solve the problems mentioned above(the copyright prblems, the creators and players’ profit sharing, etc.). Here are the details:

(1) UGC Editor Platform
In UGC Editor Platform, the creators could co-create their contents and release their story NFT, including:

1) Story content on chain
The creators can freely create their stories and update the stories according to the feedbacks, and also invite the players to decide the plot development by voting. All the story contents, updates and votes will be recorded on chain.

2) Release Story NFT
The creator could release story NFT on the corresponding chain according to the community ecosystem they want to attract. For players, they could purchase their interested story NFT to become the early adopter. Story NFT holders will be deeply bound with this story, enjoy the whole plot and even obtain future rewards from the story NFT. For creators, their income will directly be linked to the story popularity which will incentivize the production of higher quality content.

3) Co-creation with Story NFT
Based on story NFT, the co-creation will happen in two situations:
      - The creator could invite the story NFT holders to decide the plot development by voting, and the holders could put forward new plot proposals for the author's reference.
      - The creators could set the co-creation tasks, like translation, illustration design or 3D construction, and incentive others with story NFT to join the co-creation procedure.

By this way, the community with good adhesion can be created. At the end of this procedure, the story will have a high quality content or IP with their first fans.

(2) Story-gameplay Platform

1) Enjoy the unprecedented gaming experience
The completed story on UGC Editor platform will be released on the story-gameplay platform for public to experience. The players will be immersed in 3D scenes, act as one of the story roles, interact with other players to collect the scattered information, unlock the hidden clues, make reasoning and reveal the truth, just like playing a movie. The story-gameplay, which combines the strong sense of immersion, various story contents, thrilling reasoning experience and social networking, will bring the players unprecedented gaming experience.

2) Obtain incentives
With our designed tokenomics mechanism, players need to pay for the tickets of story-gameplay, and they could get more rewards if they have an excellent performance. The ticket sales of story-gameplay will be shared to its Story NFT holders. During the early stage of the construction, we will encourage creators and players by ejecting more rewards with FindTruman Eco Funds.

## Impact

1. To catalyze adoption of Flow ecosystem growth, we will further build our UGC co-creation platform and build more story-gameplays on Flow. The story contents and story NFT will be recorded on Flow. The profits generated by Story Game will be shared to the Story NFT holders on Flow. 

2. Introduce players from our Web2 platform. Our team starts story-gameplay Web2 project from 2017 and became one of the TOP brand in this category. We have accumulated more than 30 Million Web2 online users. We will attract users from Web2 by our incentive mechanisms and promotions to Flow.

3. We will build the story-gameplay content with the theme of Flow to attract more creators and players to participate in the co-creation procedure, which will have a better promotion effect of Flow. We will make promotions to make more players come to enjoy our story-gameplay on Flow. During the early stage of story construction, we will eject some incentives to the story pools by using our project’s Eco Funds. Players can also gain our incentives when playing the story-gameplays. Therefore, the story pool will grow dynamically to produce the high-quality content and attract more users to join Flow.

4. The development codes, including front-end, back-end, smart contract of the UGC Editor Platform on Flow will be open source. Moreover, aiming to making Flow accessible and approachable to more developers around the world, we will open the customized discussion zone on our community, communicate and gather suggestions from other global developers, and encourage more developers to participate in the platform co-creation process with FindTruman incentives. 

# Milestones and funding

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 – MVP- story releasing functions of UGC Editor on Flow | - Design UI/UX of story releasing functions on Flow blockchain.<br> - Develop the function of issuing story contents on Flow blockchain: The creators can freely release their own stories, and update their stories according to the readers’ feedbacks. <br> - Develop the function of Story NFT on Flow blockchain. The creators could specify the related NFT information( i.e. the total number, the price and the number of author-retained NFT), and issue the Story NFT on Flow. The story’s future profits will be shared to its Story NFT holders. <br> - Testnet Integration | 8 weeks  | - | 12000           |
| 2 – MVP-- co-creation functions of UGC Editor on Flow | - Design the UI/UX of co-creation functions on Flow blockchain. <br>- Develop the co-creation functions. The creators could set the co-creation tasks, like translation, illustration design or 3D construction, and incentivize others to join the co-creation procedure with the rewards of story NFT on  Flow blockchain. The users could submit their own works for the creators to review. Finally, the user of the best work will be rewarded as the corresponding NFT after the creator’s review. The review of the submitted works will be judged manually by the creators, while the rest of the business logic (i.e. sending NFT rewards) will be automatically executed on Flow blockchain. <br> - Gather ideas based on users’ feedback. <br>  - Testnet Integration | 6 weeks  | - | 7000           |
| 3 – Adoption and Maintenance  | - Design the UI/UX of 3D scene story-gameplay on Flow blockchain.  <br> - Develop the customized 3D scene story-gameplay for Flow blockchain. The players will be immersed in 3D scenes, act as one of the story roles, interact with other players to collect the scattered information, unlock the hidden clues, make reasoning and reveal the truth. With our designed tokenomics mechanism, players could get more rewards if they have an excellent performance.  <br> - Promote: The story-gameplay will be opened to the Flow blockchain network members to experience and play. Collaborate with other projects in Flow blockchain, e.g. co-host AMA, games and other events.  <br> - Official launch: Release 1.0. Users could join the co-creation process through Flow blockchain. | 6 weeks  | - | 6000           |
 
Total funding proposed: 25k USD

  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Will | Co-founder, CEO | He is the founder of a Web2 online story-gameplay application with 30 million users and thousands of professional content creators. | findtruman.io@gmail.com |
| Lyon | Co-founder, CTO | He got his PhD in France in data science, and enter the blockchain industry in 2017 to do some technical research and development. | Lyon_Hou_@outlook.com|
| Bing | Co-founder, CMO | She got her PhD in France in CS, and is invited as academic scholar by National University of Singapore during 2022-2023 in Blockchain Innovation Lab.| snow.xueer@hotmail.com|
| ZZ | Contract Engineer | He has 4 years of practical development experience in the blockchain industry, and is proficient in the development of smart contract language, e.g. solidity, candence, etc. | Loren936274@gmail.com|
| Fornia | 3D Scene Engineer | She has 5 years experience in 3D Scene construction. She has successfully build the 3D-Scene of Black-water Lake, Scarlet Church, etc.| angelica.kathleen@yahoo.com|
| Morax | Front-end Engineer| He is proficient in front-end frameworks. He has 4 years experience in website construction. The front-end of FindTruman story-gameplay platform is built by him. The related technical stack: React, Typescript, etc.| max_newyork@yahoo.com |
| Eric | Front-end Engineer | He has 3 years experience in web design. He is able to build front-end pages with high quality.| thomas2670@yahoo.com |
| Carl | Back-end Engineer| He has 3 years experience in website backend design. He has rich experience in network communications, multithread programming, server performance and load optimization, etc.| Makaveli9A@outlook.com|
| Simon | Test Engineer | He has 4 years experience in software testing. He is specialized in finding and analyzing testing problems to ensure the good quality of the software. | Veroxis0022@outlook.com |
| Wilson | Test Engineer | He has 3 years experience in software testing.| juyingsitu520@gmail.com |
Moreover, our team has visual artist, marketing, product designer, community maintainer, etc.

**Comment by alxflw** [comment]
thanks @FT-Flow. we reviewed this proposal and it is unclear how it would create an outsized and direct impact on developers building Flow (through CLI/SDK/API/docs). with the goals of this developer grant program in mind, we determined that the proposal is not a good fit.

wishing you all the best with your project!
