### ISSUE TITLE
Emerald City (Shield) FLIX Instance

### ISSUE THREAD

**Issue by jacob-tucker** [onflow/developer-grants#142]
# Emerald City (Shield)

# Grant category

- Developer tools / services

# Description
Emerald City DAO to run a FLIX instance. This will allow our Shield service to publish audits much faster and attempt to cover as much as the Flow ecosystem transactions as we can.

## Problem statement

- Target audience
Every user on Flow. This will help keep users safe when interacting with Flow wallets like Blocto & Lilico.

## Proposed solution
We will run our own FLIX instance and publish audits frequently.

## Impact

- In what ways does this benefit the broader Flow developer ecosystem?

# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Maintenance | Run FLIX Instance | 6 months| - | $12,000           |

Total funding proposed: $12,000
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Jacob Tucker | EC Founder | ... | jacobtucker818@gmail.com |

**Comment by MaxStalker** [comment]
Emerald City DAO and Jacob in particular are one of the most active contributors to the advancement and development of Flow. And `Shield`-like is a must-have tool for any kind of blockchain, where wallet-chain interfacing is on the forefront.

That's a 👍 from me!

**Comment by bluesign** [comment]
This is great idea

**Comment by chrisackermann** [comment]
Hi @jacob-tucker, we've approved this proposal and will be following up with next steps.  Thanks!

**Comment by Aliserag** [comment]
We appreciate your proposal and taking the time to fill it out. After careful review we've decided to close this down due the time since it's opened and not seeing the milestones completed. Please let me know if this was a mistake!
