### ISSUE TITLE
frens: token gating, allowlisting and community growth platform integration

### ISSUE THREAD

**Issue by falkonprods** [onflow/developer-grants#143]
# frens: web3 community connectivity

# Grant category

Please select one:

- Developer tools / services

# Description
frens provides Web3 projects with the ability for members to connect their wallets and assign Discord roles based on their NFT holdings. This can be handy for allowlists and airdrops, as well as providing "members only" channels. Additionally, our Web interface allows community managers to see users across platforms: twitter, Discord and wallets, so that they can really SEE the participation of everyone in their community. Ultimately, this tool automates community management, and helps grow communities organically, securely and sustainably.

## Problem statement
In Web2, we had strong product analytics to understand our customers. In Web3, we have our communities. But there are no strong tools right now to know who your users are. Currently community managers and moderators waste their time doing manual tasks and hack together Discord bots and other tools. The end result is that most projects squander the customers they have by not understanding them and not having a platform to engage them, see their contributions, and reward them.

We did extensive research on this during a residency program with another blockchain, and have validated it with our live product available at https://frens.place

## Proposed solution
frens solves these problems by making members visible for their contributions across platforms (Discord, Twitter, Ethereum wallet, etc.), and provides a suite of tools to incentivize and reward users for their contributions: tracking who brings in new members, who shares information  on social media, who purchases NFTs and more.

And lastly, we provide ways for members to be rewarded via allowlist spots, airdrops and eventually being able to receive tokens for joining communities and completing tasks.

All we need to do for Flow is to add support for connecting wallets in the Flow ecosystem so that community managers can enable members to connect with their wallets and can token gate based on their NFT holdings.

## Impact

By connecting wallets and enabling this community connectivity, this tool will empower developers to easily implement communities without having to waste time (as they often do currently) building and hacking Discord bots, or wasting critical effort capturing wallets and monitoring their communities.

# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Wallet Connect UI   | Script for users to connect wallet and set Flow address | 2 weeks  | - | 2500           |
| X - NFT editing and token gating   | 5 team using this project | 3weeks  | - | 3750           |
| X - Adoption   | 5 team using this project | 4 weeks  | - | 1000           |
| X - Maintenance   | Resolving issuing and fixing bugs | 3 months  | - | 1000           |

Total funding proposed: $8,250
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Drew Falkman | CEO/Product | [https://linkedin.com/in/drewfalkman](https://linkedin.com/in/drewfalkman) | drew@frens.place |
| Jose Petry | Full-Stack Engineer | ... | petry@frens.place |

**Comment by falkonprods** [comment]
Just FYI, here is a little explainer video: https://youtu.be/oqlLRi6WFNk

And a walkthrough of what we have (minus Flow support, obv.): https://youtu.be/s6346doDZcE 

We are shipping our analytics dashboard (see image below) next week...

**Comment by falkonprods** [comment]
Also here and monitoring, please feel free to ask any questions.

**Comment by alxflw** [comment]
Hey @falkonprods, our committee reviewed this proposal in detail and decided to pass because it is unclear if the impact on the developer ecosystem will be high enough. While we recognize the problems described, we haven't yet seen the urge for such a solution on Flow.

Thanks for taking the time to submit your proposal and feel free to reach me directly in case you have further questions.
