### ISSUE TITLE
VWBL Protocol - Decentralized Access Control Protocol

### ISSUE THREAD

**Issue by thashimoto1998** [onflow/developer-grants#144]
# VWBL Protocol - Decentralized Access Control

# Grant category
- Developer tools / services

# Description

## Problem statement
Thanks to NFT, user can prove digital ownership of game items such as Crypto kitties, NFT Art and so on. In addition, user can now enjoy unique NFT experiences such as secondary distribution and receiving royalty returns to creator. However, images which is linked to NFT is available for public viewing so the circulation of digital content that has value because only who bought it can see it, as an NFT,  is limited. Therefore we propose VWBL (Viewable) which enables only the NFT owner view the digital content.

## Proposed solution
VWBL add access control feature(Only NFT owner can view) to NFT. Specifically, only NFT owner can decrypt the encrypted data linked to NFT and view it.

<img width="486" alt="vwbl-overview" src="https://user-images.githubusercontent.com/40402518/217209327-0a5ae167-cac7-4118-a6db-21a202254f59.png">

The main features are the following two points.

**1. VWBL (NFT with Access Control Feature) Mint  (Step 1 to 3)**

The minting process of VWBL is similar to that of NFT. The metadata of VWBL NFT contains the URL referring to encrypted data, and additional process is encrypting data, uploading encrypted data and sending encryption key to VWBL Network (Key Management Network).

 **2. The decryption and viewing of encrypted data (Step 4 to 8)**

To view the VWBL NFT data, NFT owner download encrypted data, receive decryption key and decrypt encrypted data. The decryption key for digital content is managed by VWBL Network, as shown in the figure below. When VWBL Network receives the decryption key request, network verify whether the requester owns the NFT, and if the requester is eligible, return key. This verification mechanism ensures that only NFT owner can view the digital content. 

These features are implemented in the VWBL SDK written in TypeScript/JavaScript and sdk runs on a browser or NodeJs environment.

![vwbl-architecture](https://user-images.githubusercontent.com/40402518/217209669-99d167c9-63b0-4fd1-bc5c-bc2c7eec943f.png)

## Impact

**1. Empower NFT services on the Flow Blockchain**
VWBL empower NFT ecosystem by adding an access control feature to any NFT service on Flow Blockchain. 
The transfer interface of VWBL NFT is the same as that of NFT, so we can buy, sell and auction on existing NFT marketplaces. In addition, by integrating VWBL SDK for Flow into the marketplace, NFT owner can decrypt the encrypted data and view it on marketplace app.

**2. Only DAO member can view encrypted data**
Fungible token are distributing [as DAO membership token](https://github.com/onflow/developer-grants/issues/97) on the Flow Blockchain. 
There is a feature in VWBL’s advanced functionality that only who has X amount of fungible token can view encrypted data. Therefore access condition for encrypted data can also be defined as “DAO member”.

**3. Distribute personal data on Flow blockchain**
VWBL also distribute personal data in addition to digital content on Flow blockchain. 
When personal data is transferred via a third party, the administrative cost for the third party to meet privacy requirements is high and personal data utilization is slow.
Using VWBL, decentralized access control protocol, data can be transferred between individuals without a third party and enabling data to be transferred by an individual's access permission facilitates personal data distribution.

# Milestones and funding

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - VWBL Contract   | Develop VWBL smart contract for Flow | 4 weeks  | - | 10000           |
| 2 - VWBL network   | Integrate Flow to VWBL Network | 2 weeks  | - | 5000           |
| 3 - VWBL SDK & Test  | Develop VWBL SDK for Flow|  3 weeks | - |  7500    |
|4- Maintenance | Resolving issuing and fixing bugs | 3 months | - | 1000 |

Total funding proposed: 23,500
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Tatsuki Hashimoto | Smart Contract Engineer | https://github.com/thashimoto1998 | hashimoto@ango-ya.org |
| Sho Kawano | Frontend Engineer | https://github.com/bibitto | |

**Comment by Itahand** [comment]
I like this.

**Comment by alxflw** [comment]
hey @thashimoto1998, we reviewed your proposal in detail and decided to pass because it is unclear if the impact on the developer ecosystem will be high enough. More specifically, we couldn't determine if there's a strong desire from developers for such a solution right now. It certainly has its value but we've yet to see many developers tackling this challenge and looking for a 3rd party solution to solve it.

Thanks for taking the time to submit your proposal and feel free to reach me directly on Discord in case you have further questions: `alx-flw.find#6198`.
