### ISSUE TITLE
SubQuery Data Indexing Solution

### ISSUE THREAD

**Issue by brittanyseales** [onflow/developer-grants#147]
# SubQuery

# Grant category

**- Developer tools / services**

# Description

SubQuery’s mission is to make decentralised data more accessible. SubQuery is your own custom open-source API between blockchain data and your dApps and tools. Our indexer works on Polkadot, Substrate, Avalanche, Algorand, Flare and Cosmos chains, and then provides that data for developers to use for a wide array of projects (wallets, explorers, custom chains, or any other decentralised app).

## Proposed solution

We have three products:

- An open source SDK, which includes the instructions on how any Indexer should traverse the blockchain, what data to collect, and how it should be shown to users. 
- A Managed Service, which provides enterprise level hosting (99.9% uptime) for SubQuery projects by our team (with a generous free tier)
- A decentralised SubQuery Network. With the testnet just finished, we are about to launch a first version of the SubQuery Network. The SubQuery Network is our effort to move towards a decentralised and tokenised network in order to ensure no single point of failure and superior performance for SubQuery. It will support Flow from genesis and will encourage as many participants in the process as possible.

In our view, the Flow ecosystem is poised for an extreme growth period and it requires tools such as SubQuery in order to thrive.

## Problem statement

Almost every blockchain has a need to process and query data, however everyone knows that a core weakness of blockchain data is that the processing and query performance is extremely inefficient. SubQuery is an open source platform that solves that and provides a more performant and feature-rich alternative to The Graph.

We build an advanced developer tool that makes a technically challenging process easy. As a result, the sole measure of our success is the number of developers and projects in Flow using our tool to index data for their dApp/service. We put a lot of effort into business development, developer education, and ecosystem outreach to achieve this. 

But if we don’t build the best indexer tool, with unmatched features, faster performance, and higher reliability - then we will fail at onboarding developers to use our tool. Thats why we focus on both BD and product development. Additionally, our Managed service solves a huge pain point with small teams that don’t want to focus on reliability and uptime. We completely manage this critical infrastructure for many teams and we’ve become experts at it.

## Impact

SubQuery is an incredibly useful tool that developers can use to build dApps faster. It provides a critical level of infrastructure that developers need to access, organise, and utilise data efficiently. By supporting Flow, we will allow our existing customers to easily migrate over to Flow from other ecosystems by providing a common tool. We specialise in new layer-1 chains, and our customers generally take a cross chain approach to development.

We are in complete agreement with Flow’s focus on providing a simple and coherent stack for decentralized interoperability - SubQuery is designed to be one of those tools. Our goals have always been to build tools and services that accelerate the world’s transition to web3 and Flow is a fascinating layer 1 that has attracted a large developer base.

# Milestones and funding

See milestones and cost projection table in full proposal doc here: https://docs.google.com/document/d/1WJo4ZCLbuAHggSICTwhQkQwlzORzgMDNB2UuNvtR28o/edit?usp=sharing
Total funding proposed: $49,500
  
# Team

Based in New Zealand, the inception of SubQuery occurred in February 2021 and since then the below core team of 4 has rapidly grown to more than 20 members spread across New Zealand, Singapore and Portugal. We’re a high performing team, mostly comprised of software developers, devOps engineers, and business development staff with a track record of experience in extending our tooling to different layer 1 chains.

Sam Zou - CEO (https://www.linkedin.com/in/sam-zou-5b8169a/)
Entrepreneur, Investors and more than 20 years  of IT experience specialising in infrastructure and cloud service design

Ian He - CTO (https://www.linkedin.com/in/yin-he-7a266345/)
Blockchain Architect, Contributor of polkadot-js, Early adopter of substrate technology and won second place in the first polkadot hackathon.

James Bayly - COO (https://www.linkedin.com/in/james-bayly/)
Software engineer with experience creating and growing 3 startups over the past 5 years

[Full proposal found here](https://docs.google.com/document/d/1WJo4ZCLbuAHggSICTwhQkQwlzORzgMDNB2UuNvtR28o/edit?usp=sharing)

**Comment by alxflw** [comment]
thanks for your submission @brittanyseales! It seems your solution might be impacted by the active [FLIP for Access Node Event Streaming API](https://github.com/onflow/flips/pull/73). We suggest you review and chime in on the FLIP. Once it is rolled out, I would suggest you update your proposal and ping us again.

**Comment by brittanyseales** [comment]
Hi @alxflw, it's not clear to me how SubQuery expanding data indexing support to Flow would be impacted by the FLIP proposal? 

Additionally I noticed the Flow grants program was recently paused / revamped. Would you recommend we submit a new proposal now? Is there anything I can do to push this forward?

Thank you!

**Comment by franklywatson** [comment]
Hi @brittanyseales - sorry for the late response, Alex has left Flow and I'm working with some other people to catch up to grants and proposals. Yes the grant program is undergoing major changes and an announcement will be made later in the year about the new focus. As such we will close this proposal for the current time since the new focus is on products rather than infrastructure. Apologies for the confusion
