### ISSUE TITLE
Bb : Connect Beyond Grant App

### ISSUE THREAD

**Issue by adamtoowavy** [onflow/developer-grants#149]
# <Project name> Bb : Connect Beyond

# Grant category -- Seeking capital

Please select one:

- Open source maintenance
- Developer tools / services -- (This one)
- Educational material

# Description

## Problem statement -- Dating other humans is extremely difficult, Bb is an AI text companion to make curated digital relationships.

- Target audience -- Digital Natives (Gen-Z) singles
- Evidence for the need -- 75% of Gen-Z is single, Tinder has 66M monthly users in 2022, 90% are frustrated with dating apps -- new solutions for dating need to fit users existing lifestyles.

## Impact -- Bb can serve a lonely generation in a familiar medium

- In what ways does this benefit the broader Flow developer ecosystem? -- Flow has exciting projects like sports collectibles, social avatars - relationship gaming can become a new category of digital interaction we have yet to see and Flow can align with Bb to be pioneers.

# Milestones and funding 
-- Building MVP product today |  2 weeks |  $10000  
-- Launch Bb Basic website/ PR-Marketing Push | 2 months | $5000
-- Expand platform capabilities, enabling Flow, monetize interactions and create features to improve customization of Bb partner. | 6 Months | $5000

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - MVP   | Smart Contract | 2 weeks  | - | 1000           |
| X - Adoption   | 5 team using this project | 4 weeks  | - | 1000           |
| X - Maintenance   | Resolving issuing and fixing bugs | 3 months  | - | 1000           |

Total funding proposed: <total USD amount>
  
# Team
--Adam Sarkis - CTO/CEO -- Prev. co-founded e-commerce startup Cashdrop, built two smart contracts for NFT art projects in 2021. Pre 2019 producer brand marketing with adidas, Converse, Jack Daniels. | ajsark@gmail.com

--Karo Fedorwicz - COO -- Prev. Consultant talent recruiter for Boson Protocol, Prev. Project Manager for Essilorluxottica AR wearibles.

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Alex | Full-Stack Engineer | ... | alex@onflow.org |

**Comment by alxflw** [comment]
thanks for the submission @adamtoowavy. it's unclear how this project would have a direct impact on the productivity of developers building on Flow. Our grants program is not a good fit for this project. 

wishing you all the best with this project!
