### ISSUE TITLE
FNS: Show NFTs owned by a user

### ISSUE THREAD

**Issue by alxflw** [onflow/developer-grants#15]
Show NFTs a user owns by using the Alchemy API

mentioned by @albeethekid

**Comment by tyllenb** [comment]
[myflownfts.com](https://www.myflownfts.com/)

can also search by address like below

https://www.myflownfts.com/address/0xcf0c62932f6ff1eb

**Comment by caosbad** [comment]
https://fn.services/flowns.fn
Flowns Page shows users NFTs on Flow and Ethereum
Flow NFTs integrate with  Blocto Bay api and Alchemy api

**Comment by alxflw** [comment]
grant accepted, closing this wishlist item!
