### ISSUE TITLE
NFTDEAL.IO Grant Application

### ISSUE THREAD

**Issue by taivn07** [onflow/developer-grants#151]
# <NFTDEAL>

# Grant category

Please select one:

- Developer tools / services

# Description
Our NFT marketplace is a one-stop-shop for NFT enthusiasts, offering the latest features of NFT technology in a user-friendly platform. Our integration of NFT 2.0 technology ensures the secure storage of NFT data on-chain, giving users complete ownership and control of their assets. Join us today and explore the exciting world of NFTs!
## Problem statement

- Target audience
The target audience of the above NFT marketplace includes NFT enthusiasts, collectors, artists, and anyone interested in the world of NFTs. The platform is designed to cater to both novice and experienced users who want to explore, buy, sell, trade, and showcase unique digital assets. With a user-friendly interface and advanced NFT 2.0 technology, the platform provides a seamless experience for anyone looking to engage with the rapidly growing NFT community.
- Evidence for the need
We're launching the mainnet. Access https://nftdeal.io for more information. 

## Proposed solution
One proposed solution for the above NFT marketplace is to continue improving the user experience by adding more user-friendly features and expanding the selection of NFTs available for purchase. This could include introducing new search and filter options, such as sorting by popularity, artist, or price range, to help users easily find the NFTs they are interested in.

Another potential solution is to offer educational resources, tutorials, and guides to help new users better understand the world of NFTs and how to navigate the marketplace. This could include creating a knowledge base, hosting webinars, or collaborating with artists and creators to offer behind-the-scenes content.

In addition, the marketplace could explore partnerships with other NFT platforms, artists, and collectors to expand its reach and offer unique NFTs to its users. This could involve hosting exclusive drops or collaborations with popular artists to bring highly sought-after NFTs to the platform.

Overall, the proposed solution for the NFT marketplace would be to focus on enhancing the user experience, offering educational resources, and expanding the selection of NFTs available to users through partnerships and collaborations.
## Impact
Implementing the proposed solutions for the NFT marketplace is likely to have several positive impacts on the platform and its users.

By improving the user experience through the introduction of new search and filter options, users will be able to easily find the NFTs they are interested in, which is likely to lead to increased user engagement and retention.

Offering educational resources and tutorials to new users will help to attract a wider audience to the platform and increase user confidence and satisfaction. This is likely to lead to a growth in the platform's user base, as well as increased user loyalty.

Partnering with other NFT platforms, artists, and collectors to expand the selection of NFTs available on the platform is likely to lead to increased user satisfaction and engagement. This could also lead to an increase in the number of NFT sales on the platform, as users are more likely to find NFTs that they are interested in.

Overall, the impact of implementing the proposed solutions for the NFT marketplace is likely to be positive, leading to increased user engagement, retention, and satisfaction, as well as potentially increasing sales and growing the platform's user base.
- In what ways does this benefit the broader Flow developer ecosystem?
The proposed solutions for the NFT marketplace can benefit the broader Flow developer ecosystem in several ways:

Increased adoption: By improving the user experience and offering a wider range of NFTs, the NFT marketplace is likely to attract more users to the Flow blockchain, potentially leading to increased adoption of the platform and increased demand for Flow-based NFTs.
Collaboration opportunities: The NFT marketplace's partnerships and collaborations with other NFT platforms, artists, and collectors can create opportunities for other developers on the Flow blockchain to collaborate and create new NFT projects.
Innovative features: The new search and filter options and other user-friendly features introduced by the NFT marketplace can serve as a model for other developers on the Flow blockchain to create innovative features for their own projects.
Educational resources: The educational resources and tutorials offered by the NFT marketplace can help educate new users about the Flow blockchain and NFTs in general, potentially leading to increased interest in the technology and increased demand for NFTs.
Overall, the proposed solutions for the NFT marketplace can help to grow the Flow developer ecosystem by increasing adoption, fostering collaboration, and providing innovative features and educational resources.
# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - MVP   | Application mainnet launching  | 2 weeks  | - | 2000           |
| 2 - MVP   | Flow chain integration | 2 weeks  | - | 2000           |
| 3 - MVP   | Adding NFT2.0 protocol to this project | 4 weeks  | - | 4000           |
| 4 - MVP   | Adding more features to this project | 8 weeks  | - | 8000           |     |
| 5 - Maintenance   | Resolving issuing and fixing bugs | 3 months  | - | 14000           |

Total funding proposed: <$30,000>
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Hoang Pham | CTO | ... | hoangpa@paditech.com |
| Khoa Nguyen | CPO | ... | khoanx@paditech.com |
| Dang Pham | Blockchain Leader | ... | dangpm@paditech.com |

**Comment by alxflw** [comment]
Hi @taivn07, we reviewed your proposal in detail and decided to pass because it is unclear if the impact on the developer ecosystem will be high enough.

Thanks for taking the time to submit your proposal and feel free to reach me directly on Discord in case you have further questions: `alx-flw.find#6198`.
