### ISSUE TITLE
Learning Ecosystem for Flow - DApp World

### ISSUE THREAD

**Issue by ankasaw99** [onflow/developer-grants#152]
# Project Name - DApp World

### Website - https://dapp-world.com

# Grant category
- Educational material

# Description
DApp World is a learning ecosystem for Blockchain technology. We at core want to provide exceptional educational content favoring fun and interactive learning experience for developers who want to learn and get into Blockchain Space.

We aim to bring millions of developers and help them excel in Blockchain Domain.

Every developer uses various resources for learning which include Video Courses, Practical Courses, Articles, Tutorials, Labs, Competitions, etc. We provide all that on a single platform with quality curation to favor a fun and interactive learning experience.

## Problem statement 
Building high quality learning Ecosystem around Flow
- Target Audience - Web2 and Web3 Developers/non-Developers

Currently, there are very less resources and the present resources are all clouded, unorganized, and dispersed which developers find really hard to learn from.

Even though there are good communities with thousands of members but there is clearly a lack of high-quality resources to help developers learn easily.

## Proposed solution & Contribubtion to Flow Ecosystem

With DApp World’s contribution, Flow will have high-quality courses to serve the community to educate and upskill them about building on Flow in a very fun and interactive way helping developers at every stage of building.

If we provide quality resources, it helps developers to learn easily and will also help the Flow community by reducing the number of queries from developers while developing dapps.

These wide amounts of resources of different types, produced over time, covering many areas will fulfill the requirements of any developer from a beginner to an expert.

By creating these promised resources focused on Flow, these can be spread across the different communities including the ones we are building alongside, primarily across India, which over time will accelerate the pace at which developers jumping into the Flow ecosystem.

# Milestones and funding

### Description

Objective of this milestone will be creating a Practical Course on Cadence.

Similar Course for Solidity -  https://dapp-world.com/course/introduction-to-solidity-Ynws

Cadence is a new programming language for developers as most developers are used to Solidity and Shifting to Cadence or Learning Cadence firsthand feels overwhelming and a little confusing for existing developers and new developers joining web3.

This can be tackled with the hands-on practical course which helps developers **Learn by Doing.**
 
![Screenshot from 2023-02-27 12-54-54](https://user-images.githubusercontent.com/44086467/221501565-f91ef77e-9a8e-4254-80b7-5e1e3a6f9c25.png)

![Solidity Index](https://user-images.githubusercontent.com/44086467/221505369-08457b9b-2c3a-4402-8960-574bd77bf190.png)

### Deliverables

Content Types - Videos, Tutorials (*in course + Individual), Labs, Certification by Flow, etc.

**Content Count**
- Course -  30+ Topics + Labs and Certification
- Articles/Tutorials -  10+ Developer-oriented tutorials to assist in the development
- Quizzes - 4

**Timeline: 30 Days**

**Fund Ask : 2500 $**

**Goal**
- Practical Course on Cadence for better and enhanced learning experience helping beginners to experts.
- Tutorials focusing on Flow to assist developers and spread more awareness.
- Making cadence easily accessible and easy to build on like new norm in web3.

### Description
Objective of this milestone will be creating beginner-level of resources to help anyone learn about Flow and enter the Flow ecosystem. This way any developer will also get quality and useful resources for building dapps on Flow and it will also clear all the basic queries of the developers developing on Flow.
 

### Deliverables

Content Types - Videos, Blogs, Tutorials (*in course + Individual), Labs, Certification by Flow, etc.

**Content Count**
- Course -  14+ Topics + Labs and Certification
- Tutorials -  5+ Developer-oriented tutorials to assist in development
- Quizzes - 2

**Timeline: 20 Days**

**Fund Ask : 1500 $**

**Goal**
- Detailed Introductory course to get started with Flow.
- Helping present web3 developers and new web3 developers build on Flow with ease.
- Tutorials focusing on Flow to assist developers and spread more awareness.

### Description
Objective of this milestone will be covering all the topics related to Tokenomics such as Tokens, NFTs, advanced NFTs and building a project using those to get better understanding and opening up doors for developers for experimentation and building amazing dapps.
 
### Deliverables

Content Types - Videos, Blogs, Tutorials (*in course + Individual), Labs, Certification by Flow, etc.

**Content Count**
- Course -  18+ Topics + Labs and Certification
- Articles -  5+ Articles targeting Flow Blockchain
- Tutorials -  5+ Developer-oriented tutorials to assist in development
- Quizzes - 2

**Timeline: 20 Days**

**Fund Ask : 2200 $**

**Goal**
- Helping developers with Tokenomics which is very important for building numerous creative applications. 

### Description
Building more advanced applications from any of these like Defi, Dex, Marketplace, Games etc. to help developers get deeper into application building on Flow, with this developers will get more understanding of building production-level dapps which will assist them tremendously while building on Flow.

### Deliverables

Content Types - Videos, Blogs, Tutorials (*in course + Individual), Labs, Certification by Flow, etc.

**Content Count**
- Course -  22+ Topics + Labs and Certification
- Tutorials -  5+ Developer-oriented tutorials to assist in development
- Quizzes - 2

**Timeline: 20 Days**

**Fund Ask : 2500 $**

Goal
- Getting more deep into the Flow blockchain.
- Advanced courses on Flow focused on Building High-end dapps.
- Helping developers build advanced dapps.

## Milestones Overview

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| Milestone 1  | Introduction to Cadence - Practical Course | 30 Days  | - | 2500           |
| Milestone 2   | Introduction & DApp Development on Flow | 20 Days  | - | 1500           |
| Milestone 3  | Introduction to  Flow Tokenomics | 20 Days  | - | 2200           |
| Milestone 4  | Building Projects on Flow | 20 Days  | - | 2500           |

Total funding proposed:  8700 USD
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Aniket Savji | Blockchain Full Stack Developer | ... | aniket@dapp-world.com |
| Ganesh Deshpande | Blockchain Full Stack Developer | ... | ganesh@dapp-world.com |

## Previous Work
- Solidity Practical Course - https://dapp-world.com/course/introduction-to-solidity-Ynws
- Introduction to Dynamic NFT's with Revise - https://dapp-world.com/course/introduction-to-dynamic-nfts-IsYJ
[+ 5 More Course](https://dapp-world.com/courses)

**Comment by alxflw** [comment]
Hi @ankasaw99, we reviewed your proposal in detail and decided to pass because it is unclear if the impact on the developer ecosystem will be high enough. 

Thanks for taking the time to submit your proposal and feel free to reach me directly on Discord in case you have further questions: `alx-flw.find#6198`.
