### ISSUE TITLE
Awesome Flow - Social Platform for Projects & DAO's #onFlow

### ISSUE THREAD

**Issue by tolgayayci** [onflow/developer-grants#153]
# Awesome Flow

# Grant category

- Developer tools / services

# Description

Awesome Flow - the ultimate social platform for discovering and exploring the most exciting projects in the Flow ecosystem! Whether you're a developer, investor, or simply a curious enthusiast, Awesome Flow provides a one-stop-shop for accessing comprehensive and detailed applications about the projects. With this cutting-edge platform, you can discover the latest updates and developments, connect with project owners, and stay up-to-date with the most innovative projects in the Flow community.

## Problem statement

**Target Audience**

Awesome Flow targets a diverse range of audiences, including individuals who are interested in learning about Flow projects and their latest updates. This includes investors, enthusiasts, and other stakeholders who want to stay up-to-date with the developments in the Flow ecosystem.

In addition to individuals, Awesome Flow also targets both early-stage and live projects on the Flow ecosystem. By providing a comprehensive platform that supports projects of all sizes, Awesome Flow aims to support the growth and development of the entire Flow ecosystem.

Furthermore, Awesome Flow also targets ecosystem partners such as DAOs who can help to make the platform more sustainable and aligned with their vision. By engaging with the community and involving ecosystem partners in the management of the platform, Awesome Flow aims to create a more collaborative and impactful platform that benefits everyone involved in the Flow ecosystem.

---

**Evidence for need**

Project showcase platforms face several challenges that hinder their effectiveness in promoting and highlighting various projects. The most significant challenges include sustainability and limited ecosystem partner rightsFIXME. These challenges significantly affect user experience and discourage project owners and ecosystem partners from utilizing the platforms fully. To address these issues, there is a need to develop innovative and user-centric strategies that enhance the functionality and sustainability of showcase platforms.

---

Let's take a closer look at some of the issues of project showcase platforms that I have encountered: 

**Sustainability**: The long-term sustainability of a platform depends on its ability to consistently deliver value to its users. Manual updates through forms and limited content control can result in outdated or inaccurate information, reducing user trust and engagement.

**UI & UX**: The user experience (UX) of a website or platform can significantly impact user engagement and satisfaction. Poorly designed UIs, slow loading times, confusing navigation, and other factors can all contribute to a low UX.

**Poor Search Algorithms**: A platform showcasing tens of projects will require an effective search algorithm to help users easily find the specific project they are looking for. Weak search algorithms can result in irrelevant search results, leading to frustration and decreased user engagement.

**Static Project Pages**: A project page should provide detailed information about the project, such as its objectives, methodology, team members, progress, and impact. A page that only includes a brief description can leave users with unanswered questions and reduce their interest in the project.

**Educational Materials & Articles**: For users interested in a particular project, educational materials and related articles can provide valuable context and additional information. Making these resources easy to find and linking them directly to the relevant project page can enhance user engagement and interest.

**Ecosystem Partner Rights**: Partnerships with DAOs or other ecosystem partners can bring significant benefits to a platform, such as increased visibility, funding, and community support. However, without proper rights and access, these partners may not be able to fully leverage their resources and expertise to help the platform grow and succeed.

## Proposed solution

![Awesome_Flow_Mindmap](https://user-images.githubusercontent.com/40897846/222101794-9a6d224c-d28f-43be-a95c-e6d97b8f958f.png)

Awesome Flow provides solutions to the problems mentioned in the previous statements in the following ways:

**Solution to Sustainability**

Awesome flow has 2 manager personas, project owners and ecosystem partners (admins).

Project owners can send a request to publish their project. After review and approval, they will receive login information to publish and edit their project's page via their web3 wallets on a special dashboard. This enables project pages to be updated by project owners all the time and have unique dynamic pages.

On the other side, ecosystem partners (authorized ones like from like some DAOs) can have admin access to Awesome Flow. They can approve or reject projects and request to remove any harmful content with an explanation. This allows ecosystem partners to help manage Awesome Flow and ensure that all projects are aligned with sustainability goals.

In summary, Awesome Flow provides a platform where project owners and ecosystem partners can work together to create long-term sustainable platform. By empowering project owners to create and manage their own projects and providing ecosystem partners with the tools to manage and monitor the platform, Awesome Flow helps to create a sustainable future for all.

**Improvement on UI & UX**

Awesome Flow has a simple and effective user interface that makes it easy to navigate the website and find the information you are looking for. With just a few clicks, users can access general information and project details on the platform. The user interface has been designed to be fresh and cross-platform compatible, which ensures a seamless and enjoyable user experience regardless of the device or browser used.

The platform is continually undergoing UI developments to enhance the user experience further. At the final stage of development, the user interface will be fully responsible and optimized for all screen sizes, ensuring that users have a consistent and enjoyable experience across all devices. Overall, Awesome Flow prioritizes usability and user experience to create a platform that is both informative and easy to use.

Home Page             |  Projects Page | Article Page
:-------------------------:|:-------------------------:| :-------------------------:
![Awesome Flow](https://user-images.githubusercontent.com/40897846/222101990-9889cc3b-1984-42d0-8c06-12610696e341.png)  |  ![Projects](https://user-images.githubusercontent.com/40897846/222102011-fb0a40df-64eb-4b92-8103-c438061e5091.png) | ![Articles](https://user-images.githubusercontent.com/40897846/222102036-565b30bb-cc4e-419e-8eeb-61aea19a848a.png)

**Solution to Poor Search Algorithms**

Awesome Flow has a powerful search infrastructure that uses Algolia to deliver detailed and lightning-fast search results. 

On Awesome Flow, category list exist to seperate projects in detail. Ecosystem partners (admins) can add categories to this category list according to ecosystem needs, while project owners can select their category and subcategory while adding their project to the platform. Awesome Flow automatically integrates new categories into relevant pages to increase search efficiency.

Moreover, Awesome Flow's search infrastructure uses a detailed searching matrix. Unlike most showcase platforms that only use titles to search for anything, Awesome Flow's range of parameters is much wider, ranging from titles to project descriptions. This ensures that users can find what they are looking for more easily and with greater precision.

In summary, Awesome Flow's search infrastructure is designed to provide a seamless and efficient user experience. Additionally, ecosystem partners work to ensure that the platform's categories are up-to-date and relevant to the needs of the community, further enhancing the search experience.

Search Element             |  Search Focused
:-------------------------: | :-------------------------: 
![Search](https://user-images.githubusercontent.com/40897846/222102506-b071ad32-99b8-468d-8080-85eef109a9ac.png) | ![Search-Focused](https://user-images.githubusercontent.com/40897846/222102524-1eb0fed4-3d69-4809-968d-ce63e8fe29d4.png)

**Solution on Static Project Pages**

On Awesome Flow, project owners can manage their project pages, which include several modules such as:

- Project Description
- Token Stats
- GitHub Stats
- Team Info
- Latest Articles
- Frequently Asked Questions
- Job Postings 

The number of these modules will be increased and further developed.

Project owners can update their project page using these modules. In the future, additional modules can be added based on the needs of the ecosystem.

In summary, project pages on Awesome Flow are highly customizable, allowing project owners to showcase their projects using a variety of modules. By providing these modules, Awesome Flow enables project owners to provide up-to-date information about their projects and engage with the ecosystem more effectively.

**Improvement on Educational Materials & Articles**

Awesome Flow offers a platform for project owners to publish educational materials and articles to inform and engage with the ecosystem. With the built-in editor, project owners can create compelling content that keeps their audience up-to-date on the latest developments in their projects. By providing these tools, Awesome Flow helps to create a more informed and engaged community.

**Improvement on Ecosystem Partner Rights**

Ecosystem partners play a crucial role in ensuring the sustainability of the Awesome Flow platform. By giving them admin rights, they can help manage the platform and ensure that it meets the needs of the community. The committee responsible for this role will be selected based on their ability to review and manage projects effectively.

---

**Technical Details**

For my frontend, I decided to use Next.js.

When it comes to design, I went with Tailwind. It's a really efficient utility-first approach that gives my website a sleek and modern look.

For hosting, I chose AWS Amplify because it's reliable, scalable, and will be able to handle my needs as I grow. And for my database, I went with AWS DynamoDB, which is a fast and flexible NoSQL database storage.

In the future, I'm planning on implementing some cutting-edge technologies like IPFS for storage and Magic for web3 authentication. I'm really excited to see how those turn out!

MVP: https://dev.awesomeflow.org
GitHub: https://github.com/tolgayayci/awesome-flow/tree/dev
Twitter: https://twitter.com/awesomeonflow

**P.S:** This project is currently in the development stage, and as such, links and technical details will be updated at the final stage. 

**P.S:** Awesome Flow **will be published as open source!**

## Impact

Awesome Flow is a social platform that aims to benefit the broader Flow developer ecosystem in several ways. Firstly, as Flow is one of the fastest-growing chains, having a platform like Awesome Flow that aggregates all the projects in the ecosystem can help to further increase its size and diversity.

Additionally, Awesome Flow provides a fluent user experience that enables more people to stay informed about what's happening on Flow. By making it easy to access detailed information about projects and events, Awesome Flow helps to promote collaboration and engagement among developers and enthusiasts alike.

Finally, the platform will be continually supported through Twitter sharing and events, ensuring that it remains a vibrant hub of activity within the Flow ecosystem. 

# Milestones and funding

![Awesome_Flow_Development_Roadmap](https://user-images.githubusercontent.com/40897846/222102950-2bc31ad9-ab90-468b-b088-7caaf6bf6389.png)
<br/>

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - UI & UX Development | **Home Page:** Visually appealing and user-friendly homepage which includes latest articles, popular categories and many more <br /> **Projects Page:** Showcase page with detailed filtering and search infrastructure </br>**Project Detail Page:** Project details page to display detailed information about project with several modules like explained in the solution <br />**Articles Page:** Articles page to showcase informative articles related to the subject <br />**Article Detail Page:** Detail page for individual articles to display their full content <br />**Ranking Page:** Ranking page based on votes and token stats which is supported by CoinGecko api to showcase popular projects and articles </br> **Learn Page:** Useful resources to learn about flow ecosystem </br> **UX Improvements & Testing:** I will work to improve the user experience by ensuring that the user interface is fully compatible with mobile and tablet devices.| 2 weeks |- | 8000 |
| 2 - Project Owner Dashboard | As part of this milestone, I will be implementing both the frontend and backend components of the Project Owner Dashboard. This involves designing and developing the user interface (UI) for the dashboard, as well as building the necessary backend infrastructure to support its functionality. To ensure the quality of my work, I will conduct thorough testing to ensure that the dashboard is user-friendly and performs as expected. My ultimate goal is to provide project owners with a seamless and efficient experience when updating their pages and publishing articles on our platform.  <br/><br/> **For project owners who wants to make fast updates on their mobile devices also Android and IOS apps will be deployed.** | 2 weeks  | - | 5000 |
| 3 - Admin Dashboard | A powerful dashboard for managing content on the platform. As an admin, the individual responsible for managing content is tasked with setting categories, reviewing and approving or rejecting projects, and making requests for fixing inappropriate content. The dashboard is designed to streamline these tasks and provide an efficient workflow for managing platform content. <br/><br/> Similar to the Project Owner Dashboard, authentication is handled through Magic Web3 wallet to ensure a secure and seamless experience. The dashboard is tailored to meet the unique needs of admins and includes both frontend and backend implementations, as well as thorough testing to ensure the functionality and usability of the dashboard. The ultimate goal is to provide admins with a comprehensive and user-friendly platform for effectively managing content and ensuring the high quality of the platform. <br/><br/> **For admins who wants to make fast updates on their mobile devices also Android and IOS apps will be deployed.** | 2 weeks  | - | 5000 |
| 4 - Social Media Management | I will manage the **@awesomeonflow** Twitter account and keep the followers of the Awesome Flow community updated on the latest projects added to the platform. Additionally, I will create monthly threads to share developments with the community. <br/><br/> Also projects will be followed and helps to reach larger audience with range of methodologies, I will take a support from social media managers and committed to grow Awesome Flow twitter account at least for a year |  1 year | - | 4200 |
| 5 - Maintenance | To ensure the best possible user experience, I will actively monitor the Awesome Flow platform for any bugs or technical issues that may arise. I am committed to maintaining the platform's quality, and any problems that are identified will be addressed promptly.<br/><br/> I will conduct ongoing maintenance and support for a year to ensure the smooth functioning of the platform. If users encounter any issues while using Awesome Flow, they can report them by creating a GitHub issue or by filling out a form that is available on the website. <br/><br/> My goal is to provide a reliable and user-friendly platform for the web3 community, and I am dedicated to addressing any issues that arise in a timely and efficient manner. | 1 year | - | 5300 |

Total funding proposed: $27500
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Tolga Yaycı | Full-Stack Developer | As a full-stack developer with 3 years of experience, I have improved my skills in software development, with a focus on dApp development in the past year. I have a deep interest in the Web3 and NFT space and have put my skills to the test by creating a number of relevant applications. In addition to my experience, I have developed detailed React and Next.js projects, further enhancing my ability to build robust and scalable web applications <br/> <br/> In addition to my technical skills, I have also been actively involved in the wider tech community. I have served as a Chainlink Community Advocate, Aave Turkey Community Manager, and Founding Chair of ACM Student Chapter. My previous role as a Microsoft Learn Student Ambassador has also given me the opportunity to share my knowledge and experience with others. I have set of experiences and skills and particularly in the areas of full stack software development and community management.| tolgayayci@protonmail.com |

**Comment by alxflw** [comment]
Hi @tolgayayci, we reviewed your proposal in detail and decided to pass because it is unclear if the impact on the developer ecosystem will be high enough.

Thanks for taking the time to submit your proposal and feel free to reach me directly on Discord in case you have further questions: `alx-flw.find#6198`.
