### ISSUE TITLE
FlowPulse: Analytics Dashboard for Exploring Activities in Flow

### ISSUE THREAD

**Issue by justmert** [onflow/developer-grants#154]
# FlowPulse

# Grant category

`Developer tools / services`

# Description

Flow open source developer ecosystem is growing day by day. But there is currently no way to get an activity overview and easily track the development among different projects that is integrated with Flow or tools/components of Flow ecosystem on Github. Understanding the status of projects and tracking contributions made by developers can give an idea on how the Flow evolve. It is really hard to understand how the Flow ecosystem is progressing since the data is scattered all over GitHub, with contributors, commits, issues, repositories and PRs data.

The solution I present to Flow community is a platform that provides visualizations and insights for open source projects in the Flow ecosystem named FlowPulse. It offers a comprehensive view of activities of projects and insights into the ecosystem's trends. The project will allow users to gain insights into the development activity, code contributions, issue resolution, and community engagement of the Flow ecosystem through open source projects. This information will be displayed through various visualizations and charts, which will be accessible through a web-based application named **FlowPulse**.

**Website**: https://flowpulse.vercel.app
**Open-Source Backend**: https://github.com/justmert/eco-pulse-backend
**Open-Source Frontend**: https://github.com/justmert/eco-pulse-frontend

### Target audience

The target audience for FlowPulse can include developers, researchers, and enthusiasts who are interested in monitoring the development and activity of open-source projects on the Flow ecosystem. The platform's analytical tools and visualizations can provide valuable insights into the performance of various projects, making it useful for those who want to gain a better understanding of the ecosystem's progress and the direction it's headed in.

By tracking the activity of commits history, and issue resolution FlowPulse can help developers identify areas where they can improve and streamline their own development processes. By offering detailed analytics, FlowPulse can become an essential tool for anyone who is interested in the development and progress of the Flow ecosystem.

### Evidence for the need

* **Increased Interest in Flow Ecosystem**: The growth of the Flow ecosystem and the increasing number of open-source projects being developed on the chain highlight the need for a tool that can monitor and analyze the performance of these open-source projects. FlowPulse can provide valuable insights for the projects within the ecosystem.

* **Lack of Comprehensive Analytics**: There is a lack of reliable and user-friendly tools that can provide detailed analytics and visualizations for open-source projects on Flow. Besides, the demand for better analytical tools in the blockchain space is increasing, and developers and stakeholders are seeking tools that can help them monitor and analyze the performance of the projects. FlowPulse fills this gap for the Flow ecosystem.

* **Historical and Trend Data**: FlowPulse can provide a historical and trend data of the Github activity in the Flow ecosystem, allowing developers and project managers to see first hand how the ecosystem is growing, evolving, and changing over time. This data can be used to identify patterns, trends, and areas of improvement, leading to more informed decision making and better outcomes for the projects within the ecosystem.

## Impact

**Improve Project Visibility**: By providing detailed analytics and visualizations for Flow projects, FlowPulse can help increase the visibility of these projects, making it easier for developers and users to find and contribute to them.

**Enhance Developer Productivity**: With the ability to quickly access important data and metrics, developers can more easily identify areas of the project that need attention. This can lead to faster issue resolution and more efficient development cycles.

**Encourage Community Engagement**: By providing a centralized location for viewing project activity and contributions, FlowPulse can encourage community engagement and collaboration. Users can easily identify areas where they can contribute to the project and engage with other developers and users.

**See Ecosystem Evolution**: FlowPulse can help show the evolution of Flow projects over time by providing historical data and visualizations of key metrics, enabling developers to better understand the project's development trajectory and identify areas where protocol gains trends.

**Stands Out**: Currently, there is no project that provides a comprehensive analytics dashboard for open-source projects in the Flow ecosystem. FlowPulse fills this gap and provides value by enabling developers and stakeholders to easily gain insights into the activity and performance of Flow projects.

## Project Images
![flowpulse-website-images](https://user-images.githubusercontent.com/37740842/222190675-eee26044-c706-4beb-aaa6-3d0252266b38.png)

## Technical Scheme

![flowpulse-scheme-svg](https://user-images.githubusercontent.com/37740842/222190389-dd704697-ef28-4fe0-a384-4e893f313ecb.svg)

# Milestones and funding

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Building   |  <ul><li>Add an MIT License to the project's backend and frontend Github repositories.</li><li>Set up a Firebase Firestore database.</li><li>Develop a Python backend to fetch data from Github Rest and GraphQL APIs.</li><li>Build the Dashboard, Project List and Project Detail pages with corresponding backend functions.</li><li>Integrate Algolia to enhance the search functionality of the platform.</li><li>Incorporate Typeform to allow ecosystem users to suggest new projects for FlowPulse.</li><li>Integrate Google Analytics to track user engagement and adapt and improve the platform accordingly.</li></ul>  | 5 weeks  | - | 7500           |
| 2 - Deploying   |  <ul><li>Add initial project list of the Flow ecosystem to the Firestore database.</li><li>Deploy backend to Heroku.</li><li>Schedule the backend to update project data in Firestore on a regular basis.</li><li>Change domain name of FlowPulse to flowpulse.xyz.</li></ul>  | 3 weeks  | - | 1500           |
| 3 - Expanding   |  <ul><li>**User Profiles**: Create user github integration that allow users to showcase their Github contributions and connect with other developers in the Flow ecosystem. User profiles could show users' Github statistics, such as their total commits, pull requests, and issues, as well as their recent activity based on Flow projects. <br>The feature could provide a way for developers to showcase their contributions to the Flow ecosystem and build their personal brand. Users could use their profiles to connect with other developers, discover new projects to work on, and showcase their skills.</li><br><li>**Leaderboards**: Improve upon top contributors section to provide leaderboard system that allow users to compete with other developers in the Flow ecosystem based on Github activity. This provide an incentive for developers to contribute more to the Flow ecosystem and showcase their skills. The leaderboard system could track metrics such as the number of commits, pull requests, issues resolved, and lines of code written etc.</li><br><li>**Bounty Issues**: Allows developers and projects in the Flow ecosystem to offer bounties for specific Github issues. Developers could view a list of available bounty issues, which would include information on the bounty amount, the issue details, and the requirements for resolving the issue. Developers could then claim a bounty issue and work on resolving it. Once the issue has been resolved and verified by the project owner, the developer would receive the bounty amount.<br>The feature could help to incentivize developers to work on high-priority issues in the Flow ecosystem and provide a way for developers to earn money for their contributions. Projects could use this feature to attract new contributors and accelerate the development of their projects. Additionally, this feature could help to connect developers with projects that align with their interests and expertise, leading to more effective collaboration and faster issue resolution.</li></ul>  | 8 weeks  | - | 6250           |
| 4 - Maintenance   |  As the Flow ecosystem grows and evolves, it's important to ensure that FlowPulse remains a reliable and high-quality source of Github analytics and insights. I will focus on implementing best practices for code quality, testing, and documentation, to ensure that the platform remains stable and easy to maintain over one year. This will involve regular bug fixes and updates to accommodate changes in the Github API and other external factors that may affect the functionality of FlowPulse.  | 1 year  | - | 2250           |

**Total funding proposed**: $17.500
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Mert Köklü | Full-Stack Engineer | Founding vice-chair of ACM Student Chapter and acted as an ambassador of many organizations including Microsoft and Certified Instructor of NVIDIA. In Web3, AAVE Turkey Community Co-Manager and The Graph Advocate. Was working with AI video pipelines at an NVIDIA distributor company in Turkey before getting involved with blockchain.<br><br>I'm AAVE and Filecoin grantee with an already accepted 3 projects. Now, I am developing open-source, user-friendly applications that add value to the ecosystem in the Flow ecosystem.| kklumert@gmail.com |

# Additional Information

Vercel deployed frontend (flowpulse.vercel.app) has initially 17 repositories because of the demo purposes. After milestone 2, the project will have more repositories initially curated by me (or request from the onFlow Team) and the more can be added by the community via Submit button in the app. If you have any questions or requests, please feel free to contact me. Thank you.

**Comment by alxflw** [comment]
Hi @justmert. Thanks for your submission. We really like your proposal and would like to move forward- pending alignment on the following:

1) Would you be open to building a crawler to automatically update / add / remove repositories? It will be critical to have a way to stay relevant as the list of repositories change over time

2. Would you be open to adding more developer metrics specific to our network? (eg contract deployments, interactions with contracts, etc)

**Comment by alxflw** [comment]
thanks @justmert - that makes sense. I think it would be great if we could include "ecosystem activity" metrics, similar to what can be found on https://www.developerreport.com.

We'd like to accept this grant proposal. I'll email you the next steps.

**Comment by fotescodev** [comment]
@justmert just found your project and you have no idea how helpful it is already. One ask - is there a way to include a `hackathon` tag for Flow Hackathon participants? That way we can shuffle through all hackathon projects and sort as needed. Usually these have a great value as sample projects.

**Comment by alxflw** [comment]
> Flow Hackathon

FYI - the list of projects is here: https://flow-hackathon.devfolio.co/projects. Most of them have public GH repos

**Comment by bluesign** [comment]
For the lazy: `curl -s  http://tymianek.com/flow/ | grep "https://github.com" | grep href | sed "s/href=\"//" | sed "s/\".*//" | sort`

**Comment by bluesign** [comment]
Yep it is scraped from the hackathon page after the hackathon. Should be same.

**Comment by Aliserag** [comment]
Closing this down as it's been completed :)
