### ISSUE TITLE
🧙‍♂️ Gandalf Protocol - Grant Application

### ISSUE THREAD

**Issue by Rishikeshk9** [onflow/developer-grants#155]
# 🧙‍♂️ Gandalf Protocol

# Grant category

Developer tools / services

# Description

The Gandalf Protocol is an innovative solution that provides a highly secure and encrypted way of storing data on the Flow blockchain. It uses advanced encryption algorithms and distributed private keys to protect users' data and ensure maximum security and reliability. The protocol can be used for various scenarios where data needs to be private, such as password managers, identity protocols, and databases.

## Problem statement

The lack of secure and efficient data storage solutions on the Flow blockchain has been a challenge for developers looking to build Dapps that require private and secure data storage. This project targets developers who need to store sensitive data in a secure and reliable manner on the Flow blockchain.

## Proposed solution

The proposed solution is to develop and deploy the AssetControl Contract on Flow Testnet, which will save a specific encryption key on the user's storage, and decrypt it with a secret key stored inside Gandalf Protocol. The protocol will be managed by a Distributed Key Generation (DKG) algorithm, and multiple nodes will generate the secret key when required.

### Architecture

![Gandalf Protocol](https://raw.githubusercontent.com/Rishikeshk9/Gandalf/main/Gandalf.png)
This will enhance the security of the encryption and decryption process. The software will provide an interface for users to encrypt and decrypt their files and user storage key-value data using the secret key stored in Gandalf Protocol. The software will also provide an API that can be used by Dapps to encrypt and decrypt data.

## Impact

The Gandalf Protocol will benefit the broader Flow developer ecosystem by providing an efficient and secure way of storing data on the Flow blockchain. This will enable developers to build Dapps that require private and secure data storage, accelerating development and expanding the FLOW ecosystem.

# Milestones and funding

| Milestone                          | Deliverables                                                                                                                   | Timeline | Risks | USD proposal |
| ---------------------------------- | ------------------------------------------------------------------------------------------------------------------------------ | -------- | ----- | ------------ |
| 1 - Building Backend and DKG       | Improving Security in Backend for Encryption Decryption process by implementing Distributed Key Generation (DKG)               | 4 weeks  | -     | 20000        |
| 2 - Robust API Development         | Developing robust API Structure for backend, and Improving Cadence Smart Contracts which will be executed on the users wallets | 4 weeks  | -     | 20000        |
| 3 - Frontend Development           | Develop frontend for Gandalf Protocol Management                                                                               | 4 weeks  | -     | 7500         |
| 4 - Testing, Documentation, Launch | Creating Docs for Gandalf Protocol, Testing and Deployment to Mainnet                                                          | 4 weeks  | -     | 7500         |

Total funding proposed: **$55000**

# Project Details

We have developed a small prototype on Flow Blockchain at Devfolio Hackathon - https://devfolio.co/projects/gandalf-d16b

**Other Links:**

- [Github - Frontend](https://github.com/Rishikeshk9/Gandalf)
- [Github - Backend](https://github.com/Rishikeshk9/gandalf-backend)
- [Website - Frontend](https://gandalf-protocol.vercel.app/)
- [Website - Backend](https://gandalf-backend-u8mr3.ondigitalocean.app/)
- [Contract](https://flow-view-source.com/testnet/account/0x88d8816248a970ff/contract/AssetControl11)

# Team

- Rushikesh Kardile - [Github](https://github.com/Rishikeshk9), [LinkedIn](https://www.linkedin.com/in/rushikeshkardile)

- Vinay Sudrik - [Github](https://github.com/optimus789), [LinkedIn](https://www.linkedin.com/in/vinaysudrik)

| Name              | Role       | Contact                     |
| ----------------- | ---------- | --------------------------- |
| Rushikesh Kardile | Co-Founder | rushikeshkardile9@gmail.com |
| Vinay Sudrik      | Co-Founder | vinaysudrik@gmail.com       |

**Comment by alxflw** [comment]
Hi @Rishikeshk9, we reviewed your proposal in detail and decided to pass because it is unclear if the impact on the developer ecosystem will be high enough. We have yet to see strong evidence that developers need this today. We certainly see the potential of your solution, but the demand is unclear.

Thanks for taking the time to submit your proposal and feel free to reach me directly on Discord in case you have further questions: `alx-flw.find#6198`.
