### ISSUE TITLE
Flow Builder House - Emerald Brazil

### ISSUE THREAD

**Issue by diegofornalha** [onflow/developer-grants#157]
# Grant category

Emerald:
- Community: https://discord.gg/hT8EpC5mUN

# Description

The goal of this project is to promote the adoption of Flow technology in our region, involving developers, enthusiasts, and students

## Proposed solution
**Official Launch of Flow Builder House:**
We will officially announce the project on May 15, with a technical session and information during the global hackathon.

**Team Formation Sessions:**
We will hold meetings to facilitate the creation of teams interested in participating in the global hackathon and developing ideas using Flow technology.

**Bootcamps in partnership with Emerald City:**
We will promote bootcamps in partnership with Emerald City to empower developers and prepare them for the global hackathon.
[link](https://github.com/emerald-dao/emerald-academy-v2/tree/dida-portuguese)

**Collaboration with Local Innovation Hubs:**
We will establish partnerships with local innovation hubs willing to support Flow-related events and expand our presence in the community.

**Competition between two cities:**
We will adopt a competitive approach between Rio de Janeiro and Florianópolis, encouraging participation and engagement from both local communities. If this dynamic works well, we will expand to other cities.

**Local Award Events:**
We will organize events to award the winners of the hackathon and record these moments on video, creating promotional material to promote future Flow-related events.

# Team
Name | Role | Bio | Contact
-- | -- | -- | --
Diego Alcantara | Official Ambassador at Flow | Founder Coflow | diegofornalha@gmail.com
Bianca Lima | Head of Operations | CoFounder Coflow | bianca@coflow.com.br

**Comment by alxflw** [comment]
Thanks for the submission @diegofornalha! We have a few follow up questions:

1) Would part of the 30k be part of the prize money?

2) What kind and how many developers would you be able to acquire?

3) Would you be open to adding more achievement milestones (eg X developers attended)?

**Comment by diegofornalha** [comment]
Thank you for the response @alxflw, I am happy to develop this work together with you!

1. Yes, part of the 30k would be used as prize money for the winners of the hackathon. The intention is to incentivize developer participation and reward their work and creativity in creating innovative solutions.

2. Given that there is a large portion of people who are already coding blockchain applications, it is possible to gather more than 500 developers to participate in the hackathon.

3. Yes, we would be open to adding more achievement milestones. We are considering the following strategy: for the formation of 50 to 74 groups, we would receive 50% of the total value, which is 15k. For the formation of 75 to 99 groups, the value would be proportional, reaching 22.5k. For the formation of over 100 groups, the total value would be 30k.

btw: An average of 5 people per group.

**Comment by alxflw** [comment]
thanks for the follow up @diegofornalha. we'll review that and let you know shortly

**Comment by alxflw** [comment]
@diegofornalha and to be clear - how much money would you allocate for the prizes in each milestone?

**Comment by diegofornalha** [comment]
3000 tokens - 1nd
2000 tokens - 2nd
1000 tokens - 3rd

**Comment by diegofornalha** [comment]
Thanks @alxflw - It would be my pleasure to answer any questions you have.

1. Yes, it will be in person.
2, 3. We are open to adjusting the cost structure if you have any suggestions. We plan to hold our hackathon concurrently with the global hackathon. I have already reached out to a supplier for the rental of the physical venue, who will also be responsible for providing catering for the participants and filming the event. I will be personally involved in all stages of the event's organization.

Here is a preview of the local broadcast of the hackathon award ceremony:
https://www.youtube.com/watch?v=TqbmhcLSnVk

**Comment by muttoni** [comment]
Hi Diego, I'll be reviewing this going forward. Let's start by going through a more granular cost breakdown, and we can adjust from there. We can also discuss this in our meeting on monday.

**Comment by diegofornalha** [comment]
Hi @muttoni, I am improving the proposal to adapt to the Flow Builder House format. Until our next meeting, I will update this issue with more details.

**Comment by diegofornalha** [comment]
> Thanks @alxflw - It would be my pleasure to answer any questions you have.
> 
> 1. Yes, it will be in person.
>    2, 3. We are open to adjusting the cost structure if you have any suggestions. We plan to hold our hackathon concurrently with the global hackathon. I have already reached out to a supplier for the rental of the physical venue, who will also be responsible for providing catering for the participants and filming the event. I will be personally involved in all stages of the event's organization.
> 
> Here is a preview of the local broadcast of the hackathon award ceremony: https://www.youtube.com/watch?v=TqbmhcLSnVk

@SeanRobb At @Aliserag request, I am conducting a survey of the work developed in 2023.

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time given the time since this was requested. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
