### ISSUE TITLE
Web 3 Domain Provider For Flow 

### ISSUE THREAD

**Issue by Da-Alien** [onflow/developer-grants#159]
# <Web 3 Domain Provider For Flow>

# Grant category

Please select one:

- Open source maintenance

# Description

Supplying Flow with interoperable Web3 domains that operate across any Dapp.

More importantly, that help enable mass-adoption through usability and enhance the web 3 experience.

## Problem statement

The Web3 space is still growing, and Flow is doing an incredible job to facilitate mass-adoption.
However, the blockchain space as a whole still have some challenges:

1 - Crypto is still a little bit complicated for some users.
2- NFTs still have a problem with copies and Theft.
3 - Web 3 Domains (Identities) can operate on certain Dapps/Chains but not others.
4 - Merchants still find some challenges with accepting Crypto, despite all the innovation (QR codes..etc)

What if we could address all these problems, all while enhancing the user's experience?

*P.S: We’re talking about supplying FLOW’s users (and Dapps built around the ecosystem) with both FREE and paid options since some users prefer to purchase their own Custom domains.

In which case Flow gets immediate on-chain revenue split.*

Below, we’ll explain how we can solve all these aforementioned problems.

## Proposed solution

Problem 1: FIO domains removes complexity and makes sending crypto as easy as sending an email.

Problem 2: FIO Domains have a functionality called NFT signature where the users can sign  their NFT with a click, thus verifying their authenticity on chain.

(This is great for tickets sales, or for artists trying to protect themselves against forgery)

Problem 3: For merchants, FIO domains have a FIO request functionality where the vendors can set the price, request the payment from the clients in super user-friendly way.

All the client have to do is to slide accept or reject the payment making their crypto experience seamless.

**Other advantages:**

*FIO Protocol is compatible with all blockchains:*

FIO Protocol is blockchain-agnostic, meaning every FIO Crypto Handle you create on your FIO Domain can be used to transact with any DAPP built upon Flow.

By the same token, it’s super easy to onboard users from other blockchains into the Flow ecosystem.

## Impact

Far more than just a URL, crypto domains are more akin to next generation digital identities. The very key that allows you to interact with the rapidly growing web3 ecosystem. User-friendliness is key in this regard.

From NFT marketplaces, to blockchain social media, gaming in the metaverse… your entire web3 experience will be accessed by your own personal crypto domain. 

FIO Domains and handles have many groundbreaking usability features that makes the web 3 experience so seamless for novices and pros alike.

For more info, Messari has done an amazing job explaining how FIO domains are meant to accelerate mass-adoption through usability.

https://messari.io/report/fio-enabling-crypto-adoption-through-better-usability

In short, we think that usability will benefit the all the Flow ecosystems because historically, user-friendly products tend to accelerate mass-adoption,

Also, the free and affordable domain options could open the doors for many users in many poor parts of the world that may or may not afford to have their own web 3 domain and feel like a part of the community,

# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 -    | Integration | 2 weeks  | - | 3000           |
| 2 - Education videos and Marketing   | Producing 4 educational videos about Flow | 2 weeks  | - | 2000           |

Total funding proposed: <5,000 USD>
  
# Team

| Adil Elias | Growth & Latam Lead  | https://www.linkedin.com/in/thealien | adil@fioprotocol.io         |
| ---- | ------------------- | --- | --------------- |
| Wayne Marcel | Head of Business Development |https://www.linkedin.com/in/blockchainwayne/ | Wayne@fioprotocol.io |

**Comment by alxflw** [comment]
Hi @Da-Alien, we reviewed your proposal in detail and decided to pass because it is unclear if the impact on the developer ecosystem will be high enough.

Thanks for taking the time to submit your proposal and feel free to reach me directly on Discord in case you have further questions: `alx-flw.find#6198`.
