### ISSUE TITLE
Decentralised Carbon Offsetting

### ISSUE THREAD

**Issue by muttoni** [onflow/developer-grants#16]
## Abstract
At Flow, sustainability is not a feature - it’s table stakes. Beyond providing a sustainable architecture that uses significantly less energy than other platforms for web3 applications, we want to enable creators, developers and companies to make their products entirely carbon neutral - and possibly even climate positive. To achieve this, Flow is giving out a community grant for a scalable on-chain solution that allows for measuring, offsetting and verifying carbon emissions produced by application-specific transactions.

## Solution requirements
The solution needs to enable application developers to opt-in to carbon offsetting for their users’ transactions. This means that any amount for carbon offsetting needs to be deducted from the side of the application, and end-users should not need to pay offsets. The solution must at least include the following minimal viable features: 

1. **Measure**: Cadence transactions can vary greatly in their complexity, and thus use different amounts of energy. Measuring this relative complexity is the first starting point of the solution. These measurements can be estimates, and methods of measuring can vary, as long as they relate back to the global emissions data of Flow’s network.
2. **Offset:** The solution needs to enable application developers to take carbon offsetting action, ideally by helping them to set aside funds for emissions generated by their application and using this budget to pay for carbon offset credits on a recurring basis.
3. **Verify**: Any offset conducted by an application needs to be verifiably tracked and stored on-chain as proof, such that applications can guarantee carbon offset action was taken. Ideally, the solution provides an indicator applications can use for their client-facing communication to showcase this positive social action.

Since the implementation of this specification will most likely require an escrow account for offset amounts, an emphasis on security best practices and the avoidance of single points-of-failure are of utmost importance. Ideally, the offramp mechanism (on-chain tokens convert to fiat donations to carbon offset projects) should be transparent and traceable. 

## Grant details
The winning proposal will be awarded a grant of up to 80,000 USD worth of FLOW to develop the proposed solution. The grant will be paid out in four stages, according to the project progress.

## Submission requirements
Any submitted proposal should give a detailed overview of the planned solution. 

**1) Technical architecture & code examples (3-10 pages)**
Give a thorough overview at a high level of how the solution will look like. Name all the services that you are planning to use and describe how they fit into the overall architecture. 

**2) Team**
Tell us a bit about yourself and the team you are working with. Do make sure to list any blockchain-specific projects or skills you may have.

**3) Roadmap**
Give us a description on what timeframe you are planning to implement the solution and when each milestone of your project will be finished. 

**4) Financing**
Do provide us with a rough estimation on how you are going to allocate the grant for building this solution.

**Comment by Guisong-Fu** [comment]
Hi @muttoni , our team has some ideas on this Grant, would you have time for a quick talk? There are a few things that we would like to discuss with you 🙂 Thanks!
