### ISSUE TITLE
YARchain.org

### ISSUE THREAD

**Issue by YARlabs** [onflow/developer-grants#160]
# YAR

# Grant category
- Open source maintenance

# Description
YAR - blockchains interconnector that brings together all of blockchains in one place, in any place.

## Problem statement

1. Market Problem:
Currently, we have more than 800 blockchains, and 1 HUGE problem
Lack of infrastructure solutions for the interaction of blockchains with each other.
—
No blockchains and protocols communicate with each other.
All countries, regions, banks, corporations, and people can communicate with each other, and all of us understand that communication is only one way to run the world and bring all our minds into every house.
2. YAR solution:
Establish high-level communication standards (protocol, layer) which take support all types of existing private and public blockchains and protocols. The protocol should have an automation center that can create links between connected entities and of course it should be yet another blockchain. Of course, this blockchain should support smart contracts with end-to-end security states and should have a featured interface for communication person-2-person, person-2-many-persons, many-persons-2-many- persons, and many-persons-2-person. This blockchain should be established like a fully decentralized issuer. That is why we choose EVM as the root of the new blockchain and PoS as the dominant consensus. The new blockchain will be managed like DAO by node-validators. It means that all discussed changes in blockchain logic and mechanic will become reality only after the node-validators vote. It means that the transaction fee will always cost less than 0.01$ no matter what will YARcoin price is. It means that all needed updates will be implemented just after voting will be done.

## Impact
YAR makes any blockchain interoperable with FLOW, and FLOW is interoperable with any blockchain. It means more assets, more transactions, more users, and more cash flow. It means that assets from another blockchain can be tradable and transferable into FLOW, into FLOW-based projects. It means more TVL, more community, and more power.

# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - FLOW connector developing   | Connector | 1mo  | - | 50000           |
| 2 - FLOW connector developing   | Smart Contracts | 2mo  | - | 20000           |
| 2 - FLOW connector developing   | Implementation | 2mo  | - | 30000           |

Total funding proposed: 100'000USDT
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Sergey Glukhota | YAR Starter (CEO) | https://glukhota.com | sergey@glukhota.com |

**Comment by alxflw** [comment]
Thanks for the submission @YARlabs. We reviewed your proposal in detail and decided to pass because it is unclear if the impact on the developer ecosystem will be high enough.

Thanks for taking the time to submit your proposal and feel free to reach me directly on Discord in case you have further questions: `alx-flw.find#6198`.
