### ISSUE TITLE
Nilos (5.2m$ raised) - All in one banking platform to receive, track & pay in crypto and fiat.

### ISSUE THREAD

**Issue by Nilos0xLabs** [onflow/developer-grants#163]
# <Project name> Nilos (5.2m$ raised) - All in one banking platform to receive, track & pay in crypto and fiat.

# Grant category

Please select one:

- Open source maintenance
- **### Developer tools / services**
- Educational material

# Description
We help companies manage both their fiat and crypto operations, stay compliant and achieve financial viability.

We’ve built a full web3 business account for businesses that deal with both crypto and fiat incomes.
1. We provide secure multi chain custodial MPC wallets and dedicated multi currency IBANs (available in 2 months) so they can receive crypto and fiat payments easily. They don’t even need a bank account or a wallet infrastructure. Onboarding has been streamlinined to a 7 minute process.
2. The ability to dynamically tag & label transactions to have financial visibility over incomes and reconcile transactions easily for accounting purposes.
3. We allow easy crypto to crypto and crypto to fiat payouts.
We take care of invoicing, compliance and integration into traditional accounting softwares as well. It really feels like using a traditional neo bank, you almost don’t know you’re using crypto.
We partner on MPC with Fireblocks & Dfns, on IBANs with Modulr and on compliance/KYB with Elliptic, Comply Advatange and Ubble.
We’re working with merchants in both web2 and web3, some names include : Warner Music, LOSC Football Club, Ami Paris... We’ve raised 5.2m$ from Fabric and Viola and 20+ angels earlier this year.

Project impact :
Nilos is excited to have a chance to change the way companies manage their financial treasury and infrastructure in the web3 space. Making it more excisable, cheaper and cover their financial needs allowing them to focus on building and scaling their business.

## Problem statement

- Target audience
We target initially web3 dapps on specific ecosystems and focus on three main acquisition channels : referrals from investors or network, direct sales on linkedin and strong partnerships with blockchain ecosystem leads.

- Evidence for the need
Why now ? Web3 companies are building the foundations and guidelines of navigating this growing market along with a growing number of web2 companies that are looking to enter the space. Now is the time to enable an easy and excisable way for them to handle their finance and feel secure in the space.

## Proposed solution
More than money ($5.2m raised), Nilos wants to get in touch with your ecosystem leads to see how we can integrate our solution / generate value for our respective users. Nilos would need $10k to educate your blockchain users about our solution.

## Impact

- In what ways does this benefit the broader Flow developer ecosystem?
Thanks to Nilos, Dapps from integrated blockchains will be able to manage both their fiat and crypto operations seamlessly, stay compliant and achieve financial viability; boosting the whole ecosystem by enabling business holders to focus on bulding & scaling their businesses.

# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| N/A | educate your blockchain users about our solution | N/A  | Breach of client funds | 3333            |
| $50k in transaction volumes processed by Nilos on your ecosystem | educate your blockchain users about our solution | by Q3 2023  | Breach of client funds | 3333           |
| $100k in transaction volumes processed by Nilos on your ecosystem | educate your blockchain users about our solution | by Q1 2024  | Breach of client funds | 3333           |

Total funding proposed: <$10,000>
  
# Team

| Name | Role                | Bio | Contact         |

| Raphael Fettaya | Co-Founder & CEO | 5 years data scientist across different companies like check point and microsoft. | https://www.linkedin.com/in/raphael-fettaya/
| Eytan Messika | Co-Founder & CMO | 2 years as consultant and 1 year as founder | https://www.linkedin.com/in/eytanmessika/
| Israel Bismuth | Software Engineer | 1 year data scientist, 1 year computer vision engineer | https://www.linkedin.com/in/israel-bismuth-00b666106/
| Alexandre Sadoun | Head of Compliance | 6 years AML compliance specialist and senior analyst at Western Union, 5 years Mission Chief, Ministry of the Interior. | https://www.linkedin.com/in/alexandre-sadoun-94724729/
| Idan Berkovich | Software Engineer | 2+ years backend logic design engineer at intel, 4 years reaserch and cloud software engineer at IBM. | https://www.linkedin.com/in/idan-berkovich-5a2420b9/
| David D | Back end Developer | 2 years data engineer, 2 years senior backend engineer and backend tech lead, 1 year technical lead and CTO. | https://www.linkedin.com/in/dooy/
| Vlada Belopolskaya | Frontend Developer | 5 year Frontend Developer | https://www.linkedin.com/in/vlada-belopolskaya/
| Kevin Louzoun | Lead Front-End Engineer | years as advisor and founder, 2 years as front-end lecturer | https://www.linkedin.com/in/kevinsz/
| Roy Reuveni | Senior UX · Brand & Product Specialist | 2+ years product designer and design manager at Fiverr, 8 years as head of design and founder of varied companies- 2 years as business development and sales manager in B2B sales. and start-ups | https://www.linkedin.com/in/roy-reuveni-01439720/
| Danielle Lotan | Strategy and Growth | https://www.linkedin.com/in/danielle-lotan-959b8913b/
| Corentin Cadieu | Advisor | 5 years in M&A, Serial WEB3 entrepreneur | https://www.linkedin.com/in/corentincadieu/

**Comment by alxflw** [comment]
thanks for the submission @Nilos0xLabs. this doesn't seem to be a project that target developers through deliveries like new/updated SDKs, APIs, or other dev tools/content. It seems like you would like to create awareness for your project, which is not a good fit for this developer grants program. 

feel free to reopen with more details if you think otherwise.
