### ISSUE TITLE
With The Flow - A Social Network

### ISSUE THREAD

**Issue by staystacced** [onflow/developer-grants#169]
Project name: With The Flow

# Grant category

Please select one:

- Open source maintenance/Educational Material

# Description

‘With The Flow’ is a centralized space for users to receive updates, aggregated data, and news regarding the latest happenings within the Flow ecosystem. The platform aims to provide users with a more efficient and streamlined way of accessing information rather than having to scour various social media channels such as Twitter and Discord. 

## Problem statement
The Web3 ecosystem is rapidly growing, with new projects, platforms, and updates emerging on a daily basis. While Twitter and Discord are popular channels for staying up-to-date on the latest happenings, they can be overwhelming and time-consuming to navigate.

There is a clear need for a centralized space where users can easily access information regarding the Web3 ecosystem. Additionally, as the ecosystem continues to grow, there is an opportunity for the platform to expand into a social network and offer additional features and services.

The target audience is the entire Flow NFT ecosystem. There are many quality projects (NBATopShot, NFL All Day, Seussibles, DimensionxNFT, Hoodlums, Ballerz, Jolly Jokers, and more). These projects often have updates and news that occur weekly. Having to continually check the different platforms for news can be exhausting, ultimately leading to losing interest in the project/space as a whole. We believe greater engagement will lead to greater long-term returns to the Flow Ecosystem. 

- Target audience
- Evidence for the need

## Proposed solution
The proposed solution is to build a central platform that aggregates where collectors within multiple communities and collections will receive updates and information. This platform will allow two types of users: creators and community members. Creators will be responsible for updating their community. Community members will see these updates, as well as create updates of their own that other community members can verify. 

The platform will incentivize community members to validate each other’s posts as well as work together to create accurate, timely news. 

## Impact

Greater knowledge will lead to greater engagement. Greater engagement within the Flow ecosystem across the board may lead to greater spending, greater awareness, and greater incentive for projects and communities to engage in further utility for their community members. 

- In what ways does this benefit the broader Flow developer ecosystem?

# Milestones and funding

To Discuss. Currently have 2 other team members, one is creating a project similar to this one ETH, and the other is a developer who has access to a network of developers who would be able to work on this project. 

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - MVP   | Smart Contract | TBD weeks  | - | TBD           |
| X - Adoption   | 5 team using this project | TBD weeks  | - | TBD           |
| X - Maintenance   | Resolving issuing and fixing bugs | TBD months  | - | TBD           |

Total funding proposed: <TBD>
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Michael | Project Lead | ... | towerlife503@gmail.com |

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
