### ISSUE TITLE
DAOs: A new form of socio-economic institution -- Academic research & educational video

### ISSUE THREAD

**Issue by luischoening** [onflow/developer-grants#17]
# <An Institutional analysis of DAOs: A new form of socio-economic institution >

# Grant category
- [x] Educational material

# Description

Economic research on DAOs at the University of Cambridge summarised into an educational video on social media. 

The public hype about DAOs has largely overlooked a further possibility: that blockchain is an institutional technology enabling the coordination of new types of economic activity that were previously not able to be governed by firms, markets, or governments because the transaction costs were too high to justify the expected benefits (Davidson et al. 2018). Davidson et al. (2018:654) define decentralised collaborative organisations (DCOs), as “self-governing organisations with the coordination properties of a market, the governance properties of a commons and the constitutional, legal and monetary properties of a nation-state.” 

Firstly, I will follow academic suggestions and take a transaction cost economic approach to produce an academic framework that promotes a fundamental understanding of how blockchain-based organisations extend the boundaries of the market and state. 

Secondly, I plan to turn the 15,000 words research findings into a short and digestible video that will be promoted on social media in order to drive education creation and adoption of DAOs on the Flow blockchain. 

## Problem statement

Target audience: 
- Academic Paper: Academic researchers, economists, policy-makers
- Educational video: Entrepreneurs, creators, investors, users

Evidence for the need: 
- Wright and De Filippi (2015) argue that these DAOs are collective and social institutions that promote greater participation, potentially transforming corporate governance and democratic institutions. 
- However, a lack of transparency, knowledge and a clear definition of decentralised autonomous organisations (DAOs) leads to a large amount of noise around what a DAO is, what it is useful for and how it challenges existing socio-economic institutions like states, and corporations and banks. 
- Most people have not fully understood blockchain technology’s potential to be used as a digital property system and a mechanism for economic coordination through token incentives, automation and democracy.

- ## Proposed solution
Under the supervision of Professor Shailaja Fennell at the University of Cambridge, I will create an institutional economic framework to understand the impact of (i) token incentives, (ii) smart contracts, and (iii) the degree of decentralisation at DAOs on the economic transaction cost of an organisation. 

Methodology: 
- Empirical data collection on the largest DAOs and a review of existing literature will provide a foundation for further research and decision-making for policy-makers, investors and economists. 
- The paper will include new qualitative and quantitative insights from leading industry experts, including founders, investors, lawyers and decision-makers at traditional institutions such as Nomura and the German Central Bank, as well as emerging DAO founders and crypto natives.

- The proposal for the academic research paper has been approved by Professor Fennell and the Department of Land Economy at the University of Cambridge. You can read it here: https://garrulous-foxtail-d3f.notion.site/Research-Proposal-6732c65bde564ab2ad4073530482906b

Video
- Partner with a leading communications agency and publish findings in an entertaining and educational video on major social media channels with the goal to reach and inspire thousands or millions of people to join the DAO movement. 

- The difference: An informative video about DAOs backed up by credible data from researchers at the University of Cambridge. 

## Impact

- By creating a non-technical paper and publishing the summarised findings in an educational and exciting video on social media, I aim to reach more creators and other users who have previously shied away from the technical nature of blockchain. Given Flow's focus on creators, gamers and the mainstream user, I believe this paper will help to attract more users, developers and creators to the Flow ecosystem. 

- Academic research about blockchain technology is growing rapidly, however, most are focused on Ethereum.  I hope this research will contribute to the development of DAOs on the Flow blockchain and create a better understanding of the socio-economic impact DAOs will have on the established institutions of market capitalism.

# Milestones and funding

| Milestone | Deliverables   | Timeline | Risks                   | FLOW requested |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Collect data | Institutional analysis of DAOs on Flow and other blockchains | 4 weeks  | Time constraints | 3000 |
| 2 - Publish Paper | Academic Research on DAOs at University of Cambridge, submit for review in July | 10 weeks | Time, skills | 4000 |
| 3 - Educational Video | Show findings digestible video format on promote on social media | 4 weeks | Need help on video editing and promotion to reach the right people | 12000 |

# Team
| Name | Bio| Email | 
| --------- | --------------------- | ---------------- | 
| Ludolf von Schoening | Master student at the University of Cambridge, Founder of Paloneo.org (Cultural Impact DAO in stealth). Member of Digital Asset team at Nomura. Been through several crypto market cycles -- always focused on building | lv358@cam.ac.uk & ludolfschoening@gmail.com |

**Comment by alxflw** [comment]
Thanks very much for the educational material grant submission @luischoening! We reviewed this proposal in detail and decided to pass for the following reasons:
- developers in the ecosystem wouldn't directly benefitting from the research in practical ways
- DAOs are an emerging category on Flow, thus it is unclear what the research impact would be

Let me know if you have further questions; you can reach me on Discord (`alx-flw.find#6198`).
