### ISSUE TITLE
Ur-Hackathon 3.0

### ISSUE THREAD

**Issue by Shivkra** [onflow/developer-grants#171]
# Ur-Hackathon 3.0

# Grant category

Please select one:

- Educational material

# Description

- The majority of our team grew up in underprivileged households, and I personally graduated from a tier 4 college in close proximity to my village. Our experiences have made us aware of the challenges of obtaining a developer job in a reputable company, largely due to a shortage of practical skills. Hence, we founded Web3ForAll to provide students and developers with the opportunity to acquire web3 development skills through hands-on participation in hackathons.

## Problem Statement

- Developers are our Target audience.
- Our team has already organized two successful blockchain hackathons & this is our third edition.

## Proposed solution

- We're hosting a 30-hour long blockchain hackathon in Bengaluru on May 20-21 and would love to have a Flow track.

## Impact

- Our goal is to encourage participants to develop projects on Flow during our Hackathon and bring more high-quality projects into the Flow ecosystem.

# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Hackathon   | Flow Projects | 2 days  | - | 500           |

Total funding proposed: $500 USD
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Shiv | Blockchain Developer | ... | Shivkra143@gmail.com |
| Apoorva | Blockchain DevRel | ... | apoorva.cse1@gmail.com |
| Dinesh | Full Stack Web3 Dev | ... | dineshaitham@gmail.com |

**Comment by franklywatson** [comment]
Hi @sivasankarkk - thanks for submitting this grant proposal. We are presently making changes to the grant program and application process and as a result have not been able to review this. Once the grant program submissions are opened up again we will follow up and let you know next steps. Thanks for your patience.

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
