### ISSUE TITLE
Overflow followup grant #3

### ISSUE THREAD

**Issue by bjartek** [onflow/developer-grants#172]
# Overflow

# Grant category

- Open source maintenance

# Description

This is a follow up grant 3 for  https://github.com/onflow/developer-grants/issues/12, and https://github.com/onflow/developer-grants/issues/87 and https://github.com/onflow/developer-grants/issues/136

## Continued supported. 
The initial grants saw alot of value and the follow up grant continued to give value. Overflow can already enable users to test secure-cadence and give feedback to dapper. Overflow also helped prevent an error in the recent test spork simply by keeping it up to date and alive and running an extensive test suite on the new version of flow. 

I would like to ask for a monthly fee to keep overflow afloat for another 6 month period for 10.000 a month for 6 additional months.

# Milestones and funding

Only mainainance will be delivered this grant period.

> Note: You can leave the USD proposal empty / "TBD". Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Continued support   | Support | Every month  | I do not want overflow to grow unstable and want to be able to help its users. Each month for 6 months | 10000          |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Bjarte Karlsen | Code-monkey | I sling code and have fun and help some people too | bjarte@bjartek.org |

**Comment by chrisackermann** [comment]
Hi @bjartek - this maintenance renewal is approved, we will follow up directly on next steps.

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time given that it's stale. However given that the improvements were made and are useful, I think it is a great candidate for potential retroactive grants and will note that with the team :)
