### ISSUE TITLE
Revolutionizing DeFi Investment in Europe: Enhancing DeFi & Web3 Opportunities for Investors.

### ISSUE THREAD

**Issue by mcmleduc** [onflow/developer-grants#173]
# <Project name>
Bomoz -Revolutionizing DeFi Investment in Europe: Enhancing DeFi & Web3 Opportunities for Investors.

# Grant category
- Developer tools / services

# Description
Our purpose at Bomoz is to democratize access to decentralized finance (DeFi) by providing a user-friendly and transparent investment platform that empowers retail-investors to make informed and profitable investment decisions.
Bomoz is a DeFi investment platform that has been in development for over 18 months. Our platform empowers investors to invest in high-yield sophisticated DeFi strategies in a simple and transparent way. Our team has refined the product and changed our strategy based on feedback and polling, adding more customization options for clients. We are currently awaiting clearance for our French crypto license, with plans to launch in June 2023 and expand to europe with MiCA EU-framework in 2024. The team consists of 6 members, we have secured over $200k in equity fundraising and the waitlist has reached over 1000+ individuals.

## Problem statement

Initial feedback from investors and potential clients has been amazing around how much value we would provide our clients with. Furthermore, we have already gained traction with our newsletter, and our website has garnered significant visitor traffic, which indicates that there is interest in our product. 

To ensure that our idea is viable and appealing to potential users, we conducted extensive market research. This involved conducting a poll with a sample size of over 150 individuals to gauge their interest and gather feedback on our product concept. Additionally, we conducted qualitative interviews with over 10 potential users to obtain a deeper understanding of their needs and preferences. Through this research, we were able to gain valuable insights and identify areas of improvement to refine our product further.

Bomoz is entering the market at a time of rapid growth in decentralized finance (DeFi). As more investors seek out high-yield strategies and show increasing interest in crypto and blockchain technology, the market is ripe for a platform like Bomoz that offers easy access to sophisticated investment strategies. With the current economic uncertainty, investors are looking for alternative investment opportunities that can provide higher returns, making Bomoz a desirable option. Our platform's ability to provide transparent and user-friendly access to DeFi strategies positions us as a promising contender in the emerging landscape of decentralized finance.

## Proposed solution

Bomoz is a DeFi investment platform that empowers investors to invest in high-yield DeFi strategies in a simple, transparent and secure way. With our user-friendly investment platform, individuals can access sophisticated investment strategies based on decentralized finance.

## Impact

By offering easy access to sophisticated investment strategies, Bomoz aims to democratize investment opportunities and help increase adoption of blockchain technologies. Our value proposition lies in promoting greater participation and engagement in the fast-evolving world of Decentralized Finance within your ecosystem.
Flow will be beneficial in 3 ways: 
Adoption: We will increase the number of users on the blockchain by offering user-friendly FIAT gateways, leading to growth in TVL.
Trust: By being compliant, we provide a trustworthy regulatory framework for our partners.
Product development: As an institutional-grade player, we will stimulate the creation of new DeFi products, driving innovation on the blockchain.

# Milestones and funding
1) Milestone 1: First $350K TVL (Deadline: September 2023)
2) Milestone 2: First $1M TVL (Deadline: Q4 2023)
3) Milestone 3: First $8M TVL (Deadline: Q2 2024)

Within this application we are requesting funding. We are opened to anything you can get. The grant is needed for Marketing budget
1 dev.: Smart contract, + full stack, Legal/compliance in-house, following these KPIs: 
1. Website visits
2. Whitelist clicks
3. Whitelist signups
Our KPIs once our crypto license will be granted by the French regulator:
TLV on-ramped from bank accounts
Number of users brought to the procotol/chain
TLV/user

Here is how the grant will be used:  
Legal: $10k by Q3 2023

Marketing: 
$4,5k for Meta Ads, $3,5k for PR Agency, $3k for Twitter ads, by Q3 2023
$4,5k for Meta Ads, $3,5k for PR Agency, $3k for Twitter ads, by Q4 2023
$4,5k for Meta Ads, $3,5k for PR Agency, $3k for Twitter ads, by Q2 2024

# Team
2 co-founders
Théo Sagniez | CEO | https://www.linkedin.com/in/theo-sagniez/
Rodolphe Houliat | COO | https://www.linkedin.com/in/rodolphehouliat/
4 advisors :
Théodore Rozencwajg | Business | https://www.linkedin.com/in/theorozen/
Thibaut Duchêne | Developper | https://www.linkedin.com/in/thibaut-duch%C3%AAne-347283133/
Xavier Moquin | IS & Security | https://www.linkedin.com/in/xavier-m-cdxm9314b/
Corentin Cadieu | Advisor | https://www.linkedin.com/in/corentincadieu/

**Comment by franklywatson** [comment]
Hi @mcmleduc - thanks for submitting this grant proposal. We are presently making changes to the grant program and application process and as a result have not been able to review this. Once the grant program submissions are opened up again we will follow up and let you know next steps. Thanks for your patience.

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
