### ISSUE TITLE
Axelar Cross-chain bridge grant wishlist RFP

### ISSUE THREAD

**Issue by franklywatson** [onflow/developer-grants#174]
# Axelar Cross-chain bridge

# Grant category

Please select one or more of:

- [X] Open source maintenance
- [ ] Developer tools / services
- [ ] Educational material

# Description

This grant RFP is provided to facilitate the end-to-end development of a cross-chain bridge using  Axelar network technology to realize cross-chain token transfer use-cases between Flow and other major L1 blockchains. This RFP captures the goal and desired outcomes of the work but does not detail implementation specifics which will need to be provided when submitting a detailed grant proposal for this initiative. 

## Problem statement

- Target audience: DeFi users in Web3 who want to move liquidity in or out of Flow which current have limited support for cross-chain token exchange use-cases. Adding more cross-chain trading capabilities introduces fresh liquidity and participants to Flow
- Evidence for the need: a diverse and well established DeFi ecosystem is table stakes for L1 blockchains

## Solution requirements

- Axelar network technology is leveraged to enable cross-chain trading of 1-n token types from other major L2 blockchains (precise list TBD)
- The solution securely and reliably performs token transfers between Flow and another chain, at a fair cost, and within a timely manner
- The technical solution addresses all security concerns and risks identified

## Submission requirements
The grant proposal submitted in response should provide the following:

- Design proposal which specifies the key components and functionality which are required to realize this solution. At a minimum it shall specify:
    - Design diagrams to illustrate the logical flows of the above software components once integrated
    - Flow contracts and other software to be built
    - Axelar node software update to follow Flow and other software to be built
    - Edge cases which need to be handled and how they will be
    - Full list of test cases
    - Security analysis and risk assessment
        - Key management strategy and proposed solution
        - Baseline analysis to uncover possible security risks, vulnerability vectors etc
        - Provided as a starting point and will be further expanded upon through collaboration and input with Flow team
    - Operational considerations
        - Metrics to gather/monitor
    - Known limitations and suggested future improvements outside of the scope of this proposal
- Implementation work breakdown to detail specific milestones and deliverables for the following major efforts:
    - Initial implementation of Flow specific smart contracts to facilitate cross-chain token trading
    - Initial implementation of corresponding Axelar-related technical components or other required integration to facilitate cross-chain token trading aspects from other networks
    - Comprehensive unit and integration test coverage for happy and unhappy paths / supported edge cases
    - Work breakdown should account for documentation on the built software/components, how to operate and troubleshoot them, as well as other related materials
- Breakdown of ongoing work required to maintain the bridge once operational
    - Assume quarterly maintenance fee/cycle

## Milestones and funding

These will be defined by the proposing team in the grant proposal

**Comment by EricHitdex** [comment]
gm. For anyone looking to tackle this RFP, please feel free to reach out (eric@hitdex.com). I've been actively working on a cross-chain DEX as a solo founder ([Hitdex](https://hitdex-dex.web.app), hoping to launch on Ethereum and Polygon PoS/zkEVM within the next two months), and would love to sync with builders who have more experience in Cadence/backend and are interested in working on this project.
