### ISSUE TITLE
Application from Qlone AI

### ISSUE THREAD

**Issue by QLONEAI** [onflow/developer-grants#176]
Project name
Qlone AI

Grant category
Please select one:
- Developer tools / services 

Description
With the leverage of AI & Blockchain, Qlone's infrastructure is aiming to provide an all-in-one solution to generate your smart-digital AR clone. A new seamless approach on how to simulate, train, personalize, and manage AI on blockchain.
The technology that innovates fields like personal AI, Gaming, Customer service, Education and more…

## Problem statement
The current AI market offers limited and non-realistic 2D and 3D avatars, lacking interactivity and personalization using biometric data. Speech avatars cannot be tailored to specific needs, and lack identification. Generating NFT collections is a complex and time-consuming process that requires hiring multiple experts. There is room for improvement in the AI market to create more engaging and personalized experiences.

- Target audience
People from range 16-40, both male and female, living globally with interest in technologies, WEB3, AI helpful tools, content creation, business scalability. Businesses like AI providers, Games/Gaming studios, Customer service, Education, Online marketplaces.

- Evidence for the need
https://docsend.com/view/imej4x72rp4iuphf - We invite you to check our pitchdeck,  slides 9,10,11.

## Proposed solution
The emergence of AR technology will transform avatars to be more realistic, scalable, and exportable in various formats. With personal voice cloning and AR face scanning, users can customize biometric data for a variety of use cases, avoiding pre-made options. Qlone avatars can be trained for specific purposes using the GPT-4 model, ensuring unique and personalized experiences. Additionally, users can protect their rights and authenticate their NFTs or avatars using IP and AI technologies, allowing for effective control and monetization. Qlone provides a practical option for generating NFT collections without the need for hiring designers or developers, offering a seamless solution in just a few clicks.

## Impact
- In what ways does this benefit the broader Flow developer ecosystem?
AI NFT generator is really demanding tool for any blockchain. Flow ecosystem could be one of the first blockchain to integrate AI into WEB3 with the help of our team. AI cloning tolls, generators are useful tolls for many business and people, we have multiple AI models prepared to merge. Our application will be the first one to offer many AI features that are not available on mobile. To add, our AI models will be available in one infrastructure which will give seamless access to users with no need to transfer through other platforms. 

Who will benefit from Qlone AI:
Games/Gaming studios, Content/Collection creators, AI users/developers, Customer service and more…

Expected MAU in first year:
1st month: 500 active users
3rd month: 5,000 active users
6th month: 10,000 active users
12th month: 20,000 active users

Expected token holders in first year:
30,000 
Expected NFT holders in first year:
20,000 

Vision:
One of the leading AI tool providers in WEB3 market, first application to offer all-in-one AI infrastructure on mobile platforms, one of the first AI NFT generator provider, first platform to offer AR/AI merged cloning with blockchain functionality. Project that generates revenue with 20K-30K MAU in first year.

# Milestones and funding
Development Roadmap
50K Grant milestones (3 months)

First milestone (25K) 
AI NFT Generator on Flow ecosystem (1,5 month):
1. Flow protocol analysis:
Two blockchain/back-end developers 
2. AI NFT Generator (WEB platform) preparation on Flow ecosystem:
Two AI/back-end developers 
3. Flow NFT smart contract preparation with AI generator
Two blockchain/back-end developers 
4. Web application development and UX/UI
UX/UI designer, Front-end developer

Second milestone (25K)
Qlone AI NFT smart contracts on Flow ecosystem (1,5 month):
1. Flow NFT smart contract development:
Two blockchain/back-end developers 
2. Flow NFT smart contract implementation on AI NFT Generator:
Two blockchain/back-end developers 
3. AI NFT Generator back-end API development:
Two blockchain/back-end developers 
4. Flow wallet integration and connection for minting
Two blockchain/back-end developers 

Our development road map:
Future Plans
2023 - Q1
Core team & idea
Data Collection for Qlone AI V1
Visual and interactive components of the platform
Back-end architecture development
AI models integration into the platform

2023 - Q2
Qlone partners/collaborations
AI model performance optimization
UX / AI model’s parameters adjustments
Adjust model's hyperparameters into user format
Qlone AI V1 fine-tuning & Private release

2023 - Q3
Qlone AI socials launch
Blockchain functionality launch
AI NFT 2D/3D Generator
AR models integration
Mobile application launch

2023 - Q4
Qlone AI socials launch
Neural network training process
Server-side components scaling
Personal clone training feature
QR code feature implementation

2024 - Q1
AI NFT AR models Generator
Qlone AI V2 fine-tuning & Private release
Fiat payment feature
Content category expansion
Ambassadors program

2024 - Q2 - future
Blockchain creation
Full body AR cloning
DAO token
Dapp expansion
And many more to come…
  
# Team
Rysard CEO: https://www.linkedin.com/in/ry%C5%A1ard-gvozdovi%C4%8D/ 
I'm an experienced team leader with over 4 years of experience, specializing in UI/UX development for mobile applications, design, and programming services. In the past few years, I have managed UI/UX development teams for numerous well-known telecommunications, software, and other companies. In addition, I contributed to several blockchain projects, assisting them in successfully launching and scaling in the market. 

Lukas CMO: https://www.linkedin.com/in/lukas-zalagaitis-9b35211b9/ 
I'm an experienced product manager and developer in B2B and B2C markets. Worked on the development of blockchain projects and IT and engineering services. Always motivated, with a vast skillset to lead projects and find the right markets. I have gathered experience in marketing and project development and am interested in IT technologies such as blockchain, fintech, and investment.
 
Dainius CTO: https://www.linkedin.com/in/dainiussa/ 
I'm in love with JamStack and familiar with React.js as a frontend framework and Node. Backend or headless JS runtime environment. Worked as an algorithm developer in one of the leading AI companies in Lithuania. Skilled in GraphQL, REST APIs, and Web3 libraries For styling, use Tailwind, pure CSS sass, or plain CSS. I have experience as a web developer with React.js and Solidity smart contracts. 

Arvaidas Blockchain dev: https://www.linkedin.com/in/arvaidas-silgalis/ 
I'm a blockchain developer with great skills and experience in the blockchain industry. My extensive knowledge of blockchain technology and its applications has allowed me to develop decentralized applications and smart contracts that have helped various industries improve their operations.

Jonas Levinskas: Full stack
I'm a full-stack developer familiar with multiple front-end languages and libraries (e.g., HTML/CSS, JavaScript, Typescript, jQuery), has knowledge of multiple back-end languages (e.g., Go, Java, Python), JavaScript frameworks (e.g., Angular, React, Node.js), is familiar with databases (e.g., MySQL, PostgreSQL), web servers (e.g., Apache), and has knowledge of blockchain and smart contract deployment. Also, have analytic skills with experience in AI system development.

**Comment by franklywatson** [comment]
Hi @QLONEAI - thanks for submitting this grant proposal. We are presently making changes to the grant program and application process and as a result have not been able to review this. Once the grant program submissions are opened up again we will follow up and let you know next steps. Thanks for your patience.

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
