### ISSUE TITLE
Proposal for fixing issues in Access/Observer Nodes p.2

### ISSUE THREAD

**Issue by Guitarheroua** [onflow/developer-grants#181]
# <Project name>

# Grant category

- Open source maintenance

# Description

This grant request focuses on enhancing the informativeness and stability of Access/Observer nodes. It encompasses 7 open issues that address technical debt for Access and Observer nodes, which the core Flow team would like to resolve but currently cannot prioritize. Additionally, as part of the grant, we aim to provide a new and improved design proposal for the Access layer API.
The grant is divided into two separate milestones. The first milestone is dedicated to improving and resolving existing issues, while the second milestone focuses on the new Access layer API design. Due to its dependency on multiple internal and community discussions, we propose to treat the new API design as a separate milestone.

## Proposed solution

1 - [Access] Add circuit breaker for unavailable Collection/Execution nodes | Fixes: [onflow/flow-go#3129](https://github.com/onflow/flow-go/issues/3129):
[Circuit Breaker pattern](https://learn.microsoft.com/en-us/previous-versions/msp-n-p/dn589784(v=pandp.10)) should be implemented to handle the availability and reachability of Collection and Execution nodes. We propose using the existing package [gobreaker](https://github.com/sony/gobreaker) from Sony, which provides all the necessary functionality and flexible configurations.

To track the availability of each node, every call should pass through the [Circuit Breaker's `Execute` method](https://github.com/sony/gobreaker/blob/f4dfee680910ab45229b9737850f2f5094f13366/gobreaker.go#L228). This implies that each node connection must have its own individual Circuit Breaker. Additionally, this method should encapsulate [the invoker](https://github.com/onflow/flow-go/blob/6aee5ddaabc5ee6bb7edab5e9c0987b270a0bea8/engine/access/rpc/backend/connection_factory.go#L270) within a UnaryInterceptor, which we have set in the Connection Factory, to track calls success/failure.

Additionally, the node selection process should be improved. The new circuit breaker logic should not be limited [to 3 nodes](https://github.com/onflow/flow-go/blob/6aee5ddaabc5ee6bb7edab5e9c0987b270a0bea8/engine/access/rpc/backend/backend_transactions.go#LL89C48-L89C68) but should instead retrieve all available nodes and iterate through them one by one to determine if they can be used by the circuit breaker. To achieve this, we can check the [state of Circuit Breaker](https://github.com/sony/gobreaker/blob/f4dfee680910ab45229b9737850f2f5094f13366/gobreaker.go#L206) for each connection. If the state is [Opened](https://github.com/sony/gobreaker/blob/f4dfee680910ab45229b9737850f2f5094f13366/gobreaker.go#L19), we should select another connection. Furthermore, the existing selection logic should be unified and retained to be used with a command line argument when the Circuit Breaker is disabled.

2 - [Access Node] Connection pool evictions cause connection failures | Fixes: [onflow/flow-go#2833](https://github.com/onflow/flow-go/issues/2833):
To resolve this issue, we propose checking the current state of the [ClientConn](https://github.com/onflow/flow-go/blob/6aee5ddaabc5ee6bb7edab5e9c0987b270a0bea8/engine/access/rpc/backend/connection_factory.go#L67) (`GetState()` or `WaitForStateChange()` methods) and only shutting it down when it is not in the `Connecting` state. This will ensure handling of evictions without canceling existing requests.

3 -  [Access] Refactor Access RPC engines to support a single gRPC port | Fixes: [onflow/flow-go#4217](https://github.com/onflow/flow-go/issues/4217):

We should move the creation of both secure and unsecure GRPC servers from engines to a separate component which will manage the grpc server and its own dedicated worker. The configuration and construction of the Server should now be placed in the Access/Observer Node Builders, and the resulting server instances should be injected into the relevant downstream components which want to register relevant grpc services. 

4 - [Observer] Enable REST API on observers | Fixes: [onflow/flow-go#3138](https://github.com/onflow/flow-go/issues/3138):

Currently, there is a fixed mapping route -> handler. We suggest using a similar approach to grpc, where routes will be connected to an abstract interface that will contain actual handling logic. This adjustment will enable us to create two implementations: one for the local REST implementation, utilizing the existing handlers, and another for the forwarder, similar to grpc((for example see [FlowAccessAPIRouter](https://github.com/onflow/flow-go/blob/6aee5ddaabc5ee6bb7edab5e9c0987b270a0bea8/apiproxy/access_api_proxy.go#L64) and [FlowAccessAPIForwarder](https://github.com/onflow/flow-go/blob/6aee5ddaabc5ee6bb7edab5e9c0987b270a0bea8/apiproxy/access_api_proxy.go#LL252C21-L252C21))).

5 -   [Access] Enable Event streaming on REST API | Fixes: [onflow/flow-go#4379](https://github.com/onflow/flow-go/issues/4379):
We are planning to use https://github.com/nhooyr/websocket to implement websockets support for streaming calls over HTTP. Both golang.org/x/net/websocket and gorilla/websocket are not supported anymore. The plan is to extend the REST server to support a specific endpoint for registering streaming requests, once the streaming request is requested we will spawn a goroutine to serve notifications to the client. Will use the same logic for capping max number of requests as GRPC implementation. Will add unit and integration tests.

6 - [Access] Provide requests output for scripts and transactions | Fixes: [onflow/flow-emulator#226](https://github.com/onflow/flow-emulator/issues/226):
In issue 3971, changes were made to fix the REST API Metrics. As per the request in the issue 226, instead of using [NoopCollector for server RestMetrics](https://github.com/onflow/flow-go/blob/c615e4d7b3a5f11ecebd01d7fd4d295b1897a88b/engine/access/rest/server.go#L16), we need to add RestCollector to the flow-emulator. This addition will enable the collection of REST metrics.

## Impact

Proposed fixes will improve the informativeness and stability of Access/Observer nodes.

# Milestones and funding

## Milestone 1

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - [Access] Add circuit breaker for unavailable Collection/Execution nodes | Fixes: [onflow/flow-go#3129](https://github.com/onflow/flow-go/issues/3129) | 56h | - | 3640$ |
| 2 - [Access Node] Connection pool evictions cause connection failures | Fixes: [onflow/flow-go#2833](https://github.com/onflow/flow-go/issues/2833) | 40h | - | 2600$ |
| 3 - [Access] Refactor Access RPC engines to support a single gRPC port | Fixes: [onflow/flow-go#4217](https://github.com/onflow/flow-go/issues/4217) | 40h | - | 2600$ |

## Milestone 2

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 4 - [Observer] Enable REST API on observers | Fixes: [onflow/flow-go#3138](https://github.com/onflow/flow-go/issues/3138) | 80h | - | 5200$ |

## Milestone 3

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 5 - [Access] Enable Event streaming on REST API #4379 | Fixes: [onflow/flow-go#4379](https://github.com/onflow/flow-go/issues/4379) | 80h | - | 5200$ |
| 6 - [Access] Provide requests output for scripts and transactions | Fixes: [onflow/flow-emulator#226](https://github.com/onflow/flow-emulator/issues/226) | 8h | - | 400$ |

Total funding proposed: 19640 USD
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Andrii | Blockchain Engineer | Software Engineer with over 8 years of technical experience.<br />Primary skills include C++(Standards 11,14,17), Rust, and Golang.<br />I have been highly focused on blockchain development for the last few years. Here are a few examples of my projects that could be interesting when applying for this grant: <br />- `2016-2019`: Supply chain planning and management tools/applications for huge manufacturers and logistic businesses. Worked in a team of 20+ engineers. Gained experience in Golang. Build integrations between applications using REST API. <br />- `2021-2022`: Complex DeFi lending/borrowing system using Rust/Solana. Smart contracts design, implementation, and testing (using typescript). Project successfully works on the market and ranks in the top 100 of Coinmarketcap. <br />- `2022-2023`: Development of Domain name service using Rust on Elrond blockchain. Smart contracts / Backend / deployment. | andriyslisarchuk@gmail.com |
| Uliana | Blockchain Engineer | Software Engineer with over 5 years of technical experience.<br />Primary skills include C++(Standards 11,14,17), Rust, and Golang.<br />I have been highly focused on blockchain development from the very beginning of my career, here are a few examples of my projects: <br />- `2018-2021`: Creation of a multi-currency light wallet, Lightning Network-ready, that features its own DEX. C++ Development of blockchain specific features, creation of custom version of private lightning network using Golang. <br />- `2021-2022`: Complex DeFi lending/borrowing system using Rust/Solana. Smart contracts design, implementation, and testing (using typescript). <br />- `2021-2023`: Developing smart contracts for NFT Marketplace platform startup using Rust and Cosmos. | [u.andrukhiv@gmail.com](mailto:u.andrukhiv@gmail.com) |

**Comment by franklywatson** [comment]
Thanks for your proposal this looks good. Just one small change, can we switch task 6 to milestone 2, and 5 to milestone 3?

**Comment by franklywatson** [comment]
Thanks @Guitarheroua this was approved!

**Comment by franklywatson** [comment]
Milestone 1 marked completed:

* https://github.com/onflow/flow-go/issues/3129
* https://github.com/onflow/flow-go/issues/2833
* https://github.com/onflow/flow-go/issues/4217

Milestone 2 marked completed: 

* https://github.com/onflow/flow-go/issues/3138
