### ISSUE TITLE
Project DeTask - Improving Team Efficiency in Decentralized Environments with a New Methodology

### ISSUE THREAD

**Issue by rtscosta** [onflow/developer-grants#182]
# [DeTask](https://detask.io) - Manage & pay service providers globally

# Grant category

- [X] Developer tools / services

# Description

DeTask is on a mission to change how work is rewarded. We believe that companies should focus on outcomes, not outputs. Our platform encourages a shift towards a culture where efficient work delivered ahead of schedule is financially rewarded, promoting a focus on value rather than just hours worked.

DeTask improves efficiency and work-life balance. Companies can set tasks with budgets and deadlines to inspire teams to achieve greater results in less time.

## Problem statement

- Target audience

Leaders who manage decentralized teams. [How it works?](https://youtu.be/Y2m0aRxIw9k)

- Evidence for the need

Today, we face challenges in managing decentralized teams. Our current methods are ineffective. However, tomorrow, the developers who are working on decentralized projects will become managers, and DeTask will assist them in their transition.

83% of IT projects fail to meet their objectives in terms of time, budget, and promised functionalities, as per the 2022 Deloitte Global Outsourcing Survey.

As per Asana's Anatomy of Work Index, 56% of executives feel that they don't have the right incentives to retain employees.

A Review of Moonlighting in the IT Sector and Its Impact reveals that post-COVID, there has been an increase in employees taking on multiple jobs to earn extra income and find value fulfillment.

The Guardian reported that a hundred UK companies have signed up for a four-day workweek without any reduction in pay.

## Milestones and funding

Our initial proposal is to implement DeTask as it currently operates within a single team and reap the benefits of our platform. Once we have successfully demonstrated its effectiveness, we will proceed with expanding our development efforts to integrate with the Flow network. Our ultimate objective is to create a DeTask multichain solution.

**Comment by alxflw** [comment]
hi @rtscosta, we're currently not accepting new grant proposals. we're working on a relaunch of the program but until then we only continue with existing grant projects.

Thanks for you patience!
