### ISSUE TITLE
Application from SUN ZU Lab

### ISSUE THREAD

**Issue by SunZuLab** [onflow/developer-grants#184]
# SUN ZU Lab

# Grant category

Please select one or more of:

- [ ] Open source maintenance
- [x] Developer tools / services
- [ ] Educational material
- [x] Data provider

# Description

SUN ZU Lab is a leading data solutions provider, on a mission to bring better data to the global crypto ecosystem through independent quantitative analyses. We collect the most granular market data from major liquidity venues, analyze it, and deliver our solutions through real-time dashboards. SUN ZU Lab provides crypto professionals with actionable data to monitor the market.

The dashboards will allow our users to: follow price action in real time in the most accurate way possible; identify and monitor price anomalies between different exchanges; get alerted of large unusual transactions or periods of exceptional volatility; identify the venue with the best price to adjust the inventory of their tokens.

## Problem statement

Crypto has showed a tremendous growth potential but is still lacking institutional standards that help protect basic token users' rights. We believe that this is starting to change post defining events such as the Terra Luna ecosystem implosion or FTX's bankruptcy, and that our tools can help bring a deeper understanding and monitoring of tokens' market activity.

SUN ZU Lab dashboards and insights will help bring more maturity and institutionalize the crypto markets, driving the next wave of mass adoption from banks and asset managers managing trillions of retail investors money.

We target the B2B market of existing crypto market participants and TradFi Institutions. We identify 1 million addressable data consuming endpoints in TradFi alone (Bloomberg, Refinitiv… users). Our priority target clients are crypto/hybrid buy side, token ecosystems and crypto trading venues.  

## Impact

Using our dashboard, your ecosystem will be able to have a full 360 degree view of its token’s liquidity, and will be able to react in real-time to urgent market events that could be catastrophic if not well handled (deppeg, liquidity crunch, bid-ask spread spikes…). This in turn will increase the token's market circulation quality and bring a new wave of both retail and institutional users.

The idea of the collaboration with your ecosystem would be to create a free, open-source dashboard for token holders, allowing them to track the tokens’ activity in real time on a single interface. We could also make it available through API & Flat files.
A second use case is for your foundation directly (and CFO if exist); foundations are often asked to buy/sell large quantities of tokens. SUN ZU Lab Dashboard enables them to have an aggregated view and real-time monitoring tool of the market and, therefore to better choose or execute but also to be alerted if there is a liquidity issue on a market X, for example.

## Milestones and funding

100% of the Grant is used to deploy the infrastructure of the integrated protocol & maintain it
(Maintenance = $03k / Month)

1) Milestone 1: Deployment on your ecosystem (Deadline: Q3 2023) $10k Deployment + $09k Maintenance
2) Milestone 2: 2k Unique Users on your ecosytem $09k Maintenance
3) Milestone 3: 10k Unique Users on your ecosystem (Deadline: Q1 2024) $09k Maintenance

We raised $1.5m in 2022: Backed by BPI France, Kima Ventures & Elaia.
And we already have secured $1.5m on $2m for this current seed round.

Website : https://sunzulab.com/
Pitchdeck : https://drive.google.com/file/d/1mb4-x1IuX7xaB26K2OENZixDmNQeNzqJ/view?usp=sharing
1 Pager : https://drive.google.com/file/d/1yGMwazOsxkH6dbMZhXxC6DVZNh-hf6zU/view?usp=sharing
Technical Stack : https://drive.google.com/file/d/1JOzK16MRXOQdKIGJ0t4J3KoEBjri99F9/view?usp=sharing
System Architecture : https://drive.google.com/file/d/1v51C3EbuvRMW9HJotna5o2aOzGf_wi_C/view?usp=sharing
Demo URL : https://drive.google.com/file/d/1Fb_u5DjcH21A7GYf2CPtOOIdLTMfKl0h/view?usp=sharing

**Comment by alxflw** [comment]
@SunZuLab as pointed our in the readme and templates, our grants program is currently on pause until we relaunch a new program. we're not accepting new applications at this moment.
