### ISSUE TITLE
Walletless Minting API for web2 (Nftikets )

### ISSUE THREAD

**Issue by Jimmygodwin** [onflow/developer-grants#185]
# <NFTikets>
    

![Nftiket logo](https://i.imgur.com/DuWPd9o.png)

# URL
https://nftikets.io/

# Grant category

Please select one or more of the:

- [#] Developer tools / services

# Description
The team at NFTikets have successfully implemented a wallet-less-minting architecture aimed at driving ticket sales, this has led to another use case/ need. Other platforms have expressed the need to create valid authentication systems through minting of NFT's using the NFTiket wallet-less-minting architecture.
    This architecture has increased adoption for web3 on web2 applications by 61% and this will drasctically improve adoption for web2 applications. 

## Problem Statement
1. Complexity of building on the blockchain for web2 startups.
2. Cost of building on the blockchain for web2.
3. Complexity of integrating into a web2 application 
4. Need for wallet connection and complexity operations when implementing directly from a smart contract. 
5. Buy crypto to pay gas fees  

## Target audience
1. Startups looking to use NFT's as a form of validation (Certificates, Identity, Merch, Fundraisers, Badges, Tickets and Lots more).
    
2. Startups building an NFT marketplace can simple plug the API and experience Wallet-less processing in minting and transfering to tickets.

## Our Numbers (Operational for 5 months)
    1. Events Hosted: 161
    2. Users: 617
    3. Countries: 3 (2 East Africa, 1 West African)
    4. Currencies We Process: Fiat(Naira (NGN), Rwandan Francs (RWF)) Crypto: BTC, USDT(Trn), USDC. 
    5. Partnerships: 4
    6. Advisors: 2

## Proposed solution
1. Provide web2 platforms the ability to leverage on Flow's blockchain technology without spending resources on recruitment for blockchain specialists.
2. Simple Plug and Play (PnP) API architecture that covers gas fee and allow customers on web2 platforms to pay the gas fees in their local currency. 
3. A detailed document that allows the web2 platforms to onboard our plugin as an SDK or API
4. Low time onboarding process for web2 platforms allowing them to be fully onboarded and in operation within 48 hours. 

## Impact
1. Massive adoption of flow Blockchain for web2 companies: our research has show that 37% of web2 startup desire to use the blockchain but can't afford the cost of hiring or running the development process themselves
2. A more secure data management system on these platforms 
3. Decentralized data management systems which means items stored on one system can be accessed by the users and transfered to multiple systems on the Flow blockchain, making those asset universal. 

### In what ways does this benefit the broader Flow developer ecosystem?
1. Increased use cases for the ecosystem 
2. The ecosystem becomes Universal storage system for most web2 companies. 

# Milestones and funding

> Note: You can leave the USD proposal empty / "TBD". Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - MVP   | Design of the work flow and the smart contract  | 4 weeks  | - | 9000           |
| 2- BETA   | Developer Portal with Docs for integrating our API's | 8 weeks  | - | 6650           |
| 3. Beta Launch   | 10 web2 comapanies  | 3 weeks  | - | 3000           |
| 4. Maintenance   | Resolving issuing and fixing bugs | 2 months  | - | 12600           |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Godwin Jimmy | Product Mangager  |  As a Product Manager, I have managed the development and deployment of various blockchain applications some of which are: Plutoswap (DEX), Dantown (https://www.dantownms.com/), Social Stack (https://www.socialstack.co), Cyrus NFT (https://www.cyruspahlavi.com/), Zoo NFT  (https://zoolabs.io/). | jimmygodwin371@gmail.com | 
  David Esser  | Advisor(Product) |  Chief Product Officer at Minterestt, Serial entrepreneur building blockchain, defi, internet, mobile, and IoT applications Specialties: -- Product Management for enterprise blockchain, internet, and mobile applications.-- Strategy and implementation for complex technology products.-- Building & leading extremely capable teams of technologists to deliver amazing quality and productivity results | Desser@tradewindsystems.com |
| Joseph Iroghama | Lead Frontend |  A frontend engineer with 3 years experience in javascript, react, next, web3.js and threejs. | iroghamajoseph@gmail.com
| Helen Chinweike | UI/UX Designer |  UI/UX design with 4 years of experience in design and have worked on a series of projects cutting across payments gateways and Defi products. | hchinweike19@gmail.com
 |Gift Elenwo | intern Frontend |  A computer science graduate with 6 months of experience in javascript and react |elenwogift2@gmail.com
| Juliet Babatunde | Content Developer |  Content Developer and Copyright with 2 years experience. | babatundejuliet@gmail.com |
   | Ludovico Rossi   | Advisor(Revenue and Finance) |Currently the CRO at Brikken An entrepreneur specialized in security tokens, project scouting, go-to-market strategies, fundraising and lean growth. He also lectures on business in the web3 industry in different business schools. | ludovico@brickken.com | 
   Davies Ikhazobor Oyasor    | Backend Developer | Backend developer with 3 years experience in JavaScript, Node.js and express.js | davies@nftikets.io |

**Comment by alxflw** [comment]
Hey @Jimmygodwin - good to hear from you. we're currently not accepting new grant proposals. we're working on a relaunch of the program but until then we only continue with existing grant projects.

Thanks for you patience!
