### ISSUE TITLE
Infinity Wallet & Web3 Browser Grant

### ISSUE THREAD

**Issue by InfinityWallet** [onflow/developer-grants#188]
# Infinity Wallet & Web3 Browser

# Grant category
Developer tools / services

# Description
![image](https://github.com/onflow/developer-grants/assets/64919828/0d6a061a-9625-476f-9f18-849e8bc45472)

Infinity Wallet is an all-in-one non-custodial wallet ecosystem and first standalone Web3 browser of its kind on desktop (“a Wallet and Web3 browser Super App”), launched in 2019, and supporting hundreds of thousands of users. Not a browser extension, but a complete standalone desktop application providing a one-stop solution for seamless access and usability of DeFi, NFTs and cross-border payments, with a gateway to the world of Web3/DApps via the first desktop Web3 browser and Dapp store. Fulfilling all a user’s decentralized needs in a single platform, while removing the complexities of decentralized finance and Web3, enabling economic freedom for everyone globally!

Infinity Wallet was created to finally enable mass adoption, as a single access point to the entire decentralized world. We have focused on providing the best possible user experience, to lower the barrier to entry and allow for streamlined and secure adoption of DeFi and Web3. Providing a world-class user experience with a seamless user interface, and a full spectrum of constantly growing in-wallet features and services as a one-stop hub. Making Infinity Wallet the complete solution for all crypto users’ needs, while making adoption and usage of cross-border payments, DeFi, NFTs and Web3 easier than ever before for mainstream adoption.

Infinity Wallet is not just a unique one-stop wallet built for the masses, it is also the first desktop platform to provide users with access to the entire Web3 and DApp space without needing a browser extension on desktop, with the first Web3 browser and DApp store on desktop as a standalone App. Finally removing the need to use unintuitive, unfriendly and feature-lacking browser extension wallets ever again! Providing a far superior, safer and more natural user experience, with a range of unique advantages for users, DApps, and chains alike, enabling easier usage and adoption of Web3!

A further introduction can also be found in our information deck https://infinitywallet.io/docs/Infinity%20Wallet%20Deck.pdf

## Problem/Solution Statement
Wallets are the core component required for any chain, enabling users to interact and onboard to FLOW, and access the FLOW ecosystem (Payments, DApps, DeFi, Web3, NFTs and much more). Making wallets the defining factor for usage and adoption of a chain and its entire ecosystem, however as of today wallets are one of the least well developed applications in the crypto ecosystem.

Today, wallets act mainly as an interface, serving primarily as a transaction signing layer, with very limited functionality or in-wallet features, requiring use of multiple platforms, and are generally lacking in basic UX, while providing very unprofessional, hard to use and aesthetically poor user interfaces, with most platforms built with a focus on developers rather than end users. This has been sufficient for the early adopters in crypto, however, for the next billion users to onboard, a more curated, frictionless and high quality user experience is required!

Desktop Web3 wallet options are limited in particular, delivering very little in terms of new innovation, or solving today’s issues, while requiring the user to install a browser extension, which is not the natural flow. Overall delivering an unintuitive and feature-lacking user experience, with limited or no native support for FLOW and its ecosystem/DApps, greatly restricting the possibility for discoverability and adoption.

For FLOW to compete and attract users and developers, it needs a one-stop wallet super app providing a seamless user experience, to enable users to onboard and adopt FLOW, and learn/discover the FLOW ecosystem as their home.

Infinity Wallet steps in as a one-stop hub for all crypto, payment, DeFi, NFT and Web3 activity. Providing a unique all-in-one standalone wallet solution and first Web3 browser with DApp store, removing the need for unfriendly and feature-less browser extension wallets. Enabling easier usage, onboarding and discoverability of FLOW and its ecosystem, along with a full spectrum of in-wallet services, features and protocols, as an all-in-one wallet super app for all a user’s decentralized needs!

We are focused on redefining the wallet experience and solving today’s issues, delivering a premium platform and enhancing the user experience, while providing a user centric interface for a frictionless and high quality decentralized experience that users are generally used to with web2/centralized solutions. Lowering the barrier to entry, to allow for easy onboarding and true adoption of DeFi, crypto payments & Web3 globally, while allowing users to maintain complete privacy and self-custody!

### Target audience
Our target audience would primarily be retail users (for wallet, instant cross-border payments, accessing DeFi, NFTs and Web3), along with a secondary focus on developers with helping them achieve further adoption and awareness (for DApps, Tokens and NFTs).

### Demand
We have received many requests from the FLOW community/users over the last year. Requesting for us to bring our unique ecosystem to develop out on FLOW with the Infinity Wallet, Web3 Browser, and our wide range of infrastructure/features/services. Hence why we are reaching out for a grant to make this possible.

## Impact
The goal of the proposal would be to enhance FLOW with a much needed one-stop user focused wallet and web3 browser ecosystem, providing FLOW access to the many advancements we have, bringing much needed valuable infrastructure, services and ecosystem support, which FLOW currently lacks (for DeFi, Web3, and cross-border payments). While enhancing the user experience and bringing new utility, and allowing for easier usage, access and adoption of FLOW and its ecosystem by less tech-savvy users, while also empowering developers with easier discoverability and usability of their DApps & Tokens, driving easier adoption.

Infinity Wallet will allow Flow and its ecosystem to be more easily adopted and used by the general public, in a unique crypto wallet, payment solution and Web3/DApp browser built for the masses, and used already by hundreds of thousands of users worldwide for easy cross-border payments, access to DeFi, NFTs and interacting with Web3/DApps directly within their wallet. As a one-stop platform for all users to directly access all their DeFi, Web3 and crypto needs, making adoption of the Flow ecosystem as easy and intuitive as possible and boosting awareness, usage and utility.

Additionally, FLOW currently lacks streamlined Web3 support for connecting and transacting with DApps. As the FIRST desktop Web3 browser and DApp store, we bring a unique more natural user experience and value to any chain integrated when accessing DApps and Web3 (compared with browser-extensions), finally freeing desktop users from having to use unintuitive, unfriendly and feature-lacking browser extension wallets to access Web3 and DApps, while enabling easier DApp/developer discoverability!

Below are some of the key infrastructure and features/services that could benefit and bring value to FLOW and its ecosystem:

- Portfolio and Analytics Monitoring/Dashboard -
![image](https://github.com/onflow/developer-grants/assets/64919828/7cc7e708-6061-4d4c-a981-18ded7f62e86)

- One-stop DeFi Wallet Solution with a strong focus on user experience -
![image](https://github.com/onflow/developer-grants/assets/64919828/0b5d5abd-d057-446c-ae73-d03ae39d02a3)
![image](https://github.com/onflow/developer-grants/assets/64919828/ba8d9df1-359b-4472-9b02-83926012c7cd)

- Desktop Web3 Browser (One-click connect and transact with Web3 DApps, with utmost discoverability and use of a chains’ ecosystem) This removes the need for unfriendly and feature-lacking browser extensions to access Web3 and decentralized applications on desktop, while providing a standalone browser for web3!
![image](https://github.com/onflow/developer-grants/assets/64919828/3b5bc997-8b9b-4f43-bcb2-3d258709a8fa)

- Web3 DApp Store (Enables easier DApp & ecosystem discoverability, adoption and usage) -
![image](https://github.com/onflow/developer-grants/assets/64919828/cdc936ac-6090-458a-ac54-cf64586e88fd)

- Cross-chain swap & bridge (Swap/Bridge between multiple supported chains) -
![image](https://github.com/onflow/developer-grants/assets/64919828/b5883db4-0e4d-4b32-86f9-5b1562d57d0f)

- In-wallet decentralized exchange aggregator -
![image](https://github.com/onflow/developer-grants/assets/64919828/5eff52bc-c760-493e-9bcb-5788816e7096)

- NFT support and Gallery to manage (view, send and receive) and easily trade NFTs -
![image](https://github.com/onflow/developer-grants/assets/64919828/bab802b6-ddcd-4475-baf0-aed707484e57)
![image](https://github.com/onflow/developer-grants/assets/64919828/e1400bc2-9d1f-40b7-be0d-92046b9e167a)

- Fiat on/off Ramp (enabling easy and direct onboarding into crypto and supported chains) -
![image](https://github.com/onflow/developer-grants/assets/64919828/82db12e6-c309-47fe-9dea-3b76629a0a7e)
![buy and sell crypto options|690x360](https://i.gyazo.com/a032289e853ec8acfb7018ddcc64b32c.png)

- Complete Transaction History for all transaction types with DApp resolving and balance/performance tracking -
![image](https://github.com/onflow/developer-grants/assets/64919828/1c5c3316-0fd2-4cdc-aa2a-894dc94add42)

- Custom Token Importing (Allowing any token to be imported on any supported chain) -
![image](https://github.com/onflow/developer-grants/assets/64919828/cbfba499-789c-44ab-96a2-13ecb3930c05)

- Live user and chain support, with a focus on delivering the best possible user experience to make onboarding for users as easy and seamless as possible

For a detailed look over our many other features/services and future development roadmap please see our information deck available at https://infinitywallet.io/docs/Infinity%20Wallet%20Deck.pdf, or our docs at [Features & Notable Advancements - Infinity Wallet](https://docs.infinitywallet.io/infinity-wallet/features-and-notable-advancements) (detailing further information on core features/services and secondary features).

We also look to launch our highly anticipated mobile release later this year on Android and iOS, a sneak peak can be found below
![image](https://i.imgur.com/C330Hn2.jpeg)

### In what ways does this benefit the broader Flow developer ecosystem?
Integration with the Infinity Wallet would allow FLOW developers to benefit from easier usability (enabling users to more easily use their projects) and access to a wide range of features for their projects (DApps, Tokens and NFTs), as well as ongoing discoverability and adoption.

# Milestones and funding
The goal of this grant would be the complete integration of FLOW into Infinity Wallet, Web3 Browser and its wide range of features/services for unparalleled ease of use and adoption of Flow. Providing Flow and the Flow ecosystem access to a vast user base, on-going support, integration of projects (DApps, NFTs and tokens) launching on Flow, as well as bringing constant free marketing, awareness and adoption.

We would be requesting $60,000 in FLOW as a single milestone, on the complete live launch of FLOW and all proposed deliverables.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Core Integration   | Integrate core FLOW wallet functionalities to be able to interact with and utilize the FLOW chain (store, send, receive, create/restore, transaction history, balance tracking and other core FLOW functionality) | 3 weeks  | N/A | 15,000 |
| 2 - Token Support | Integrate support for FLOW  tokens, with the ability to import non-default supported tokens, enabling easy use of all tokens on FLOW within the Infinity Wallet and its features/services | 2 weeks  | N/A | 10,000 |
| 3 - Portfolio dashboard, Swap/Bridge & Fiat on/off ramp | Portfolio dashboard support, with charts, price and historical tracking for FLOW and tokens; <br><br> Swap & Bridge support, enabling one-click swap/bridge from different chains and tokens to/from FLOW; <br><br> Buy/Sell support, enabling easy onboarding into the FLOW ecosystem from/to fiat currencies | 6 days | N/A | 6,000 |
| 4 - Web3 Browser & DApp Store | Web3 Browser and connector integration, allowing for seamless transacting and connecting to FLOW Web3 projects and DApps, removing the need for browser extensions via the Web3 browser; <br> <br> Web3 DApp store for FLOW projects, to allow for easy discoverability and adoption of FLOW ecosystem project;  | 3.5 weeks | N/A | 19,000 |
| 5 - NFT Support | NFT support for FLOW  , including NFT gallery to view all NFTs, individual NFT viewing with all NFT stats/information, ability to send/receive and easily buy/sell NFTs | 2 weeks  | N/A | 10,000 |
| 6 - Secondary features | Integration of FLOW into all secondary features (Address book, Payment requests, Market Stats, Alerts, Notifications, etc.). |  1 day | N/A | 0 |
| 7 - Testing | Internal testing/auditing of the integrations and all developments | 1 week  | N/A | 0 |
| 8 - Release | Live release of FLOW integration, in-wallet release and notification, announcement across social channels, native default support in-wallet for every new user creating a wallet, custom website page, and start collaborating with FLOW projects on integrating them into the Infinity Wallet Web3 Browser. | on-going | N/A | 0 |

Total funding proposed: $60,000 in FLOW

### On-going Support
On completion and live launch of the deliverables above, we look to continue to provide ongoing support to FLOW and the FLOW ecosystem, including:

- Expanding support for FLOW into our future mobile release and social wallet support;

-  Ongoing development support for FLOW within the Infinity Wallet into future features/services on a case by case basis, such as Social wallet and etc.. (part of our current public roadmap can be found on page 27 here https://infinitywallet.io/docs/Infinity%20Wallet%20Deck.pdf);

- Supporting FLOW as a native and default chain within the Infinity Wallet, providing maximum visibility and awareness to new users;

- Collaborating and integrating FLOW developers' DApps with direct support for their projects within the Infinity Web3 Browser and DApp store for free, to help drive ecosystem adoption and usage;

- Provide ongoing maintenance and live support for the FLOW chain;

### Our development roadmap
We have a lot of developments planned over the next couple of years, however some of the developments planned over the next 6 months that could benefit FLOW on a case by case basis include:

- UX focused Mobile Wallet release in early 2024 (redefining the entire DeFi & Web3 experience);

- Social Wallet (removing the need for a seed phrase and enabling users to create a wallet via social login, allowing for easier onboarding and usage of DeFi & Web3 by the general Web2 user);

More on our overall roadmap that could benefit FLOW can be found on page 27, here: [https://infinitywallet.io/docs/Infinity%20Wallet%20Deck.pdf](https://infinitywallet.io/docs/Infinity%20Wallet%20Deck.pdf)

  
# Team
We are an already launched project supporting hundreds of thousands of users globally. Built from the ground up as a complete self funded project, providing free to use infrastructure and a one-stop wallet/Web3 ecosystem.

Additionally, our team members have between 5-10 years of experience within the space (as investors, miners and developers), so we have a vast amount of experience and understanding of major shortcomings in the market, along with what is needed to enable mass adoption.

Information on the core/founding team members can be found at the following link https://docs.google.com/document/d/1c4fpyzI64569uNr8l9Ygo_G3x2NTs_Dq8wRGSnOXH14/edit?usp=sharing

**Comment by InfinityWallet** [comment]
Hello @KshitijChaudhary666, I am following up as we have not heard back and were wondering if there was any update on the proposal? Thanks

**Comment by InfinityWallet** [comment]
Hello @franklywatson, @KshitijChaudhary666 and @turbolent, we were wondering if there was any update in-regards to the proposal? Or if there is anything that requires further explanation? Thanks

**Comment by InfinityWallet** [comment]
Hello @SeanRobb, we are following up in-regards to the proposal as its been a long time since we received an update. Thanks

**Comment by InfinityWallet** [comment]
Hello @SeanRobb, we are following up in-regards to the proposal as its been a long time since we received an update. Thanks

**Comment by InfinityWallet** [comment]
Hello @SeanRobb, @franklywatson, @KshitijChaudhary666 and @turbolent, we are following up in-regards to the proposal as its been a long time since we received an update. Thanks

**Comment by InfinityWallet** [comment]
Hello @SeanRobb, @franklywatson, @KshitijChaudhary666 and @turbolent, we are following up in-regards to the proposal as its been a long time since we received an update. Thanks

**Comment by SeanRobb** [comment]
Hello,

This currently doesn't align with the goals for grants this cycle. 

We are pushing more towards adoption metrics for users and developers.

Thank you for your time and effort towards this submission.

**Comment by InfinityWallet** [comment]
> Hello,
> 
> This currently doesn't align with the goals for grants this cycle.
> 
> We are pushing more towards adoption metrics for users and developers.
> 
> Thank you for your time and effort towards this submission.

Hello @SeanRobb, appreciate the reply.

In regards to "We are pushing more towards adoption metrics for users and developers.", this is exactly what our proposal looks to achieve! Not only by driving our hundreds of thousands of users to have access to Flow, but also through providing users of Flow with a quality platform that is lacking in the Flow ecosystem as you have a huge ecosystem gap that we look to fill. In addition to all the developer support we look to bring, to drive awareness and adoption to developer's projects on Flow.

We would appreciate if you could review the proposal fully, as it sounds like some parts may have been missed. And if you have any questions do let us know!

Thanks

**Comment by InfinityWallet** [comment]
Hello @SeanRobb, following up regarding the previous message.
