### ISSUE TITLE
Conference NFT Application

### ISSUE THREAD

**Issue by lealobanov** [onflow/developer-grants#189]
# Conference NFT Application

# Grant category

Please select one:

- **Open source maintenance**
- Developer tools / services
- **Educational material**

# Description

MVP for a web application targeted towards conference attendees. The app seeks to expose traditionally Web2 users to Web3, as well as showcase the capabilities of Flow blockchain. The MVP of the app will enable users to take part in an NFT scavenger hunt around the conference venue and perform in-person NFT swaps with other conference attendees.

## Problem statement

- Target audience: conference attendees; primarily a Web2 crowd. By engaging with the app, attendees will become acquainted with some of the core capabilities of Flow blockchain as well as gain exposure to the Web3 ecosystem. The app will support basic admin functionality, such that it can repurposed and tailored to future conferences.

- Evidence for the need: Conferences are a great way to expose users to new and emerging tech. Currently, no other market alternatives exist for the location-based/in-person NFT swap functionality, which we hope to iterate on in future versions of the app (for example, potentially extending to more sophisticated tooling using NFC or BLE technology). The app provides and interactive and engaging experience for conference attendees, whilst serving an educational purpose for users new to Web3 or the Flow ecosystem. 

## Proposed solution

The MVP encompasses the following functionality:

**Front-end**
- React web application
- Initial landing page and social login (Google) for unauthenticated users
- Interstitial reveal page when an NFT is dropped to the user or found at the conference venue
- View user's current NFT collection 
- Swap functionality; MVP will facilitate this in-person interaction using QR codes 
- Leaderboard polling user scores (based on NFTs owned/their associated point values) at repeated intervals, e.g. every 5 minutes

**Cadence**
- Mint NFT collection 
- On initial sign in, initialize dapp custody account using Flow Account Linking
- Initial token drop upon user creation
- Airdrop NFT to recipient when found in scavenger hunt 
- Keeping track of user scores; reading user scores to generate leaderboard
- Fetch NFTs currently owned by user 
- Functionality to perform an NFT swap between 2 users

**Back-end**
- This section includes some basic admin tooling to facilitate conference management. For the MVP, this can be accomplished using a lambda function(s) which is lightweight and cost-effective; as the app scales, this can be extended to a centralized backend if needed. 
- Functionality to start/stop scavenger hunt
- Functionality to reset participating users and scores

## Impact

 In what ways does this benefit the broader Flow developer ecosystem?

- Expanding user awareness of Flow and its capabilities, particularly to Web2 users who are new to Web3 
- Providing a hands-on, educational experience to conference attendees that is both informative and interactive
- The app has potential for extended scope; new features (e.g. in-app gameplay, token gating) could be added to showcase more Flow capabilities 
- The app can be re-purpose at future conferences and events to provide an interactive NFT experience

# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Front-end development   |  Building out all front-end screens of the app, including: user auth, NFT reveal, user's NFT collection, scavenger hunt leaderboard, NFT swap facilitated via QR codes.  | 1.5 weeks  | A more seamless UX for the NFT swap could potentially be achieved using location-based technology such as NFC or BLE. However, as they are still experimental in terms of browser support, the initial MVP will make use of QR codes to facilitate NFT swapping. We can investigate adopting NFC/BLE/other solutions in subsequent iterations of the app.  | 8500        |
| 2 - Smart contract development   |  Completing all smart contract functionality as described in the 'Cadence' section above. Test cases for smart contract functionality. This milestone includes integrating the front-end with smart contract where necessary (e.g. user auth, swapping, fetching user's NFT collection, polling leaderboard via events, etc.)  | 1.5 weeks | - | 3500           |
| 3 - Admin tools   | Setting up infrastructure for basic admin management of the app to allow for it's re-purpose at future events, including: resetting state of leaderboard, resetting user participants, starting/stopping the scavenger hunt. This will be accomplished using a lambda for the initial MVP and can be built out further as needed in future iterations of the app. | 1 week | - | 1750           |
| 4 - Adoption/Maintenace  | Assistance supporting go-live of the app at its first in-person event. Detailed documentation of all components of the application, onboarding materials for conference attendees. Availability to answer questions as needed, resolution of bug fixes. | TBC  | - | 1250           |

Total funding proposed: 15,000 USD
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Lea Lobanov | Full-Stack/Blockchain Developer  |  Founder at [Purple Dash](https://purpledash.dev). | info@lealobanov.com |

**Comment by franklywatson** [comment]
Closing this since the problem was solved by a hackathon participant
