### ISSUE TITLE
Banner NFT & On-Chain Resume

### ISSUE THREAD

**Issue by ShainDholakiya** [onflow/developer-grants#19]
# BuildOnFlowBanner

# Grant category

- [ ] OpenSource maintenance
- [ ] Developer service
- [x] Product bounty
- [ ] Educational material

# Description
Start with a Banner NFT and then have tracks for learning and completing quests on Flow. Each quest completed earns you a "stamp" in your on-chain resume NFT.
[Test Site](https://build-on-flow-banner-ar92blkgh-shain-d.vercel.app/)

## Problem statement
Gamify learning and showcase your development journey in the Flow ecosystem.

- Target audience: Flow developers 
- Evidence for the need: Emerald City DAO BootCamp (I am a graduate of the first BootCamp). Hard to easily identify what someone's experience level is.

## Proposed solution
Currently, the site allows users to customize their banner NFT and showcase their FLOATS.
Future Features: 
- Depending on which FLOATS you own, you would have some unique attributes. For example, if you have the Emerald City DAO BootCamp graduate FLOAT, you could have a graduation hat somewhere. 
- Developing tracks and quests to complete. (Flow university)
- Developing the on-chain resume booklet and SVG stamps for track/quest completions. 
- Users will be able to share their on-chain Resume on social platforms.
- More customizations to the banner (having flow website on the desktop, adding frames to choose which FLOATS to showcase, etc.)
- Allow users to upload their own custom SVG attributes and make royalties off of them when someone mints.

## Impact

- In what ways does this benefit the broader Flow developer ecosystem?
Onboards more developers to the Flow ecosystem! Developers would get to build example Dapps, be incentivized to do so, and most importantly, have fun while buidling.

# Milestones and funding

| Milestone | Deliverables   | Timeline | Risks                   | FLOW requested |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 -  Smart Contracts   | Smart Contracts on Testnet with all the attributes for the banner NFT following the standards, functions that allow the ability to change these attributes, and the on-chain SVG attributes.  | ~3 weeks  | Need time for me as I am a new Flow developer | 2500           |
| 2 - Frontend & Landing Page (https://www.buildonflow.art/)   | Make it easy and intuitive for users to customize their banner. Have a landing page clearly stating our roadmap and expectations. Get a logo created and the branding of the website. | ~2 weeks  | Waiting on logo and designer | 1500           |
| 3 -  Smart Contracts   | Smart Contracts on Mainnet  | ~1 week  | If any significant changes need to be made from the Tesnet smart contracts | 0           |
| 4 - Flow University Planning, Preparation, and Landing Page (http://flowuniversity.xyz/)   | Build a roadmap for Flow University. This would include the overall structure of tracks, submission of quests, partnerships, SVG stamps, fleshed-out quests for the first track, smart contract architecture, website designs, and on-chain resume SVG design. Also, build the landing page   | ~1 month  | Waiting on designer  | 4000           |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Shain Dholakiya | Full-Stack Engineer | Currently a Developer Advocate at Decentology and Software Engineer at Influur. Previously Software Engineer at Synthesis School, The Boring Company, NASA, Amazon, and Microsoft | shainshain99@gmail.com |

**Comment by alxflw** [comment]
Thanks for the product bounty submission @ShainDholakiya. We've carefully reviewed this and decided to pass for the following reason: Adoption and market need is unclear, making it difficult to predict the impact of the milestones.

Please feel free to resubmit once you see more adoption and clear user needs emerge. If you have any questions, you can reach out to me on Discord (`alx-flw.find#6198`).
