### ISSUE TITLE
NFT Bridges 

### ISSUE THREAD

**Issue by kofif1** [onflow/developer-grants#190]
# <Project name>
NFT Bridges
# Grant category
Developer tools / services

# Description
We are building a set of bridges that will allow NFT collections and games to move their NFTs to any chain that supports the NFT Bridges protocol.
NFT Bridges is building  liquidity pipeline between chains in the form of NFTs.

The bridges will only transfer NFTs. Never Fungible tokens. 
We are a pure play in the NFT market.

Please view this short video of me delivering the NFT Bridges pitch at the Stacks accelerator Demo day. 
https://youtu.be/WTWjqWR8Zdo

## Problem statement
DEFI moves $82 Billions a year worth of fungible tokens between chains by bridging.
NFTs move less than $1 Billion a year.
They are locked in owners wallets and in native NFT market.
NFTs are a big non-monetized segment of  Web 3.0

NFT Bridges is building a set of bridges and a launch pad that will allow makers to mint their collections/Game assets across chains and tap into multiple liquidity pools and multiple collectors/gamers pools. 

We will help make NFTs as liquid as fungible tokens. Increase liquidity across chains and grow the market for everyone. 
 
- Target audience
NFT Collection owners, NFT Collectors/investors. Web 3.0 game developers, Gamers, NFT markets and chains that want to participate in our launch pad and get to mint/sell/enjoy the liquidity that comes with participating in  our Multi-chain launch mechanism. 

- Evidence for the need

Degods collection - Degods were a very succesful NFT collection on Solana. The floor price was about 600 SOL. ($11,000). Frank, the head Degod, figured out where the market was going to, and got a $4 Million grant from Polygon to bridge the collection. He used the money to bridge to Polygon. Ethereum and Bitcoin. 
Two months later the Floor price rose to more than 1000 SOL. 
Frank injected more than $78 Millions to the collection by bridging and tapping into liquidity pools and collectors pools on other chains.

All collections will want to do that.

And we can provide them a way to do so!

## Proposed solution
We are building a set of bridges that will allow collectors to move their NFTs between chains and monetize them  where it makes the most sense to do so.
Our platform will allow collection owners to mint across chain on day one and sell out by tapping into numerous liquidity pools and collectors pools on different chains.
The bridges will facilitate the transfer of NFTs between chains by locking an NFT in a smart contract vault in the bridge and minting an exact same NFT on the new chains. 
Collectors will be able to move the NFT to where it has more demand/better pricing. 
Collection owners and game developers will be able to develop and monetize diverse communities across chains. Growing their user base.
NFT Bridges developed the "Bridge monitor" smart contract and API that checks and verifies that the specific wallet has the right to move an NFT in and out of the vault, even if the wallet is new to the NFT. Regardless to the chain the NFTs is active on at this point in time. 

## Impact

NFTs will become much more liquid. The transaction volume will grow and chains that will support the NFT Bridges protocol will be able to enjoy from more liquidity, more token usage, more users etc. 
Same thing for the NFT markets that are active on the chains that will support the NFT Bridges protocol. 

NFTs will become as liquid as fungible tokens when we are fully deployed.

- In what ways does this benefit the broader Flow developer ecosystem?

Flow can become even a bigger player in the NFT segment of Web 3.0.
The chain, and NFT markets within it can entice collections from Ethereum, and other chains to move to Flow through the bridge and get additional transactions and liquidity.
the bridge will create a competitive race between chains to get collections and users to mint more on their infrastructure. Flow is strongly positioned to take advantage of this situation if it chooses to support the project.

Game creators can grow their audience by offering the game assets as NFTs on other chains and allowing users to move them to the Flow game environment. 

DEFI companies can offer loans for high value NFTs that we can move to Flow from other chains. Allowing the NFT investors to monetize with Flow tokens without having to sell. 
We will work with Flow DEFI companies that want to fascinate that and actively collaborate with them and the chain on targeting the desirable assets and enabling their migration to Flow.

These new liquidity pools and human pools will grow Flow's user base and the use of its tokens. 

I believe that this is what we are all striving to do.

# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - MVP   | Smart Contracts | 6 weeks  | - | 10,000           |
| X - Adoption   | Recruiting collections and game companies. Creating Smart contracts for them to migrate to Flow| 14 weeks  | - | 25,000           |
| X - Maintenance   | Resolving issuing and fixing bugs | 10 weeks  | - | 15,000           |

Total funding proposed: <$50,000>
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Ilan | Founder | ... | ilan@nftbridges.xyz |

**Comment by franklywatson** [comment]
Thanks for the chat today. As discussed we're not yet able to prioritize NFT bridge development until a few other platform updates are in place, specifically cross-chain messaging. We can take a look again at some future time when those are delivered to consider this proposal.
