### ISSUE TITLE
 Cadence Linter Minimal Type Recommendation

### ISSUE THREAD

**Issue by nozim** [onflow/developer-grants#191]
### Grant category

[x] Developer tools / services
 
[x] Open source maintenance
 
### Description

The Principle of least privileges states that every unit of computer system/code/user or other component should have access to very minimal possible set of privileges to accomplish it's work. 

### Problem statement 

Let's imagine following smart contract:
```
pub contract VaultContract {
	pub resource Vault {
          pub var balance : Int

          init(amount: Int) {    
	          self.balance = amount
          }

        pub fun getBalance(): Int{
	        return self.balance
        }

        pub fun rob() {
	        log("this should not be reachable")
        }
   }
			
   pub fun createVault(){
	 let res <- create Vault(amount: 10)
         log(res.getBalance())
         self.account.save(<-res, to: /storage/vault)
   }
}
```

The variable `res` when placed in storage exposes more of internals of the `Vault` resource that it should in order to retrieve the balance.  
A much safer way to write it would be to declare interface:
```
pub resource interface VaultBalance {
   pub fun getBalance(): Int
}
```
and restrict resource to an interface that only exposes `getBalance`:

```let res : @{VaultBalance} <- create Vault(amount: 10)```

The same analysis can be equally applied to structures and contracts. 
### Problem solution

The solution for this problem would be extension of Cadence linter to detect those scenarios for all the resources, structures and contracts detected.  

### Impact

Main impact will be for the Cadence smart contract developers, allowing them to write more secure and reliable contracts. At the same time reduce time for smart contract code audit before deployment. 

## Milestones and Funding 

| Milestones      | Deliverables | Timeline  |  Risks |  USD Proposal |  
| ----------- | ----------- |----------- |----------- |----------- |
| Initial Research and MVP      | Initial version of analyser for Resources and Structs  | ~ 5 weeks | - | 5 000 | 
| Research and implementation for Contracts | Additional commits in same pull request  | ~ 5 weeks | - | 5 000 |
| Update of documentation and other artefacts | Amendments in cadence-tools repository | ~1 week | - | 2000 |
| Bug Fixes and maintenance | Code refactoring and test suite enhancement | ~5 week | - | 5000 | 

Total funding proposed: 17 000 USD
## Team 

| Name | Role | Bio | Contact | 
|------|------|-------|----------|
| Nozim Mehrubonov | Backend Developer | Experienced backend engineer with over a decade of experience in development of various systems. Crypto and Open Source enthusiast. | nozim.mehrubonov@gmail.com |

**Comment by nozim** [comment]
Related https://github.com/onflow/cadence-tools/issues/5

**Comment by nozim** [comment]
Work in progress: https://github.com/onflow/cadence-tools/pull/193

**Comment by franklywatson** [comment]
Closing since this lint case won't apply to future stable cadence
