### ISSUE TITLE
Footprint Analytics - Grant Application

### ISSUE THREAD

**Issue by LynnTsang** [onflow/developer-grants#193]
# Footprint Analytics

# Grant category
- Developer tools / services

# Description: 
Footprint Analytics is a blockchain data solutions provider. We leverage cutting-edge AI technology to help analysts, builders, and investors turn blockchain data and combine web2 data into insights with accessible visualization tools and a powerful multi-chain API across 20+ chains for NFTs, GameFi, wallet profiles, and money flow data.

## Problem statement
Blockchain is still a new technology. It’s fair to say that we are just beginning to understand and explore the value of the data it provides. At this early stage, being able to collect, summarize and visualize data effectively is critical. Currently, most blockchain analytics tools focus on cryptocurrency quotes and compliance analysis. Why? Up to now, several roadblocks hinder the creation of powerful, easy-to-use analytics platforms for blockchain. 
- Difficult to process data
- Hard to import incremental data
- Platforms are incomplete
- Lack of data applications
- Poor analysis experiences

## Proposed solution
Footprint is the go-to web3 data infrastructure:
1. The tool that builds tools. 
1.1 27 chains, covering from raw data to business indicators to AIGC tags
1.2 The first Single source of truth for Web3 metadata
2. Saves time and resources while providing a holistic view
2.1 Can build all data aspects of a protocol on top of Footprint
2.2 Can connect Web2 data sources to understand the whole user journey
2.3 Can track cross-chain analyses on multiple projects

2 years ago, we aimed to become a better Dune for analysts. We built the first no-coding analytics tool for cross-chain analysis, covering more than 27 chains. 
After engaging with numerous industry project builders, we noticed analysts, developers, and operators need more efficient data utilization tools. Different teams within the same project are using multiple tools simultaneously, resulting in redundant and inefficient data work：
- Development: The Graph, Moralis
- Operations: Dune Analytics
- Marketing: Other growth tools

There need to be more professional providers in the industry for such solutions, which presents an opportunity for Footprint Analytics. Building upon the Footprint data platform, Footprint has outgrown data analytics to a one-stop solution provider for on-chain data. Fusing data across multiple scenarios is one of Footprint's core competitive advantages.

The data platform includes BI tools and offers multiple API output options to meet different departments' and scenarios' data utilization needs.

Here are some highlights of Footprint:
- **Most comprehensive coverage of chains and domains.** Now Footprint Analytics has the most comprehensive warehouse of indexed on-chain data, covering 27 chains, 18 NFT marketplaces, over 2000 GameFi projects, and over 1,000,000 NFT collections. 
**- The first all-in-one growth analytics tool supports Web2 and Web3 data to understand users across the webs.** Developers can simply integrate the growth SDK and seamlessly monitor project growth with our automated flows.
**- The first blockchain data platform supports structured tables which enables a 0-coding analytics experience.** Footprint provides users with an easy-to-use and drag-and-drop experience for analyzing blockchain data without the need for SQL or coding skills. Its interface is accessible to anyone looking for actionable insights.
**- Build your customized Web3 platforms with Data APIs.** Now, Footprint Analytics puts all data at the world's fingertips with a unified data API. It allows developers to access data with a single query with SQL and REST versions.
With Footprint, anyone can collect, summarize, and visualize data from the blockchain, making it easier to process and understand blockchain data. It's time to explore the actual value of blockchain data solutions with Footprint Analytics

## Impact
**1. For Ecosystem: monitor ecosystem development with data**
- Free standard growth analytics dashboard with ecosystem development metrics: such as the number of developers, projects, active users, wallets, transactions, gas fee data, etc. Take the Ethereum chain as an example: [Ethereum Ecosystem Overview](https://www.footprint.network/@Higi/Transaction-monitor)

**2. For Researchers: help the ecosystem find growth opportunities**
- Use Footprint structured data and reference data to discover potential projects, monitor different domains' development, and track key projects' performance.
- Chain comparison between the Flow chain and other chains to understand the ecosystem development, such as new developers, new contracts, etc.

**3. For Developers: accelerate your ecosystem with ready-to-use developer tools.**
- Free-to-use REST and SQL APIs covering chain, GameFi, NFT, wallet data, and more. This reduces the time and costs for developers building on Flow.
**- Several partners of Footprint are waiting for the indexing of Flow, for example, Revv studio and Animoca want to do GameFi projects analytics on Flow chain.**

**4. For Community: activate the community and increase exposure**
- Zero-coding analytics tool and standard project dashboard. All the users can do an analysis on Footprint.
- Multi-type marketing support: with insightful dashboards and research reports, we can spread the word about Flow's progress.
- GEO distribution: We have more than 50+ media channels with 500k exposure, such as [Cryptoslate](https://cryptoslate.com/author/footprint-analytics/) and [CoinMarketCap](https://coinmarketcap.com/alexandria/author/footprint-analytics).

# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-44be5de7-7fff-647b-72b7-a822c990d73f"><div dir="ltr" style="margin-left:-33pt;" align="left">

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-3dda6817-7fff-bf55-be8b-b89d80059ab6"><div dir="ltr" style="margin-left:-33pt;" align="left">

Milestone | Deliverables | Timeline | Risks | USD proposal
-- | -- | -- | -- | --
Adoption - Flow chain data on Footprint | Structured data table: Flow_transactions, Flow_event and more | 2 - 4 weeks | - | 10000
Adoption - Flow chain data APIs on Footprint | Flow chain data APIs | 1 week | - | 2000
Adoption - Flow GameFi data on Footprint | Structured GameFi data table | 1-2 weeks | - | 4000
Adoption - Flow GameFi data APIs on Footprint | Flow GameFi data APIs | 1 week | - | 2000
Adoption - Flow NFT marketplace data on Footprint | Structured NFT marketplace data table | 2-4 weeks | - | 4000
Adoption - Flow NFT marketplace data APIs on Footprint | Flow NFT marketplace data APIs | 1 week | - | 2000
Adoption - Flow NFT Collection data on Footprint | Structured NFT Collection data table | 2-4 weeks | - | 4000
Adoption - Flow NFT Collection data APIs on Footprint | Flow NFT Collection data APIs | 1 week | - | 2000

</div></b>
</body>
</html>

Total funding proposed: <30000 USD amount>
  
# Team
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-e779328c-7fff-08d7-7ac1-0794f5ff0a7b"><div dir="ltr" style="margin-left:0pt;" align="left">

Name | Role | Bio | Contact
-- | -- | -- | --
Navy | Co-founder  & CEO | 1. Over 10 years of experience in fintech, big data, e-commerce, and mobile internet development2. Entered the blockchain technology space in 20173. Led the team to develop several DeFi projects | navy@footprint.network
Tony | Co-founder & Chairman | 1. A serial entrepreneur with over 20 years of experience on Wall Street 3. Formerly Senior Vice President of Global Credit 3. Trading at Bank of America in New York; Director of Credit Derivatives Trading at Merrill Lynch, also worked at Goldman Sachs Global, JPMorgan  and Lehman Brothers | tony@footprint.network
Wade | Co-founder & CTO | 1. Over a decade of tech experience2. Director of a fintech company where he built anti-fraud systems and AI models for credit score3. Led a crypto trading team, which focused on algo trading strategy on CeFi | wade@footprint.network

</div></b>
</body>
</html>

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
