### ISSUE TITLE
Legendary Picks: Fantasy Sports Platform for Flow's Sports NFTs

### ISSUE THREAD

**Issue by micahp** [onflow/developer-grants#194]
# Legendary Picks: Fantasy Sports Platform for Flow's Sports NFTs
<img width="250" alt="Asset 1@2x" src="https://github.com/onflow/developer-grants/assets/6407848/703e9050-1567-45de-8262-b008f16911f5">

# Grant category
Developer tools / services

# Description

Legendary Picks is an innovative decentralized fantasy sports platform built on top of the Flow blockchain. Our mission is to activate sports NFTs on Flow and add new use cases that increases the velocity and value of these NFTs, by providing an interactive and secure experience for sports enthusiasts worldwide. 

### Target audience
Owners of sports NFTs on the Flow blockchain, specifically from NBA Top Shot, NFL All Day, UFC Strike, and LaLiga Golazos.

### Evidence for the need

Currently, there are no dedicated fantasy sports platforms built specifically for the Flow blockchain, although Flow has more sports NFTs than any other blockchain. The sales volume for NFTs, including NBA Top Shot & other Flow sports NFTs, hasn't been anywhere near what it used to be. According to Arizton's latest research report, fantasy sports is going to grow 2x in the next 6 years. That, coupled with the lackluster volume of NFTs since their 2021 peak, makes the timing is perfect to introduce a dedicated platform that brings together the best of both worlds. NBA Top Shot is 1000x off it's peak in volume, and a platform that incorporates existing NFTs people already hold into the real-time, day to day of sports leagues, creates a new relevance for these NFTs. A quick look at cryptoslam.io shows us that, of the 700,000 NBA Top Shot owners, < 1% of owners are transacting within a 30 days. This platform can 10x the Daily Active Users for these sports NFTs. 

Existing fantasy sports solutions are often centralized, lack transparency, and are prone to fraud. By building a decentralized fantasy sports platform on Flow, we aim to address these issues and provide a more secure, transparent, and enjoyable experience for users. Current decentralized prediction market offerings that don't prioritize sports fans, such as hedgehog.markets, suffer from low participation rates (averaging only 10 participants per poll), highlighting the need for a more engaging and user-friendly solution. Sports fans are among the most passionate and dedicated communities globally, and giving them a platform worthy of their enthusiasm could be the catalyst need for continued adoption of sports NFTs on Flow.

## Proposed solution

Legendary Picks is a dedicated fantasy sports platform on the Flow blockchain that integrates its sports NFTs, such as NBA Top Shot, NFL All Day, UFC Strike, and LaLiga golazos. This platform aims to breathe life into these NFTs by allowing their owners to participate in daily fantasy sports games, season-long leagues, and ongoing contests, thus activating them beyond mere collectibles. Sports, by nature, captivates fans. The passion and zeal surrounding sports fans are unrivaled, making a sports-centric platform like Legendary Picks a valuable proposition. 

## Impact

Legendary Picks can potentially have a significant impact on the Flow ecosystem for the following reasons:
- It amplifies the utility of sports NFTs on the Flow blockchain, thus encouraging owners to buy, use, and trade these NFTs.
- It drives higher engagement within the Flow ecosystem, making it more attractive for developers and users alike.
- It attracts new users to the flow ecosystem through and innovative, new use case
- Promotes the adoption of Flow tokens, as incentives are created for $FLOW token holders participating in fantasy sports leagues.
- The platform can become a standard for future fantasy & sports related projects, integrating them seamlessly into the fantasy sports arena.

# Milestones and funding

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Planning & Spec | Product roadmap, design assets, mockups, feature to story breakdown | 1 weeks | n/a | 1000 |
| 2 - MVP | Initial platform with basic fantasy sports functionalities integrated with NBA Top Shot | 3 weeks | Smart contract hurdles, API changes | 5000 |
| 3 - Expansion | Integration of NFL All Day, UFC Strike, and LaLiga Golazos into the platform | 4 weeks | Integration challenges, data storage | 6000 |
| 4 - Marketing & Community Building | Marketing campaigns, content, and talks to onboard users | Ongoing |  user engagement issues | 1000 |
| 5 - Post-launch Maintenance | Resolving issues, fixing bugs | 2 months | Resolving issues, fixing bugs, and changes in the Flow blockchain affecting the platform | 2000 |

Total funding proposed: 15000 USD
  
# Team
The Innovative Hype team is behind Legendary Picks. 

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Micah Peoples | CEO/Full-Stack Engineer/PM | Micah is an experience Full-Stack Engineer & Product Manager with over 6 years of experience and a computer science degree | https://linkedin.com/in/micahpeoples |
| John Rodriguez | CMO | John is an expert at viral marketing, and has been doing it for years for Bell Media SEO | https://www.linkedin.com/in/john-rodriguez-1b6033151 |
| Diane Aliño | Graphic Designer | Zhang is an extremely talented artist and graphic designer who's done all our assets for Terra Squad | https://www.instagram.com/divinedianasaur/ |
We are looking for one additional engineer to join the team as well.

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
