### ISSUE TITLE
XuperAuth | Walletless and Passwordless authentication 

### ISSUE THREAD

**Issue by Jimmygodwin** [onflow/developer-grants#197]
![](https://hackmd.io/_uploads/SyVMGaD22.png)

# Description
Welcome to XuperAuth, the walletless, Passwordless Authentication for Web3.

Our suite of APIs and SDKs is designed to empower DApps with a walletless, and passwordless authentication, revolutionizing user experiences, and increasing adoption rates in the web3 ecosystem. 

# URL
[https://supa-auth-ten.vercel.app/](https://supa-auth-ten.vercel.app/)

# Grant category

- [#] Infrastructure
- [#] Developer tools / services

## Problem Statement
**For Dapps**
1.  Research has also shown that most web3/DApps companies experience a 67% drop off due to the complexity of the wallet connection onboarding process.

2. Most DApps lose 61% of their marketing expenses due to poor onboarding flow when connecting a wallet.

3. Poor turnover due to complexity during onboarding of new users. 

**For End-users**
1. The complexity of connecting to a wallet, especially via mobile phones.
2. Connecting a wallet without understanding the security level of the platform
3. Time spent in connecting the wallet to the DApp

## Target audience
1. DApps using wallet connections to onboard end-users

## Proposed solution
1. **Simplify the Web3 User Onboarding Process:** Provide a wallet-less and Password-less onboarding process for web3 Dapps via our SDK and API's. 

2. **Reduce Complexity:** Provide zero complexity when integrating our simple auth modal within a 72 hours integration time.

3. **Intuitive UI:** Create a simple, basic, and easy-to-use interface for the users

4. **Increase web3 adoptions:** Easily onboard users using DApps that give them the average web2 user experience.

5. **Optimize Ad and Marketing Budget:** Increase retention and conversion  for DApps and helping them optimize their advertising and marketing budget.
 

## Impact
1. Massive adoption of flow Blockchain for DApps and web2 companies: Our research has show that 37% of web2 startups desire to use the blockchain but can't afford the cost of hiring or running the development process themselves. With our SDK and APIs, companies can build a DeFi or NFT application with zero smart contract interaction.

2. Massive adoption for web2 users: Increase the adoption to the flow blockchain due to the frictionless onboarding process.  

3. Universal login tool for users to access multiple DApps on the flow blockchain.

### In what ways does this benefit the broader Flow developer ecosystem?
1. Increased use cases for the ecosystem 
2. The ecosystem becomes universal storage system for most web2 companies. 

# Milestones and funding

> Note: You can leave the USD proposal empty / "TBD". Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - MVP   | Design of the workflow and the smart contract  | 2 weeks  | - | 8000           |
| 2- BETA   | Developer the SDK/API for | 4 weeks  | - | 10000           |
| 3. Beta Launch   | 20 Dapps to be onboarded  | 3 weeks  | - | 8,560           |
| 4. Maintenance   | Resolving issuing and fixing bugs | 2 months  | - | 10700           |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Godwin Jimmy | Product Manager  |  As a Product Manager, I have managed the development and deployment of various blockchain and smart contract-based applications some of which are: NFTikets (https://nftikets.io), Plutoswap (DEX), Dantown (https://www.dantownms.com/), Social Stack (https://www.socialstack.co), Cyrus NFT (https://www.cyruspahlavi.com/), Zoo NFT  (https://zoolabs.io/). | jimmygodwin371@gmail.com |
| Reuben Odunze | Blockchain Engineer |  A blockchain engineer with 3+ years of experience in smart contracts and blockchain development. | royalruby@gmail.com
| Joseph Iroghama | Lead, Frontend |  A frontend engineer with 3 years of experience in javascript, react, next, web3.js and threejs. | iroghamajoseph@gmail.com
| Helen Chinweike | UI/UX Designer |  UI/UX design with 4 years of experience in design and have worked on a series of projects cutting across payments gateways and Defi products. | hchinweike19@gmail.com
| Juliet Babatunde | Content Developer |  Content Developer and Copyright with 2 years experience. | babatundejuliet@gmail.com | 
Davies Ikhazobor Oyasor    | Backend Developer | Backend developer with 3 years experience in JavaScript, Node.js and express.js | davies@nftikets.io |

**Comment by Jimmygodwin** [comment]
Hello @SeanRobb, Is there additional information you would need to facilitate the review?

**Comment by SeanRobb** [comment]
Hello @Jimmygodwin let's chat.

We are working to ensure that building walletless applications and support account linking natively is simple and accessible for developers. (https://flow.com/account-linking)

Would love to chat to see how you see XuperAuth fitting into this vision.

Emailing you directly.

**Comment by Jimmygodwin** [comment]
Hello @SeanRobb 

following up on this for feedback

**Comment by SeanRobb** [comment]
Hey @Jimmygodwin 

In discussing with the team, this grant isn't something we will move forward with. 

Thank you for your submission.
