### ISSUE TITLE
Cadence Cookbook Updates

### ISSUE THREAD

**Issue by lealobanov** [onflow/developer-grants#198]
# Cadence Cookbook Updates

# Grant category

Please select one:

- **Open source maintenance**
- Developer tools / services
- **Educational material**

# Description

This proposal seeks to formalize requirements around potential improvements to the Cadence Cookbook, including:
- Improvements to the site's information architecture 
- Improvements to the site's UI and branding in alignment with Flow
- An MVP to demonstrate how Cadence test cases can be added to existing smart contract examples in the Cookbook

Additionally, this proposal includes updating several existing blog posts: https://medium.com/@lea.lobanov/list/flow-8cd2b40a11cd. The aim of revamping the articles' content includes: highlighting differences between Cadence and EVM-based programming paradigms, showcasing use-cases/features unique to Cadence, refreshing content to reflect latest Cadence standards, general improvements. 

## Problem statement

Target audience: 

- Developers who are new to Flow and are looking for a hands-on approach to learning Cadence via smart contract examples that follow a logical, journey-based structure. 
- Blockchain developers already familiar with basic Cadence but are looking for examples of functionality and features unique to Flow.

 
Evidence for the need:
- The current state of the Cadence Cookbook is in need of a refresh; this includes the UI, information architecture, and content presented on the site 

## Proposed solution

This proposal is an initial starting point for updates to the Cadence Cookbook, primarily focused around ideation, wire framing, and an MVP for adding smart contract test cases to the site.

## Impact

- In what ways does this benefit the broader Flow developer ecosystem?
 
By adding relevant examples and pertinent smart contract use-cases to the site, the Cadence Cookbook can serve as an authority/knowledge base for Cadence developers and those new to Flow. Many blockchain applications require similar smart contract paradigms; these can be templatized as code examples within the Cookbook and serve as a useful point of reference for developers, featuring high quality code examples and robust testing of the smart contract. Additionally, examples featured in the Cookbook can highlight the unique capabilities of Cadence/Flow and encourage new developers to join the ecosystem.

# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Information Architecture  | Develop an updated information architecture for the site. This includes: defining new journey-based information flows that follow a sequential ordering, defining Flow-centric themes that highlight the strengths/unique aspects of Cadence, regrouping existing content on the site in a logical way. | 1 week  | - | 400        |
| 2 - UI  | Prepare wireframes for updated site UI. This includes: a) refreshing existing screens/modals to have a more modern appearance in line with Flow branding, b) designing UI mock-ups of all new screens and components needed for updated site architecture, c) UI for test cases MVP. This milestone will be delivered in Figma (or other compatible UI) software. At this stage we can iterate on the UI/IA further with the Flow team based on initial feedback. | 1 week  | - | 500      |
| 3 - MVP - Smart Contract Test Cases  | Develop an MVP for how Cadence test-cases could be displayed alongside each smart contract example, ideally in an interactive format with explanation and references to the Flow documentation. This includes facilitating the data entry process for test cases when contributing to the Cookbook. Additionally, as a prototype, this milestone includes developing sample test cases for one of the existing smart contract examples in the Cookbook.   | 1 week  | - | 800        |
| 4 - Ideating new content for the Cookbook  | Ideating new use-cases/smart contract examples to add to the Cadence Cookbook, as well as more generally brainstorming new directions for the project. The deliverable for this milestone will be in the form of a written document/mindmap. | 1 week  | - | 350         |
| 5 - Article updates  | Revamp of the 5 Flow articles currently published on Medium: [link](https://medium.com/@lea.lobanov/list/flow-8cd2b40a11cd ). This includes: highlighting differences between Cadence and EVM-based programming paradigms, showcasing use-cases/features unique to Cadence, general improvements.   | 1 week  | - | 400         |

*Milestones 1,2,4 can be worked on concurrently

Total funding proposed: $2450
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Lea Lobanov | Full-Stack/Blockchain Developer  |  Founder at [Purple Dash](https://purpledash.dev). | info@lealobanov.com |

**Comment by franklywatson** [comment]
Thanks, have accepted this and looking forward to getting this done!

**Comment by lealobanov** [comment]
This grant has now been completed, will create subsequent follow-up grant for next stages of the project shortly. Thank you!
