### ISSUE TITLE
docit discord document chatbot

### ISSUE THREAD

**Issue by mrnigelalford** [onflow/developer-grants#200]
# Flow Documentation Discord Bot

## Grant category

- Developer tools / services

### Problem statement

- **Target audience:** Flow developers, community members, and newcomers to the Flow ecosystem.
- **Evidence for the need:** As the Flow network grows, there's an increasing need for instant support. The community and developers often have to search through various documentation pages or wait for community support to answer their queries. An immediate, efficient support mechanism is currently missing in the ecosystem.

### Proposed solution

A state-of-the-art Discord bot for Flow, leveraging the latest Large Language Models (LLMs) to allow users to "talk to docs" by querying Flow's Github repositories, documentation, and related articles. The bot will serve as a bridge between Flow's existing documentation and its community, providing instant answers to frequent queries.

### Impact

- The bot will streamline the support process within the Flow ecosystem, offering immediate answers. This will not only enhance the user experience but also reduce the workload on manual support teams. Moreover, by providing a centralized and interactive method to access documentation, the bot can encourage more developers to build on Flow, fostering growth in the ecosystem.

## Milestones and funding

| Milestone | Deliverables                        | Timeline | Risks                                           | USD proposal |
|-----------|-------------------------------------|----------|-------------------------------------------------|--------------|
| 1 - MVP   | Initial Bot with basic functionalities, linking to primary Flow documentation | 2 weeks  | Technical challenges in bot integration         | 3000         |
| 2 - Adoption   | Achieve 500 unique users interacting with the bot | 4 weeks  | Difficulty in user adoption and engagement      | 2000         |
| 3 - Maintenance   | Ongoing support, resolving issues, and fixing bugs | 3 months  | Technical challenges with newer versions of docs | 3000         |

**Total funding proposed:** 8000 USD
  
## Team

| Name | Role                | Bio                                                        | Contact             |
|------|---------------------|------------------------------------------------------------|---------------------|
| Nigel Alford | Lead Developer and Bot Specialist | Nigel has spearheaded numerous decentralized solutions, including building building docIT for blockchain ecosystems. | ngalford@gmail.com |

**Comment by franklywatson** [comment]
Hi @mrnigelalford - thanks for your proposal. However, we do already have a solution to this through https://kapa.ai. You can find the discord bot here: https://discord.com/channels/613813861610684416/1092650545203916810.
