### ISSUE TITLE
Extended NFT Metadata Standards

### ISSUE THREAD

**Issue by dougbutner** [onflow/developer-grants#204]
# cXc

# Grant category

- Developer tools / services

# Description

This grant is to create and document metadata standards for Music, Video, Literature, Photography NFTs. 

## Problem statement

We answer a big question that every NFT creator has had. What fields do I use for the metadata?? 

- Target audience
NFT Projects and creators of all kind. 

- Evidence for the need
In [flips 636](https://github.com/onflow/flips/blob/120b8aa473e5040db2b99034d2118fb78d053cdf/application/20210916-nft-metadata.md#L4) an identical need was addressed. This is a technical need that most technical people glance over, but every end-user is directly affected by. It's a small but impactful way to make the NFT ecosystem easier and more useful.

## Proposed solution

To put Flow further ahead in terms of NFTs, we hope to expand the Metadata standards offered.  

This grant will create metadata standards for video, music, and more, as well as teach people how to use them. In addition to solving this glaring real- world problem, our metadata is the first to incorporate both time and geography, giving future applications more information to use to sort it later on.

[example](https://github.com/currentxchange/WAX-NFT-Metadata-Standards)

## Impact
Creators want to create, and stepping into the NFT world can be daunting at first. Choosing the right fields when creating a Music NFT, or other media NFT is surprisingly difficult to nail, and can be time-consuming. Neglecting to add and fill out the proper feels means that the NFT purchaser gets something that seems of less value, something generic. With our easy metadata standards, anybody can click a few buttons and have great metadata that represents their art fully. This grant will create metadata standards for video, music, and more, as well as teach people how to use them.

# Milestones and funding

| Milestone | Deliverables | Timeline | Risks | USD proposal |
|-|-|-|-|-|  
| 1 - Metadata standards | We will provide a series of well-thought-out JSON metadata structures for Music, Video, Literature and Photography NFTs. These standards will be designed for broad compatibility and published in a Github repository. They will include a general standard along with specific standards for each media type. | 2 weeks | Compatibility | $9,900 |
| 2 - Implementation guides | We will write comprehensive documentation on how to implement these metadata standards to create NFTs on Flow. The docs will explain the metadata standard, provide instructions on implementation, cover how to modify the standard, and detail how to mint. The goal is to enable anyone to seamlessly create NFTs on Flow using our metadata standards. | 2 weeks | Communication | $15,100 |
| 3 - Tutorial articles | We will publish instructional articles that walk through how to use our standards to generate NFTs on Flow. To drive adoption, we will produce visual assets and marketing copy to promote the articles on social media. The articles will include an overview of the metadata standard, a guide to implementing it, and a start-to-finish tutorial on deploying an NFT collection using the standard. Our documentation and tutorials will provide the information needed for creators to easily mint NFTs on Flow. | 2 weeks | Examples | $14,000 |
| 4 - Marketing | Promoting articles on social media including paid ads | 4 weeks | Cost vs Impact | $8,000 |
| 5 - Upkeep | Ongoing updates to docs and standards | 10 weeks | Scheduling | $3,000 |

Total funding proposed: $50,000

  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Douglas Butner | Full-Stack Developer | [linkedin](https://www.linkedin.com/in/douglasbutner/) | douglas@cxc.world|

**Comment by franklywatson** [comment]
The FLIP referenced has already been implemented: https://developers.flow.com/building-on-flow/core-contracts/nft-metadata. To my understanding this has been addressed already

**Comment by dougbutner** [comment]
Hello @franklywatson, 

Yes, FLIP 636 addressed the same need. 

I'm offering to bring the metadata into the real world to help creators make more useful NFTs. 

<img width="543" alt="Screen Shot 2023-09-16 at 7 23 49 AM" src="https://github.com/onflow/developer-grants/assets/1251232/de3ba868-d49c-43f3-8c34-ca3569168032">

What you have is wonderful, it's just not very **immediately useful** to the people who need to use it. 

You can compare these metadata to the standards I deliver, which are extension on top of the existing solution(s) you've linked. 

<img width="755" alt="Screen Shot 2023-09-16 at 7 28 33 AM" src="https://github.com/onflow/developer-grants/assets/1251232/343212fe-c551-4010-818c-be53e9a2441a">

If you'd like to work with me, I'll make your metadata more useful. If you have any more clarifications I'm happy to respond. If you don't see the value, that's fine too, all good just trying to help out crypto for those who will listen.

**Comment by franklywatson** [comment]
Thanks. We discussed this internally and given current priorities this isn't something that we can move forward with at the current time.
