### ISSUE TITLE
Follow up grant Overflow

### ISSUE THREAD

**Issue by bjartek** [onflow/developer-grants#206]
# Overflow

# Grant category

- developer tooling
- 
# Description

This is a follow up grant 4 for  https://github.com/onflow/developer-grants/issues/12, https://github.com/onflow/developer-grants/issues/87, https://github.com/onflow/developer-grants/issues/136 and https://github.com/onflow/developer-grants/issues/172

## Continued supported. 
The initial grants saw a lot of value and the follow up grant continued to give value. Overflow can already enable users to test secure-cadence and give feedback to dapper. Overflow also helped prevent an error in the recent test spork simply by keeping it up to date and alive and running an extensive test suite on the new version of flow. 

# Milestones and funding

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Stable cadende support   | Support | stable cadence release  | Overflow needs to support stable cadence.  This work has already been going on since the last grant| 10000          |
| 2 - Better parsing of input/output   | new version/library | 3 weeks| Overflow currently has code to parse input and output from go to cadence. This code needs to be restructure to meet the needs that some developers have. An added benefit is that i want to extract code that only rely on cadence into a seperate library so that it is easier for others to reuse.| 5000          |
| 3 - Tutor mode  | new version/library | 3 weeks | When creating demos using overflow there are currently some manul steps that needs to be done. This goal would enable that process to be a lot smoother | 5000          |
| 4 - Flix support | new version/library | 3 weeks |  FLIX has been introduced in flow-cli/flixkit. It would be very nice to support flix directly in overflow so that it can be more widely adopted | 5000          |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Bjarte Karlsen | Code-monkey | I sling code and have fun and help some people too | bjarte@bjartek.org |

**Comment by bjartek** [comment]
I was asked to set the period to 6months in the previous grant but if you want that can be adjusted.

**Comment by bjartek** [comment]
For clarity the previous grant is valid until end of october.

**Comment by chimpytuts** [comment]
@bjartek Hello! Nice to meet you! Do you still need someone to do this?

**Comment by bjartek** [comment]
@chimpytuts i dont follow, this is me applying for a grant, not me creating a grant for others to apply to.

**Comment by bjartek** [comment]
demo urls  

1. https://asciinema.org/a/HRSwjTL1f0yk0KGXxt86D6ct9

1. https://github.com/bjartek/stable-cadence/blob/give-admin-direct-cap/main.go

**Comment by bjartek** [comment]
New features that are already part of the stable-cadence branch

- get the entitlements of different authorizers in the result object of a transaction.

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
