### ISSUE TITLE
WalletD - Application

### ISSUE THREAD

**Issue by LivBoss** [onflow/developer-grants#208]
Project Name:

WalletD

Grant Category:

Open Source Maintenance
Developer Tools / Services
Educational Material

Description:

WalletD is an open source, multi-currency cryptocurrency wallet SDK. It is designed to allow any new or existing blockchain entrepreneurs to instantly build a fully operational, secure, and interoperable wallet infrastructure. In addition, the SDK will include pre-built integrations with existing blockchain and cryptocurrency service providers (such as swap providers, on/off-ramps, reporting tools etc) which can be added just as easily.

Problem Statement:
[Target Audience; Evidence for the need]

Almost every single blockchain project or tool requires wallet infrastructure, but this isn’t always easy to build, and is also very resource intensive to maintain. WalletD’s SDK removes the need for time and development resources to be spent on building and maintaining a secure wallet infrastructure, as developers can pick out which currencies they want to support from our library and slot them straight into their back-end with peace of mind.

What we are building is completely novel to developers, and in time is aimed at becoming the backbone of almost all blockchain and cryptocurrency projects.
Our goal is to provide developer tooling that improves the overall development experience.

Our target audience is broad as we are looking to attract all current and future blockchain developers. We have seen a drastic increase in the use of SDKs in cryptocurrency projects with [SDK installs growing 191% Y/Y in Q2 of 2023](https://www.alchemy.com//blog/web3-developer-report-q2-2023) and we also have in depth experience of how difficult it is to build and maintain a wallet. Current costs of wallet development are eye-watering ([around $120K without maintenance](https://topflightapps.com/ideas/how-to-build-a-crypto-wallet-app/) [[source 2](https://www.cryptotimes.io/cost-to-develop-your-crypto-wallet-app/)]) and that doesn’t even account for the risks involved as one tiny mistake could lead to a fatal vulnerability. The need for a reliable, easy-to-use, wallet SDK is undeniable.

Proposed Solution

We’re building a massive open-source SDK which will include ready-to-use modules for noncustodial cryptocurrency wallets on as many different blockchains as possible. This will allow new and existing developers to instantly pull together the backend of a multi-currency wallet that supports whatever blockchains they want. In addition, the SDK will include modules with ready-made integrations with other services such as credit card on-ramps, in-app swaps, or wallet reporting tools thus allowing developers to provide additional (potentially revenue-generating) services to their customers.

Impact
[In what ways does this benefit the broader Flow developer community?]

Firstly, what this integration will do is allow developers looking to build in the Flow ecosystem a foundation to build upon. Almost every blockchain project needs a wallet and WalletD will provide a fully-functional wallet module which can become the base upon which any future Flow tool could be built. However, this is just the tip of the iceberg.

The second and most important consequence of this module is that any developers building any blockchain project or tools can incorporate Flow into their project without the need for any additional resource spend. Flow can quickly be incorporated into any multi-chain environment and become a part of the interconnected multi-ecosystem blockchain industry. This means that there will be increased exposure to Flow, increased use and trading of FLOW tokens, and the potential for a wider range of tools becoming available to the Flow ecosystem.

Milestones & Funding:

Milestone 1: 
Integration module for Flow in WalletD.
Estimated Timeline: One month

Milestone 2:
Smart Contract Support. This would include, but is not limited to the development of the functionality within WalletD to enable the deployment of smart contracts which interact directly with Flow.
Estimated Timeline: One month

In order to achieve these two milestones, our project would require our full core team.

Below is a breakdown of our monthly team costs, and the requested grant funding would cover a portion of these costs for one month:

Head of Engineering - Cost: $15,000
Senior Engineer 1 - Cost: $12,000
Senior Engineer 2 - Cost: $12,000
Senior Engineer 3 - Cost: $12,000
CEO / Founder/Ops: $20,000
Finance: $10,000

Total Funding Proposed:
[USD]

$50,000

Team
[Name; Role; Bio; Contact Info]

Riccardo Spagni 
Github: https://github.com/fluffypony
Our key team member, Riccardo Spagni has been involved in the cryptocurrency world since the early stages as he has been a member of the Monero Core Team since Monero’s inception. He acted as its first Lead Maintainer and was one of its core contributors for many years. Since then, he was the founder of cryptocurrency invoicing platform, GloBee; the founder and CEO of MyMonero; the Co-Founder of Tari (an upcoming smart contract protocol operating as a sidechain of Monero); Co-Founder of Yat; as well as a founder and CEO of a number of more traditional businesses.

Zaheer Seedat - 
LinkedIn: https://www.linkedin.com/in/zaheer-seedat-ca-sa-7aa8b558/
Zaheer is a qualified and experienced chartered accountant.  He has previously worked in the financial sector with some reputable institutions, such as Deloitte South Africa, ABSA Bank, and Nedbank.  Whilst being the CFO for The Spagnis, which is an investment office focused mainly on the cryptocurrency and NFT industries. This has allowed him to gain extensive experience within the crypto space. As a financial leader, he has become an asset as the CFO of Slaz.

Jonathan Purnell -
LinkedIn: https://www.linkedin.com/in/jonathan-purnell-874069105/
Jonathan completed his Bachelor of Laws at the University of Cape Town and his Masters of Laws at New York University. He has 5 years experience working at the world renowned Norton Rose Fulbright as a tax attorney and being influential in the establishment of their cryptocurrency and blockchain practices. Since becoming the General Counsel for The Spagnis, as well as for Tari Labs, he has developed a deep understanding of the practical and regulatory laws within the crypto industry. He is currently serving as the General Counsel for Slaz.

Devin Pearson - 
LinkedIn: https://www.linkedin.com/in/pearsondevin/
Github: https://github.com/devinpearson
Devin operates at a senior level, with 15 years of software development experience.
He started out as a PHP Developer, and worked as a Software Architect for GloBee, where he started to grow his knowledge in crypto technology and development. With a massive amount of experience in the space, he has been a force to be reckoned with as the Lead Maintainer of MyMonero. He is putting his extensive knowledge of crypto tech to work as the Head of Engineering for Slaz.

Karl Buys - 
LinkedIn: https://www.linkedin.com/in/karl-buys/
Github: https://github.com/karlbuys
Karl has a strong 18 years of software development experience, which has given him an extensive and a deep understanding of the development environment. He operates at a senior level within the crypto dev space, and he put this extensive knowledge to work when he joined The Spagnis team as Development Lead. He then became a Core Developer at MyMonero, and has since become a strong asset to the Slaz team as a Senior Software Development Engineer.

Patrizio Spitalieri - 
LinkedIn: https://www.linkedin.com/in/patrizio-spitalieri/
Patrizio completed his Bachelors Degree in Business Administration and Management at Regent Business School. He built a high skill-set while working for GloBee as the head of Business Development and Operations. This gave him the edge when it came to understanding the inner workings of crypto in the business space. He then moved on to become the Head of Operations, Crypto Payments and Digital Asset Interoperability at MyMonero. The leadership and business development skills that he possesses are an asset to the Slaz team, where he now holds the role of Head of Operations and Growth.

**Comment by SeanRobb** [comment]
@LivBoss could you please share your dev docs and adoption metrics for your SDK?

**Comment by LivBoss** [comment]
> @LivBoss could you please share your dev docs and adoption metrics for your SDK?

@SeanRobb - Here is. the link to out developer docs: https://developer.walletd.org/
As an open source library, we don't track adoption metrics.

**Comment by SeanRobb** [comment]
@LivBoss thank you for submitting to our grant program.

This doesn't currently align with the committee's goals. 

Thank you for your submission.
