### ISSUE TITLE
WAVES

### ISSUE THREAD

**Issue by waves-project** [onflow/developer-grants#212]
# Waves: The Next-Gen Music Production Ecosystem on Flow

## Grant Category

- Developer tools/services
- Educational material

#### Target Audience

- Independent music producers who struggle with revenue and beat ownership
- Artists seeking unique beats and enhanced lyric production tools

#### Evidence for the Need

- **Low Earnings**: Many producers sell beats for as low as $25 per license, creating a race to the bottom.
- **Data Loss**: Producers lose valuable work due to hardware failure or data corruption.
- **Ownership Disputes**: Lack of standardized contracts and authentication often leads to disputes over beat ownership.

### Proposed Solution

Waves will revolutionize the beat-making industry by creating a blockchain-backed marketplace to securely create, tokenize, and sell beats. We'll also enhance the beat-buying experience by integrating an AI tool that assists with lyric and vocal generation. This combination does not exist in any current marketplace and leverages web3 capabilities to solve age-old issues.

### Impact

Waves will offer a unique use-case for Flow’s blockchain technology, demonstrating how smart contracts and decentralization can solve tangible problems in the music industry. We will also create open-source libraries to foster similar innovations on Flow.

## Milestones and Funding

| Milestone                    | Deliverables                                | Timeline | Risks                       | USD Proposal |
|------------------------------|---------------------------------------------|----------|-----------------------------|--------------|
| 1 - Platform Development     | Seamless payments and abstracted web3 experience as well as AI tool enhancement | 3 weeks | Technical difficulties, UI/UX hurdles  | $20,000     |
| 2 - Waves Beats Challenge    | Hosting competition with top industry judges| 4 weeks  | Low participation, Technical failures | $30,000     |
**Total funding proposed: $50,000**

## Team

| Name   | Role               | Bio                                           | Contact                 |
|--------|--------------------|------------------------------------------------|--------------------------|
| Delz   | Founder & CEO      | Background in Economics and Marketing Management. Experienced in UX design. Built agrifyafrica.xyz & astraverse.xyz | contact@collectwaves.com  |
| Seun   | CTO                | Skilled in software architecture and back-end development  | seunsanyaa@gmail.com     |
| Joseph | Smart Contract Lead| Specializes in blockchain and smart contract development  | Jsatimehin@gmail.com      |
| Theo   | AI Integration Lead| Expert in machine learning and AI-powered tools | theophilus.ogbolu@gmail.com |

## Additional Information

We have been selected for an accelerator program by Sony Music, giving us direct access to mentors from Sony Music, Spotify, TikTok, Meta, Soundcloud, Empire, and more. These mentors will serve as the judges for the Waves Beats Challenge, adding credibility and outreach to our initiative.

**Comment by Aliserag** [comment]
Hey team, given recent ecosystem developments there might be an opportunity to explore a conversation around this, reaching out.

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
