### ISSUE TITLE
Platform Game and entertainment video content edukasi animasi  

### ISSUE THREAD

**Issue by axlywb** [onflow/developer-grants#214]
# <Project name>
     Entertainment Game and edtech 

# Grant category
    Game and video edukasi animasi

Please select one:

- Developer tools / services
- Educational material

# Description
  GAME and entertainment industry education video film animasi
this project takes people from web2 to web3.
overcoming the problem of expensive web3 games to play NFT games with this the team has a solution and makes players feel free to evolve to web3. 

Entertainment and education

there are 3 that we built.

1. Games
2. NFT
3. educational content through film entertainment / virtual space

Project objectives
# Projects
in the GAME that we made.
makes it easier for users to purchase GAME items by ton/sol, flow,
buy tons/sol, flow, easily and exchange them for fiat money.
because the platform we built provides global payment cards.

#education
and educational animated film projects aimed at children. This goal is only to entertain and engage users on Telegram. Currently, the media is dominated by political interests. We also provide learning materials on the open campus web3

bringing together platform, technology and community. This is the basis of our vision regarding the entertainment Industry, and this is why we decided to host two platforms simultaneously to emphasize this idea. more unique space.

The benefits of adopting chain flow, sol,Ton are demonstrated by attracting new audiences, brilliant exhibitions, and the creation of virtual spaces.

With the world of architecture paying high attention to space and cyberspace

We hope to reach more than 3 million people through creator and partner social media, media releases, and collaborations with influencers;

will look aesthetically pleasing, so we expect a lot of content and media engagement

https://www.bonfire.xyz/GLADIESNEY/365325080-823272549591097-8137195961368032667-n

https://drive.google.com/file/d/1_ZKhLbJbkpZCNBzmGV8A0hxgaRgyqZIC/view?usp=drivesdk

## Problem statement
  bringing many web2 users to web3
  
- Target audience
Target audience for small children to adults.

- Evidence for the need
our initial needs,
$24000USD

We have also proposed support to other parties but their decision is not yet clear

## Proposed solution
   overcoming gaming on web3

## Impact
    The impact of our project is education through GAME and entertainment. and will bring many users

- In what ways does this benefit the broader Flow developer ecosystem?
  we will utilize on chain flow in our GAME

impact on the flow ecosystem we will use fees in GAME using flow tokens

For educational videos, we will not focus too much on cost services because our vision is education through entertainment

# Milestones and funding
Education builds online association communities involving artists, etc
2000USD
VR designer art
5000USD
Development and launch
8000USD
marketing
2000USD
project introduction event on initial release
7000USD
about $24000USD
Address Multichain team
0x22b62684B043fB949B0d8924C596f70B39669026

> Note: Please consider adoption and/or maintenance milestones at the end of your project. 

if this support soon

We hope the process will be completed in development

| Milestone | Deliverables   | Timeline desember 2023 | Risks             | USD proposal | $24000
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - MVP   | developer | 7 weeks  | $8000 |          |
| X - Adoption   | 5 team using this project | 4 weeks  | - | -          |
| X - Maintenance   | Resolving issuing and fixing bugs | 3 months  | - | -       |

Total funding proposed: <total USD amount> $24000
  
# Team
Community developer VR 

| Name devan | Role   engineering    | Bio education build GAME and avatar and AR/VR | Contact https://www.bonfire.xyz/GLADIESNEY       |
| ---- | ------------------- | --- | --------------- |
| contact | Full-Stack Engineer | ... | starmoonlightdevgame@gmail.com |

**Comment by axlywb** [comment]
https://questbook.app/dashboard/?grantId=0xbf93fc6825b5e9ba9a3d7fcf3d14cdfcf3b4c734&chainId=10&proposalId=0x4b5&isRenderingProposalBody=true

**Comment by axlywb** [comment]
@franklywatson discussion 
https://github.com/axlywb/interact-with-your-first-smart-contract-

**Comment by axlywb** [comment]
https://github.com/axlywb/security-of-the-game-platform./tree/main

**Comment by SeanRobb** [comment]
Hello @axlywb, we appreciate you submitting your grant proposal. This currently is not aligned with our current goals for the grant program. 

Thank you,
Sean
