### ISSUE TITLE
Creating reviews, threads, articles, videos and educating French speaking audience to Flow protocol and ecosystem

### ISSUE THREAD

**Issue by FloJdC** [onflow/developer-grants#217]
# Name
- Journal du Coin Grant Proposal

# Grant category
- Educational and promotional material

# Description
The past 5 years, as the first French speaking crypto related media in the world, we’ve been looking to join the concrete community of the main actors of the blockchain ecosystem, raising and boosting mass adoption of all the different services and projects the technology can bring on the table, like infrastructures layer 1/2/3, DeFi, NFT, and so … You may remember we already worked with the Flow project in 2021 (1 of the articles we produced is here : https://journalducoin.com/nft/plongee-au-coeur-du-phenomene-nft-flow-et-sa-croissance-insatiable-affolent-la-cryptosphere/)

Since the creation of our media, we have progressed to become the largest French-speaking crypto media by far, and we will put our skills and experience at the service of the Flow protocol to succeed in this new kind of promotion. We already have 1 million regular readers/month.

Our goal today is to become the main lever to raise the reputation and increase the Flow community among the French speaking public. To do so we have a lot to offer. The objective of this proposal is to offer Flow community the possibility to commission a full year contents package and to educate French community to Flow ecosystem in various ways and with all types of Journal du Coin contents.

## Problem statement
As the blockchain technology rises in a perpetual fight between a few reliable actors and a lot of pointless projects, our main objective is to guide our community in this wild ecosystem. As we believe in your vision and project, we would like to introduce more Flow to our followers.

We have at our disposal many communication tools on various networks : 

- Social networks such as Facebook, Linkedin, Discord, Instagram ... (more than 150K subscribers)
- Videos on platforms such as Youtube, Twitch, TikTok ... (more than 250K subscribers)
- Newsletter with 60K readers daily
- On top of this our website journalducoin.com with more than 1 million readers/month 

That allow us to create effective strategies in the long term to impose Flow in the French-speaking countries (300 million people speak French in the world). I’m sure you can figure out how this opportunity can bring our readers community to consider Flow in terms of investment.

## Proposed solution
As told before, the main objective is to introduce Flow to our community, encourage them to use your services, and join the governance of voting protocol by staking. To achieve this, we will of course implement sophisticated and highly effective long-term communication strategies through all our means of communication :
 
- Press articles (for e. g. [La révélation Flow : tout savoir sur la cryptomonnaie du futur géant des NFT - Journal du Coin](https://journalducoin.com/nft/flow-token-blockchain-tokenomics/))
- Technical & data releases (kind of “Messari state of”) like this one, but in French : [Osmosis Protocol Usage Report Q2 2023 | Messari](https://messari.io/report/osmosis-protocol-usage-report-q2-2023?referrer=all-research)
- Tutorial videos [Tuto dYdX : tout savoir sur le DEX qui vous paie pour trader des cryptomonnaies - YouTube](https://www.youtube.com/watch?v=XiBIjrjmgbA&t=599s) 
- Podcasts, like this one [Near, le futur OS du Web3 ? Entretien avec Marieke Flament - YouTube](https://www.youtube.com/watch?v=_lXz1gd9ErI)
- Interviews [Rencontre avec Julien Niset co-fondateur d'Argent, le wallet essentiel pour Ethereum et ses L2 - YouTube](https://www.youtube.com/watch?v=euD9ixc4UmE)
- Twitter Threads [Mantle ecosystem presentation thread](https://twitter.com/LeJournalDuCoin/status/1683515117726572554?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1683515117726572554%7Ctwgr%5E1da14bc037b1527cb6c640b1b664be55fac6a6f1%7Ctwcon%5Es1_&ref_url=https://gov.1inch.io/new/discussion?topic=2893)
- Short Tiktok videos [Journal du Coin (@journalducoin) | TikTok](https://www.tiktok.com/@journalducoin)
- Instagram Bubbles [Journal du Coin (@lejournalducoin) • Instagram](https://www.instagram.com/lejournalducoin/?hl=fr)
- Social network campaign (Facebook, Twitter, Linkedin etc ...,) [Facebook](https://www.facebook.com/lejournalducoin)
- In the long term, gamification (Galxe strategies, Easter Eggs Hunt, Call to Action, Tokenization of articles (NFT),  etc …)

Ultimately, we can offer a full editorial coverage to Flow ecosystem. The idea is to plan the Flow promotional strategy for 1 year in direct collaboration with the team, and help our large and loyal community to become a pillar of the Flow ecosystem.

## Impact
First of all, with more than one million readers per month, we are undoubtedly the most important French-speaking media for cryptocurrencies and blockchain technology. We have readers all around the world. We are an international team of about 20 people, and we work with many top partners/DeFiprotocols/Layers 1-2-3 ... 

Moreover we have a great expertise based on several years of experience, and a huge network since we are present on all the most popular social networks (facebook/Twitter/Discord/Linkedin/Instagram ...) as well as video/podcast and streaming platforms (Youtube/Twitch/TikTok ...). 

In addition we distinguish our media in a real Web3 way, becoming a validator of the Flow ecosystem, as we began to offer technical infrastructure for partners this summer. It's a very usefull tool to bring community into the governance. You can check here : https://journalducoin.com/staking/ (a lot more to come very soon). We don't include this aspect in this topic, but we're open to discuss about it.

We also launch gamified education with Galxe campaigns dedicated to partners, and we have historically organised dev meetups in France since 2016. Now, we can target devs with recurring dedicated local meetups in 5 French cities (Toulouse, Nice, Monaco, Paris, Strasbourg).

Finally, we can rely on a French-speaking community of regular readers who appreciate and trust us since many years.

# Milestones and funding

As this is a long-term content delivery and community building project, we can give this example running on a 1 year schedule, where we applied a global rebate as you would be paying us an annual grant (you can check our public prices on our media kit here : https://drive.google.com/file/d/1Ysy5e1cajfSZlWMjyoUYO-Ce18CBMy4l/view?usp=share_link

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |

| 2 long format articles | (tutorial, technology review, interview) | spread in 1 year | - | 5000 |
| 1 podcast | interview w/ 1 of Flow executives | spread 1 year | - | offered |
| 12 standard articles | Press releases | spread in 1 year | - | 25000 |
| 4 technical & data State Of |(full periodic ecosystemic review, as the Messari “State Of” series)| spread in 1 year  | - | 11000 |
| 2 Videos JDC | tailor made explaining the protocol as a tutorial on Flow or ecosystem | spread in 1 year  | - | 16 000 |
| 2 Twitter threads | giveaways or else | spread in 1 year  | - | 1000 |
| 8 short TikTok video |  contents on Flow feature or ecosystem  | spread in 1 year  | - | 10 000 |
| Periodic 1inch report on Instagram (one every two weeks) |  25 Flow reports on a full year basis | spread in 1 year  | - | 20 000 |
| 36 articles relay | Newsletter & Twitter/FB/Lkdn  | spread in 1 year  | - | offered |
| 36 retweets of important news | from Flow Twitter account or ecosystem partners) | spread in 1 year  | - | offered |
| 30 Backlinks |  on Flow or ecosystem projects articles | spread in 1 year  | - | 5 000 |
| 4 newsletters | sponsoring weeks (60k readers daily) | spread in 1 year  | - | 2 offered, 2 more for 3 000 |
| 4 weeks banner | display on the homepage of the website | spread in 1 year  | - | 2 offered, 2 more for 2 000 |
| 5 Galxe quest | gamified educational course | spread in 1 year  | - | 3 offered, 2 more for 2 000  |
| 1 Flow event | Hackaton or B2B meeting in Paris or Nice or Strasbourg or Monaco | spread in 1 year  | - | 25 000  |

Total funding proposed: <125000> for an entire year to launch all the promotional items included in this partnership. We accept to be paid in Flow tokens.

We will also occasionally need a direct communication channel, media & technical support, press releases, visuals, exclusive announcements, opportunities to meet with executives for interviews, and all the human and logistical support you can provide us. It is possible that in order to scale up in terms of communication and promotion we will make a new request in the medium term, but we do not yet have sufficient data to estimate the amount.

# Conclusion
Our purpose is to increase user literacy, development of the DeFi industry and decentralization. To give everyone who wants to understand the topic of decentralized finance and Flow products an opportunity to do it for free. We are in a long-term approach since the birth of our media. We have been able to find the means of our survival and our significant development for all these years. 

Today we are building a new model that will lead to a stronger involvement of our team, but especially of our community, at the heart of the 1inch protocol. It's a virtuous circle that benefits all participants, and draws its strength from this mutual and shared benefit. Have no doubts, we will be able to sustain the whole strategy perfectly.

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Florent | Partnership manager | ... | florent@journalducoin.com |
| Gregory | Editor in chief | ... | gregory@journalducoin.com |

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
