### ISSUE TITLE
Decentraclasses

### ISSUE THREAD

**Issue by HiberNuts** [onflow/developer-grants#218]
# <Project name>

# Grant category

Please select one:
- Educational material

# Description

- Decentraclasses is an innovative ed-tech platform that works on the Learn-to-Earn model enhanced by Blockchain Technology and we will be a proudly and fully decentralized platform.

- Our main goal is to transform educational courses into valuable assets and revolutionize the education sector through decentralization.With the help of our course-staking features, we hope to make education available to everyone by enabling them to earn money while they learn.

- Our main focus is to remove the traditional barriers associated with education and empower learners to benefit from their knowledge by enrolling in courses.

- We offer a wide range of both web2 and web3 educational courses to increase awareness and facilitate the transition to web3 technology.

- We are dedicated to promoting the adoption of web3, offering mentorship programs, creating career opportunities, and providing lifelong incentives.

- DecentraClasses is all about turning learning into a means of earning, making it fair and accessible to everyone.

- As per our name, we are using only decentralized/web3 based tools and services.

## Problem statement
The main problem that the project aims to solve is the lack of accessibility and monetization opportunities in traditional education systems. Many YouTubers specializing in blockchain development offer private courses on their websites, but these courses are not easily accessible to all students. Additionally, there is limited opportunity for instructors and learners to monetize their knowledge and skills. By decentralizing education and introducing staking features, Decentraclasses addresses these issues by making education more accessible, empowering instructors to earn additional income, and allowing learners to monetize their learning experiences. This not only benefits individuals by providing financial incentives but also promotes a more inclusive and democratized learning ecosystem.
Students usually buy the course but then never finish it.

- Target audience
=>Anyone with a motive to learn new technology!
- Evidence for the need
=>Integration with Our Decentralized Ed-Tech Platform: We have integrated flow into our decentralized ed-tech platform. This integration allows users to seamlessly enroll in courses on our platform using flow technology.
=>Offering Courses for flow chain Projects: In addition to enrollment, we provide specialized courses that teach users how to build projects on the flow chain. These courses not only educate users about the flow chain but also demonstrate the practical benefits it offers.

## Proposed solution

By developing Decentraclasses, an ed-tech platform that decentralizes teaching and adds staking capabilities, the initiative seeks to solve the issue. It enables blockchain development-focused YouTubers to launch their courses on the platform, improving accessibility for students. The notion of tradable courses is distinctive because it allows both teachers and students to stake their own courses and make money while they are learning, generating incentives for both sides that last a lifetime.
We provide features like:

- Course Marketplace
- Segmented Purchases
- LIVE PROJECT
- Course Reselling
- Dynamic NFT for tracking course progress on chain
- Proctored tasks and assessments

## Impact

- In what ways does this benefit the broader Flow developer ecosystem?

We are aiming for a completely decentralized education platform to prove to the web2 developer that we can truly build anything on web3 architecture, cause if you see the current implementations of other education platforms they are all based on web2 architecture which says that web3 is not credible enough to build everything which is what we want to prove wrong, which is why building on top of flow would prove the credibility of blockchain technology and at the same time we are also bringing more developers and learners onto the flow ecosystem which will help flow's vision for mass adoption of web3. 
Apart from this we also provide a dedicated academy for Flow so that Flow can host courses related to its platform, as the main key to mass adoption is by teaching and educating newcomers about the ecosystem. This platform will be a go-to stop for all Flow enthusiasts so they can learn and develop on the Flow ecosystem ultimately contributing to the ecosystem. (Flow Academy if you wanna call it😁).

# Milestones and funding

PHASE 1 Progress (In progress ~ 2 months):

1. Development of the alpha version of the product is currently underway.
2. Users will have the capability to purchase courses.
3. A wide variety of courses will be available for users to choose from.
4. The alpha version is planned for launch at the beginning of September.
5. Mentorship feature: Mentors can schedule regular meetings with students and provide special doubt sessions for users who have purchased courses.
6. Post-launch, a one-month testing period will be initiated.
7. During this testing period, users can explore the platform's features and provide feedback.
8. The focus will be on fostering community engagement to expand the user base on the platform.

PHASE 2 Goals (~2 Months):

1. Implement a strict assessment policy.
2. Incorporate a "learn to earn" model into the platform.
3. Establish partnerships with companies to showcase Bounties, Surveys, and Micro Tasks.
4. Collaborate with companies to display job and internship listings.
5. Post launch of Phase 2 a time of one month will be taken for model feasibility, product evaluation, user feedback and improvements

PHASE 3 Future Features: (~2 Months)

1. Cohorts Implementation
2. Hands-on Learning Feature
3. Proof of Learning NFT
4. Customized Roadmaps
5. Coding Leagues Integration (P2P)

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - MVP   | Phase 1 features | 2 months  | - | 2000           |
| Phase 2   | Working on feedback and phase 2 features | 2 months  | - | 2000           |
| User adoption | Active users across platform | 2 Months | - | 1000

Total funding proposed: 5000
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Aryan Ghosh | Founder | My name is Aryan Ghosh, and I'm an accidental Entrepreneur, working for myself to build something great which can neither be disruptable. Providing exposure to the students and building a student community to grow together.  | aryanghosh2002@gmail.com 
| Raghav Jindal | Developer | I am Raghav Jindal, an experienced and refined developer with comprehensive proficiency in the field of Blockchain development from writing, testing and deploying smart contracts on various chains along with Full stack - Web and App development, using technologies like - Flutter, React Js , Node Js, Database, Ui libraries, API | raghavjindal0212@gmail.com | 
Srikar Mks | Frontend developer | Advocate at The graph protocol | https://github.com/Srikarmk |
Parth Verma | Blockchain developer | Freelance crossplatform blockchain developer | https://github.com/infoparth |

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
