### ISSUE TITLE
ConnectX 

### ISSUE THREAD

**Issue by ConnectX3** [onflow/developer-grants#219]
# ConnectX

# Grant category
Developer tools / services

# Description
ConnectX is a socialFi platform that makes it easier for people to connect with each other and collaborate on financial opportunities. We're building a platform that is transparent, secure, and rewarding for users

## Problem statement
🕵️ Problem
The current social media landscape is dominated by a few centralized platforms that control the flow of information and dictate the terms of service for their users. This has led to a number of problems, including:
♻️ Lack of transparency♻️ Security concerns♻️ Limited user control♻️ Lack of user rewards

- Target audience
Daily Social media users & financial capitals

- Evidence for the need
We are a start-up company seeking out investment and grants to build our projects, and we are integrating protocol chain that provide us the fund and support we need.

## Proposed solution
🕵️ Solution ConnectX will provide 
♻️ Transparency♻️ Security♻️ User control♻️ User rewards

## Impact
ConnectX has the potential to make a significant contribution to the broader Flow developer ecosystem. By increasing the adoption of Flow, creating more development opportunities, and exploring new use cases for Flow, ConnectX can help to make Flow a more attractive platform for developers and users.

# Milestones and funding

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
1 - MVP   | Interface & Smart Contract |  4 weeks  | - | 50000         |
2 - Adoption   | 10 team using this project | 4 weeks  | - | 40000         
3 - Maintenance   | Resolving issuing and fixing bugs | 4 months  | - | 40000  
4 - Marketing  | 100k Registered User | 3 months  | - | 50000  
5 - Legal Enity | Company registration | 1 month | - | 20000
 
Total funding proposed: 200-500k
  
# Team
Mac King  - CoFounder/CEO (Full-time) 
Linkedin: https://www.linkedin.com/in/mac-king/

Chucks  - Frontend Developer (Part-time) 
Linkedin: https://www.linkedin.com/in/chukwumadblockchaindev/

OxShegz- Marketing Manager (Part-time) 
Twitter: https://twitter.com/shegzXBT

Kay- Product Design & PR (Full-time) 
Linkedin: https://www.linkedin.com/in/kaycee-alex/

Teeraboh- UI & UX Designer (Full-time)

#Link
Website: https://connectx.space/
Twitter: https://x.com/ConnectX_
Telegram: https://t.me/ConnectX3
Discord: https://discord.gg/64U4byFfxT
Medium: https://medium.com/@Connect2Earn
Pitch Desk : https://drive.google.com/file/d/1XzIxb446Qjp91AypPix2oY_yABsEtt-s/view?usp=drive_link
Whitepaper: https://net3.gitbook.io/connectx
Join Waitlist: https://noteforms.com/forms/connectx-wait-list-ardlh
Company LinkedIn: https://linkedin.com/company/connectx-incs
Linktre: https://linktr.ee/ConnectX3
Github: https://github.com/ConnectX-HQ

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
