### ISSUE TITLE
FlowBetPalace Grant

### ISSUE THREAD

**Issue by jazdevv** [onflow/developer-grants#220]
# FlowBetPalace

# Grant category

- Product

# Description

## Problem statement
Online betting platforms must address concerns about transparency and fairness, as users fear manipulation of bets and odds. Notably, experienced bettors suspect hidden bets and personalized odd adjustments, raising doubts about the platforms' integrity. Moreover, the substantial control wielded over user funds, including the potential for blockage, exacerbates these concerns. A pressing need exists for solutions ensuring equitable practices, user empowerment, and financial security.

## Proposed solution
Using flow and cadence it provides users with increased control and transparency over their bets, as the decentralized nature ensures trust and eliminates reliance on centralized authorities. Additionally, the odds are calculated algorithmically, reducing the potential for  manipulation. 
Also we aim to create a easy user experience to non-crypto users for atract more users.

## Impact

- In what ways does this benefit the broader Flow developer ecosystem?
By introducing a betting platform on the Flow blockchain, we expand the ecosystem to new areas, offering diverse opportunities for users to engage and participate in decentralized finance activities. This expansion strengthens the Flow ecosystem and promotes the adoption of blockchain technology in the betting industry.
# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Adapt to non-crypto users   | Introduce fiat payments and friendly experience to interact with flow blockchain on our site and the deployed contract on  flow blockchain for non-crypto users | 2 weeks  | - | 2500 |
| 2 - Automate bets  | Create architecture that create bets and set the results automatically | 2 weeks  | - | 2500 |
| 3 - Users actraction  | Introduce gaming bets for atract another big audience | 2 weeks  | - | 2500 |
| 4 - App deployment to serverless | Study wich platform is cheapier and better for our application & deploy the app to it server | 1 week | - | 0 |
| 4 - Marketing Design | Create advertisements and keep innovating  | 3 months  | - | 2500 |
| X - Marketing / Adoption   | Colaborations with streamers to reach people | -  | Low user atraction | 25000 |
| X - Marketing / Adoption  | Twitch ADS | -  | Low user atraction | 10000 |
| X - Serverless services & Bets API Plan | Pay the products for 3 months | 3 months  | - | 1000 |
| X - Maintenance   | Resolving issuing and fixing bugs | 3 months  | - | 1000 |

Total funding proposed: 47.000USD. Open to negotiate
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Joel Pegueroles | Full-Stack & Blockchain developer | Passionate Fullstack and Blockchain Developer aiming to revolutionize with web3 technology and betting ecosystem | joelpepa2@gmail.com 
| Iñigo Zepeda | UX Designer | Fascinated by creating efficient user experiences and engaging interfaces in the Web3 industry | inigis@hotmail.com 
 | Diego Zepeda | Frontend Developer | Enthusiastic Fullstack Developer with a focus on Frontend, dedicated to pioneering web3 technologies. | estzepeda@outlook.com |

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
