### ISSUE TITLE
ZUNI - Decentralized Identity & Verifiable Credential

### ISSUE THREAD

**Issue by vinhtrand8** [onflow/developer-grants#221]
# ZUNI

# Grant category

- Developer tools / services

# Description

ZUNI is a revolutionary solution designed to address the pressing issues of data ownership, privacy protection, and secure verification in the digital world. Built on the W3C’s Decentralized ID and Verifiable Credential data model, ZUNI ensures users have full control over their data and share only what’s necessary. Our verification process is quick and accurate, thanks to Zero-Knowledge proof technology.

## Problem statement

- **Data ownership**: Users often relinquish control of their data to external parties.
- **Sensitive Data Disclosure**: Users frequently share more personal data than necessary. This excessive disclosure exposes them to potential risks as this additional information can be easily duplicated and misused by malicious third parties.
- **Fraud Data**: The process of verifying certificates and credentials has become complex and time-consuming. Manual checks like KYC are prone to human errors and security lapses, leaving businesses vulnerable to fraud.
- **Verification on-chain**: Currently, it is hard to process KYC on-chain, due to lack of connection between on-chain & off-chain data. The verification on-chain not only needs to protect users privacy, but also ensures the correctness of data. 
- **Challenges in Building ZUNI**: During the development of ZUNI, our team recognized the lack of library support for building Zero-Knowledge verification on Cadence (we utilized Circom to construct ZK circuits).

## Proposed solution

- **Open-Source Decentralized ID Solution**: Building an open-source Decentralized ID solution based on W3C standards. This solution will empower data ownership, giving individuals control over their data and ensuring secure verification processes.
- **Verifiable Credential**: dApps can leverage ZUNI to create Verifiable Credentials. Users can then derive a claim from these Verifiable Credentials. For instance, if a dApp requires a user to be above 18 and reside in a whitelisted country to purchase NFTs, the verification and purchase processes can occur on-chain while still preserving user privacy.
- **Application of ZK Proofs**: We apply ZK proofs to protect privacy.
- **Library for ZK Verification Smart Contracts Generator with Cadence**: Recognizing the lack of library support for building Cadence ZK verification, we plan to build a library that supports generating ZK verification smart contracts with Cadence from Circom. This will not only enable ZUNI to generate ZK proofs on-chain, but also open for other developer building ZK on Flow.

## Impact

- **Interoperability**: By adhering to the W3C specification, our solution is not dependent on any specific blockchain or service. This means that a DID on Flow can be used across any blockchain to create Verifiable Credentials, enhancing interoperability.

- **Expanded Use Cases**: Our solution opens up more use cases relevant to privacy verification on-chain, such as Verifiable Credentials and Private Voting on DAO. These applications can leverage the security and privacy features of DIDs to enhance user trust and data protection.

- **Ease of Development with ZK Generator Library**: With our ZK generator library, developers no longer need to worry about porting ZK verification code from Solidity or Rust to Cadence. This simplifies the development process and makes it easier to build secure, privacy-preserving applications on the Flow blockchain.

# Milestones and funding

- ZUNI, [a first-prize winner at Flow Hackathon Season 2](https://devfolio.co/projects/zuni-6403), is currently in its MVP stage. We are now focusing on enhancing this MVP by making it more user-friendly and improving the user experience. Our goal is to prepare ZUNI for a successful launch on the Flow. We believe that these improvements will significantly enhance the value of our product for our users.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - ZK Library Development | Build ZK verifier generator for Cadence on top of the [snarkjs](https://github.com/iden3/snarkjs) library | 2 weeks | Update on Cadence 1.0 | 3000 |
| 1 - Testing ZK Library | Write unit tests and integration tests for the ZK Library | 1 week | - | 1000 |
| 1 - Document ZK Library | Write a guideline for using the ZK Library | 3 days | - | - |
| 2 - DID Logic Development | Implement DID standards smart contract following [W3C](https://www.w3.org/TR/did-core/)  | 2 weeks | Update on Cadence 1.0 | 2000 |
| 2 - Credential Logic Development | On-chain credential verification  | 1 week | Update on Cadence 1.0 | 2000 |
| 3 - UX/UI Development  | Develop mobile and web responsive interfaces, ensure performance, and integrate systems | 5 weeks  | - | 5000 |
| 4 - Go-live | Production delopment | 1 week | iOS deployment may take additional time due to platform-specific requirements | 1000 |
| 4 - ZUNI Document | Write a guideline for users to use ZUNI | 1 week | - | - |
| 5 - Maintenance | Resolve issues and fix bugs | 6 months  | - | - |

Total funding proposed: $14,000
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Vinh Tran | Blockchain Engineer | I am always eager to learn new technologies and explore the potential of decentralized systems. | vinhtrand8@gmail.com |
| David Tran | Full-Stack Engineer |  I love diving into complex problems and building innovative solutions in the world of decentralized technologies. @tranhuyducseven  | tranhuyducseven@gmail.com |
| Galin Chung | Software Engineer | With a strong foundation in Data Structures and Algorithms, I never stop learning and delving deep into technologies. @galin-chung-nguyen | galin.chung.nguyen@gmail.com |

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
