### ISSUE TITLE
Niftory Hybrid Custody Frontend Showcase

### ISSUE THREAD

**Issue by siddthesquid** [onflow/developer-grants#222]
# Niftory Hybrid Custody Frontend Showcase

## Grant category

- Developer tools / services

### Problem statement

- **Target audience**: Developers, NFT creators, and entrepreneurs aiming to build and integrate NFT platforms with the Flow blockchain, as well as end-users looking to engage with a user-friendly NFT platform.
  
- **Evidence for the need**: As the Flow blockchain evolves, new features such as Hybrid Custody present untapped opportunities for developers. Niftory has received specific requests from developers for examples integrating this technology. There's a clear demand to help developers understand and utilize these groundbreaking capabilities.

### Proposed solution

1. **User Authentication and Wallet Creation**: Implement a seamless authentication mechanism allowing users to sign in via their Google accounts, resulting in the creation of a Flow blockchain wallet.
  
2. **NFT Purchase**: While minting and listing of NFTs are done through the Niftory admin portal by the project owner, the frontend will provide the interface for NFT collectors to purchase the NFTs listed by the project owner.
  
3. **Hybrid Custody**: Showcase the integration of the newly released Hybrid Custody feature. While our example will demonstrate with the Blocto wallet, the implementation can serve as a guideline for integration with other wallets, such as NuFi and Flipper. With Hybrid Custody, collectors can manage their Niftory NFTs using their Blocto wallet as if the NFTs resided directly in their Blocto wallet.
  
4. **3rd Party Marketplace Integration**: Demonstrate the capability to list and sell NFTs on any hybrid custody compliant marketplace, providing collectors with more avenues to trade their NFTs.

### Impact

- **User Accessibility**: By integrating Google sign-in, we reduce the barriers to entry. Traditional wallet setups can be intimidating for non-enthusiasts. With Hybrid Custody, users experience the best of both worlds—simplicity in access and flexibility in management.
  
- **Ecosystem Enrichment**: By providing a practical demonstration of the Hybrid Custody feature, we empower developers and creators to leverage this cutting-edge technology in their projects, further enriching the Flow ecosystem.

- **Standardized Implementations**: Our frontend showcase serves as a best-practices guide for others looking to integrate similar functionalities, making it easier for developers to produce user-friendly applications.

## Milestones and funding

| Milestone               | Deliverables                                              | Risks                                              | USD proposal |
| ----------------------- | --------------------------------------------------------- | -------------------------------------------------- | ------------ |
| 1 - MVP                 | Initial frontend with authentication & NFT purchase       | Integration with Niftory's backend                 | 7000         |
| 2 - Hybrid Custody      | Implementing the hybrid custody mechanism                 | Handling various wallet integrations               | 6000         |
| 3 - Marketplace         | Demonstrated integration with the Flowty marketplace      | Compatibility with 3rd party APIs                  | 5000         |
| 4 - Adoption & Outreach | Drive adoption and receive feedback for future iterations | Driving adoption and gauging feedback appropriately | 2000         |

Total funding proposed: $20,000
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Kiran Pathakota | Product Manager | PM at Niftory | kiran@niftory.com |
| Mark Reese | Fullstack Engineer | Dev at Niftory | mark@niftory.com |
| Sidd Singal | Blockchain Engineer | Dev at Niftory | sidd@niftory.com |

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
