### ISSUE TITLE
Integration of DAOsign platform with Flow

### ISSUE THREAD

**Issue by TetianaRiabova** [onflow/developer-grants#225]
# DAOsign

# Grant category

- Developer tools/services

# Description

DAOsign is a smart signature and workflow automation platform, with publicly verifiable, cryptographic proofs-of-signature, designed for DAOs and WEB3 companies.

Currently, our product is on Testnet. DAOsign already allows users to store proofs of signature in the IPFS, Ethereum launch is planned in the nearest week. Also, recently, we received grants from SUI and Polkadot, so DAOsign users will be able to use SUI and Polkadot blockchains for proofs storing purposes soon as well. Also, our team is working on expanding the number of use cases.

Please, take a look at our pitch deck: https://docsend.com/view/sbexkxn5su3ahdg8

## Problem statement

Our primary audience includes Web3 organizations, DAOs, startups, and individual users within the Filecoin and broader blockchain community.

Traditional methods of signing agreements, such as paper-based systems or legacy e-signatures, are prone to fraud and lack transparency, and offer no solution for verifying the signer's identity or authority to execute the agreement. Instead, these systems rely on costly legal proceedings to enforce agreements.

## Proposed solution

Verifiable Signature is at the core of DAOsign and is based on 3 key proofs: proof-of-identify, proof-of-authority, and proof-of-agreement. Utilizing these proofs, DAOsign provides a platform to design and configure complex workflows that combine smart-contract-based automation with authorized approvals.

## Impact

We want to integrate the DAOsign tool with the Flow platform, allowing your team to sign agreements, and contracts, and manage grants directly through the Flow interface.

We think the completion of this work will bring significant value to the Flow ecosystem in several key ways:

DAOsign will streamline the process of creating and executing legal agreements and contracts within the Flow platform, which will greatly improve the overall user experience making it more user-friendly and secure.

Also, the DAOsign tool will enhance governance processes within the Flow ecosystem. Users can use it to formalize governance proposals, voting, and decision-making, improving transparency and efficiency.

The example of the use case for foundation purposes, which describes how Flow can benefit from the DAOsign tool can be found here: https://docsend.com/view/rj2eqmiet6k9k2e6

# Milestones and funding

| Milestones # | Description | Deliverable | Completion Date | Funding |
| --- | --- | --- | --- | --- |
| Milestone 1 | Flow Testnet Version | The ability to store proofs on the Flow Testnet blockchain and verify them there. The functionality includes: “Create an agreement” implementation; Assigning signers and observers; Implementation of Proof-of-Authority; Implementation of Proof-of-Signature; Implementation of Proof-of-Agreement. Early adopters program preparation | Q4 2023 | 10,000 |
| Milestone 2 | Incentivized Testnet version | Early Adopters Program launch; Online onboarding events; Feedback collecting; Roadmap adjustment | Q4 2023 | 5,000 |
| Milestone 3 | Mainnet version | Launching blockchain-stored and verified proofs version of DAOsign. Production support System resiliency; NFT-based Signer Authority Verification System | Q1 2024 | 10,000 |
| Milestone 4 | Mainnet version extended | Snapshot integration. GPT3 integration Agreement legal templates | Q1 2024 | 5,000 |

Total funding proposed: $30,000 (the final amount is negotiable, of course)
  
# Team

| Name              | Role              | Bio                                                                                                                                           | Contact                |
|-------------------|-------------------|-----------------------------------------------------------------------------------------------------------------------------------------------|------------------------|
| Eugene Fine       | CEO & Founder     | Over 20 years of building, scaling, and managing technology organizations. Recent experience includes a CTO role at Explorer Surgical Corp., which was recently acquired by GHX, and VP of Engineering at GHX. Eugene is a founder at consideritdone.tech, a Blockchain/WEB3 development studio. | eugene@daosign.org     |
| Ramil Amerzyanov   | CTO               | 15+ years building complex technical architecture and software solutions, focusing on Blockchain/WEB3 technologies over the past 7 years. Recent projects include the Fractional CTO role at Landslide Network and CTO role at consideritdone.tech.                                                      |                        |
| Misha Kushka      | Technical Lead    | 6+ years developing Blockchain/WEB3 technical architecture and software solutions. Recent projects include Lead Technical Architect roles at Akiva Capital Holdings and Avalaunch.                                                                                                                   |                        |
| Oleksandra Burmenska | Head of Partnerships | Over 10 years of experience in Business Development and Management roles in Technology organizations, focusing on Blockchain/WEB3 technologies over the past 5 years. Recent projects include contributions to NEAR, Axelar, GnosisSafe, and Avalanche ecosystems.                  | sandra@daosign.org     |

**Comment by TetianaRiabova** [comment]
Hi, @franklywatson,
I hope you are doing well. I would like to clarify the status of our application form. If you need additional details or have any questions, please let me know.

Also, I invite you to check out our Testnet here: https://testnet.daosign.org/connect

We would greatly appreciate the opportunity to schedule a brief introductory call with our Founder to showcase DAOsign's potential to enrich the Flow Ecosystem. Would you mind sharing your calendly to schedule a call?

Thanks in advance!

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
