### ISSUE TITLE
Basket Protocol 

### ISSUE THREAD

**Issue by hckrg** [onflow/developer-grants#227]
# Basket Protocol

# Grant category

- Open source maintenance
- Developer tools/services

# Description

Basket Protocol is a decentralized asset management solution built on the Flow blockchain. It empowers financial advisors, fund managers, and investors with the ability to create, manage, and invest in diversified portfolios of tokenized assets, all executed on-chain.

We proudly secured the [3rd position in the Flow Hackathon Season 2](https://devfolio.co/projects/basket-protocol-f113) in the DeFi category, a testament to our commitment to innovation and excellence in the field of decentralized finance. We strive to continue building the project on Flow chain and look forward to your support!

## Problem statement

The emergence of decentralized finance (DeFi) and the recent challenges faced by centralized investment companies underscore the pressing need for innovative, transparent, and accessible investment solutions like Basket Protocol.

1. **The Rise of DeFi and the Fall of Centralized Investment Companies:** Within the past year, we have seen the fall of some of the biggest financial institutions collapsing in both the crypto and non-crypto space. These incidents have highlighted the fragility of centralized systems, where single points of failure, lack of transparency, and susceptibility to manipulation have eroded investor trust as well as their hard-earned money.
2. **Opaqueness in Existing Solutions:** Traditional solutions used by fund managers operate in an opaque manner. Investors are confronted with complex, costly intermediaries, high fees, and limited access to diversified assets. This opaqueness in traditional asset management systems is detrimental to both fund managers and investors. It inhibits clear understanding, hinders risk assessment, and ultimately reduces the quality of investment decisions.

## Proposed solution

Basket Protocol offers a decentralised solution, enabling fund managers and advisors to create and manage ETF-like baskets of assets directly on the Flow blockchain. It democratises access to diversified assets, as users can seamlessly invest in various tokenised baskets using Flow tokens. It leverages the efficiency of smart contracts, reducing administrative costs and providing users with a transparent, cost-effective solution compared to traditional asset management. By enabling the creation and management of diversified portfolios on-chain, Basket Protocol attracts DeFi and asset management projects, further solidifying Flow's position in the blockchain landscape. 

By developing open-sourced SDKs while building this project, we will allow to projects to utilise some parts or build on top of Basket Protocol. Developers and projects within the Flow blockchain ecosystem can also benefit from Basket Protocol. It opens up new opportunities for decentralized finance (DeFi) projects and other blockchain-based applications, enhancing the overall appeal and functionality of the Flow blockchain.

## Target audience

Basket Protocol is tailored to meet the needs of a diverse range of stakeholders within the decentralized asset management landscape.

1. **Fund Managers/Advisors:** They can utilise Basket Protocol to streamline the creation and management of diversified portfolios. By leveraging on-chain smart contracts, they can design and administer tokenised baskets efficiently, reducing the complexity and costs associated with traditional asset management. This empowers fund managers to stay competitive in the rapidly evolving digital asset space.
2. **Investors (retail/institutions):** The protocol caters to investors interested in decentralized asset management. It provides secure, transparent, and cost-effective access to a variety of investment products, allowing investors to diversify their portfolios, manage risk, and access niche assets easily.

# Milestones and funding

| Milestone | Deliverables | Timeline | Risks | USD proposal |
| --- | --- | --- | --- | --- |
| 1. DEX Aggregator Library in TypeScript | A user-friendly API + ts library that allows developers to aggregate prices across multiple DEXs to ensure that the token swaps are executed at the most favourable rates in real-time. | 4 weeks | - | 3500 |
| 2. Entire Protocol Logic on-chain and Frontend | Deploy the core smart contracts for Basket Protocol on the Flow blockchain. Enhance the UI already created during the hackathon period. | 6 weeks | - | 6500 |
| 3. Security Audit, Comprehensive Documentation and Creator’s Fee Logic | A comprehensive report detailing the findings of the security audit. Expansion and refinement of the project's documentation to include best practices, FAQs, and guides for users and developers Implement a fee module, allowing creators of the Basket to have subscription-based/one-time fee options. | 6 weeks | - | 4000 |
| 4. Maintenance  | Resolves issues and bug fixes | 3 months |  | - |

Total funding proposed: 14000 USD

This is not the end goal but rather just the beginning for us. This grant will allow us to kickstart the initial development. We will continue to build and take our product to the masses.

# Team

| Name | Role | Bio | Contact |
| --- | --- | --- | --- |
| Ravinder Kumar  | Blockchain Engineer | I love learning new technologies and solving real-world problems with code. | [rkumar13100@gmail.com](mailto:rkumar13100@gmail.com) |
| Anand | Fullstack Engineer | Enthusiastic Fullstack Developer with a focus on Backend & contracts, dedicated to pioneering web3 technologies. | [anandamrit53@gmail.com](mailto:anandamrit53@gmail.com) |
| Harsha (Primary Contact) | Frontend Engineer & UI Designer | I have a strong interest in crafting effective user experiences and captivating interfaces, first with Figma then with code | [harshagogia11gmail.com](mailto:harshagogia11gmail.com) |

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
