### ISSUE TITLE
# Valocracy: A Novel Governance Protocol for Next-Gen DAOs

### ISSUE THREAD

**Issue by valocracy** [onflow/developer-grants#231]
# Valocracy: A Novel Governance Protocol for Next-Gen DAOs 
\#CommunityBuilding
\#PublicCommonGoods

# Grant category
- Developer tools / services

# Full Manifesto
https://valocracy.xyz

# Description
We are in the midst of Web2 to Web3 experimentation, even though we cannot agree on what Web3 actually means.

Some will say that it is about ownership, others will say that it is about the metaverse, and some will even argue that it is about privacy and the decentralized foundations for a crypto-anarchist future. All in all, it seems that what Web3 is really trying to encompass is an amalgam of social, economic, and political shifts in how we perceive and engage ourselves as individuals within collectives.

Not to be surprised, the creation of digital communities here is prevalent, and it seems to be at the heart of what we can observe as the “Web3 phenomenon”; in which lots of communities are attempting to thrive through the experimentation of different and recent technological building blocks, such as social platforms and blockchain.

Nonetheless, some of these communities, especially the ones that attempt to be more inclusive and democratic in the form of DAOs, are failing to escalate and to create proper incentives that actually promote true social and economic shifts in human relations.

Hence, “Valocracy”: A novel and structured social, economic, and governance protocol that attempts to leverage blockchain technology in order to create new kinds of organizations with the goal of empowering communities along with their individuals and their combined efforts.

## Problem statement
We owe much of what is now the blockchain universe thanks to the ideals and technology that originated from the High-Tech Hayekians and Cypherpunks movements, and as such, we are still embedded by several traits and thoughts cultivated by them. 

One of the most prevalent ideas seems to be that we should “pursue decentralization of power to prevent the formation of elites” as a response to “dangerous forms of control enabled by those power elites”.

If we go by the mainstream mindset of today’s Web 3, the answer to that problem is to pursue “systemic-decentralization”, or the idea that if something is decentralized, it will not be corrupted. Nevertheless, the harsh reality we are facing is that “decentralizing” for the sole sake of “decentralizing” is not an infallible formula for social, economic, and governance improvement.

Why does that happen?

Our answer is that in a DAO where we can pay to acquire a token that gives voting power, we are still reproducing a system where "MORE PURCHASING POWER" equals "MORE POLITICAL POWER", an arrangement that in the end is not so different from what we already have.

Or in a more generic fashion: if we attempt to decentralize an organization via a tokenized system that has bad economic incentives, we still end up with a bad organization that has bad economic incentives — “A decentralized and tokenized apple is still an apple”.

## Proposed solution
Born out of this realization, Valocracy is a system that aims to economically incentivize individuals to constantly generate true value for their collectives and for themselves, and in which “purchasing power” does not easily translate into “political power”.

For that, we started with the redaction of the Valocracy Manifesto, which states a set of principles upon which a valocratic collective must be built.

### 1st Principle: Human Effort is NOT Fungible
![image](https://github.com/onflow/developer-grants/assets/25505219/084eba6b-8dd3-4917-9e5b-a88eea59e574)

We are proposing that human effort is not fungible and that it should not be exchanged directly for money, but rather through an intermediate layer that “tokenizes the individual effort in the collective”. In Valocracy, those who perform an effort for the collective are granted a NFT from the collective that states and preserves the non-fungible aspects of the effort.

### 2nd Principle: Split Economic and Governance Power
![image](https://github.com/onflow/developer-grants/assets/25505219/2e0a8eff-6cec-4329-8082-4af69fcf38ed)

Every effort employed shall entitle the performer with a share of economic power and governance power within the collective. Both are independent from each other, being two separate sub-assets contained within the effort asset.

- **Tokenized Governance Power (TGP):** Gives the performer of the effort governance rights, to vote and propose on community governance.
- **Tokenized Economic Power (TEP):** Gives the performer of the effort a share of the community treasury, which may be claimed whenever the performer sees fit.

Economic Power may be sold and negotiated at the secondary market, but Governance Power cannot, and it is meant to behave as a “soul-bound token”.

### 3rd Principle: Isonomy > Equality/Equity
![image](https://github.com/onflow/developer-grants/assets/25505219/cf5a09e4-c5aa-4e7a-8912-e489fa7d6966)

![image](https://github.com/onflow/developer-grants/assets/25505219/3f08f7c6-e575-4d20-9cd9-af972b8d09c8)

Valocracy does not aim to enforce the concept of equality as the elimination of social or wealth disparities among members of a collective. Instead, Valocracy emphasizes the principle of **isonomy**: ensuring that the same set of rules is applied consistently to all members of a collective, regardless of their economic status or governance influence.

As such, individuals who contribute with more effort shall be rewarded with more governance and economic power within the collective, but all contributors shall agree to adhere to the same rewarding and contributing mechanisms.

### 4th Principle: Farewell “Shareholder”… long live “Valueholder”
![image](https://github.com/onflow/developer-grants/assets/25505219/8d2f1488-793a-429b-913d-c6cf43b5dc55)

Valocracy aims to blur the distinction between shareholders and laborers (or stocks vs salaries) by introducing the concept of “Valueholder”. A Valueholder of a collective is anyone who possesses a share of “Tokenized Economic Power” within that collective.

It is important to understand that “Tokenized Economic Power” represents a claimable share in a collective treasury. A Valueholder can, at any time, burn their “Tokenized Economic Power” to claim their fiduciary/fungible share of the treasury. 

So, while a “Tokenized Economic Power” behaves as a “stock” in the sense that it denotes a share of collective profits, it can also serve as a “salary” if the original contributor decides to regularly claim their earned shares via the burning of the “Tokenized Economy Power” instead of selling or holding it. 

It also allows foreign individuals to take a stake in the treasury by acquiring “Tokenized Economic Power” in the secondary market if they believe their bought shares are to be worth more in the future, like an “advance against receivables” to the benefit of the originally employed effort.

Thus, the “Valueholder” concept blurs the distinction between shareholders and laborers, offering individual freedom to decide when to act as a paid laborer and when to act as a shareholder, or even to do both at the same time with different parcels of their earned “Tokenized Economic Power”.

### 5th Principle: Incentivize Efficienty
![image](https://github.com/onflow/developer-grants/assets/25505219/75455b90-881d-458d-ab4a-939ce0934a94)

In Valocracy, if we take the fluctuation of Treasury over the Collective Effort put together by individuals over time, we can derive “Collective Efficiency” as a metric.

$$
CollectiveEfficiency = \frac{Treasury}{CollectiveEffort}
$$

As both Treasury and Collective Effort are subject to changes over time, so is the derived Efficiency.

If a collective treasury grows at a higher rate than the collective effort, it means that individual effort is being put to good use, it is efficient. And, as such, individuals are further incentivized not only to hold their treasury shares but also to further collaborate and increase their stake in the collective.

This “holding” mentality is not meant to reflect the goal of flipping assets that have no tangible value by themselves (i.e. true floor price) but to reflect that individuals may prefer to be “shareholders” than “employees” if they are engaging in prosperous collectives.

In this sense, Valocratic collectives are subjected to efficiency... They need to be efficient, or else individuals will be incentivized to not only sell their shares but to also stop putting effort into the collective altogether.

### 6th Principle: Time in the Collective > Timing the Collective
![image](https://github.com/onflow/developer-grants/assets/25505219/2d827865-c0fb-407a-b347-7528061dd1f1)

As collectives get bigger and (ideally) wealthier, Governance becomes of more importance. 

The separation of economic power and governance power aims to mitigate governance attacks, as governance power is soul-bound. It cannot be bought at market and must be earned from collaborative effort.

However, Valocracy aims to go even further and implement a governance efficacy curve over Tokenized Governance Power, where efficacy is null at birth, grows over time, and then decreases until it becomes null again.

Such measure aims to reinforce the governance power of individuals who consistently contribute effort, to the detriment of those who may have been great contributors of the past, but who have abandoned the collective, or even those who are newcomers and are still beginning to understand the collective, and as such have not enough experience to contribute in governance. 

## Impact
We intend Valocracy to be a multi-chain solution, in which new collectives can choose between one or more possible settlement blockchains. In this proposal, we want to fund the development of the first Valocracy implementation and offer Flow blockchain as one of the first available options for building a Valocracy.

As such, new projects within the Flow ecosystem can experiment with new economic incentives for decentralized cooperation. 

We also envision cooperation between existing projects and a default Valocracy implementation. For instance, leveraging a Valocratic layer over Toucans, in order to provide more sophisticated socio-economic tools for their DAOs, or even building Valocracies using identities minted on Flovatar.

Valocracy should not be viewed as a closed system on itself, but rather as socio-economic building blocks for leveraging human coordination on decentralized collectives.

# Implementation & Architecture
![image](https://github.com/onflow/developer-grants/assets/25505219/a521e893-586f-4f89-b041-42f76acbcb7c)

We aim to build a modular multi-chain architecture that allows Valocracies to be built in different chains.

- **VALOCRACY PORTAL:** The Valocracy Portal aims to facilitate the instatiation and management of new valocratic collectives, in which the founders can choose their preferred chain. The Portal is not an exclusive means to create new valocracies but will also function as both a reference implementation and a VaaS (Valocracy-as-a-Service) system that can generate further revenue for the Valocracy development. The Portal will be first developed on Web 2 infrastructure, with plans to migrate the whole application to Web 3 in the future. Those who do not wish to build Valocracies using the Portal will be able to copy the API and any smart contracts, as these are going to be released in open-source.

- **VALOCRACY API:** A generic API with all the required functions for a valocracy to work is being developed in Node.JS. Any number of implementations can be derived for specific chains that want to support Valocracy. This does not mean (yet) cross-chain or interoperability support, but only the option to settle new valocracies on different blockchains.

# Milestones and Funding
We are arraging our roadmap for the first iteration of Valocracy in three phases.

![image](https://github.com/onflow/developer-grants/assets/25505219/86ab5c52-bb59-4092-800c-c8286ce64729)

- **PHASE 1 (GREEN):** Fundraising for the development of the first implementations of Valocracy, based on the evolution and migration of the already-functioning [[Casta Guilda](https://www.notion.so/CastaGuilda-3ce1090875f5441cb8b6bb36e481a07d?pvs=21)](https://www.notion.so/CastaGuilda-3ce1090875f5441cb8b6bb36e481a07d?pvs=21) community, with the expected onboarding of 500+ members, on a yet to be defined implementation.

- **PHASE 2 (YELLOW):** Promotion of the Valocracy experiment and onboarding of a selected number of whitelisted collectives to Valocracy. Also, during this phase, feedback will be collected from all the migration processes and from the first experiences with Valocracy.

- **PHASE 3 (BLUE):** Start the specification and fundraising for the development of Valocracy 0.2 with regards to the collected feedback and experimentation from v0.1.

In this proposal we are pledging a grant of 12500 USD counting from 1st December, to achieve the following milestones:

Milestone/Deliverables | Timeline | Risks | USD Proposal
-- | -- | -- | --
1 - Architectural/API Project and Development Kickstart | 1 month from 1st Dec | Low risk as we already have a clear idea | 2850
2 - Portal Development | 4 months from 1st Dec | Low risk as we already have a Web2 team | 1500
3 - API Development | 4 months from 1st Dec | Higher risk as integration can be tricky and we aim to hide multi-chain complexity inside the API | 2900
4 - FLOW Development | 6 months from 1st Dec | Mid risk as this is the specific Cadence implementation module, and we are counting on a experiencied developer | 2400
5 - Valocracy Treasury | 6 months from 1st Dec | Zero risk - Funds to feed the treasury of the first working Valocracy, to experiment with new incentives in it, and also to reatroactively reward indirect collaborators that cannot be featured on this grant, via valocratic means | 1350
6 - Ecosystem Incentives | 8 months from 1st Dec | Zero risk - Funds to promote a hackaton in which Flow projects can attempt to develop new governance mechanisms over the Valocracy implementation | 1500

Total funding proposed: 12500 USD
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Rafael Castaneda | Founder, Tech-Lead and Architect | MSc in Computer Science with 20+ years as tech-lead and professor in computer science, Rafael now is a content producer, web 3 builder and community manager in Brazil. Talks about crypto and web3 not from an investiment perspective, but rather on the economic and social impacts of blockchain technology. As of today the main area of research for Castaneda are novel systems for social coordination and alternatives to current DAO systems. | rafaelcastaneda@gmail.com |
| Diego Fornalha | Supporter | Diego is the Flow Ambassador for Brazil with experience on projects within the ecosystem. | diegofornalha@gmail.com |
| Guilherme Neves | Advisor | Co-founder and Head of Blockchain at Blockful.io. Guilheme is experienced in DeFi, DAOs, NFTs & RWA. As a builder and full-stack developer has over 20 projects delivered and is specialized in solidity smart contracts with extent knowledge of Rust and zk-proofs. | guilherme@blockful.io |
| João Kamradt | Advisor | Partner and head of investments and research at Viden Ventures. Has deep knowledge in Web3, cryptoassets, DeFi, GameFi, metaverse, NFTs and DAOs. Holds a PhD in Political Science and a Master’s degree in Sociology, both from UFSC. Also has a degree in Journalism and acts as a University professor. Author of the book “O primeiro mergulho no mundo da Web3: como as criptomoedas, o metaverso e os NFTs”, as well as two other books and more than 15 scientific articles in national and international journals". |  joao.kamradt@viden.vc |
| Monkey Branch | Portal Development | Monkey Branch is a software development house in Brazil with expertise on web development, back-end integration and A.I. technology.  Currently, Monkey Branch is actively contributing to Web3 projects such as Valocracy | https://monkeybranch.dev/ |
| Cursed Stone | API Development | Cursed Stone team works on a GameFi project with expertise on Web2/Web3 integration, they also assemble and mantain blockchain schools in Brazil for poor communities in favelas | https://twitter.com/cursedstonegame |
| Glaicon Peixer | Cadence Development | Peixer is an experienced Flow blockchain developer at AE Studio, responsible for Artifact SCMP collections and Melanie's Marketplace. | gjpeixer@gmail.com |

**Comment by valocracy** [comment]
** ERRATUM **

We copy and pasted a budget that was simulated in FLOW valued at $3 considering the market may be recovering, but we forgot to put the final version converted to USD. Please consider the version below:

In this proposal we are pledging a grant of 12500 USD counting from 1st December, to achieve the following milestones:

Milestone/Deliverables | Timeline | Risks | USD Proposal
-- | -- | -- | --
1 - Architectural/API Project and Development Kickstart | 1 month from 1st Dec | Low risk as we already have a clear idea | 2850
2 - Portal Development | 4 months from 1st Dec | Low risk as we already have a Web2 team | 1500
3 - API Development | 4 months from 1st Dec | Higher risk as integration can be tricky and we aim to hide multi-chain complexity inside the API | 2900
4 - FLOW Development | 6 months from 1st Dec | Mid risk as this is the specific Cadence implementation module, and we are counting on a experiencied developer | 2400
5 - Valocracy Treasury | 6 months from 1st Dec | Zero risk - Funds to feed the treasury of the first working Valocracy, to experiment with new incentives in it, and also to reatroactively reward indirect collaborators that cannot be featured on this grant, via valocratic means | 1350
6 - Ecosystem Incentives | 8 months from 1st Dec | Zero risk - Funds to promote a hackaton in which Flow projects can attempt to develop new governance mechanisms over the Valocracy implementation | 1500

Total funding proposed: 12500 USD

**Comment by diegofornalha** [comment]
Regarding the issue of 'time in the collective > timing the collective', I understand that the intention is to value the dedication and long-term commitment of the members, which is fundamental. However, this can inadvertently devalue significant contributions from new members, who can bring fresh perspectives and essential innovative ideas for evolution.

A mechanism that balances experience and loyalty with innovation and merit. Perhaps a governance system that allows new ideas to be recognized, and gain traction based on their intrinsic value, regardless of the member's seniority. This would encourage all members, regardless of how long they have been in the collective, to actively contribute and have the possibility of positively influencing the community's direction.

Encouraging an environment where the merit of ideas prevails, perhaps through an open voting process or peer review, could not only improve the dynamism of the Valocracy project. It could also serve as an inspiring example of inclusion and meritocracy for other initiatives.

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
