### ISSUE TITLE
Onramp and Crypto Card plugin for wallets on FLOW Blockchain

### ISSUE THREAD

**Issue by Ricchnear** [onflow/developer-grants#232]
# <Swyype Pay>

# Grant category

Please select one:

- Developer tools / services

# Description
Swyype Pay is a wallet onramp infrastructure that allows businesses and developers to offer and sell crypto to their users easily and affordably at no cost to their businesses or products.

## Problem statement
The need for Nigerian developers and business owners to offer instant sale of crypto assets to their users without peer-to-peer intervention

- Target audience: Businesses and Developers
- Evidence for the need: We have been building Swyype Pay and currently strive with a team of 10, plus the need to build the new product would require Swyype Pay purchasing and holding all crypto assets we would want to make available to these different businesses.

## Proposed solution
An onramp API package that would be easily integrated into both mobile apps and web apps. Giving developers with different products access to make instant onramps of flow tokens available to their Nigerian market.

## Impact

- In what ways does this benefit the broader Flow developer ecosystem?
Fiat onramp payment solution that plugs into any wallet on FLOW allowing more users to access any token on FLOW Blockchain faster and more affordable in the Nigerian market through direct bank transfer, payID, debit card payment, and more. Developers would be able to integrate this into their wallets with a single line of code and at no extra cost, creating a seamless mode of purchase for users and a seamless integration interface for developers and business owners.
**This Impact would be replicated in more African countries as we scale.**

# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - MVP   | Building our onramp infrastructure for FLOW token alone| 4 weeks  | - | 5,000          |
| 2 - Beta launch  | Launching our onramp across 4 wallet on FLOW Bockchain | 4 weeks  | - | 5,000          |
| 3 - Full Launch  | Adding Onramp of all Stable coins on FLOW blockchain | 4 weeks | - | 5,000           |
| 4 - Growth | Scaling towards adoption with all wallet on FLOW adopting Swyype pay to provide onramping to their Nigeria user base | 8 weeks | - | 10,000           |
| 5 - Marketing| Launch of Swyype pay marketing campaign, including developers advocate program, developers community launch, web3 event gathering promoting Swyype Pay and FLOW blockchain | 6 weeks | - | 5,000           |
| 6 - Expansion| Expanding our product scope by including cryptocard service to allow more wallet to offer more cryptocards to their users on FLOW Blockchain | 6 weeks | - | 10,000           |

Total funding proposed: <USD 40,000>
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Divinegift Soetan| Founder and CEO | Blockchain business developer | [linkedin](https://www.linkedin.com/in/divinegift-afolabi-04497118a/) |
| Elijah Chinedu | Product manager | Innovative product manager | [Linkedin](https://www.linkedin.com/in/elijah-chinedu-a8b6811aa/) |
| Kolawole Elijah | CTO | Full stack and blockchain developer |[Linkedin]( https://www.linkedin.com/in/elijah-kolawole/) |

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
