### ISSUE TITLE
Grant Proposal: Flow Audio-series

### ISSUE THREAD

**Issue by gabrielrondon** [onflow/developer-grants#233]
# Unveiling Flow (audio-series) studios.tuturama.com/flow

# Grant category
- Educational material

# Description
Demo (studios.tuturama.com/flow) - We propose "Unveiling Flow" a 10-episode audio series aiming to elucidate the complexities of Flow's blockchain technology. This educational initiative targets developers, new users, and enthusiasts, offering them a clear and engaging medium to grasp advanced concepts. The series plans to break down intricate topics into digestible episodes, fostering a well-informed community within the Flow ecosystem. With a funding request of $14500, the project outlines a structured timeline for scriptwriting, production, and distribution, led by Tuturama OÜ, to deliver a high-quality educational resource on Spotify.

## Problem statement
- Target audience: Developers, new users, and enthusiasts looking to understand Flow's technology
- Evidence for the need: Complexity of blockchain concepts requires clear and engaging educational material

## Proposed solution
A 10-episode audio series breaking down Flow's core concepts, released on Spotify to educate and engage a broader audience.
Demo: studios.tuturama.com/flow

## Impact
Benefits the broader Flow developer ecosystem by making technical concepts accessible and fostering a more informed community.

# Milestones and funding
Milestone | Deliverables | Timeline | Risks | USD proposal
-- | -- | -- | -- | --
1 - Scriptwriting for Episodes | 10 Episode Scripts | 4 weeks | Delays in scripting | 3500
2 - Audio Production | 10 Episodes Recorded | 6 weeks | Production delays | 7500
3 - Editing and Finalizing | 10 Episodes Edited | 2 weeks | Editing setbacks | 1500
4 - Distribution | Episodes Released on Spotify (at least 10,000 impressions) | 2 weeks | Distribution hiccups | 2000

Total funding proposed: $14500
  
# Team

Name | Role | Bio | Contact
-- | -- | -- | --
Gabriel R | Executive Producer | Founder of Tuturama, experienced in educational products | mailto:contact@tuturama.com
Denise | Audio | editing, voice-over, visuals (landing page) | mailto:contact@tuturama.com

**Comment by gabrielrondon** [comment]
Hey @franklywatson ! I'm thrilled to share an exciting update with you! We've successfully secured a partnership that enables us to produce content in one additional language. The great news is that our budget remains unchanged, and we've already arranged for the necessary voice-over work. (we're chasing another er partnership now).

We really believe we can reach new audiences by promoting flow in different channels with this approach (audioseries with quizzes and mini e-books). I'll be glad to have a call and demonstrate in detail. thank you!

**Comment by diegofornalha** [comment]
If the goal is to reach developers, new users, and enthusiasts, is the podcast format ideal? Often, technical blockchain concepts are better absorbed with visual material that a podcast does not offer.

**Comment by gabrielrondon** [comment]
Hey Diego, I completely agree with you. These are not podcasts the way we know (long), but rather educational mini-episodes that will be followed by quizzes and challenges on our website. We didn't request any funds for the website or the development of quizzes/challenges since we've already secured that on our own. However, we believe that creating audio content to explain difficult concepts would be a crucial part of this educational initiative, as it can help us reach new people who are not yet familiar with our work through other means such as Youtube videos and gitbooks. We don't want to miss out on this opportunity.

**Comment by gabrielrondon** [comment]
Hey Diego, thanks for your insight! I agree that visual aids are crucial for explaining technical concepts. However, at Tuturama OÜ, we're leveraging a mix of audio-driven mini-episodes and interactive quizzes on our website to cater to various learning styles. This approach is not only about auditory vs. visual learning; it's about inclusivity. Audio content is especially accessible for individuals with visual impairments, making blockchain and web3 topics more approachable to a diverse audience. Some people learn better from audios. By embracing multiple educational formats, we aim to bridge the knowledge gap in these complex technologies and create an inclusive learning environment for everyone, regardless of their learning preferences or abilities.

**Comment by diegofornalha** [comment]
Just launching on Spotify and waiting for 10,000 impressions seems like a
very vague distribution plan. How will you ensure that this number is
reached?

**Comment by gabrielrondon** [comment]
Diego, you raise an important issue about distribution. Our strategy extends far beyond simply waiting for the impressions. We're part of a few web2/web3 groups. We aim to tap into various of these channels (work on that), notably a group connected with WebSummit, comprising startup founders and aspiring web3 enthusiasts. This group is a key target as its members are keen on entering or transitioning to the web3 space but haven't fully delved in yet (and we believe knowing Flow is a good way to make them consider their path choices in the web3). Leveraging such networks will enhance visibility and foster engagement.

Furthermore, while Spotify is our initial platform, we're open to distributing our content on other platforms and always welcome suggestions. It's crucial to note that all our content is open-source, with no intellectual property restrictions. This approach allows the community to freely reuse and repurpose our educational material (for instance, to bring this to other formats, or even other languages!), fostering a collaborative learning environment and ensuring our content reaches and benefits as many people as possible in the web3 community.

**Comment by gabrielrondon** [comment]
Before moving to production, we will take two important iterations to validate everything. This will help us to better validate the episodes and final scripts before they are produced. This process will ensure that everything is validated and in line with community expectations.
<img width="2144" alt="ee0ae627279b62096dec0eca669672eddd6636ba" src="https://github.com/onflow/developer-grants/assets/8773083/542ef540-902b-43c8-b93f-3a34eb5c32d6">

**Comment by diegofornalha** [comment]
During the Web Summit **Rio**, we were the only representatives of the international blockchain market. This exclusivity allowed us to capture all the attention of the event, which proved to be extremely positive.

I strongly recommend a conversation with @jacob-tucker. He can offer an excellent opportunity for integration with the @emerald-dao on the Open Source Academy platform, accessible at academy.ecdao.org.

**Comment by gabrielrondon** [comment]
Definitely! Thank you for bringing this up.

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
