### ISSUE TITLE
Flowverse Account Linking

### ISSUE THREAD

**Issue by flowjames** [onflow/developer-grants#234]
# <Project name>

# Grant category

- Developer tools / services

# Description

## Problem statement

- Account Linking represents a pivotal advancement in blockchain user interface, offering seamless onboarding while maintaining the core principles of composability, ownership, and decentralization. This technology marks a significant leap forward in blockchain UI/UX, but its widespread adoption requires support from key infrastructure projects within the Flow ecosystem including top-tier marketplaces like Flowverse NFT.
- The utility of Account Linking can be improved by its integration into popular platforms. Users, having linked their accounts, require applications like Flowverse NFT where they can fully leverage the benefits of this feature. More importantly, platforms such as Flowverse provide a compelling incentive for users to engage in account linking in the first place – for example, enabling them to trade their NFTs in a secondary market.
- Furthermore, the broader adoption of Account Linking by new and existing projects is likely to accelerate if there are clear benefits for end-users, such as seamless secondary trading experiences that also uphold creator royalties. This not only enhances their user engagement but also offers a revenue-generating avenue for the projects themselves.
- **Target audience:** Users of the Flowverse NFT marketplace (NFT collectors, traders), users of account linking, projects / entrepreneurs

## Proposed solution

- We will integrate account linking functionality into Flowverse NFT. 
- This will involve numerous UI changes, transaction and script modifications to work with hybrid custody and child accounts. It will enable users to view/sell/list NFTs from connected child accounts, receive payments from sales to parent accounts and display and filter NFTs for child accounts.

## Impact

- **Enhanced User Experience and Expanded Utility:** This integration into Flowverse NFT will enhance the overall user experience. It offers users a compelling new reason for users to account link so they can trade their assets on a decentralized marketplace.
- **Promoting Adoption:** Flowverse NFT, being a prominent player in the Flow NFT ecosystem, has the capacity to influence industry standards with the adoption of account linking. The integration of account linking in Flowverse NFT can set a precedent and encourage other applications and NFT projects to adopt this feature. 
- **Boosting Ecosystem Interoperability:** The implementation of account linking in Flowverse NFT fosters greater interoperability within the Flow ecosystem. At the moment many custodial applications prevent trading NFTs outside of their website, the introduction of account linking and implementation on Flowverse NFT encourages a more decentralized and user-centric ecosystem.

# Milestones and funding

| Milestone                                          | Deliverables                                                                                                                                                          | Timeline  | Risks                                         | USD Proposal |
|----------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------|-----------------------------------------------|--------------|
| 1 - Transactions and scripts                       | Modifying Flowverse NFT transactions and scripts to work with account linking and child accounts.                                                                     | 2 weeks | -                                             | 2000        |
| 2 - Implementing on Flowverse NFT (UI/ UX changes) | Displaying all NFTs for child and the parent account. Ensuring that account linking functions elegantly on Flowverse NFT so users can take full advantage of the feature. Phase includes QA testing (testnet + mainnet) and ends with account linking launch. | 2-3 weeks | Unforeseen implications on Flowverse backend<br>QA testing delays/ bugs | 2000        |
| 3 - Marketing & Adoption (optional)                | Launching account linking functionality prominently through all Flowverse channels (twitter, newsletter, discord).                                                      | 1 week | -                                             | 2000        |
| 4 - Maintenance                                    | Ongoing support and maintenance for the implemented features.                                                                                                          | Ongoing for at least 3 months  | -                                             | 2000        |

Total funding proposed: USD 6000-8000
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| James Petchey | Founder, Product & QA | Founder at Flowverse | james@flowverse.co |
| Nishanta Dharmaseri | Founder, Marketing, Data & QA | Founder at Flowverse | nish@flowverse.co |
| Brian Min | Lead Developer | Dev at Flowverse | brian@flowverse.co |

**Comment by Aliserag** [comment]
Incorporated in another grant.
