### ISSUE TITLE
Grant Application: Granite Wallet

### ISSUE THREAD

**Issue by jobyid** [onflow/developer-grants#235]
# Granite Wallet

# Grant category

- Developer tools / services

# Description
Granite Wallet was developed to address the growing need for a unified and secure platform in the digital economy, where the convergence of various online services and transactions has become increasingly complex and security-sensitive. In a landscape where users frequently engage with multiple websites and applications, each requiring separate login credentials, payment methods, and compliance with various regulatory standards, there was a clear demand for a more streamlined and secure way to manage these digital interactions.

At the core of Granite Wallet's development was the recognition of the challenges faced by both users and developers in navigating the digital world. For users, the hassle of remembering multiple passwords, concerns about the security of their financial and personal information, and the complexity of interacting with emerging technologies like blockchain were significant pain points. For developers, the burdens of implementing robust security measures, ensuring compliance with regulatory standards like KYC and AML, and integrating blockchain functionalities posed substantial barriers. Granite Wallet was envisioned as a solution to these problems, offering a single platform that simplifies user authentication, financial transactions, identity verification, and blockchain interactions. By consolidating these services, Granite Wallet aims to enhance the user experience, streamline development processes, and ensure a high level of security and compliance, catering to the evolving needs of the digital age.

## Problem statement

- Target audience
The primary target audience includes tech-savvy consumers, e-commerce businesses, fintech companies, blockchain and cryptocurrency platforms, startups, SMEs, SaaS providers, gaming and online betting platforms, regulated industries, and developers in tech companies.

- Evidence for the need
The digital economy is increasingly complex, with users managing multiple online identities and financial transactions across various platforms. Developers face challenges in integrating secure and compliant user authentication, payment processing, and blockchain functionalities. There is a growing demand for a unified solution that simplifies these aspects while ensuring security and regulatory compliance.

## Proposed solution
Granite Wallet offers a comprehensive digital wallet solution that encompasses user authentication (Sign in With Granite), blockchain transaction facilitation (Wallet Actions), regulatory compliance and identity verification (Verify), and secure payment processing (Pay with Granite). This unified platform addresses the key challenges faced by both users and developers in the digital economy, streamlining online interactions and transactions.

- Sign in With Granite allows users to maintain a single set of login credentials across multiple platforms, offering developers an easy-to-integrate sign-in solution equipped with a powerful API and instant access to an expansive user network.

- Wallet Actions alleviates the intricacies of blockchain interactions, enabling straightforward dealings with smart contracts through a user's wallet that's built into their account. This chain-agnostic system supports all major blockchains, making transactions invisible to users and effortlessly handled by secure server-side processes.

- Verify is seamlessly woven into the fabric of Granite Wallet, removing the complexities of identity verification. It ensures compliance with AML and KYC standards while verifying user statuses, like sophisticated investor qualifications, through a one-time process with benefits extending to every subsequent transaction.

- Pay with Granite streamlines the payment process within the Granite Wallet app. Users input their payment information once, and developers can initiate secure transactions via an API, ensuring payment capture and transfer while eliminating the risks associated with handling sensitive data.

## Impact
Granite Wallet significantly benefits the broader Flow developer ecosystem by providing a robust, easy-to-integrate platform that simplifies user authentication, financial transactions, identity verification, and blockchain interactions. It reduces development time and costs, enhances user experience, and ensures high security and compliance standards.
Granite Wallet also opens up the prospect of cross chain interactions, interoperability and multi chain apps. By positioning the wallet in the centre developers can, see, handle and interact with the users assets regardless of the chain they are on. Allowing for a seamless multi-chain world.   

<h1 style="caret-color: rgb(0, 0, 0); color: var(--text-primary); font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: pre-wrap; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; border: 0px solid rgb(217, 217, 227); box-sizing: border-box; font-size: 2.25em; font-weight: 600; margin: 0px 0px 0.888889em; line-height: 1.111111; font-family: Söhne, ui-sans-serif, system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, Ubuntu, Cantarell, &quot;Noto Sans&quot;, sans-serif, &quot;Helvetica Neue&quot;, Arial, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;">Milestones and funding</h1>

Milestone | Deliverables | Timeline | Risks | USD Proposal
-- | -- | -- | -- | --
1 - Sign in With Granite MVP | Development and integration of Sign in With Granite service | 6 weeks | Integration complexity, user data security | 12,000 USD
2 - Onboarding for Sign in With Granite | Onboarding of 10 businesses for Sign in With Granite | 4 weeks | Adoption rate, market competition | 5,000 USD
3 - Wallet Actions MVP | Development and integration of Wallet Actions service | 8 weeks | Blockchain integration complexities | 15,000 USD
4 - Onboarding for Wallet Actions | Onboarding of 10 businesses for Wallet Actions | 4 weeks | Blockchain market volatility, user adoption | 7,000 USD
5 - Verify MVP | Development and integration of Verify service | 6 weeks | Compliance with regulatory standards | 12,000 USD
6 - Onboarding for Verify | Onboarding of 10 businesses for Verify | 4 weeks | Regulatory landscape changes, privacy concerns | 6,000 USD
7 - Pay with Granite MVP | Development and integration of Pay with Granite service | 10 weeks | Payment gateway partnerships, security | 20,000 USD
8 - Onboarding for Pay with Granite | Onboarding of 10 businesses for Pay with Granite | 4 weeks | Financial market fluctuations, security concerns | 8,000 USD
9 - Maintenance | Continuous support, updates, and bug fixes for all services | Ongoing | Technological advancements, security risks | 15,000 USD

<p style="caret-color: rgb(0, 0, 0); color: var(--text-primary); font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: pre-wrap; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; border: 0px solid rgb(217, 217, 227); box-sizing: border-box; margin: 1.25em 0px; font-family: Söhne, ui-sans-serif, system-ui, -apple-system, &quot;Segoe UI&quot;, Roboto, Ubuntu, Cantarell, &quot;Noto Sans&quot;, sans-serif, &quot;Helvetica Neue&quot;, Arial, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;;">Total funding proposed: 100,000 USD</p><br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;"><br class="Apple-interchange-newline">
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Joby | Founder & Full-Stack Engineer | Joby is a software engineer and Entrepreneur, he started his professional life a cyclist racing all over the world, before moving to a career in finance and then into business building and tech. He has founded companies in media, retail, sport and tech. After going down the crypto rabbit hole, he's now passionate about bringing this revolutionary technology to the masses.  | granite@granitewallet.com |

**Comment by jobyid** [comment]
Hi @SeanRobb just wondering if you need anything else on this.

**Comment by jobyid** [comment]
@JeffreyDoyle Just touching base to see if there is an update on this?

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
