### ISSUE TITLE
vNFTy - Futuristic NFT Platform

### ISSUE THREAD

**Issue by Vara25** [onflow/developer-grants#238]
# Project Name: **vNFTy**

# Grant category

Please select one:

- Developer tools / services

# Description
In the ever-evolving world of blockchain technology and digital assets, our platform introduces a groundbreaking concept that transforms the way we perceive NFTs. We're thrilled to present a pioneering feature: Token-Embedded NFTs.

At the core, this innovation combines the unparalleled uniqueness of NFTs with the real-world utility of cryptocurrencies. With Token-Embedded NFTs, each digital collectible seamlessly encapsulates a basket of underlying tokens. It's not just about owning a piece of digital art, a rare virtual item, or an exclusive moment in the metaverse. It's about enhancing these treasures with tangible, quantifiable value.

Imagine owning an NFT that isn't just a piece of art but also contains tokens that can be traded, spent, or staked within the same digital wallet. Our platform brings practicality and versatility to the world of NFTs, allowing users to experience their digital assets like never before.

## Problem statement
NFTs are digital assets and are prone to value degradation over time or when market downtrends. NFTs price is coming out of the blue or by the look only. First to a certain level users will see profits but, the last wave of users always will end up investing large sums of crypto and eventually losses. Additionally, there’s no real world usage and attached digital screens or wallets only.

- Target audience: Each and every crypto user who is interested in NFTs and the Web3 ecosystem.
- Evidence for the need: The recent NFT market has seen a downtrend and users are facing massive losses.

## Proposed solution
To sustain the value of the NFTs even after the last wave or downtrend, the value must remain the same or at least should cover the value of the initial price. By adding or locking some of the crypto tokens into the NFT, the value prevails. Even though the value of the artwork goes down, when the user extracts the tokens, it might not feel the loss and decrease the value of the loss.

## Impact
At the core, this innovation combines the unparalleled uniqueness of NFTs with the real-world utility of cryptocurrencies. With Token-Embedded NFTs, each digital collectible seamlessly encapsulates a basket of underlying tokens. It's not just about owning a piece of digital art, a rare virtual item, or an exclusive moment in the metaverse. It's about enhancing these treasures with tangible, quantifiable value.

Imagine owning an NFT that isn't just a piece of art but also contains tokens that can be traded, spent, or staked within the same digital wallet. Our platform brings practicality and versatility to the world of NFTs, allowing users to experience their digital assets like never before.

- In what ways does this benefit the broader Flow developer ecosystem?
The ecosystem always thrives with new improvements and developments. The idea resembles the current NFT market solution. This can benefit any ecosystem that has a hunger for the new.

# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - MVP   | Smart Contracts | 3 weeks  | - | 7500           |
| 2 - Frontend | UI for the Platform with Basic Features | 3-5 weeks  | - | 5000           |
| 3 - Deploy | Cloud Infrastructure | 1-2 weeks  | - | 2500           |
| 4 - Maintenance | Bug Fixes and Agile Testing | 2-3 weeks | - | 2500 |

Total funding proposed: 17,500 USD
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Vara Prasad Satti | CEO/Founder | ... | info@vnfty.com |

Website: [https://www.vnfty.com](https://www.vnfty.com)

**Comment by franklywatson** [comment]
"Imagine owning an NFT that isn't just a piece of art but also contains tokens that can be traded, spent, or staked within the same digital wallet"

Sorry @Vara25 but it perhaps you haven't taken the time to learn about Flow and Cadence, our smart contract language? We are not EVM or Solidity based and in Cadence Resources are dedicated types that are used for tokens which can be nested and composed in one another. Therefore it means your proposal is not adding to our ecosystem since the language native features we have already provide the described functionality

https://cadence-lang.org/docs/language/resources#nested-resources
