### ISSUE TITLE
Ludo Developer Grant submission

### ISSUE THREAD

**Issue by AdrianStratulat** [onflow/developer-grants#243]
# <Project name>
Ludo
# Grant category
- Developer tools / services

# Description
Ludo - The Search Engine of the Web3 space
Ludo provides discoverability to web3 with AI-driven curation tools fueled by the algorithm called Ludo Rank - a technology tested on 200M+ NFTs indexed across 17+ most popular chains and 20+ marketplaces.
With Ludo, web3 users can easily find opportunities behind all NFT’s and brands get access to new user acquisition and engagement strategies.
## Problem statement

Web 3 discoverability is severely hampered by its sheer scale and lack of effective multi-chain discoverability tools. With over 24 ecosystems and 500 million Non-Fungible Assets, it's challenging to sift through the noise and find true value, leading to widespread scams and brand impersonations. This issue is compounded by the global nature of Web 3, which blurs jurisdictional lines and complicates IP rights enforcement. Counterfeits, representing 3.3% of world trade and causing significant economic and brand damage, exacerbate the problem. In the U.S., 52% of consumers lose trust in brands due to counterfeits, while in Europe, counterfeit products account for 5.8% of all imports. Additionally, major NFT marketplaces like OpenSea, lacking robust monitoring, become breeding grounds for IP infringements, highlighting the urgent need for more effective legal frameworks and enforcement mechanisms in the Web 3 environment.

## Proposed solution

Ludo provides discoverability to web3 with AI-driven curation tools fueled by the algorithm called Ludo Rank - a technology tested on 200M+ NFTs indexed across 17+ most popular chains and 20+ marketplaces.
With Ludo, web3 users can easily find opportunities behind all NFT’s and brands get access to new user acquisition and engagement strategies.
Through our Ludo Rank system (similar to Google Page Rank algorithm), we can reduce low quality assets, fraud and spam by curating assets and assigning a trusted score. This will allow us to monitor your brand assets, rank them properly and differentiate them from spam and IP infringement. The tool is already available as API and as Chrome Extension, which you can install and test [here](https://chromewebstore.google.com/detail/ludo-rank/fgcmebogmgdheonhhefnblfodobpmfip). Ludo Rank is currently deployed for Ethereum and MultiverseX.

We have successfully integrated Flow into our systems and are currently developing more features that allow us to oversee the status of NFTs within the infrastructure.

## Impact

Some explicit advantages that our solution provides for Flow developers and the broader ecosystem are the following:

- Ludo Rank, our innovative ranking algorithm, will be accessible at no cost through our API, enabling Flow developers to seamlessly integrate it into their decentralized applications (dApps)
- Ludo Rank is available via the [Ludo Chrome Extension](https://chromewebstore.google.com/detail/ludo-rank/fgcmebogmgdheonhhefnblfodobpmfip), an essential tool for any Flow NFT collector. This extension aids collectors in understanding the trust score of an asset, empowering them to make well-informed decisions.
- NFT project creators can leverage Ludo Rank to display their project's authority level, enhancing their appeal to potential users.
- Ludo Rank also adds value for users, who can showcase their Reputation Level—based on the Ludo Rank of the assets they own—to attract more incentives from projects seeking users with high reputations.

# Milestones and funding

Our plan is to allocate additional resources towards indexing every NFT on Flow and implementing the Ludo Rank algorithm for a comprehensive ranking of all assets. This approach will enable us to provide a trust score for each new NFT minted on Flow within minutes of its creation. This rapid assessment aims to significantly reduce the risk of scams for Flow users, thereby bolstering trust within the ecosystem. The enhanced security and reliability are expected to attract new users, further capitalizing on network effects and contributing to the ecosystem's growth.

Total funding proposed: <$100.000>
  
# Team

Sergiu Draganus founded GeoRanker - leader in Data Acquisition Services and Search Engine Optimization Algorithm Analysis platform - back in 2009. He also funded in 2017 - CryptoCoin.PRO is one of the first European licensed FIAT On/Off Ramps. NFT Collector with a portfolio of over 10K NFTs including 2 of the first 100 Axies, 1000+ Sandbox Lands, Azukis and many others.
Renan Gomes Baretto - joined GeoRanker in 2011 - later becoming the CTO and in 2020 - Partner at GeoRanker. 
Joining Ludo as CTO back in 2021, Dmytro Nasyrov excels in building robust, heavily-loaded distributed systems. His extensive background in blockchain technology and software architecture significantly contributes to Ludo's innovative solutions in the rapidly evolving Web3 and Metaverse domains.
https://www.linkedin.com/in/sergiudraganus/
https://www.linkedin.com/in/renangbarreto/
https://twitter.com/_0xMatt_
https://www.linkedin.com/in/dmytronasyrov/

Contacts for this application: Adrian Stratulat, PM Ludo, astratulat@ludo.com or Sergiu Draganus, CEO, sergiu@ludo.com

Additional details about the team in the below pitch deck.

# Pitch deck (for further details about Ludo)
https://ludo.com/pitchdeck

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
