### ISSUE TITLE
Swaplace - Open source and collaborative P2P, OTC and Swap Protocol

### ISSUE THREAD

**Issue by danimim** [onflow/developer-grants#244]
# <Swaplace>

# Grant category
- Developer tools / services

# Description
[Swaplace](https://swaplace.xyz/) is a P2P DEX, Ownerless, Open-source, and Feeless environment for Swaps and OTC market. The project's goal is to create an infrastructure capable of being modular to create new approaches of swaps above it, this allows the community to use it as an SDK for new business models and businesses to use HTML for integrating into their apps.

Access Swaplace [Github](https://github.com/orgs/blockful-io/projects/3)

## Problem statement
1. Frustration of not swapping assets in a bunch
2. Facing fees from marketplaces
3. High slippage for high value ERC20 swaps
4. Lack of open source infrastructures that can lead to a greater adoption to the ecosystem

Swaplace's comprehensiveness allows all of this to be done in a single instance to enrich Flow ecosystem.

Liquidity Pools come with inherent constraints, particularly for coins with smaller market capitalization and lower liquidity. Traders dealing with lower-cap assets frequently encounter significant impacts in terms of price differences and slippage. Platforms like Swaplace offer traders an alternative space for the purchase and sale of tokens.

An OTC is a market for trading anything, much like Swaplace. It is P2P, allowing users to decide to trade with one person or be open to anyone. Furthermore, beyond the completeness of the dApp itself, we are an infrastructure that enables people to build on top of the Swaplace technology. **This allows the creation of diverse dApps and protocols, fostering the growth of the Flow ecosystem with ease.**

- Target audience
	1. Web3 Developers (mainly the beginners) – Found in Dev Communities
	2. Builders searching for infrastructure to build a new protocol – Found in Hackathons or incubators
	3. Web3 users – Web3 users will eventually need to carry out Swap transactions or engage in the OTC market, seeking a platform without fees.

- Evidence for the need
	1. *The growth of the OTC market is evident when we talk about the more than $3,945,938,603 of volume (Cumulative All-time Volume) on AirSwap, https://dune.com/airswap/airswap-v3*
	2. *"Ethereum remains the largest and strongest developer community • Ethereum’s contributor community has grown at a 24.9% compound annual growth rate over the past 4 years since January 1, 2018. • Since Ethereum’s peak of price in November 2021, the number of monthly active contributors has a drawdown of 9.0%." **Blockchain Open-Source Developers Signal Strength of Web3 Community. (2022).** Telstra Ventures,  https://telstraventures.com/wp-content/uploads/2022/07/Blockchain-Open-Source-Report-July-2022.pdf)*

## Proposed solution
1. Mitigating high fees associated with marketplaces
2. Eliminating intermediaries in transactions
3. Streamlining the process of transferring various tokens through a single transaction
5. Enabling payment for tokens with diverse asset combinations without additional fees
6. Opening possibilities to the OTC market and liquidity
7. SDK/Open Source (collaborative) so builders can create new products on top of Swaplace

The project's goal is to create an infrastructure capable of being modular and easy to create new approaches above it. As an open-source and brand-new model for swapping, we want to the community foster new solutions and discover new utilities for it, as facilitates exchanges of tokens between players from the ecosystem.

## Impact

- In what ways does this benefit the broader Flow developer ecosystem?

Swaplace benefits the broader Flow developer ecosystem because 
 	1. We are building an Open Source infrastructure and SDK, which will bring more developers through our incentive campaigns;
 	2. Swaplace opens opportunities for more dApps to be built in the Flow ecosystem, due to the ease of developing new products on top of Swaplace;
 	3. Swaplace is the gateway to a wider range of users who will be able to interact with a complete platform (ranging from token swaps to the OTC market) with the attraction of transacting without fees..

- Competitive factor: 
	1. If we implement Swaplace in Cadence, we can deploy the product on other blockchains that use Cadence, which is a competitive advantage
	4. The larger reach of users, the less fees we have, the more users for Flow and the more gas consumption for the network
	5. With a great adoption and more products, we can also try to bing Chainlink to the Flow ecosystem, in order to create, on Flow, a cross-chain version of Swaplace

-   What is the evidence showing that it is worth tackling?

*In addition to the articles mentioned in the evidence of market needs in relation to Open Source, Swaps and OTC, we can bring a very large range of developers to the Flow ecosystem, which will necessarily be a builder and comprehensive of a large ecosystem for a Layer 1 filled with uniquely powerful dApps. So the work is more than worthwhile, as we are building something that opens the doors to new products that can be a game-changer not only for Flow, but for the ecosystem as a whole.*

-   How likely would this be completed as planned?

*If there is no technical problem, the certainty that the deliverables will be ready is something concrete. The team has been building in the ecosystem with some huge players and for a long time and has already acted as a squad-as-a-service. Participating in hackathons and the professional experience gives us the certainty that we are capable of building everything as planned.*

-   In what ways does this enrich or accelerate other projects?

*Delivering an organized and Open Source code structure for Swaps and OTC market to all those who want to implement it in their products or create new ones.*

# Milestones and funding

> Note: Only adoption data is included in the milestones, as maintenance is carried out due to the community-driven characteristic of the product

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Smart Contract optimization   | Code deployed in the Local host env with all unit tests executed | 2 weeks  | There are no risks because anyone can build a front-end and communicate with the Smart Contract | 2000           |
| 2 - Front-end application  | Code deployed in a Local host ambient with all functions working without problems or bugs | 8 weeks  | There are no risks because anyone can communicate with the Smart Contract | 5000           |
| 3 - Documentation and Gitbook   | First version of documentation ready with principal guidelines for installation, overview, instructions, API Calls, functions, repository organization and Gitbook | 1 week  | No risks as the documentation is embedded in the contract itself | 500           |
| 4 - Cadence Implementation and Deploy on Flow   | Development in Cadence and deployment on Flow network | 2 weeks  | The contract is ownerless and not upgradable, which means no risks on our side | 7000           |
| 5 - Business Development and Engagement   | Scale the Flow ecosystem with, at least, 2 forks of Smart Contract, 100 users and 10 developers collaborating with the repository in the first 2 months  | 2 months | Risk of not getting qualified users/dApps | 1500 
         

Total funding proposed: <16.000 USD>
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Alex T. Netto | CEO, Blockchain and Smart Contract Engineer | 8º Top Delegate from ENS Protocol; Chainlink Advocate and Contributor for the blockchain ecosystem; Winner of more than 7 Hackathons including ETHSão Paulo, ETHSamba and ETHGlobal NY | alex@blockful.io |
| Guilherme Neves | Blockchain and Smart Contract Engineer | Contributor for the blockchain ecosystem, built different applications in blockchain; Winner of more than 5 Hackathons including 2 from Ethereum. | guilherme@blockful.io |
| Gabriel Novak | Business Developer | Ex-cofounder of a fintech in Brazil; Engineering consultant at Blockful; Winner of 3 Ethereum Hackathons | gabriel@blockful.io |
| Daniela Zschaber | Product Marketing Manager | Chainlink Community Advocate; Post graduate professor in Web3 MBAs and colleges; Winner of Ethereum Argentina Hackathon; Speaker at ETH Belgrade, Ethereum Argentina, SmartCon and the main events in Brazil | daniela@blockful.io |
| Franco Aguzzi | Front-end Engineer | Worked with worldwide companies; Winner of 2 Ethereum Hackathons | franco@blockful.io |

**Comment by danimim** [comment]
Hello, GM! :) How are you? @franklywatson 
If you have any questions, feel free to reach out—I'm available to clarify. Have an excellent week!

Best,
Dani

**Comment by danimim** [comment]
Hello, GM! :) How are you? @franklywatson 
If you have any questions, feel free to reach out—I'm available to clarify. Have an excellent week!

Best,
Dani

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
