### ISSUE TITLE
LLM-based support bot for Discord support channel

### ISSUE THREAD

**Issue by tri2820** [onflow/developer-grants#248]
# Compilot for Flow

# Grant category

- Educational material

# Description

## Problem statement

- **Target audience**: Developers and users within the Flow blockchain ecosystem.
- **Evidence for the need**: As the Flow ecosystem grows, there's an increasing need for an interactive, educational tool that simplifies the learning curve for both new and experienced users. There's a gap in real-time, AI-driven support for developers and users who are navigating the unique aspects of Flow's blockchain.

## Proposed solution

Compilot, an AI-driven support bot, will be integrated into Flow's Discord support channel to provide real-time assistance and educational content. It will leverage AI to answer queries, guide smart contract development, and explain Flow’s features and best practices.

## Impact

- Enhanced Developer Onboarding: By providing instant, AI-driven answers to technical queries, it will reduce the initial learning curve associated with Flow’s unique blockchain architecture and smart contract development.

- Community Engagement and Support: Compilot will act as an always-available resource for both developers and users, fostering a more engaged and active community. This continuous engagement can lead to higher retention rates and a more vibrant ecosystem.

- Knowledge Dissemination: By providing accurate, easy-to-understand information and tutorials about Flow’s features, Compilot will be instrumental in spreading knowledge within the community.

- Cross-Language Accessibility: The introduction of multilingual support in Compilot will open doors for non-English speaking developers and enthusiasts, significantly expanding Flow’s global reach and inclusivity.

- Feedback Loop for Continuous Improvement: User interactions with Compilot will generate valuable feedback and insights into common queries and challenges faced by users.

# Milestones and funding

| Milestone | Deliverables | Timeline | Risks | FLOW proposal |
| --------- | ------------ | -------- | ----- | ------------ |
| 1 - MVP | AI Bot Development & Integration | 2 weeks | Technical challenges in AI integration | 2600 |
| 2 - Educational Content Creation | Database of Flow-specific tutorials and FAQs | 1 weeks | Ensuring accuracy and relevance of content | 2600 |
| 3- Multilingual Support Implementation | Adding support for multiple languages | 1 weeks | Translation accuracy and cultural appropriateness | 1500 |
| 4 - Beta Testing and Feedback Integration | Methods to give feedback to bot conversations and adapt | 1 week | Adapting to user needs and feedback | 2600 |

Total funding proposed: 9300 FLOW

# Team

| Name     | Role                | Bio                                                                                   | Contact              |
| -------- | ------------------- | ------------------------------------------------------------------------------------- | -------------------- |
| Ganesh R | CEO                 | Seasoned founder with extensive experience in AI and blockchain technologies.         | ganesh@firebond.xyz  |
| Tri Nguyen | CTO              | Expert in AI/ML, with a background in software engineering and blockchain development. | tri@firebond.xyz     |
| Sodiq    | Developer   | Experienced in building scalable Discord bot | sodiq@firebond.xyz   |

Firebond has been experimenting with LLM for quite some time to enable efficient marketing and analytics for web3 communities. Before Compilot, we have developed a simple LLM model to generate quizzes from developer docs of blockchain projects - https://thirdwiz.vercel.app/ . This project has never been put into production, but the core tech is solid enough to act as the foundation for Compilot. We believe the idea of Compilot is simple yet can bring direct results to communities, and we envision the bot to become a powerful chatbot that can also support other aspects of web3 community management.

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
