### ISSUE TITLE
Sess_ns : Flow Grant Proposal

### ISSUE THREAD

**Issue by adamtoowavy** [onflow/developer-grants#252]
# <Project name> Sess_ns

# Grant category

Please select one:

- Open source maintenance
- Developer tools / services -- YES
- Educational material

# Description -- Sess_ns is a platform for musicians to monetize their creative process, selling demos, archival music, live recordings, lost tapes, stems & unreleased gems.

## Problem statement -- Musicians do not make enough money from streaming platforms like Spotify. 

- Target audience -- Superman's, 15% of general population are superfans one of more musicians - per Luminate Case Study 2023.

 Evidence for the need -- 0.16% of musicians on Spotify earn over $50K in 2023. I've managed and worked with musicians since 2018, many artists have mountains of unreleased music that do not fit release calendar and sits on hard drives. A case study by  Fancircles in 2023 identified 92% of fans seek a more intimate connections with artists, 78% stated they seek unreleased content for deeper connection (behind the scenes footage, demo sessions, live recordings). Lastly, Goldman Sachs "Music In The Air" report from 2023 identified a $4B untapped market in the music industry of artists monetizing demo sessions, lyric sheets, unreleased tracks etc.

These studies combined with my experience working directly with musicians understanding their needs and their process as well as being a lifelong music collector validates my conviction for Sess_ns paving new lanes for stronger connections between artists and fans.
 
## Impact

- In what ways does this benefit the broader Flow developer ecosystem? -- Sess_ns can increase Flow's prominence of blockchain intersecting with blockchain while offering utility to Flow's existing relationships within the entertainment industry. We are pioneering a new market for music and we want Flow to be the blockchain we build on and grow with.

# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - MVP   | Smart Contract, A, B Testing | March 25th  | - | 20000           |
| X - Adoption   | Run 4-5 Case Studies with mid-major artists | May-June  | - | 10000           |
| X - Expand platform offerings based on artist and fan feedback  |  | August-Sept  | - | 10000           |

Total funding proposed: <total USD amount> 40,000
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
-Adam Sarkis aka Adam Wavy | CEO | 7 Years Marketing, 5 Years Artist Management, 3 Years Product Management, 2019 Lauched an e-commerce startup Cashdrop- two person team with no funding scaled to 50K transactions with 6 months. | I've designed the UX for Sess_ns, I've contracted a backend developer to finish MVP within the coming weeks.

-Michael Kirsanov(3 years web3 developer)  with complete the blockchain contract, stress test.
-Sara Yazdani(10 years PR in Music) will develop and release the PR campaigns for the case study artists. 
-Milton McKinney(10 years musician & artist manager) will A&R - utilizing his connection within music industry will scout and onboard artists to the platform.

here's a link to the pitch deck ---> https://discord.gg/VSJF9nHg

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
