### ISSUE TITLE
Shibui Universe X Flow

### ISSUE THREAD

**Issue by ShibuiUniverse** [onflow/developer-grants#253]
# <Shibui Universe>

Shibui Universe

The Shibui Universe is a cinematic universe empowered by a new groundbreaking WEB3 model. From the Light Walker warriors battling it out in the Soulless Citadel to the legendary Women Warriors to the cursed Pirates of Fukushu - our Universe has rich, expansive lore with interconnected adventures spanning generations. Together, we shape the cinematic landscape of tomorrow.

As a multi-chain universe, we have launched (and sold out) 3 collections so far, home to 2 blockchains, amassing a community of over 40k across socials and bringing communities of different chains together, introducing both new people to new blockchains, and incorporating a blockchains existing communities seamlessly into ours.

# Grant category

- Developer tools / services

# Description

Our goal is integrating with a new, fast blockchain that will not only be the home to our next NFT collection, the Kubu people, but potentially as well to our token $SHIBUI (which will be launched on chain, untradeable at first, with us being able to hit the switch once we have built enough demand to sustain it). For that, we are looking for a grant.

## Problem statement

The problem that Shibui solves is as simple as it is grand.

Filmmakers and screenwriters, in order to create a movie, a franchise or a cinematic universe, are 100% dependent on producers. With such an unnatural state of power, the state of film and movies has declined, and creativity been overtaken by greed.

NFTs have the power to introduce change to this unhealthy system, and we plan to lead the way.

- Target audience

Movie enthusiasts, Anime lovers, NFT communities and Manga readers

## Proposed solution

The solution lies, as so often, in the new technology introduced by crypto. 

Through engaging in a community first way, we are able to take the power back as screenwriters, not needing producers to fund until our product is built out In the flesh. By building a community first, we are able to leverage all our products, anime episodes, mangas, toys or collectibles, in a way a web2 company can not.

It's a new era for film, and we are laying out the blue print.

## Impact

We plan to introduce new users to the Flow blockchain, as well as incorporate existing NFT enthusiasts into ours. Everywhere Shibui goes, we resemble our blockchains and their communities.

# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - MVP   | Launch of the Kubu people | 3 months  | - | 50 000      |
| X - Adoption   | Launch of $SHIBUI stacks | 6 months  | - | 50 000           |
| X - Maintenance   | Incorporation of Flow into shibuiuniverse.com | 9 months  | - | 50 000           |

Total funding proposed: < 150 000 USD >
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Jonny | Web3 Manager | ... | jonny@shibuilabs.io |
| James | Founders | ... | james@shibuilabs.io

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
