### ISSUE TITLE
Flow 101 - An easy to follow introductory video tutorial series

### ISSUE THREAD

**Issue by Saumay-Agrawal** [onflow/developer-grants#257]
# Flow 101

# Grant category

Please select one:

- [ ] Open source maintenance
- [ ] Developer tools / services
- [x] Educational material

# Description

Flow 101 is an easy to follow video tutorial series aimed at onboarding new developers in Flow ecosystem within a week. 

## Problem statement

Flow Ecosystem lacks a good structured video tutorial series that can help a new developer navigate it’s ecosystem. 

There is some developer material available, but it’s scattered across different content formats & platforms. 

Reducing friction in developer onboarding is very critical for the growth of any blockchain ecosystem. The easier it is for a new developer to join the ecosystem, the faster they can start building something new or start contributing to the existing projects.

## Proposed solution

The idea is to create a well-thought out video series that should start with explaining basic concepts of Flow and move towards deploying dapps on Flow. 

The content should be:

- Structured
- Easy to understand
- Not overwhelming
- And give practical examples

I have created a similar series for the Mina protocol, and it has received a very positive response from the community members. It’s live on Youtube, you can check it out here: https://www.youtube.com/playlist?list=PLqgutSGloqiIhvkaLRXwh4wmIxkd0e1Le

### Tentative Content Outline

- Intro to Flow
    - Brief overview of flow
    - Walkthrough of Flow’s architecture
    - How’s it different from other layers 1s
    - It’s unique features
    - Use cases of Flow
- Intro to Cadence
    - Brief overview of Cadence
    - Difference in programming paradigm with other layer 1s (resource oriented programming paradigm, access control etc)
    - Comparison with solidity
    - Intro to available developer toolings
- Learn concepts by a few examples
    - Basics of cadence like syntax, variables, arrays, functions, interfaces etc.
    - Smart contracts
    - Transactions
    - Resources (fungible tokens, NFTs etc)
    - Events
    - Security best practices
    - Testing
- What next can developers do in Flow ecosystem (eg hackathons, grants, ecosystem dapps etc)

Note that this is a tentative outline. I’m open to feedback & suggestions from the community members.

## Impact

This series would make it easy for any new developer to get onboard with the Flow ecosystem. Then they can start building their own dapps, or they can also start contributing to any existing dapps. It will boost the developer community of Flow. 

# Milestones and funding

Milestone | Deliverables | Timeline | Risks | USD proposal
-- | -- | -- | -- | --
1 - Finalise Content Outline & Props | A document detailing the final content outline (after feedback & suggestions from the community members) + Relevant content props (slides, code snippets etc) | 4 weeks | - | $5,000
2 - Live videos | Video series accessible on YouTube + Code samples accessible via Github repo | 6 weeks | - | $7,500

Total funding proposed: $12,500
  
# Team

Name | Role | Bio | Contact
-- | -- | -- | --
Saumay Agrawal | Full-Stack Engineer | I have 6+ years of experience in software development across various teams & research labs. Beyond that since past 4 years, I’ve worked with various Web3 orgs like Solana, ICP, Filecoin, Mina, Polkadot etc. | hi@quezar.xyz

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
