### ISSUE TITLE
MemeQuantSwap

### ISSUE THREAD

**Issue by Brendan-Lucas** [onflow/developer-grants#258]
# <Project name>
Meme Quantitative Analysis Dex (working title). 
# Grant category
DEFI  

# Description
as we enter this new bull cycle, Prominent investors and economists have identified that meme-coins and attention based investing is a prominent narrative. Flow is an ecosystem built to capitalize on this market however lacks the ecosystem community attention around this issue. We can change that. 

We want to build an advanced dex for meme-coins on Flow. 

## Problem statement
Memers and real traders alike want to capture the rush of attention that specific trends are capturing and be able to monetize this attention. Tokens enable this but an ecosystem and community encourages this. Flow is the attention chain where collectors and investors have found a place to invest in moments of significance, this is the other side of that coin. 

Users are not launching these meme coins on flow, 
Users are not trading meme coins on flow, 

## Proposed solution
We will build a sophisticated dex that enables users to do two things: 
1. launch meme tokens based on a meme they like with minimal effort. (non developer lead launches) 
2. trade meme tokens via a swap

now lets talk about the vision for the front end: 
We want to provide users with all of the classic tools sophisticated quants would expect from a serious trading experience: information brought from off-chain analytical sources like know your meme and Google trends for search and attention that different memes and cultural moments are getting. 
this will allow users to Identify memes that are trending and easily launch a token that pertains to a given meme also ofcourse traders will have access to some "blue chip memes" like the philospraptor and charlie bit me.

## Impact

I think this tool will help put flow at the center of the attention revolution/narative in crypto for this cycle. 

# Milestones and funding
TBD after gauging interest we will scope requirements more effectively. 

Total funding proposed: >100,000 USD
  
# Team
Brendan Lucas and Co (I run a devshop and if you are seriously interested lets talk more @csnormie on telegram)

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. There's already pumpflow and kittypunch/trado finance. 

Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
