### ISSUE TITLE
Communa Network - Decentralized Freelance Identity

### ISSUE THREAD

**Issue by ivanproskuryakov** [onflow/developer-grants#259]
# Communa Network
# Grant category
Developer tools/services

# Description
Communa Network represents a crypto-infused advancement in platforms for remote workers, drawing inspiration from established platforms like Upwork. Our core objective is to leverage the power of blockchain technology to elevate transparency, security, and efficiency for remote workers.
For a detailed overview of our vision, please refer to the lite paper, which outlines our mission, values, and the innovative ways in which we aim to reshape the freelancing landscape through blockchain integration.
- https://communa.network/
- https://github.com/communa

## Problem statement
In the current landscape, there is a glaring absence of open-source platforms tailored specifically for remote workers. This gap limits accessibility and innovation within the freelancing community.
1. Existing platforms predominantly operate on centralized models, often imposing fees on users and maintaining control over user accounts. This centralized control introduces vulnerabilities, where user accounts can be arbitrarily blocked, jeopardizing not only their access but also their hard-earned reputation and trust within the platform's ecosystem.
2. The repercussions of account blocking are severe for freelancers, as they risk losing their accumulated ratings and the trust they've painstakingly built over time.
This loss not only impacts their ability to secure new projects but also undermines their credibility and livelihood in the freelance marketplace.
3. The lack of ownership over user profiles exacerbates these challenges. Freelancers are essentially at the mercy of platform policies, with limited control over their data and reputations. This lack of ownership not only diminishes autonomy but also undermines the trust and transparency essential for healthy freelance ecosystems.
## Impact
Communa will positively impact the blockchain ecosystem by driving adoption.

**Productivity tooling**
Communa's utilization of smart contracts for tasks such as time-tracking, invoicing, and payments is a practical example for other developers interested in incorporating automation into their projects on EVM blockchains. 

**Decentralized Identity**
The implementation of a decentralized reputation system on Communa provides a valuable use case for other developers exploring ways to establish trust and transparency within their applications.

**Open-Source Contribution**
Communa is an open-source project, that contributes to the ethos of collaboration within blockchain community. Other developers can leverage our codebase, learn from our implementation, and potentially contribute to the project's enhancement, fostering a culture of shared knowledge and innovation.

**Ecosystem growth**
By operating on the EVM blockchain, Communa inherently becomes part of a broader ecosystem.

## Milestones and funding
We aspire to secure $50,000 in funding, primarily earmarked for the development of key components crucial to our platform's success. This includes the backend, which encompasses the API layer, the front end constituting the primary user interface, the implementation of smart contracts, and the creation of our time-tracking application. 

Total funding proposed: $50,000 

1. Web Application
Define and shape APIs necessary for seamless integration with the upcoming Time Tracking Application. 

2. ime Tracker (Current Phase)
Build a cross-platform time-tracking application using the QT framework, offering users a free tool for effective time management.
QT Framework integration, user interface design, and platform-specific optimization.

3. Decentralized Identity Contracts
Develop and deploy smart contracts on EVM networks to automate processes related to profiles and Decentralized Identity

4. Escrow Contracts
Implement payment functionalities within the Communa platform, utilizing smart contracts for secure and transparent transactions.

5. Utility Token (COMM)
Launch the Communa utility token to incentivize platform participation. Token issuance, ecosystem selection (in progress), airdrops, bounties, establishment of tokenomics, presence of funds, and investments.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| Web Application   | Functional web app and backend structure ready for further integration. | Up to 3 months | - | 10000   |
| Time Tracker   | Launch of the free Communa Time Tracker application to enhance user onboarding | Up to 2 months  | - | 10000 |
| Decentralized Identity   | Integration of blockchain-based smart contracts | Up to 2 months | - | 10000           |
| Escrow Contracts   | Full integration of payment functionalities, marking the completion of the core development phase | Up to 2 months | - | 10000           |
| Utility Token   | Introduction of the Communa utility token with established tokenomics | Up to 2 months | - | 10000           |

References:
- https://github.com/communa/backend
- https://github.com/communa/frontend
- https://github.com/communa/timetracker

# Team
Ivan Proskuryakov
A senior software engineer with an impressive track record of over 10 years of commercial experience in startups
- https://www.linkedin.com/in/ivanproskuryakov/
- https://twitter.com/ivanproskuryakov
- ivan@communa.network

Andrey U
39 years old, currently responsible for market research, financial planning, and future work on the tokenization of Communa and the development of partnership relations. Has extensive experience in the IT sphere since 1999, in niches such as affiliate programs, direct marketing, research and sales, stock, and crypto trading. Previously, co-owner of private affiliate programs with a wide network of advertisements and popular products with a turnover of over $1 million per month. Also, has significant experience in managing businesses in the local region, as well as in the development and management of personnel.
- hello@communa.network

Dmitrii Shneyder
38 years old. HR and operations director. The project manager is the person responsible for the systematization of work processes, planning, and the whole cycle of management tasks. Methodologist of product development and idea evolution.
- shneyder.d@gmail.com

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
