### ISSUE TITLE
Hypery - Music NFT Platform

### ISSUE THREAD

**Issue by alexmann1** [onflow/developer-grants#26]
# Hypery Music

# Grant category

Please select one or more of:

- [ ] OpenSource maintenance
- [ ] Developer service
- [x] Product bounty
- [ ] Educational material

# Description

## Problem statement

Musicians receive on average only 12% of the music industry’s $43 billion in revenue, in other words, over 95% of artists are barely making enough money to afford internet connectivity. Despite being the foundation of the industry, musicians are often cut out of the revenue equation. This situation worsened with the recent lockdowns that cut out the only significant source of revenue to most musicians, live performances.

On the other hand, music fans have little ownership of the music they like, most depending on streaming platforms where one can listen to an extensive selection of music but owns nothing, and is always under the centralized streaming platforms' scrutiny. 

- Target audience: Musicians, artists, music fans, NFT collectors
- Evidence for the need: Lots of testimonials on social media from artists complaining about how hard is to make a living  as a musician (less than 5% according to recent studies), official numbers of the music industry show how unfair the musicians are treated

## Proposed solution

To provide artists with a platform that gives them complete control of their creative work allowing them to get reliable payouts by selling music NFTs and income royalties from secondary market sales, and engaging with their fan base through community tokens,  while at the same time creating a new way to consume music by bringing back the ownership of music to listeners allowing them to collect, sell and rent music NFTs.  (white paper attached)

## Impact

- In what ways does this benefit the broader Flow developer ecosystem?
Leveraging the fan base of artists and the Hypery community, would bring a great number of new users to the flow blockchain and related products/services (like wallets) and expose them to other dApps enriching the entire Flow ecosystem. 

# Milestones and funding

> Note: You can leave the USD proposal empty / "TBD"

| Milestone                                | Deliverables       | Timeline  | Risks                                         | USD proposal |
| ---------------------------- | --------------    | --------  | ----------------------------- | -------------- |
| 1 - Non Fungible Contracts  | Smart Contract | July 22    | Need a Cadence engineer      | TBD                 |
| 2 - Split Payment Contract  | Smart Contract  | July 22     | Need a Cadence engineer      | TBD                 |
| 3 - Hyper Token Contract    | Smart Contract  | July 22     | Need a Cadence engineer      | TBD                 |
| 4 - SC integration                  | Smart Contract  | July 22    | Need a Web3/Flow specialist  | TBD                |

# Team

| Name                      | Role                           | Bio                                                                                                                     | Contact         |
| ------------------ | --------------- | ---------------------------------------------------------------------- | --------------- |
| Oliver Goedicke     |  CEO                  | 40 years as a DJ, producer, label owner, artist manager, and publisher. | karl@hypery.co |
| Alex Mancini           | CTO                  | 25+ years in software engineering, product development and team building. Co-founded 4 startups with successful exit, participating in Techstars and FI.                 | alex@hypery.co |
| Jakob Diechmann  |  COO                | Music industry expert with 20+ years experience, manager, producer   | jakob@hypery.co |
| Guilherme Ferreira | Head Of Tech | 25+ years of experience in soft. dev., high traffic solutions, mobile, AI   | guilherme@hypery.co |
| Wilterson Garcia    | Full-Stack Engineer | 8+ years of experience with web applications                          | wilterson.garcia@hypery.co |
| Guilherme Santos  | Full-Stack Engineer | 5+ years of experience with nodejs, vuejs, graphql, etc       | guilherme.santos@hypery.co |
| Matheus Abreu      | Full-Stack Engineer | 5+ years of experience with backend applications                 | matheus.abreu@hypery.co   |

Our team is already developing the whole frontend and backend for the platform. The funds will allow us to hire people to develop the smart contracts and integration needed to work with the Flow blockchain. 
[Hypery White Paper.pdf](https://github.com/onflow/developer-grants/files/8741511/Hypery.White.Paper.pdf)

**Comment by alxflw** [comment]
thanks for the submission, we'll review this application soon

**Comment by alxflw** [comment]
Hi @alexmann1, we reviewed your proposal in detail and decided to pass for the following reason:

Developers are not the primary target audience of this project, so the anticipated developer ecosystem impact is not high enough.

Feel free to reach me directly on Discord in case you have further questions: `alx-flw.find#6198`.
