### ISSUE TITLE
POMA: Build-to-earn platform 

### ISSUE THREAD

**Issue by POMA-Inst** [onflow/developer-grants#261]
# <Project name>
POMA: Build-to-earn platform 

# Grant category
Developer tools / services

# Description
POMA is a platform that brings the affiliate marketing in software development. On POMA, software houses and developers receive a cashback through a smart contract, distributed based on the transactions generated. 

Cashback can be provided by different entities interested in the growth of the blockchain:
- Blockchain companies/ fundations
- Node operators/ RPC providers

**The technical architecture works as follow:**
1) A notification relay is listening on the chain for operations performed on a specific smart contract
2) For each transaction executed, a notification is sent via webhook to the POMA infrastructure API
3) Once the information for each transaction is retrieved, the infrastructure takes care of calculating the cashback using one of the following strategies:
  - Real-time: Cashback is calculated for each transaction and transferred from the source wallet to the target wallet.
  - Periodic: Cashback is calculated for each transaction and saved to a persistence layer, incrementing the counter of the amount dedicated to the user who owns the project. The user is free to return to the platform to claim the accumulated cashbackOn the platform 

**The user experience is the following:**
For Developers & Software houses:
1. Choose a blockchain to build on
2. Learn & engage with the blockchain, if necessary
3. Link their account using our smart contract
4. Receive a cashback based on transactions enabled by the projects

For Blockchains companies:
1. Publish Cashback opportunities
2. Provide learning contents and developing tools

## Problem statement
Many Blockchain companies to be successful need developers to use their technology and use different marketing activities to get visibility, in particulary through various social media channels (such as Discord, Telegram, and blockchain websites).
There is no a specific tool that give a strong incentive to developers to use a specific blockchain.

## Proposed solution
POMA acts as a platform that encourages engagement between blockchains and developers, with cashbacks distributed based on the transactions generated. The platform usage for developers will be entirely free of charge.

## Impact
We belive POMA will boost the adoption of Flow, as developers will have added incentive to utilize it due to the cashback system.

# Milestones and funding
1. Platform Development – 16.000$ (2-3 months)
- Website and webapp developing – 4.000$
- Smart contract dev & integration – 10.000$
- Dashboard with analytics of developers’ usage – 2.000$ 

2. Marketing & community– 1.500$ (3-6 months)
- Initial B2B activities and marketing expenses – 500$
- Ads campaign and community engagement – 1.000$

3. Maintenance/Resolving issuing and fixing bugs – 500$ (3-6 months)

Total funding proposed: 18.000$

  
# Team
1. Paolo Medici, co-founder. He has an engineering background and he's also founder of another company in the e-commerce sector.
email: p.medici@pomainstitute.com
2. Alessio Oriolo, co-founder. He was innovation Manager at Accenture with a 8-year experience in innovation projects, also in web 3. Alessio has a business background, with a MSc in Marketing Management. email: a.oriolo@pomainstitute.com
3. Vincenzo Rana is CEO of Urania, an Investment fund owning some equities in POMA. He is also Co-founder & CEO at KNOBS, Co-founder at BCode, and Professor and Researcher at the University of Milan. Urania and KNOBS are technical partners of Poma Institute.
4. Giacomo Cavicchioli, CTO & QA - (former CTO and founder of Vyper protocol and italia Defi platform)

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
