### ISSUE TITLE
Absolute Labs - the Salesforce for Web3

### ISSUE THREAD

**Issue by annebrace** [onflow/developer-grants#262]
# Absolute Labs Wallet Relationship Management (WRM) 

# Grant category

Please select one:

- Developer tools / services

# Description 

Absolute Labs created the first enterprise-grade Saas Wallet Relationship Management platform (WRM), bringing CRM capabilities to web3. It is the leading no-code, enterprise-grade web3 CRM and marketing automation platform. The product is used by web2 and web3 brands and dApps to leverage on-chain data for targeted client acquisition, deeper client engagement, and long-term retention. It combines existing web2 data (e.g. purchase history, email, etc) with on-chain wallet data.

The core of the Absolute Labs product is the wallet data that we index from blockchains. To date, users can access the on-chain data and activity of all wallets on Ethereum, Polygon, Near, Linea, and Base (~800m wallets and growing daily). With this data, the product enables customer engagement and the ability to navigate hundreds of millions of wallets, using on-chain data to gain insights. We seek grant funds to support the indexing of Flow into our product, which is listed as the first feature below. We will submit additional proposals to achieve the other features.

Our product has the following key features for users:

- Direct Access to On-Chain Wallet Data: Insights into tokens, NFTs, dApp usage, portfolio value, and much more.
- Segmentation Capabilities: For both web3 and web2 data.
- Unified Data: Combine web2 and web3 data for comprehensive insights.
- Automated Marketing Campaigns: Seamlessly run cross-channel campaigns across the marketing funnel, including in-wallet messaging, airdrops, email, Discord, Twitter, push notifications, and SMS.
- No-Code NFT minting and custom smart contract calls.
- WalletTracker SDK: the ability to identify how many website visitors already have a digital wallet, thus identifying a target audience market. 

Our product has the following key features and opportunities for Flow developers: 
- Analyze other protocols, competitors, and dApps built on other chains, to target and actively recruit developers to grow the Flow ecosystem. 
- Increase on-chain transactions by significantly lowering friction for users. 
- Incentivize web2 brands to build projects on Flow, with the support of an enterprise-grade CRM that will integrate with their web2 CRM (note: we have a Salesforce partnership and connector).
- Enable crypto payments on e-commerce websites (we have partnerships with Stripe, crypto.com, Coinbase, and Shopify).
- The ability to offer brands and developers discounts and incentives to use the Absolute Labs product, via our partnership.
 
This particular grant would fund the indexing of all Flow active wallets, and their contents, into the platform and generate profiles for each. All Flow data will be incorporated into the 'Collection Insights' product feature, which will enable platform users to search and analyze Flow wallets based on the following metrics: wallet activity, portfolio value, investments, activity history, exchanges and dApp usage, X followers, custom data input by users, and their interests. Once this is achieved and we are live, we will submit another grant application to incorporate the additional product features. 

Absolute Labs launched in early 2022 and manages a steadily growing roster of customers and partners. Customers include the LVMH group, Chanel, Ledger, Animoca Brands, BNP Paribas, World of Women, and Française des Jeux; ecosystem partners include Google Cloud, Salesforce, Publicis, Coinbase, crypto.com, Shopify, Mojito, Fireblocks, and more. The Absolute Labs team can encourage these teams to integrate with the Flow ecosystem – a powerful benefit that we bring to our chain partners. 

The Absolute Labs founding team has a proven track record of building, launching, and selling marketing tech, together, for 15 years. They launched and exited three companies in marketing technology, one of which was a leader in the Gartner Magic Quadrant for Mobile Marketing Platforms (FollowAnalytics). The team is currently 25 people and growing. 

Absolute Labs is committed to supporting the Flow ecosystem by providing the tools needed for growth and innovation. Through our product and partnership, we will bring powerful marketing tools, brands, and developers to your chain.

## Problem Statement

Problems our product solves:
- Inability for business teams within brands to combine their clients’ traditional ‘web2’ CRM data (e.g. email, address, purchase history, interests) with their new wallet-related data (e.g. NFTs held in wallets, portfolio value, dApps used). 
- Inability for business teams within brands to leverage on-chain data to develop, and automate, marketing campaigns for customer acquisition, engagement, and retention. 
- Lack of ‘no-code,’ enterprise-grade marketing automation product for managing on-chain assets. 
- Lack of ‘no-code,’ enterprise-grade marketing automation product for managing on-chain profile and wallet data. 
- We are serving as the no-code intermediary between enterprise brands and the network of available web3 tooling. 

Target market(s):
- Absolute Labs is primarily a B2B SaaS product for web2 and web3 companies/brands.
- We also target developers who are responsible for recruiting dApps and developers to a particular chain. 
- We help chains identify the most promising dApps in other ecosystems for recruiting purposes; we provide them robust analytics and marketing automation tools.

## Solution

The Absolute Labs platform addresses the challenges faced by business teams within brands in integrating traditional 'web2' CRM data with new wallet-related data, leveraging on-chain data for automated marketing campaigns, and managing on-chain assets and profile data. By providing a no-code, enterprise-grade marketing automation solution, we act as an intermediary, connecting enterprise brands with the web3 tools they need.

## Impact

As explained above, our product has the following key features and opportunities for Flow developers: 

- Analyze other protocols, competitors, and dApps built on other chains, to target and actively recruit developers to grow the Flow ecosystem. 
- Increase on-chain transactions by significantly lowering friction for users. 
- Incentivize web2 brands to build projects on Flow, with the support of an enterprise-grade CRM that will integrate with their web2 CRM (note: we have a Salesforce partnership and connector).
- Enable crypto payments on e-commerce websites (we have partnerships with Stripe, crypto.com, Coinbase, and Shopify).
- The ability to offer brands and developers discounts and incentives to use the Absolute Labs product, via our partnership.

# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Adapt the Absolute Labs indexers to support Flow and make the blockchain data available throughout the platform.   | Accessible Flow data | 6 weeks  | - | 30000           |
| 2 -  One-time data ingestion to activate Flow and make the blockchain data available throughout the platform.   | Users can search and analyze Flow wallets based on the following metrics: wallet activity, portfolio value, investments, activity history, exchanges and dApp usage, X followers, custom data input by users, and their interest | 2 weeks  | - | 10000           |
| 3 - Ability to sync data in real-time for new blocks, wallets, and collections   | All data related to wallets, historical transactions, buying power, dApp interactions, segment inclusions, and key metrics of Flow collections is kept up to date on a near real-time basis. All data for further activations are updated and maintained in real time.  | 2 weeks  | - | 10000           |
| 4 - Adoption   | Absolute Labs' VP of Partnerships and VP of Business Develop will agree upon targeted number of brands to bring to Flow. They will share pipeline of existing and prospective customers with relevant Flow team members on a recurring basis to ensure web2 brand adoption.  | Ongoing  | - | 0           |

Total funding proposed: <60,000 USD>
  
# Leadership Team 

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Samir Addamine | CEO | Samir Addamine is CEO and co-founder of Absolute Labs, a Web3 CRM software-as-a-service (SaaS) company based in San Francisco, CA. The company announced an $8 million seed raise on April 11, 2023. Prior to Absolute Labs, Samir founded FollowAnalytics, an industry-leading mobile analytics and engagement solution, whose first private investor was Marc Benioff, founder of Salesforce.com, and which was frequently recognized by the Gartner Magic Quadrant for its excellence in mobile marketing. His first company, Clicmobile, was one of the first mobile consulting and development studios in Paris. Founded in 2008, it forged a strong collaboration with Apple Europe, helping dozens of large companies build their first mobile apps. Mr. Addamine is an investor in several SaaS Marketing software startups, serves as a Non-Executive Director of Bryi Technologies (post Series C). He has written numerous articles on marketing technologies for both Web2 and Web3, for Forbes, Venturebeat, and others, and is a frequent speaker at industry events. | samir@absolutelabs.io |
| Antony Gardez | CPTO                | Antony Gardez, Co-Founder and CPTO at Absolute Labs, is a veteran platform engineer with extensive experience in product design, known for creating feature-rich and user-friendly products. His dual expertise ensures robust technical infrastructure and exceptional user experiences. Prior to this position, he led product and innovation at FollowAnalytics, a mobile marketing platform, where he also contributed significantly to data architecture design. He studied software engineering at the INSA Rouen school of engineering in France and at McGill University in Montreal. | antony@absolutelabs.io         |
| Riad Lemhachheche | VP of Business Development                | Riad Lemhachheche is currently the VP of Business Development at Absolute Labs. Additionally, he is a Co-Founder and VP of Factory at Absolute Labs, leading the development of its Customer Engagement platform. Previously held positions at Bryj included Co-Founder and Customer Success Manager, Director of Presales & Solution Engineering, VP of Solution Engineering, VP of Business Development & Partnerships, and Strategic Advisor. Riad has been involved in various organizations, such as the PreSales Collective, a Founder of Moobil Ventures, a Member of CLUB3, and BusinessFirst. He has also served as an Intervenant at IIM - Institut de l'internet et du multimédia, where he contributed as a Master Transformation Digitale et Licence Web Developer. Riad has also served as a Strategic Advisor at Momentum and BusinessFirst, and as the President of Mobiwhirl. Riad has a Baccalauréat in the field of Scientifique from the Lycée Saint Pierre Chanel, an MS in Computer Engineering and Networking from CPE Lyon, an MS in Information System Engineering, Industrial and Manufacturing Engineering, and Business Administration from Oregon State University. He also received a certification in R Programming from John Hopkins University and completed a course on Decentralized Finance (DeFi) Infrastructure at Duke University. | riad@absolutelabs.io        |
| Anne Bracegirdle | VP of Partnerships                | Anne Bracegirdle leads US Partnerships for Absolute Labs, the leading enterprise software for web3 marketing, and provides independent advisory on topics related to blockchain and the arts. She is also the Co-Founder of the Art & Antiquities Blockchain Consortium 501(c)(3) in 2018. Recently held positions include VP of BD at Metaversal, Head of Sales at Convelio, and Senior Director of Special Projects at Superblue. Prior to Superblue, Anne was an AVP and Specialist at Christie’s New York, where she co-founded Christie’s Art + Tech initiative which culminated in two Art + Tech Summits, Exploring Blockchain (2018) and The A.I. Revolution (2019). During her ten years at Christie’s, Anne was a specialist of Russian Art, 19th Century European Art, and Photographs. Anne speaks widely on the topics of art, blockchain, and web3 and has been cited in The New York Times, Wired, The Financial Times, Forbes, The Art Newspaper, among others. | anne@absolutelabs.io         |
| Pierre Vibert | CFO              | Pierre joined Absolute Labs in 2022 as the Chief Financial Officer. Before that, he held the same position at Bryj from July 2020 to November 2021. Pierre also served as DAF EMEA at Bryj from September 2013 to July 2020. Prior to Bryj, Pierre worked at EWDN as the VP of Business Development for the entirety of 2013. Pierre briefly served as a financial adviser at Displair in 2012 and as a financial controller at Rasec International from February 2012 to June 2012. Pierre had a significant role as the CFO of Rasec Vostok from October 2007 to November 2011. Pierre worked as a financial manager at Vinci Construction Grands Projets from March 2006 to January 2007. Pierre also worked as a financial controller at Belgo Gen Belgo Serv from January 2004 to December 2005. Pierre began his career as a project engineer at SOGREAH from January 2001 to September 2002. Pierre has a degree in Engineering from ENSEEIHT and an MBA in Finance from the University of Paris I: Panthéon-Sorbonne.  | pierre@absolutelabs.io        |

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
