### ISSUE TITLE
XFX Academy Grants

### ISSUE THREAD

**Issue by XFXAcademy** [onflow/developer-grants#265]
Name of project:
XFX Academy

Grant Category
Educational material

Description
Problem Statement
Target Audience:

Aspiring blockchain developers
Enthusiasts and professionals looking to transition into the blockchain space
Current developers seeking to deepen their understanding of blockchain technology

Evidence for the Need:

The increasing demand for blockchain education and skilled professionals in the rapidly growing Web3 and blockchain industries.

The lack of comprehensive and structured educational resources focused specifically on blockchain development and applications.

Feedback from industry professionals indicating a significant skills gap in blockchain technology and Web3 development.

Proposed Solution
The XFX Academy aims to provide high-quality, comprehensive educational materials focused on blockchain technology and Web3 development. By offering structured courses, hands-on projects, and community engagement, the academy will help bridge the skills gap in the blockchain industry and empower individuals to contribute effectively to the ecosystem.

Impact
Benefit to the Broader Flow Developer Ecosystem:

Providing a steady stream of well-trained developers who can contribute to the Flow blockchain and its ecosystem.
Enhancing the overall knowledge base and skill level within the Flow community, leading to more innovative projects and applications.
Supporting the growth of the Flow blockchain by making it more accessible to new developers through targeted education and training.

Milestones and Funding

Milestone	Deliverables	Timeline	Risks	USD Proposal
1 - Initial Setup and Content Creation	Hire team members, develop and launch first set of courses	3 months	Delay in hiring, content quality issues	$25,000
2 - Marketing and User Acquisition	Launch ad campaigns, optimize marketing strategies	3 months	Ineffective marketing, low user acquisition	$25,000
3 - Platform Enhancement and Expansion	Expand course offerings, improve platform UX/UI	3 months	Technical issues, user feedback implementation delays	$25,000
4 - Scaling and Community Building	Scale marketing efforts, foster community engagement	3 months	Community engagement challenges, market competition	$25,000

Total funding proposed: $100,000

Team
Name	Role	Bio	Contact
Alexandre Bianchi	Founder / Advisor	Experienced crypto investor and influencer since 2017, author of 'Manual do CriptoInvestidor', and founder of XFX Academy.	contact@xfxacademy.com

COO -
Diego Alcantara – Blockchain Senior
Diego Âlcantara is a blockchain developer with years of experience and extensive knowledge in web3 and good relationships in the crypto market. He graduated from one of the few renowned universities specialized in programming in Brazil, called 42. He will be our teacher and instructor in the blockchain programming curriculum at xfx academy

Rachel – Sales Manager
Investor, specialist consultant and commercial manager in digital projects.
With extensive experience in leading and training teams, she is responsible for monitoring performance, motivating and empowering closers. She is certified in project management, investments on the Brazilian and US stock exchanges, as well as specialized training in cryptocurrencies. Combining exceptional communication and organizational skills to continually explore opportunities in the digital and financial environment.

José Câmara – Specialist in Automations
Enthusiastic about no-code tools and automations that use core artificial intelligence, he stands out for his creativity and dynamism. With a history of commitment and problem solving, he has significant experience in managing teams and 7-figure digital projects, always seeking innovation.

Mariana Alves – Specialist in Social Media
Since 2019, focused on Digital Marketing strategies for companies in Portugal and Brazil. Founder of Midia ON, a digital marketing agency dedicated to leveraging local businesses and experts through personalized and effective strategies.
She has worked on more than 30 projects, creating social media campaigns, developing growth strategies and producing high-quality visual content.

Thales Lorenzo – Leader of advertisings
Traffic Manager specialized in infoproducts and digital strategist.
Traffic Manager for over 5 years, with more than 25 million reais invested in advertisements and 60 million reais billed to his clients.
[XFX Academy - Pitch Deck - English.pdf](https://github.com/user-attachments/files/16396370/XFX.Academy.-.Pitch.Deck.-.English.pdf)
[XFX Academy - Pitch Deck - English.pdf](https://github.com/user-attachments/files/16396375/XFX.Academy.-.Pitch.Deck.-.English.pdf)

By achieving these milestones, the XFX Academy will create a robust educational platform that empowers new and existing developers, enriches the Flow ecosystem, and supports the long-term growth and sustainability of blockchain technology.

**Comment by diegofornalha** [comment]
In my role as COO of XFX Academy and as an instructor for the Smart
Contract Cadence 1.0 course, my responsibilities include:

 1. Operational Management
 2. Regulatory Compliance and Safety
 3. Customer Experience
 4. Performance Monitoring
 5. Technology and Innovation
 6. Operational Scalability
 7. Crisis Management
 8. Business Development
 9. Customer Retention
 10. Technology Integration
 11. Workforce Planning
 12. Process Optimization


Em sex., 26 de jul. de 2024 às 17:17, XFXAcademy ***@***.***>
escreveu:

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
