### ISSUE TITLE
 Flow.com Advocate Grant Program in Brazil

### ISSUE THREAD

**Issue by cavazinf** [onflow/developer-grants#267]
# Flow.com Advocate Grant Program in Brazil: A Financial Projection 💰🇧🇷

Link official: https://coda.io/d/Programa-Flow-Advocate-Brasil_d5YVzZ9H8nM/Programa-Flow-Brasil_suah9#_lu47m
# Grant category
Advocate Grant Program
- Developer tools / services
- Educational material

# Description

## Problem statement

- Target audience
- Evidence for the need

To fuel the growth and visibility of Flow.com in Brazil, we propose the establishment of a dedicated grant program to financially support passionate advocates. This program will empower advocates to create and share engaging content, organize events, and spearhead initiatives that promote Flow.com and its innovative blockchain technology. Below, we present a financial projection for a 12-month period.

1. Grant Objectives 🎯

* Stimulate Content Creation: Provide funding to advocates who produce blogs, videos, podcasts, and other compelling content related to Flow.com and its ecosystem.Support Events & Meetups: Offer financial support for organizing events, meetups, and workshops that promote the Flow.com brand and its products/services.Develop Engaging Projects: Award grants for specific projects designed to increase community engagement and expand Flow.com's visibility within the Brazilian market.

2. Grant Structure 💵

Grant Categories:

1. Micro-Grants (R$500 - R$1,000 / $100 - $200 USD): For smaller-scale initiatives such as blog posts, short videos, and targeted social media campaigns.Medium Grants (R$1,000 - R$5,000 / $200 - $1,000 USD): For higher-impact projects such as high-quality video production, podcast development, or marketing campaigns.Large Grants (R$5,000 - R$10,000 / $1,000 - $2,000 USD): For larger-scale events, meetups, and ambitious projects that require more substantial resources.

3. Grant Distribution Projection 📊

Based on a total budget of R$200,000 ($40,000 USD) for 12 months: (Based on an exchange rate of R$5 = $1 USD).

* Micro-Grants:Number of Grants: 50Average Cost per Grant: R$800 ($160 USD)Total Cost: R$40,000 ($8,000 USD)Medium Grants:Number of Grants: 30Average Cost per Grant: R$3,000 ($600 USD)Total Cost: R$90,000 ($18,000 USD)Large Grants:Number of Grants: 10Average Cost per Grant: R$7,000 ($1,400 USD)Total Cost: R$70,000 ($14,000 USD)

Total Overall: R$200,000 ($40,000 USD)

4. Grant Evaluation and Approval Criteria 📝

1. Relevance to the Flow.com Brand: Projects must align with Flow.com's values and objectives, promoting its products and services in a positive and impactful way.
2. Reach and Engagement Potential: Priority will be given to initiatives that have the potential to reach a large audience or generate high levels of engagement within the Web3 community.Originality and Creativity: Innovative and creative projects that bring fresh perspectives to brand promotion will be favored.
3. Execution Plan and Feasibility: Well-structured proposals with a clear execution plan, defined timelines, measurable goals, and realistic budgets will be viewed favorably.

5. Monitoring & Reporting 📈

1. Progress Reports: Grant recipients will be required to submit regular progress reports outlining the development of their projects.Impact Analysis: We will measure the impact of each initiative in terms of reach, engagement, community feedback, and alignment with program goals.
2. Program Adjustments: Based on results and feedback, the grant program will be iteratively refined to optimize its effectiveness and alignment with Flow.com's objectives.

6. Grant Program Promotion 📢

1. Social Media Promotion: Targeted campaigns will be launched to announce the grant program and encourage applications from passionate advocates.Q&A Sessions: We will host informative Q&A sessions to address any questions about the application process and program goals.
2. Advocate Testimonials: We will share success stories from grant recipients, highlighting the benefits and impact of their projects.

Conclusion:

This strategic grant program will empower Flow.com to significantly boost its brand visibility and engagement within the Brazilian market. This investment will not only strengthen the advocate community but also create a lasting impact on Flow.com's expansion and adoption in Brazil. With creativity, collaboration, and a focus on results, we will ride this wave of success together! 🌊🏄‍♂️🚀

| Milestone | Deliverables   | Timeline | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 -Micro-Grants : For smaller-scale initiatives such as blog posts, short videos, and targeted social media campaigns.  | Advocate | 12 months  | - | (R$500 - R$1,000 / $100 - $200 USD) |
| 2 - Medium Grants : For higher-impact projects such as high-quality video production, podcast development, or marketing campaigns.| 12 months  | - |(R$1,000 - R$5,000 / $200 - $1,000 USD)|
| 3 - Large Grants : For larger-scale events, meetups, and ambitious projects that require more substantial resources.  | Advocate | 12 months  | - | (R$5,000 - R$10,000 / $1,000 - $2,000 USD)|
| National Ambassador who will lead the program in Brazil ( president of the Brazil Ambassadors and Advocates program. )  
| 12 months  | $5,000 USDC
| 4 Program leader(will coordinate the program in 27 different regions.) | 54 Advocates in Brazil | 12 Months | $1,000 USDC

Total funding proposed: <total USD amount>
""One of the 3 Grants for Advocate options can be chosen""  
 
# Team
Advocate Flow Brasil - there will be 2 people per state
Ambassador in Brazil - Will manage and put together strategic planning for Flow's growth through Web3 movements

| Name Tiago Ferreira Cavazin | Role Ambassador in Brazil| Bio Founder of Fitcash-Fth, a token created on the ethereum blockchain, reaching 117 countries and listed on some brokers. 2021 saw 10 approvals between accelerations and incubations, winning awards. administration academic, web 3.0 researcher. Full smart contract programmer. web 3.0 project consultant, I mentored a few startups in 2021 and 2022. And I recently came in 2nd place in the lift learning hackton (central bank). | Contact https://www.linkedin.com/in/tiagoferreiracavazin/  |
| ---- | ------------------- | --- | --------------- |

**Comment by diegofornalha** [comment]
Firstly, I would like to congratulate you on the brilliant initiative of the Advocate Program in Brazil. I see that other prominent blockchains are adopting similar approaches, which underscores the importance and effectiveness of such programs for growth and market visibility.

As the Official Global Ambassador of Flow since January of last year, I can attest to the positive impact that initiatives like this can have on our community.
https://floats.city/event/0xa918ca8fb2a4bdeb/867090848

I am fully available to collaborate and support this initiative. Together, we can continue to grow and establish Flow as a reference in the blockchain sector.

Count on me!

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to find new ambassador and advocacy opportunities as they arise in your region.
