### ISSUE TITLE
[SDK] flow.net and fcl.net updates and maintenance

### ISSUE THREAD

**Issue by tyronbrand** [onflow/developer-grants#269]
# .NET SDK

# Grant category

- Open source maintenance
- Developer tools / services

# Description

There have been many exciting changes and the .NET SDKs require updates.

## Problem statement

The SDK's are currently lacking needed updates.

## Impact

This will help ensure that Flow developers have access to the latest features Flow has to offer.

# Milestones and funding

I will start by updating [flow.net](https://github.com/tyronbrand/flow.net) and then moving onto [fcl.net](https://github.com/tyronbrand/fcl.net).

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| Updates and Maintenance   | Updating the SDK's, resolving issues and fixing bugs | Every month  | I do not want the SDK to grow unstable and want to be able to help its users. Each month for 6 months | 10000           |

Total funding proposed: 60000
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| [Tyron](https://github.com/tyronbrand?tab=repositories) | Full-Stack Engineer | Developer of the [flow.net](https://github.com/tyronbrand/flow.net) SDK and [fcl.net](https://github.com/tyronbrand/fcl.net) | tyron.brand@gmail.com |

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
