### ISSUE TITLE
Open Source Physical NFTs on Flow

### ISSUE THREAD

**Issue by KevinMckE** [onflow/developer-grants#270]
# Open Source Physical NFT Infrastructure on Flow

# Grant category

Please select one:

- Open source maintenance
- Developer tools / services X
- Educational material

# Description

PhysiKey.xyz is building Open Source Hardware wallets to bring the simplicity of in person physical transactions to Web 3 digital assets.

Our Open Source Hardware wallet solution transforms open source, off-the-shelf, consumer-grade NFC tags into physical Flow NFTs, effectively recreating the advantages of traditional physical art sales for our digital future.

## Problem statement

- Target audience - New Users need a wallet before they can buy a digital asset, but our tech turns consumer grade NFC tags into physical wallets that contain NFTs and digital assets, meaning a person can purchase one of our tags from an artist/vendor and have both a wallet and a digital asset in one simple transaction.
- Evidence for the need - While people who are already involved in Web 3 understand the value, the difficulty in crossing the adoption chasm into the general market demonstrates that the onboarding and custody tools are not good enough to grow the ecosystem with normal people.

## Proposed solution

Our mobile application turns your mobile phone into a digital asset ATM, turning NFC tags into digital assets.

We will include Flow functionality into our mobile application we will be launching in 2025, and include Flow functionality into our open source SDK which will allow other devs to include this access and self-custody technology into their mobile application functionality.

The video at this link demonstrates the high level idea: https://www.physikey.xyz/physikey-cash

The video at this link shows a working version of our payment card that uses similar technology: https://www.physikey.xyz/physikey-payment-card

Here is a link to our project presentation: https://drive.google.com/file/d/1-dZfc58UoitqoVBtHqcxIsYMMC_xMgW_/view?usp=sharing

## Impact

- In what ways does this benefit the broader Flow developer ecosystem?
- Our open source React Native SDK will offer an innovative adoption tool available for developers to integrate into their mobile applications, increasing overall adoption and usability of the entire Flow ecosystem.

# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - MVP | Flow integration in Web 3 Mobile Application | 6 months  | - | 50,000 |
| 2 - SDK | Open Source Code for Flow integration in React Native SDK | 3 months  | - | 10,000 |
| 3 - Docs | Docs for React Native SDK | 3 months  | - | 2,500 |
| 4 - Security Audit | Mobile Application Security Audit | 6 months  | - | 15,000 |
| 5 - Adoption | 15,000 card giveaway for conferences and user adoption | 9 months  | - | 30,000  |
| 6 - Maintenance | Support and maintenance for Flow developer ecosystem | 24 months  | - | 30,000  |

Total funding proposed: $137,500
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |

| Kevin Ecke | Founder/Engineer/Product | Two time founder, PhysiKey inventor, Master's degree in technology design with a focus on cybersecurity, embedded systems, and user experience, and a certificate from MIT Sloan School of Business in Blockchain Innovation. | kevin@physikey.xyz |
| Mark Lisanti | Co-Founder/CTO | Former IBM engineer. Master's degree in technology design with a focus on mobile app development, user experience, and web development. | mark@anywhereaccess.io |

**Comment by chimpytuts** [comment]
Hello,
How can I candidate?

**Comment by KevinMckE** [comment]
> Hello, How can I candidate?

Hello, can you clarify what you are asking?

**Comment by chimpytuts** [comment]
I want to submit for one of the tasks that you mentioned on you ticket description:
![Image](https://github.com/user-attachments/assets/7da61608-b013-4e5c-aaa8-4be510383060)

**Comment by Aliserag** [comment]
We appreciate your proposal. After careful review we've decided not to proceed at this time. Please stay connected to our Twitter and working groups to stay on top of the latest developments in the ecosystem and new grant opportunities.
