### ISSUE TITLE
On-chain analytics dashboard

### ISSUE THREAD

**Issue by alxflw** [onflow/developer-grants#3]
Similar to Dune, it would be great to make the chain state queryable 

> Note: [For Dune to support Flow, it needs significant community support. Vote if you haven't done that yet](https://feedback.dune.xyz/features/p/support-flow-chain).

**Comment by Guisong-Fu** [comment]
# Grant category

Please select one or more of:

- [ ] OpenSource maintenance
- [*] Developer service
- [ ] Product bounty
- [ ] Educational material

# Description
Similar to Dune. A general analytics tool for Flow blockchain.

## Problem statement

Dune does not support Flow blockchain yet, and there is no other tool that provides similar services for Flow blockchain.

## Proposed solution
- Build a data warehouse that stores chain state 
- Build a platform where everyone could do some analysis on Flow blockchain activities

## Impact

- Everyone would be able to easily do some analysis on Flow blockchain.

# Milestones and funding


| Milestone | Deliverables   | Timeline | Risks                   | FLOW requested |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Data Analysis P1  | Determine what data should be collected | 1 week  | May need some support from Flow Team | 1000           |
| 2 - Data Analysis P2 | Determine the best way to collect data  | 1 week  | May need to set up an access node | 1000           |
| 3 - Data Storage   | Determine the suitable table structure | 2 weeks  | Time | 2000           |
| 4 - Job Implementation   | Setup data warehouse; Implement the corresponding ETL jobs | 4 weeks  | Time | 5000           |
| 5 - Visualization Tool Set up  | Configure SuperSet | 2 weeks  | May need to tweak SuperSet a bit   | 3000           |
| 6 - Integration Test  | Dashboard being connected to data warehouse | 1 week  |  | 1000           |
| 7 - Pre-build some dashboards  | A few dashboards can be seen | 1 week  | Some bugs may pop out and some rework maybe needed  | 1000           |
| 8 - Open for testing | Platform are ready to be tested | 1 week  |   | 1000           |
| 9 - Documentation  | Docmentation is ready | 1 week  |   | 1000           |
| 10 - Maintainence  | Maintain Cloud Service; Support | 1 week  |   | 1000           |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Guisong Fu | Data Architect/Engineer | CTO of SoulMade; muti-year experiences as Data Architect | guisongfu@gmail.com |
| SkyOne | Senior Flow Blockchain Developer | Founder of 7DayReFundNFT; core developer of SoulMade | skyone.nanshan@gmail.com  |

**Comment by Guisong-Fu** [comment]
Hi @alxflw  ,  would you have time to take a look at our proposal? 
Thanks!

**Comment by alxflw** [comment]
sure thing, thanks for the submission @Guisong-Fu!

**Comment by Guisong-Fu** [comment]
> 

Definitely, here it is [https://github.com/onflow/developer-grants/issues/25](https://github.com/onflow/developer-grants/issues/25)

**Comment by alxflw** [comment]
grant was accepted, closing this wishlist item!
