### ISSUE TITLE
flow.net SDK updates and maintenance

### ISSUE THREAD

**Issue by tyronbrand** [onflow/developer-grants#30]
# [flow.net](https://github.com/tyronbrand/flow.net)

# Grant category
OpenSource maintenance

# Description
I aim to implement the [Flow HTTP API](https://docs.onflow.org/http-api/).

## Problem statement

- Currently, the SDK supports the gRPC implementation. I would like to support both gRPC and the new [Flow HTTP API](https://docs.onflow.org/http-api/).

## Proposed solution

- Update the .NET SDK to support the [Flow HTTP API](https://docs.onflow.org/http-api/).

## Impact

- All developers using the .NET SDK will be able to work with the new [Flow HTTP API](https://docs.onflow.org/http-api/).

# Milestones and funding

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Http Implementaion   | Flow HTTP API implementation plus examples | 3 weeks  | Time | TBD          |
| 2 - Maintenance   | Resolving issuing and fixing bugs | 3 months  | - | TBD           |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| [Tyron](https://github.com/tyronbrand?tab=repositories) | Full-Stack Engineer | Developer of the Flow.NET SDK | tyron.brand@gmail.com |

# Milestone completion
- [x] Flow HTTP API implementation plus examples
- [x] Maintenance

**Comment by alxflw** [comment]
hey @tyronbrand, we are excited about this grant and I'll follow up with you wrt the TBD parts of the proposal

**Comment by alxflw** [comment]
this grant was accepted 🚀
