### ISSUE TITLE
Flow Developer Grants :: Cadence

### ISSUE THREAD

**Issue by int96** [onflow/developer-grants#33]
# <Project name>
Learning Cadence
# Grant category
Learning
Please select one or more of:

- [ ] OpenSource maintenance
- [ ] Developer service
- [x ] Product bounty
- [ ] Educational material

# Description
I would like to learn Cadence to further help out the blockchain.
## Problem statement
My problem is I will need help and resources to help me learn Cadence
- Target audience
- Evidence for the need

## Proposed solution
I know of a course I can take in the Emerald City Discord to learn Cadence
## Impact
Learning Cadence will enable me to help out projects and maybe become part of a team.
- In what ways does this benefit the broader Flow developer ecosystem?
Learning Cadence will make for better smart contracts 
# Milestones and funding
My milestones would be seen through my advancement through the Emerald City Cadence Courses.
> Note: You can leave the USD proposal empty / "TBD". Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - MVP   | Smart Contract | 2 weeks  | - | 1000           |
| X - Adoption   | 5 team using this project | 4 weeks  | - | 1000           |
| X - Maintenance   | Resolving issuing and fixing bugs | 3 months  | - | 1000           |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Alex | Full-Stack Engineer | ... | alex@onflow.org |

**Comment by alxflw** [comment]
hey @int96, I'd propose you complete some tutorials, check out open cadence, and the classes that emerald DAO offers. There are more things in the works that you can try out soon!

Having said that, we do not extend grants for personal learning. Grants should include deliverables that benefit other developers in the Flow ecosystem in direct ways (eg for the education category: produce a contract, class, blog, tutorial, etc).
