### ISSUE TITLE
Snap Protocol

### ISSUE THREAD

**Issue by DappCoderr** [onflow/developer-grants#38]
# Snap Protocol

# Grant category

Please select one or more of the:

- [x] Product bounty

Website - https://snap-protocol.vercel.app/

# Description
Snap Protocol is a protocol for creating a liquid market for illiquid Non-Fungible Tokens for the flow blockchain.

Users deposit their NFT into a Snap vault and mint a fungible token (sToken) that represents a claim on a random asset from within the vault. 

sTokens can also be used to redeem a specific NFT from a vault.

#### Benefits include

- Instantly sell any NFT by minting it as a fungible token and swapping via bloctoSwap with the flow native token.
- Better distribution and price discovery for NFT projects
- Swap your NFT for another NFT in the same pool.
- LP and stake minted sTokens to earn rewards

#### Architecture
![snap_architecture](https://user-images.githubusercontent.com/68939930/176653585-386c2784-1e14-433e-9e4b-c3ded8e241df.png)

#### Working

1. Vault Creation: Initially, Only the Snap Admin can create the Vault, Once the Vault is open anyone can deposit the eligible NFT into the vault to mint the fungible backed NFT token names as sTokens.
2. Minting sTokens: Anyone can deposit NFT in the Vault to mint the NFT-backed sTokens to claim 1:1 random NFT from the vault.
3. sToken Price: Initially, the sToken price is decided by the floor price of that collection.
4. Eligibilities: Snap is using metadata to build a different vault for different eligible NFTs so that higher rarity NFTs will have a good price. 
(Note: Its price functionality is different from other NFTs)

## Problem statement

- Target audience: 
Current & Future NFT projects, Artist, NFT Collector, Web3 Gamer.
- Evidence for the need: 
Web3 is a growing ecosystem and Flow plays a major role in building the pillars of web3, flow is built for the fast and decentralized foundation for a new generation of games and digital assets.
But as a bear market appear, the market reveals (data from NFT Price Floor) that the average 30-day price floors of NFTs have declined by approximately 50% from a little over 40 towards the end of June. Transaction volumes have also declined significantly in the space. Artists and Collectors are facing issues, in selling NFTs at a good price.

#### Research Part - 
According to the Financial Times and Chainalysis, approximately 360,000 NFT owners hold around $2.7 million in NFTs around the globe in 2021.

## Proposed solution
We are building a Snap protocol, which will create a pool of NFTs for a specific collection and converts NFTs (illiquid assets) into fungible tokens, making them easily tradable.

## Impact

- In what ways does this benefit the Flow ecosystem?
Snap protocol will tokenise NFTs into the fungible token backed by the NFT collection. Anyone on the flow can easily liquidate NFT (that means, it will be easily tradable) with the native flow token. 

# Milestones and funding

> Note: Overall duration to deliver future milestones: ~6.5 months. Total FLOW requested: 34,000.
> Duration to deliver MVP - 4 months.

| Milestone.  | Deliverables   | Timeline | Risks                   | FLOW proposal |
| ---------------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Initial Requirements Gathering with Potential Users and Architecture design  | list of top 10 features to implement & Project Development | 1 Week | - | 1000 FLOW         |
| 2- Building     | Smart Contract development | 6 Weeks  | - | 8000  FLOW        |
| 3 - Website     | Frontend and Backend development | 6 Weeks  | (Need a Full Stack Engineer) | 6000  FLOW         |
| 4 - Testing & Deployment   | Testing of product| 3 Weeks  | Fixing testing vulnerability of product | 2000  FLOW         |
| 5 - Adoption     | Onboard 10 Flow projects | 2 Weeks  | - | 2000  FLOW         |
| 6 - Maintenance     | Resolving issues and fixing bugs | 2 months  | - | 15000  FLOW         |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Hardik | Founder | Currently working on the snap protocol (Liquidity protocol for illiquid assets). Previously, Build Non Fungible Address on Ethereum, Cadence smart contract dev at NFT Genius, Next Decentrum and Solidity engineer at fusible | er.hardiksharma05@gmail.com |

**Comment by alxflw** [comment]
thanks for your proposal @DappCoderr! we'll review it soon and get back to you asap

**Comment by alxflw** [comment]
@DappCoderr before we review in depth, may I ask for two more things:

First, could we add two more milestones?
1) initial requirements gathering with potential users. deliverable could be: `list of top X features to implement` (milestone #0 - before infra)
2) adoption milestone upon release. deliverable could be: `onboard 10 Flow projects` (milestone #8 - before maintenance)
- Ask them to provide more details on the architectural design (solution has to work with all NFTs)

Second, could you shed more light on the architecture you are envisioning and how projects could use Snap? Are there any requirements or limitations that emerge from the design?

**Comment by DappCoderr** [comment]
Hi @alxflw,

I'm sorry for the delay in the response. As you know Fractionalisation is a bit-long and complex process, so I'm working on the in-depth architecture of snap so that it will be easier to understand and envision. 

Thank you for reaching out and providing us with valuable feedback.

I appreciate your patience!

**Comment by DappCoderr** [comment]
Hey @alxflw,

We have made significant changes, Previously we were focused on the Fractional NFT, but after doing market research, we have changed our architecture and now we are building liquidate market for NFTs which makes NFTs more easily tradable in the market. 

Kindly review the proposal and let us know if you have any queries. Happy to answer them :).

**Comment by alxflw** [comment]
thanks, we'll take a look soon!

**Comment by alxflw** [comment]
@DappCoderr we took a look at the updated proposal and it would be great if you could hop on a call to get more details. mind adding me on Discord to find some time? `alx-flw.find#6198`. Thanks!

**Comment by DappCoderr** [comment]
Sure, that works better @alxflw . 
btw, I have sent you the request on discord and pinged you up?

**Comment by alxflw** [comment]
hey @DappCoderr - thanks again for chatting with me. As mentioned on our call, I don't think this project is a good fit for the developer grants program. I suggest you check out https://flow.com/ecosystemsupport - maybe the other programs might be of relevance.

Thanks again for your submission!

**Comment by DappCoderr** [comment]
Thanks, @alxflw, for the feedback & having a call with me.
I'm going to look around other flow ecosystem programs for the snap. :)
