### ISSUE TITLE
Sample app: DAO on Flow

### ISSUE THREAD

**Issue by alxflw** [onflow/developer-grants#4]
A simple sample app that shows an MVP DAO on Flow

**Comment by dryruner** [comment]
Here we should introduce Dapper [Collectives](https://twitter.com/_Collectives_), Jacob @[Emerald City Dao](https://twitter.com/emerald_dao), and folks that have done tremendous work for DAOs on Flow!

**Comment by AzizGetBlock** [comment]
Hi @dryruner.
Just curious if we can get more data about it because we are confused about 
what kind of problem needs to be solved by this app or if there are any specific preferences? :)

**Comment by alxflw** [comment]
sure thing, find me on discord: `alx-flw.find#6198`

**Comment by AzizGetBlock** [comment]
Have sent a request :)

**Comment by Blockversity** [comment]
Hi, where are you at with this?  Is it still a requirement?  We are working on a project and are about to start the development of a DAO and NFT marketplace on Flow.  If this can apply to this grand, can you please let me know

**Comment by alxflw** [comment]
hey @Blockversity. this is still relevant and nobody applied for this grant yet. would be great to review your application 🙏

**Comment by Blockversity** [comment]
Great, we will review the process and prepare accordingly

thank you for your prompt reply

Line

**Comment by Blockversity** [comment]
Hi Alex,  I see that you have canceled our meeting today.  We are finally ready to submit a proposal, but I had a few questions for you before submitting it.  Is this possible to book another time?   thank you

Line

**Comment by R3V-1** [comment]
Hello Alex. I was trying to locate you on Discord to schedule a call, but I couldn't find you. Not sure if I was looking in the wrong server. I searched for this... alx-flw.find#6198

Anyhow, I would like to submit a proposal for this, but I have a few questions. What's the best way to connect?

Thx!

**Comment by chrisackermann** [comment]
Hi @R3V-1!  Feel free to reach out me on Discord at chrisa#6592, happy to answer your questions.
