### ISSUE TITLE
Guide: Wallets on Flow

### ISSUE THREAD

**Issue by ZERO-PHC** [onflow/developer-grants#41]
# Guide: Wallets on Flow

# Grant category

Educational material

# Description

Documentation with details about the wallets that are available on the Flow ecosystem.

## Problem statement

Currently, it is possible to find some information about the existing wallets in the ecosystem. Still, it is difficult to understand the main differences, advantages, or even disadvantages between the options, especially if the developers or users have to enter the website of each wallet to look for its particularities.

In addition, with the arrival of new wallets or updates and new features of existing ones, the scenario is constantly evolving, and users and devs need a lot of time to keep up to date.

## Proposed solution

Create a website where the main objective will be:

Learn how to choose the right wallet. We will outline the main features of each wallet and help the user make a more educated decision based on their needs.

Show the wallets available in the ecosystem.

Facilitate the choice of the wallet that the user or developer needs. We will compare their differences so that the user doesn't have to spend hours researching.

To achieve these goals, our professional writers will create a series of articles on every concept the developers and users need to understand about the Flow Wallets.

We made an interactive prototype where you guys can navigate and see our vision for the website.
[Figma Design](https://www.figma.com/proto/14WbYY1G9eniMnwbbtv3AD/Flow-Wallets?node-id=33%3A774&scaling=scale-down&page-id=0%3A1&starting-point-node-id=2%3A2)

## Qualifications

Our lead writer Daniel has extensive experience with web3 copywriting; here are some of his works and his medium:

https://docs.nested.fi/
https://clubswan.com/blog/
https://danielnyairo.medium.com/

Daniel´s skills will help us with all the subjects we need to cover.

We have been part of the Flow ecosystem /  Emerald City for a while.
Our team has been creating and developing Apps, Dapps, Websites, and other services with a focus on user experience.
We have experience with creative 3D development, and with these skills, we can improve the UX of the website.

Our Contributions:
Emerald Id ( Front-end ). https://id.ecdao.org/
Emerald Gateway ( Front-end ). https://github.com/emerald-dao/emerald-gateway
Emerald Bot ( Front-end ). <https://bot.ecdao.org/>
Token Minter ( Guide ). https://token-minter-sand.vercel.app/guide/en/welcome

## Impact

This website will allow users to find the most suitable wallets for them; they will be able to compare the different products and better understand what they offer.
The user's journey to discover the available wallets and recognize their main differences and particularities will be much easier.

# Milestones and funding

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Final UI/UX design  | Interactive Prototype |  2 weeks  | - | TBD  |
| 2 - Development  | Functional website | 4 weeks | (Need of a professional writers with Web3 knowledge) | TBD |
| 3 - Final tests and Deployment  | Production ready website | 1 week  | - | TBD |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Felipe Ribeiro | Project Co-Lead | Blockchain and Full-Stack Developer | frlabsmd@gmail.com |
| Alan Dega | Project Co-Lead | Designer and Full-Stack Developer | zero@cyphers.gg |
| Daniel (Ong'era) Nyairo | Professional Writer |  [Web3 Writer](https://danielnyairo.medium.com/)  | danielnyairo@gmail.com 

# Milestone completion
- [x] Final UI/UX design (ongoing)
- [x] Development
- [ ] Final tests and Deployment

**Comment by alxflw** [comment]
thanks for the proposal @ZERO-PHC! 

We reviewed your proposal and have two follow ups:

1) We noticed you have to writer on your team and the content is not part of the milestones. We believe the content is a critical part of this grant. Do you think you could recruit a professional writer to help with the content? If so, please update the proposal and add it to the milestones
2) For inspiration, here is another wallet overview that we like: https://www.cryptocompare.com/wallets/#/popular

**Comment by ZERO-PHC** [comment]
Hi Alex!
Thanks for the response.

1.  We already updated the proposal and we already recruited a professional writer that we know from Emerald City (She wrote some guides for the Token Minter Bounty).
2. Thanks. We are going to use that reference in the design.

Would you like us to translate the guides into Spanish and Portuguese?

**Comment by alxflw** [comment]
Thanks! I'll follow up with you via email to discuss TBD items. WRT translations, let's hold off on these for now. we could add them later as well as a follow up

**Comment by ZERO-PHC** [comment]
Alright, thanks!

**Comment by alxflw** [comment]
hey @ZERO-PHC! thanks for updating the proposal. this is looking great. this grant was accepted and I'll follow up with you directly about next steps! 🚀

**Comment by regresamosacasa** [comment]
@alxflw Hi Alex, This is Maritza. I'm one of the writers for this proposal. I was recruited by Alan, but haven't heard anything from him since July 5. He stopped responding and communicating out of the blue since then. What's going on with our project?

**Comment by ZERO-PHC** [comment]
I got back in communication with Maritza.

**Comment by FelipeRibeiroLabs** [comment]
Flow wallets website it's live! All community can access it through this [link](https://flowallets.com)

Want to give suggestions, please fulfill this [survey](https://forms.gle/iByYVP6NbCYAJMc87)! 

Are you a wallet provider? Let's add your wallet to the website, do this through this [form](https://docs.google.com/forms/d/e/1FAIpQLSfH8T6BwqJD4uF0IZVgbM3gcQIMK7pqx9ITdZM2jBQAumgnKg/viewform)!

**Comment by chrisackermann** [comment]
This grant is complete.
