### ISSUE TITLE
Take easy card payment for NFTs

### ISSUE THREAD

**Issue by wfalcon0x** [onflow/developer-grants#42]
# Walletless

# Grant category
Please select one or more of:
- [ ] Open source maintenance
- [x] Developer tools / services
- [ ] Educational material

# Description
Buy NFTs directly with card 

## Problem statement
- Selling NFTs to non-crypto natives is harder than it should be – you first buy crypto, then buy the NFT, paying twice the fees and go through a lengthier process 
- Accepting direct card payments requires a significant amount of dev work

### Target audience
- NFT merchants on FLOW wanting a ‘Pay with Card’ checkout option

### Evidence for the need
- Direct card-to-NFT purchases boost sales by 300% (MoonPay survey)
- Discussions with other founders about their experiences selling NFTs
- Survey friends and family about their experiences buying NFTs

## Proposed solution
- A ‘Pay with Card’ button to checkout NFTs with cards
- Checkout solution can be added to a merchant website through a code snippet
- Buyers won’t need to already have a crypto wallet to buy NFTs
- Merchant can still offer 'Connect Wallet' button for checkout with crypto wallets like Dapper, Blocto, Lilico

## Impact
- Higher sales conversions for FLOW projects

In what ways does this benefit the broader Flow developer ecosystem?
- Save months of dev work 

# Milestones and funding

> Note: You can leave the USD proposal empty / "TBD". Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Wireframes & Architecture   | - Wireframes of the checkout process<br> - Wireframes of the wallet UI<br> - High-level architecture diagrams | 1 week  | - |            |
| 2 - FCL compatible wallet | - FCL endpoint APIs<br> - Magic link authentication<br> -  Pluggable private key management solution   | 4 weeks | 3rd party integrations |  |
| 3 - Card Payments | -  Fiat payment for NFT purchases with USDC<br> - Send an email to the user after the purchase with receipt   | 2 weeks | |  |
| 4 - Wallet UI | - Show minimal NFT gallery for purchased NFTs (compatible with FLOW’s metadata standard)<br> - Transfer NFTs out of wallet   | 2 weeks |  |  |
| 5 - Security | - Secure private key management solution utilising HSM<br> - Adopt best practices to prevent fraudulent activity   | 3 weeks | 3rd party integrations  |  |
| 6 - Merchant checkout solution | - The UI for the merchant setting up the NFT checkout<br> - The NFT checkout page<br> - Checkout APIs   | 3 weeks | 3rd party integrations  |  |
| 7 - Testing and rolling to live environment| - Testing and bug fixing<br> - Rolling out the solution to live environment / Mainnet   | 2 weeks |  |  |
| 8 - Adoption | - 3 merchants use Walletless checkout solution<br> - Gather feedback   | 1 week |  |  |
| 9 - SDK for Devs | - SDK to add button to app & customise checkout experience<br> - SDK documentation   | 4 weeks |  |  |
| 10 - Maintenance | Supporting merchants, resolving issues   | 4 months |  |  |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Daniel N| Product | Oxford University Engineering scholar, Ex-BAML, experience in tech and finance | daniel@eucleides.com |
| Akos E| Architect and Full Stack | Engineer graduating in Germany, years in software development, technical leadership and architecture | akos@eucleides.com |
| Mislav K | Front-end Engineer | Front-end experience for many start-ups, including web3 |  |
| Paul F| Business Analyst | Accountant, ex-Deloitte, c-suite experience, background in finance and healthcare |  |

**Comment by alxflw** [comment]
Thanks again for sharing more details with us! We'd be in favor of #48
