### ISSUE TITLE
Marz VST (Virtual Instrument)

### ISSUE THREAD

**Issue by adamsawake** [onflow/developer-grants#44]
# <Project name>
Marz VST 
# Grant category
Music, entertainment
Please select one or more of:

- [ x] Open source maintenance
- [x ] Developer tools / services
- [x] Educational material

# Description

Recently developed a standalone virtual instrument. 

## Problem statement

- Target audience Music producers and art collectors 
- Evidence for the need
 Utility for musicians 

## Proposed solution
Standalone Virtual instrument 
## Impact
New Utility 
- In what ways does this benefit the broader Flow developer ecosystem?
Brings new users to untapped markets via utility promotion 

# Milestones and funding
*Bootstrapped

> Note: You can leave the USD proposal empty / "TBD". Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone $1,000+ in sales with 14 days of MVP1 release, no bugs reported  | Deliverables  Secondary VST  | Timeline 2 weeks | Risks       funding            | USD proposal $1M|
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - MVP   | Smart Contract | 2 weeks  | - | 1000           |
| X - Adoption   | 5 team using this project | 4 weeks  | - | 1000           |
| X - Maintenance   | Resolving issuing and fixing bugs | 3 months  | - | 1000           |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Alex | Full-Stack Engineer | ... | alex@onflow.org |

**Comment by alxflw** [comment]
@adamsawake thanks for submitting a developer grant application but this proposal is not targeting developers.

I'm closing this issue because it is not applicable for this program.
