### ISSUE TITLE
Learning Cadence - Quick and Easy

### ISSUE THREAD

**Issue by jasonbakthakumar** [onflow/developer-grants#49]
# Learning Cadence - Quick and Easy

# Grant category

Please select one or more of:

- [ ] Open source maintenance
- [X] Developer tools / services
- [X] Educational material

# Description

## Problem statement
To establish a basic understanding of Cadence (especially the resource-oriented part) within 2 minutes with simple illustrations and easy to understand analogies catering to anyone. 

While engineers / developers who are intentional about learning Cadence can benefit from  video based courses that span over multiple hours or reading technical articles. This mobile-first website aims to be a quick “start here” guide for Cadence that helps understand the concepts involved in Cadence using simple and fun illustrations.

- Target audience
    - This is intended for people of all disciplines - entrepreneurs, engineers (all levels), product owners or anyone who wants to hit the ground running with Cadence.
    - This is also a great resource for beginner developers to understand the concepts of resource - oriented programming without having much pre-requisite knowledge
    - In essence - given the concepts are going to be explained in non-technical terms using simple illustrations - anyone with any background can understand the concepts being explained

- Evidence for the need
    - The popular series called “[Programming Language X] in 100 seconds” on Youtube by Fireship is consistently viewed more than 200,000 times and really helps get the essence of any programming language in just 100 seconds. This helps developers establish a base line understanding of the programming language while just casually browsing the web rather than intentionally burying their head deep in documentation.
    - The book called “Gently Down The Stream” by Mitch Seymour - gives a gentle introduction into the world of event streaming and Kafka by using easy to understand illustrations and non-technical terms that anyone from any background can understand the concepts behind event streaming EASILY and rather QUICKLY. The book is highly rated on Amazon and the website version of the book `[gentlydownthe.stream]`(https://gentlydownthe.stream) has been visited more than [[38K times in the last month alone](https://www.similarweb.com/website/gentlydownthe.stream/#ranking)](https://www.similarweb.com/website/gentlydownthe.stream/#ranking) (May 2022) - and is regarded one the the best starting points to understand event-streaming
    - This one is from a macro point of view but way more people are inclined to watch / engage with short-form content when  surfing the web as evidenced by [[2022 Video in Business Benchmark Report by Vidyard](https://www.vidyard.com/business-video-benchmarks/)](https://www.vidyard.com/business-video-benchmarks/)
  
In a similar fashion having an EASY to understand solution that is QUICK to go through and explains the underlying concepts of Cadence would boost the engagement rate of developers and entrepreneurs alike into the Flow Ecosystem. 

## Proposed solution

To create a website that explains resource-oriented programming in Cadence using simple illustrations and non-technical terminology. The content will be delivered in a simple wizard type user flow encasing simple illustrations to explain concepts. This website will have three different learning paths.

- The 2-minute version
    - Explains what are “Resources” in Cadence using simple illustrations and analogies.
    - Explains how “Resources” are perceived and handled in Cadence with illustrations.
    - The 2-minute version is primarily intended on explaining resources in Cadence as that sits at the core of Cadence while the rest of the understanding can be brought in from other programming languages / paradigms.
    
- The 5-minute version
    - Continues on from the 2-minute version (contains everything in the two minute version )- At the end of the 2-minute version we will provide a prompt asking if the user wants to continue on.
    - Talks about composite types in Cadence and the difference between them and resources
    
- The 10 minute version
    - Continues on from the 5-minute version (contains everything in the five minute version )- At the end of the 5-minute version we will provide a prompt asking if the user wants to continue on to the 10-minute version.
    - Talks about functions in Cadence using simple illustrations
    - Talks about Control Flow in Cadence using simple illustrations
    
    All “paths” will provide links to relevant documentation and other content if the user wants to dive a bit deeper.

## Impact

- In what ways does this benefit the broader Flow developer ecosystem?
    - This is great “start here” guide to building on Flow. With simple illustrations we establish a baseline understanding of Cadence.
    - People from all disciplines - product owners, entrepreneurs, developers (of all levels) can establish a baseline understanding of how Cadence works - boosting engagement rate across the ecosystem. Boosting the engagement rate as in Developers can quickly get an idea of how their solution might look like in Cadence. Non-technical entrepreneurs and product owners can also be on the “same-page” which makes it easier to have high level architecture conversations
    - At the end of the project we will share metrics report of how the website was consumed by users. This will come from the data captured through different events as users navigate the platform and also short surveys that will be added at the end of each “path”.

# Milestones and funding

> Note: You can leave the USD proposal empty / "TBD". Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | USD proposal |
| --------- | -------------- | -------- | -------------- |
| The 2-minute version   | The website live in production with the 2-minute version / fun illustrations and easy to understand analogies | 4 weeks from approval | 5500           |
| The 5-minute version    | Adding the 5-minute version on to the website | 4 weeks from the previous milestone | 5500           |
| The 10-minute version   | Building on the 5-minute version - the 10-minute version will go live on the website | 4 weeks from the previous milestone  | 5500       |
| 50,000 visitors who have completed the [any]-minute version   | Providing a metric report on how the website is being used - with the help of third party analytics service like Google Analytics etc | N/A  | 2500           |
| 100,000 unique visitors who have completed the [any]-minute version   | Provide a metric report how the website is being used - with the help of third party analytics service like Google Analytics etc | N/A  | 2500           |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Jason B | Engineer First; Architect Second | Strong believer of “beautiful” UX over everything. I’m a full-stack engineer with a focus on front-end and Have worked on projects with nationwide-scale in New Zealand and considerable impact. I’ve worked both with government project like the NZ Covid Tracer app and also projects in the private sector. I also have a Masters in Information Technology from the University of Auckland and have been writing code in a professional capacity for around 6 years now - worked in multiple large-scale web2 projects and have mentored many younger students in code through Girl Guiding New Zealand.  | Email: jasonbakthakumar@live.com  Discord: radjayz#7047 |

Note: I will also hire an illustrator in a free-lancing capacity to polish up my drawings if and when needed

**Comment by alxflw** [comment]
thanks for the submission, @jasonbakthakumar! we'll review this and get back to you soon

**Comment by jasonbakthakumar** [comment]
sure @alxflw let me know if you have any questions in the meantime.

**Comment by alxflw** [comment]
Hi @jasonbakthakumar we reviewed your proposal in detail and decided to pass because it is unclear if the impact on the developer ecosystem will be high enough.

Thanks for taking the time to submit your proposal and feel free to reach me directly on Discord in case you have further questions: `alx-flw.find#6198`.

**Comment by jasonbakthakumar** [comment]
Thanks for getting back @alxflw
