### ISSUE TITLE
Sample app: NFT integration

### ISSUE THREAD

**Issue by alxflw** [onflow/developer-grants#5]
A sample app that checks for NFT ownership and changes behavior based on that

**Comment by ZERO-PHC** [comment]
Hi Alex.
we need more data about it because we are confused
what kind of problem do you want to solve with this app?

**Comment by alxflw** [comment]
hey @ZERO-PHC, great question! this needs more clarification. The idea is the following:
- there is an existing NFT in the market that users can acquire
- there is a Flow dapp that users can log in to
- if the logged in user owns an NFT that is supported, the app enables specific features (this functionality is where we wanted a sample)

The main problem we want to solve for developers is: how to provide utility for NFT ownership. One real world implementation of this concept is [Web3Wear](https://web3wear.com/home). If you own one of the NFTs, you can order swag. Another example is mentioned in the [Next Steps section of the Kitty Items tutorial](https://docs.onflow.org/kitty-items/next-steps/#add-utility)

Does that input help? I'm happy to jam on this and/or write up more details.

**Comment by alee-blcksync** [comment]
@alxflw I haven't noticed any updates so far, but we have worked on a project last month for a hackathon, and I think there may be some opportunities here to expand the eco-system to flow as one of our roadmap. Here's our [pitch deck](https://drive.google.com/file/d/1jCxOlQqz8lkvYr1YewBIC5fIkTc3qKsB/view?usp=sharing) and video [demo](https://www.youtube.com/watch?v=7zFRepPBUGM). We can address the followings:

- proving NFT ownership which is our core feature aka `Profile` in our context.
- Profile expands to trust and other potential use cases as mentioned in our demo.
- live feed and monitoring on NFT transfer and activities

We will love to follow up and get your input. I know this is on the wishlist, and we are new to FLOW and looking forward to join the journey. We wonder if this could be converted to a RFP and Grant application moving forward. Appreciate your input and feedback. Thanks.
