### ISSUE TITLE
useFlow - a react hooks library for DApp development on Flow

### ISSUE THREAD

**Issue by maggo** [onflow/developer-grants#50]
# `useFlow` - a react hooks library for DApp development on Flow

# Grant category
Open source maintenance

# Description

`useFlow` is a library of react hooks enabling developers to build DApps on Flow quickly and efficiently. 
The libary provides hook abstractions for all FCL functionality, like wallet connection, executing scripts and transactions and signing messages, all while featuring built in caching, request deduplication and loading states powered by [react-query](https://github.com/TanStack/query).

`useFlow` is based on experience from developing [Chainmonsters](https://chainmonsters.com) and other Flow DApps and inspired by [wagmi](https://github.com/tmm/wagmi), a collection of react hooks for Ethereum DApp development.

I started setting up the library and would like to use the developer grant to be able to focus on making it feature complete and bring it to a release state :) https://github.com/maggo/use-flow

## Problem statement

- React is the [most popular frontend framework](https://survey.stackoverflow.co/2022/#section-most-popular-technologies-web-frameworks-and-technologies) but there's no "react native" way to integrate Flow interactions
- While building Chainmonsters and other Flow DApps, I caught myself writing the same code again and again (boilerplate to set up FCL  and use it with react-query) and I'm sure that other frontend developers are doing the exact same

## Proposed solution

- Implement a library that provides a familiar interface (react hooks) for FCL interaction

## Impact

- Developers will be able to accomplish Flow blockchain interaction in their apps using a familiar concept, without having to write boilerplate code
- Developers get automatic best UX and performance improvements (loading states, caching, request deduplication) thanks to react-query integration
- Examples will allow for quick MVP development

# Milestones and funding

| Milestone                                       | Deliverables                        | Timeline | Risks                   | USD proposal |
| ----------------------------------------------- | ----------------------------------- | -------- | ----------------------- | ------------ |
| 1 - First stable release                        | Feature parity with FCL: Hooks for all API functions as [specified in the docs](https://docs.onflow.org/fcl/reference/api), including a rich test suite | 6 weeks | Timeframe | TBD |
| 2 - Documentation & Examples                    | Docs website explaining the hooks and their parameters with usage examples | 5 weeks | - | TBD |
| 3 - Integrate useFlow in Chainmonsters website  | Update [chainmonsters.com](https://chainmonsters.com) codebase to use useFlow for all chain interaction; "dogfooding" to make sure that the libary is production ready | 3 weeks | - | TBD |
| 4 - Adoption                                    | Get 5+ DApps to use useFlow, by providing consultation and support | ??? | - | TBD |
| 5 - Maintenance                                    | Keep library up-to-date with latest FCL updates, bugfixes and community support | 6 months | - | TBD |

# Team

| Name  | Role             | Bio         | Contact      |
| ----  | ---------------- | ----------- | ------------ |
| Marco | Main Contributor | Freelance full-stack developer with over 10y experience, 2y focusing on Flow & ETH. <br>Web Developer @ [Chainmonsters](https://chainmonsters.com), focusing on website, marketplace and onchain interactions | me@mar.co.de<br> maggo#1337 |

# Milestone completion
- [ ] First stable release
- [ ] Documentation & Examples
- [ ] Integrate useFlow in Chainmonsters website
- [ ] Adoption
- [ ] Maintenance

**Comment by alxflw** [comment]
thanks for the submission @maggo! We took a look and wanted to see if you would be open to updating your milestones as such:

- Add an adoption milestone at the end (eg get 5+ projects to use useFlow)

- Reduce the scope to fit a new project seeking adoption. So: 1) reduce the testing scope, 2) remove the maintenance milestone, and 3) remove the sample app milestone (covered by docs and basic examples)

**Comment by maggo** [comment]
Hi @alxflw thank you for your feedback! I've updated the milestones as following:

* Combined first release & test suite milestones
* Combined documentation & basic examples milestones
* Removed example dapp and maintenance milestones
* Added adoption (5+ users) milestone

| Milestone                                       | Deliverables                        | Timeline | Risks                   | USD proposal |
| ----------------------------------------------- | ----------------------------------- | -------- | ----------------------- | ------------ |
| 1 - First stable release                        | Feature parity with FCL: Hooks for all API functions as [specified in the docs](https://docs.onflow.org/fcl/reference/api), including a rich test suite | 6 weeks | Timeframe | TBD |
| 2 - Documentation & Examples                    | Docs website explaining the hooks and their parameters with usage examples | 5 weeks | - | TBD |
| 3 - Integrate useFlow in Chainmonsters website  | Update [chainmonsters.com](https://chainmonsters.com) codebase to use useFlow for all chain interaction; "dogfooding" to make sure that the libary is production ready | 3 weeks | - | TBD |
| 4 - Adoption                                    | Get 5+ DApps to use useFlow, by providing consultation and support | ??? | - | TBD |

Please let me know if you had other changes in mind that I might have missed :)

**Comment by alxflw** [comment]
wonderful, thanks for updating! we'll review and get back soon

**Comment by alxflw** [comment]
hey @maggo, we'd like to accept this proposal if you are willing to add one more milestone at the end for 6 months maintenance (to keep up with latest NPM version of FCL). Please confirm and we can discuss the TBD portion of your project via email.

**Comment by alxflw** [comment]
great, I sent you an email to discuss the USD proposal / TBD.

**Comment by alxflw** [comment]
this application has been approved 🚀

**Comment by maggo** [comment]
Thank you @alxflw and team, excited to work on awesome Flow developer tooling 🚀

**Comment by Aliserag** [comment]
Given the time since this has been submitted I'm closing this down, please reach out to me if you'd like to share what you're working on now and explore potential opportunities [ali.serag@flowfoundation.org](mailto:ali.serag@flowfoundation.org).
