### ISSUE TITLE
NFTikets

### ISSUE THREAD

**Issue by Jimmygodwin** [onflow/developer-grants#51]
# <NFTikets>
    

    

![](https://i.imgur.com/DuWPd9o.png)

# Staging Link
https://nftikets-bromagift.vercel.app/

# Grant category

Please select one or more of the:

- [ ] Open source maintenance
- [#] Developer tools / services
- [ ] Educational material

# Description
    
Nftikets is an event ticket minting platform that allows users to create, purchase and mint tickets for any of their events as NFTs. Using our Widgets, API, and SDKs, event hosts will be able to integrate this feature on their websites with few lines of code.

## Problem Statement
1. Tickets to offline events can be duplicated without authorization
2. Tickets to online events are difficult to access by people from other locations due to barriers in payments
3. Event organizers constantly need to redirect users to the purchase page of the platform where their events are hosted.
4. Verifying tickets online is hard for platforms like Eventbrite and takes a lot of time per user.

## Target audience
1. Event organizers looking to sell tickets to a global audience without avoiding payment portal issues.

## Proposed solution
1. Low cost of producing tickets: you can mint 100 tickets with low gas fees
2. Borderless way to purchase tickets
3. Zero paper ticketing (very ecological)
4. Easy integration on event owner website, with very few lines of code.
5. Tickets can be purchased on telegram by your community without even visiting the website (Ease)
6. Swift ticket verification API: The event owner can verify a ticket by inputting the wallet address only

## Impact
1. This will help reduce paper ticketing for offline events.
2. Enable borderless events from anywhere in the world
3. Improve event ticketing using NFTs
4. Store individual tickets as NFTs

- In what ways does this benefit the broader Flow developer ecosystem?
1. Increase use case for the ecosystem 
2. More users interating with the flow blockchain

# Milestones and funding

> Note: You can leave the USD proposal empty / "TBD". Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - MVP   | Functional website that allows users to mint event ticket and smart contract  | 3 weeks  | - | 8000           |
| 2- BETA   | Developer Portal with Docs for integrating our API's | 8 weeks  | - | 15750           |
| 3. Launch   | 100 events | 3 weeks  | - | 4600           |
| 4. Maintenance   | Resolving issuing and fixing bugs | 2 months  | - | 12600           |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Godwin Jimmy | Product Mangager  |  As a Product Manager, I have managed the development and deployment of various blockchain applications some of which are: Plutoswap (DEX), Dantown (https://www.dantownms.com/), Social Stack (https://www.socialstack.co), Cyrus NFT (https://www.cyruspahlavi.com/), Zoo NFT  (https://zoolabs.io/). | jimmygodwin371@gmail.com | 
  David Esser  | Advisor(Product) |  Chief Product Officer at Minterestt, Serial entrepreneur building blockchain, defi, internet, mobile, and IoT applications Specialties: -- Product Management for enterprise blockchain, internet, and mobile applications.-- Strategy and implementation for complex technology products.-- Building & leading extremely capable teams of technologists to deliver amazing quality and productivity results | Desser@tradewindsystems.com |
| Victor Ogbonna | Lead Frontend |  A frontend engineer with 3 years experience in javascript, react, next, web3.js and threejs. | victorgbonna@gmail.com
| Ayolehi Lurogho | UI/UX Designer |  UI/UX design with 4 years of experience in design and have worked on a series of projects cutting across payments gateways and Defi products. | ayoleyilurogho@gmail.com
 |Gift Elenwo | intern Frontend |  A computer science graduate with 6 months of experience in javascript and react |elenwogift2@gmail.com
| Juliet Babatunde | Content Developer |  Content Developer and Copyright with 2 years experience. | babatundejuliet@gmail.com

**Comment by alxflw** [comment]
thanks for the submission @Jimmygodwin - how would this compare to https://floats.city ?

**Comment by Jimmygodwin** [comment]
Hello Alex

For Float, event owners have the option of creating their events and must force users back to float to claim this event ticket, However, for Nftikets we give the event owner the ability to create this event on our platform after which they make these tickets available for their users on telegram, Twitter and discord. With our code snippets, anyone can easily create and share an event without having a vest knowledge of web3 and without having to educate their buyers on how to claim tickets

Nftikets is built on a series of users behavior research and I can tell you for a fact their complexity will lead to a high bounce rate, unlike the other platforms Nftikets will give users the web 2 feeling in a web3 environment, which means they may not even have to understand web3 to use our service.

For the event owners, our SDKs/API gives them the luxury of integrating their NFT's on their own websites or social media making it a worthwhile user experience for their customers.

**Comment by alxflw** [comment]
got it! and a few more questions that came up:

- Can you provide a clearer definition of your target audience (who are the organizer, ticket holders) and use cases you want to focus on solving?
- What types of ticketing would be supported  (eg membership, single use, etc)
- What are the properties each ticket would have (eg metadata, state)?

**Comment by Jimmygodwin** [comment]
Okay, 

1. Currently our research and build is targeted at servicing organizers of tech events globally (online and offline events), here is a brief on our user profile

**Targeted User**
- User Type:  Event Host/Organizers
- Event Type: Tech Event 
- Event Specifics: Web 2/web 3 events
- Event Channel: Online/Offline 
example: South South Blockchain Conference ( [https://ssblockchaincon.com/](https://ssblockchaincon.com/) ) we are already in talks with this conference and they will be glad to use our ticketing system.

**Why Target this audience** 
1. it is niche market 
2. It is Easy to understand and adopt
3. Value from the product (Financially: it cost about $250 - $350 to print 100 copies of colored tickets ,and Ecological)
4. Longterm value for event tickets 
5. Maintain Attendees attention beyond event (Membership tickets)

**Use Case**
1. Event Ticketing 

**Types of Tickets we support**
1. Single 
2. membership
3. Partnership (Donations)

**Properties/Meta Data**

1. Single ticket 
* Event name 
* Host name  
* Event description
* Ticket number 
* image/pdf

An Example
{
    "title": "Single Ticket Metadata",
    "type": "object",
    "properties": {
        "event name": {
            "type": "string",
            "description": "Nftikets Global NFT events"
        },
       "host name": {
            "type": "string",
            "description": "Nftikets Global NFT events"
        },
        "event description": {
            "type": "string",
            "description": "Welcome to the NFTikets global Nfts event"
        },
        "ticket number": {
            "type": "int",
            "description": "3092039"
        },
        "image": {
            "type": "string",
            "description": "image URL."
        }
    }
}


2. Membership ticket 
* Event name 
* Host name  
* Event description
* Ticket type (membership)
* Ticket number 
* image/pdf

An Example
{
    "title": "Single Ticket Metadata",
    "type": "object",
    "properties": {
        "event name": {
            "type": "string",
            "description": "Nftikets Global NFT events"
        },
       "host name": {
            "type": "string",
            "description": "Nftikets Global NFT events"
        },
        "event description": {
            "type": "string",
            "description": "Welcome to the NFTikets global Nfts event"
        },
        "ticket type": {
            "type": "string",
            "description": "Membership"
        },
        "ticket number": {
            "type": "int",
            "description": "3092039"
        },
        "image": {
            "type": "string",
            "description": "image URL."
        }
    }
}

3. Partnership tickets(Donations)
* Event name 
* Host name  
* Event description
* Ticket type (membership)
* Ticket number 
* image/pdf

An Example
{
    "title": "Single Ticket Metadata",
    "type": "object",
    "properties": {
        "event name": {
            "type": "string",
            "description": "Nftikets Global NFT events"
        },
       "host name": {
            "type": "string",
            "description": "Nftikets Global NFT events"
        },
        "event description": {
            "type": "string",
            "description": "Welcome to the NFTikets global Nfts event"
        },
        "ticket type": {
            "type": "string",
            "description": "Donation"
        },
        "ticket number": {
            "type": "int",
            "description": "3092039"
        },
        "image": {
            "type": "string",
            "description": "image URL."
        }
    }
}

**Comment by alxflw** [comment]
thanks @Jimmygodwin 

cc @albeethekid @srinjoyc

**Comment by alxflw** [comment]
hey @Jimmygodwin, we're excited to let you know that we've accepted your grant application! 🙌 

I'll follow up with you via email with next steps.

**Comment by Jimmygodwin** [comment]
Hello @alxflw that is exciting news! I have received the mail I will follow up on it immediately.
