### ISSUE TITLE
Flow.Study-Cadence code search engine

### ISSUE THREAD

**Issue by maris205** [onflow/developer-grants#52]
Flow.Study, Cadence code search engine,  http://flow.study/

# Grant category

- [x]  Developer tools / services

# Description

## Problem statement

There are 1000+ contracts in Flow,  Ethereum has 10,000,000.

Show the excellent cadence codes to developers is a good way to promote the development ecology.

We need a good cadence search engine.

## Proposed solution

Our solution is cadence code search engine .

We design our solution based on ElasticSearch. 

The solution contains 3 parts:

1 Basic cadence code search engine. The developers could search contracts, interface, function, resources, etc. For example, you could user the query "the resource of nba top shot".

![code search engine](https://lin-speed-test.oss-us-west-1.aliyuncs.com/nft/fig1.png)

2 cadence code visualization. How to show the search result of contracts?  In addition to code, related scripts, transactions, code structure, similar codes, online call relation are also displayed

![code search engine](https://lin-speed-test.oss-us-west-1.aliyuncs.com/nft/fig2.png)

3 Connect to playground.  Yes, you could directly run code search result in playground. We prepare the contracts and related transaction, scripts.
 

Main work

1 cadence code Spider. We will get cadence codes from flow chain, github, etc.

2 cadence code search engine.  We use ElasticSearch to build the search system. The code search results will be ranked by  pagerank algorithm.

3 A little NLP(Natural Language Processing) for cadence language.  We need parse the cadence into functions, resources, etc.   We need find the similar codes  and  auto generate scripts. So some AI technology is needed. 

## Impact

Which developer can reject a cadence search engine like google : ) 

# Milestones and funding

Overall duration to deliver future milestones: ~6 months. Total USD requested: 45,000  + 18,000(6 month maintenance)

| Milestone | Deliverables   | Timeline | Risks                   |USD requested |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Flow Cadence spider/codebase   | code databases | 1 month  | - | 5,000           |
| 2 - Flow Cadence search engine   | code searching platform|  1 month  | - |10,000           |
| 3 - Flow playground integration   |  playground-based online learning platform integrated | 1 month  | - | 10,000           |
| 4 - Cadence code parser   | Static Cadence code parser/python written | 1 month   | - | 1,0000           |
| 5 -  Basic NLP(Natural Language Processing) for cadence   |  NLP function for cadence, support similar code recommend, query parser, etc /python written | 1 month  | - | 1,0000           |
| 6 - system maintenance   | web, data system, maintenance| 6 month  | - | 18,000           |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
|mariswang | AI Engineer | 10+ years AI research experience, head of several artificial intelligence systems of Tencent,Sogou,etc| @maris205 |
| HoppingChar | Full-Stack Engineer | 5 years experience in blockchain research, responsible for IPFs Minerva and other blockchain products| @HoppingChar|
| xingqi | Full-Stack Engineer | Leader of several big data projects, several years of NLP research experience, proficient in Code AI algorithms | @harboart |

**Comment by maris205** [comment]
I revise the former Cadence Code Intelligence to  simple Cadence search engine.
Code AI seems still too difficult in current period : )
@alxflw

**Comment by alxflw** [comment]
thanks! we'd love to hear about about your plans, esp as it relates to the playground. I'll send you an email so we can schedule something - what is your email @maris205 ?

**Comment by maris205** [comment]
> thanks! we'd love to hear about about your plans, esp as it relates to the playground. I'll send you an email so we can schedule something - what is your email @maris205 ?

my email is  58100533@qq.com

**Comment by maris205** [comment]
@alxflw

**Comment by alxflw** [comment]
just reached out via email!

**Comment by alxflw** [comment]
hey @maris205, we're excited to let you know that we're accepting your grant application! 🚀  I'll follow up via email with next steps. 

also, @muttoni it would be awesome if you could share some feedback/suggestions for this project

**Comment by Aliserag** [comment]
We appreciate your proposal and taking the time to fill it out. Given the time since this has been submitted I'm closing this down, please reach out to me if you'd like to share what you're working on now and explore potential opportunities [ali.serag@flowfoundation.org](mailto:ali.serag@flowfoundation.org).
