### ISSUE TITLE
Flow promotion and developer training program

### ISSUE THREAD

**Issue by dapeng1215** [onflow/developer-grants#54]
# <Project name>
Flow promotion and developer training program
# Grant category

Please select one or more of:

- [ ] Open source maintenance
- [ ✓] Developer tools / services
- [✓ ] Educational material

# Description

## Problem statement
In the Asia-Pacific Chinese developer community, Flow has a low brand awareness, low developer attention, and few developers proficient in cadence language. The number of Web3 projects developed based on Flow is small.
Currently, entrepreneurship based on Web3 is very popular in the Asian-Pacific Chinese community. A large number of teams, computer majors in colleges, and Web2 developers are exploring Web3 entrepreneurship, but there is a lack of Web3 courses suitable for Chinese developers.
Through Google Trends comparison and research on enterprises and some Web2 practitioners, we found that the most used front-end framework is vue in the Chinese community. We believe that Flow is suitable for Web3 entrepreneurship in the Asia-Pacific Chinese community. But this is not a familiar front-end framework, and it will also lead to high learning costs and reduced development efficiency.

## Proposed solution
1.	We hope to develop a cadence development course which is suitable for the Asian-Pacific Chinese community and college graduates.
2.	Complete the construction of a cadence+vue3+elementui scaffolding, and complete an nft casting and trading platform based on the scaffolding for course case explanation.
3.	Cadence+vue3+elementui can enrich the scaffolding case library of the cadence community and reduce the learning cost of Chinese community developers and students. Elementui is based on the vue component library, which greatly improves the development efficiency of dapp.
4.	Promote this course to college developers and Web2 developers by our "Web3 Accelerator", "2022 China University Web3 Acceleration Camp", "China Entrepreneurs Conference".
5.	Promote this course to Web2 developers in conjunction with the Chinese developer community (CSDN,  SegmentFault) and developer education platforms (Geek Time, Tencent Classroom, Netease Classroom), YouTube, bilibili, Baidu Video, etc.

**Course Details**
course1：Learn about Flow and Cadence.
1.	Learn about Block-chain and Its Basic Vocabulary
2.	Learn about Flow
3.	Learn about Cadence
4.	Install the Flow CLI
5.	Learn about Playground
6.	Complete the First Smart Contract Development: Hello Cadence
7.	What Web2.0 Practitioners Need to Prepare for Learning Web3.0
 
course2：Cadence Basic Grammar
1.	Values and Types
2.	Struct & Resource
3.	Control Flow
4.	Function
 
course3: Engineering Development
1.	Local environment build, Environment configuration and Simulator
2.	Accounts
3.	Transactions
4.	Events
5.	Interface
6.	Capability-based Access Control
7.	Contract Upgrade Specifications and Standards
 
course4：FCL
1. Learn about FCL
2. FCL Integrated
3. The Use of FCL Common Functions
4. Testnet Deployment
 
course5： Practical Operation 1
1.	Teach You to Develop DAPP quickly
2.	Introduction to the Engineering Structure
3.	Introduction to Vue3 + Elementui + Fcl Scaffolding
4.	Interact with the Front-end,Store and mint NFT 

course6： Practical Operation 2
1.	NFT Sales
2.	NFT Transaction
3.	Testnet Deployment

**Qualifications**
We created the "WEB 3.0 Accelerator" and launched the "2022 Chinese University Web3 Acceleration Camp". We held 9 "China Entrepreneurs Conference" and "China University Youth Entrepreneurship Conference" in the Chinese community. We cooperated with the Chinese developer community (CSDN, Sifu) and developer education platforms (Tencent Classroom, Netease Classroom, Geek Time, etc.) established a course promotion partnership. We have our own columns on Chinese video platforms (Baidu Video, blibli) and Youtube.
links:
http://9.cyz.cn/ 
http://8.cyz.cn/ 
https://ke.qq.com/course/5271218#term_id=105445645
https://space.bilibili.com/1781314512?spm_id_from=333.1007.0.0
https://www.youtube.com/channel/UC4G60PmMwvgBGRf9a73o4lw
https://haokan.baidu.com/author/1727801298887666
https://www.8btc.com/college/item/548
https://haokan.baidu.com/author/1727801298887666
https://segmentfault.com/u/metatribe_623d0e914e484
https://www.zhihu.com/people/da-peng-72-69-64/zvideos

## Impact

- In what ways does this benefit the broader Flow developer ecosystem?
1、Developed courses suitable for Chinese community colleges and Web2.0 developers.                                     
2、Course promotion covers the Chinese developer community, education platform and video platform. The cumulative exposure exceeded 100,000.
3、The number of participants in the course is not less than 1,500, and 300-500 qualified Flow developers are trained.
4、Building brand influence in the Chinese developer community.

# Milestones and funding

> Note: You can leave the USD proposal empty / "TBD". Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1-course1 | Recording and Editing |1 weeks | - | 2500 |
| 2-course2 | Recording and Editing |1 weeks | - | 2500 |
| 3-course3 | Recording and Editing |1 weeks | - | 2500 |
| 4-course4 | Recording and Editing |1 weeks | - | 2500 |
| 5-course5 | Recording and Editing |1 weeks | - | 2500 |
| 6-course6 | Recording and Editing |1 weeks | - | 2500 |
| Web3 Acceleration Camp I | Recruit 500-1000 students |4 weeks | - |10000 |
| Web3 Acceleration Camp II | Recruit 500-1000 students |4 weeks | - |10000 |
| online promotion | Online more than 5 publicity channels, accumulated learning and watching 50000 |2 weeks | - |5000 |
| online promotion | Online more than 10 publicity channels, accumulated learning and watching 100000 |2 weeks | - |5000 |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Schiele |  Project leader | 6 years of experience in crypto community market and operation, 10 years of experience in IT market | liuyunpeng1215@gmail.com |
| Kaka |  Senior development engineer, lecturer | years of experience in development and system architecture | kakaliu499@gmail.com |
| Seven  |  Senior Web3 Researcher | 10 years experience in course development and promotion, Senior researcher in Web3 and Crypto | hypiota@sina.com |
| Moya |  Senior development engineer | 5 years experience in block-chain project development and system architecture | metamoya@yahoo.com |

**Comment by alxflw** [comment]
Hi @dapeng1215 we reviewed your proposal in detail and decided to pass because it is unclear if the impact on the developer ecosystem will be high enough.

Thanks for taking the time to submit your proposal and feel free to reach me directly on Discord in case you have further questions: `alx-flw.find#6198`.

**Comment by dapeng1215** [comment]
Thank you for your reply, we will provide data for review at each stage @alxflw

**Comment by alxflw** [comment]
@dapeng1215 to be clear, we've passed on this grant proposal. you are very welcome to work on this project of course.
