### ISSUE TITLE
Cadence Debugger in Flow Emulator

### ISSUE THREAD

**Issue by turbolent** [onflow/developer-grants#55]
# Grant category

Please select one or more of:

- [x]  Open source maintenance
- [x]  Developer tools / services
- [ ]  Educational material

# Description

## Problem statement

The Flow Emulator is the developer tool for the Flow blockchain which allows developers to develop Cadence smart contracts.

Debugging is an essential part of the development workflow.

The Flow Emulator should provide a debugging facility for developers. It should integrate with the existing main development workflow of using the Emulator with the CLI, Visual Studio Code, the Cadence extension, and the Cadence Language Server.

This feature / tool is often requested by the developer community.

The Cadence core contributors added debugging functionality to Cadence, and also started the implementation of the [[Debug Adapter Protocol](https://microsoft.github.io/debug-adapter-protocol/)](https://microsoft.github.io/debug-adapter-protocol/) to the Emulator. This allows editors which support the protocol, such as Visual Studio Code, to debug Cadence scripts, using functionality such as pausing and resuming the script, setting breakpoints, inspecting variables and the call stack.

See [https://github.com/onflow/flow-emulator/pull/164](https://github.com/onflow/flow-emulator/pull/164)

## Solution requirements

The solution should expand on the current state of the debugger in the Flow Emulator and add support for one or more of these features, in order of importance:

- Integrating with the CLI (FlowKit) to leverage the flow.json configuration to map on-chain addresses to local files
- Allow the debugging of transactions
- Allow the inspection of variables (structured information, like array/dictionary elements, composite fields)
- Allow the inspection of account state
- Step over, Step in, Step out

## Submission requirements

- Integration tests
- Tested with Visual Studio Code Cadence extension

**Comment by bjartek** [comment]
This should be closed? @turbolent and Deniz have dine this?
