### ISSUE TITLE
Developer Tool on Lilico Wallet

### ISSUE THREAD

**Issue by lmcmz** [onflow/developer-grants#56]
# Developer Tool in Lilico Wallet

# Grant category

- [x] Developer tools / services

# Description

One of the main goals for lilico is developer friendly. To achieve this, we would like to provide more tools for developers to test their dApp while they are in development. 

## Problem statement

1. When a developer creates their custom FT or NFT, they can't get it to display on the wallet when it's in testing.
Because they have to go through the whole progress to submit PR or form to let wallet to display. 
It's not easy for them to test their NFT or FT. 

2. I heard from some of the dApp team ( The fabricant ) are struggling with automation testing since they need to collaborate with the wallet to provide the automation ability. So Lilico would like to step further to provide this ability to all developer on flow.

- Target audience
Developer

- Evidence for the need
Emmm.... other ecosystem have a similar tool, we believe it will be needed by developers.

<img width="220" alt="Screen Shot 2022-07-08 at 3 26 44 am" src="https://user-images.githubusercontent.com/9669733/177833957-7279d316-81d7-4dd1-b0ad-11434debbff2.png">

## Proposed solution

1. Once the developer mode is on, Lilico will have a custom FT or NFT input field inside of the wallet, the developer can enter their project key info like  `contract_name`, `address`, `storage_path` and etc. Then Lilico will store it locally and will fetch and display those FT or NFT in the wallet. So developers can test their project for displaying or sending all kind of stuff before submit to alchemy or wallet to make it public. 

2. Lilico will create an auto-approve ability in the developer setting, which will sign the coming transaction and message automatically. So the dapp can resume their testing without waiting for approval.

## Impact

- In what ways does this benefit the broader Flow developer ecosystem?

Yes, it will benefit all flow developers if they need this kind of ability.

# Milestones and funding

> Note: You can leave the USD proposal empty / "TBD". Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Custom FT support   |  Developer can test their FT token during development  | 2 weeks  | - |   4000           |
| 2 - Custom NFT support   |  Allow developer to display and test their NFT in the wallet during development  | 4 weeks  | Take time to build own NFT API |   8000           |
| 3 - Automation testing tool   | Unblock some team for automation testing | 2 weeks   | - |  2000           |
| 4 - Documentation | Giving a doc instruction about how to add custom token and NFT into wallet and display it locally  |  2 weeks   | - |  2000           |
| 5 - Adoption | Add analytics on how many dev has been using this function and generate a report by a period of time  |  2 weeks | - |  2000 |
| 5 - Maintenance | Keep updating and maintaining those features by listening to the developer's feedback |  6 months   | - |  6000           |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Hao | Full-Stack Engineer | Founder of outblock, the core developer of lilico wallet. Built flow-swift, fcl-swift SDK. | hao@outblock.io |
| Han | Full-Stack Engineer |  CTO of outblock, educated in NYU, USYD, ANU. Double Master's degree in CS. Worked on mozilla foundation, tumblr, Alibaba before.  | han@outblock.io |

**Comment by alxflw** [comment]
hey @lmcmz, we've reviewed this application would like to accept it if you could:

1) Add a documentation milestone
2) Add an adoption milestone before maintenance (eg 100 developers used the feature in dev mode)

Please let me know if that is ok and we can move forward.

**Comment by lmcmz** [comment]
Hi @alxflw 

Sure, got it.  We will work on it and update here.

**Comment by alxflw** [comment]
great, could you update the milestones, deliverables, timelines, and costs in your issue based on the feedback?

**Comment by alxflw** [comment]
hi @lmcmz, can you please update the description based on the above?

**Comment by alxflw** [comment]
hey @lmcmz, please update the application above. we cannot review this before and will mark this as stale due to inactivity

**Comment by lmcmz** [comment]
Hey @alxflw 

Sorry for the late reply, some distraction on our end. 
I have update the milestone base on your comments, please have a look.

**Comment by alxflw** [comment]
thanks, we'll do a final review on this and get back soon

**Comment by lmcmz** [comment]
Yeah, the adoption was planning to track and generate a usage report to flow developer experience team.
If it's no need, we can simply remove it. :)

**Comment by chrisackermann** [comment]
Sorry @lmcmz  - wasn't saying it wasn't needed, but instead was looking for you to propose a specific level of adoption that would trigger the milestone being completed.  For instance, the milestone could be marked as complete when X developers have used the feature on dev mode.  Does that work?

**Comment by chrisackermann** [comment]
Hi @lmcmz, we're closing this proposal out based on our conversation around current resourcing.  We'll revisit at a later point when there is resourcing ready to take this one forward.  Thanks!

**Comment by Aliserag** [comment]
We appreciate your proposal and taking the time to fill it out. Given the time since this has been submitted I'm closing this down, please reach out to me if you'd like to share what you're working on now and explore potential opportunities [ali.serag@flowfoundation.org](mailto:ali.serag@flowfoundation.org).
