### ISSUE TITLE
Nakji Network: Flow Data Indexing

### ISSUE THREAD

**Issue by danatung** [onflow/developer-grants#57]
# <Nakji Network>

# Grant category

Please select one or more of:

- [ ] Open source maintenance
- [x] Developer tools / services
- [ ] Educational material

# Description
Nakji acts as a transporter of data from the blockchain to the Internet. It efficiently moves millions of data points off-chain to be accessed freely and openly by anyone who wants to connect to Nakji’s set of APIs. Nakji's robust blockchain data infrastructure solution provides cross-chain data indexed and queried with ease, seamless access to smart contract activities across blockchains and real-time data access with millisecond refresh rates. This allows developers to create Web 3.0 apps with familiar data backend structure as they can grab blockchain data via SQL, WebSocket, GraphQL, and Rest API.

## Problem statement
We’ve identified 3 major problems in the Web 3.0 data infrastructure level:   
1. Limited multi-chain data coverage– not all on-chain data from major blockchains are made available (only Ethereum had decent coverage). 
2.  On-chain data providers have unreliable uptime and slow “real-time” data
3. It is costly and inefficient to build and maintain in-house data infrastructure

## Proposed solution
To solve the above industry problems, we built Nakji Network, differentiated from existing data providers in many dimensions. Our first edge is being chain agnostic. Today, we are integrated with Ethereum, Harmony, Polygon, StarkEx, Solana, Binance Smart Chain, Avalanche, Fantom, Optimism, and Flow (coming soon), as well Quickswap, Ronin/Axie Infinity, Compound, MakerDAO, and more. Our second edge is our speed. We query up to 20 times faster than our leading competitor. Our third edge is our team. Our team brings decades of development and product management experience in and out of Web 3.0 and Web 2.0. Our co-founders built Nakji's industry grade, core data infrastructure platform all in-house, by themselves. 

## Impact
In what ways does this benefit the broader Flow developer ecosystem?

Nakji would like to collaborate with Flow and help grow the Flow ecosystem by indexing Flow data and making them available to as many Web 3.0 developers as possible free of charge (for the time being). We are also expanding the Nakji docs (https://docs.nakji.network/) to educate the developer community about Flow and exploring a high-level dashboard of Flow data on one of our landing pages. 

Nakji will offer the Flow community with fast and easy access to real-time on-chain data, making the developer experience more frictionless than ever and catalyzing growth of the overall ecosystem. 

# Milestones and funding

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Integrate Flow into Nakji Network   | Flow on-chain data APIs | 15 man-days | May need support from Flow engineering team, especially for getting access to backfill all historical data.  | $15,000           |
| 2 - Make APIs available to Flow and its ecosystem  | Public and accessible Flow on-chain data APIs | 10 man-days | - | $10,000           |
| 3 -  Expand Nakji docs (https://docs.nakji.network/docs/intro) with Flow  | Updated Nakji docs | 5 man-days | - | $5,000           |
| 4 - [optional] Flow dashboard on Nakji’s landing page | Web page with Flow analytics | 10 man-days | - | $10,000           |

Total $30,000 (excluding optional Milestone 4)

Purpose of Funds: Funds will be used for initial software development for building the connector, the APIs, and making the APIs publicly available. On-going maintenance and server costs have not been included and are optional. We are also requesting a technical point of contact from Flow’s engineering team, especially for getting access to backfill all historical data.

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Allie Zhang | Co-founder / CEO | Allie served as the leading engineer in designing and building the architecture for real-time data intelligence at Bottlenose, a Palantir competitor. Since 2018, she has served as an advisor to Rocket Fuel, a blockchain investment and advisory firm consisting of top minds from cutting-edge companies such as Snapchat, Salesforce, Uber, Airbnb, Accenture, and McKinsey. She graduated with a BS in Computer Engineering from Carnegie Mellon University. | allie@nakji.network  |
| David Kim | Co-founder / COO / CSO | David comes from a 13-year career in M&A Advisory and Consulting covering blockchain and financial services with PwC and Deloitte. In 2016, he helped establish the first Big4 blockchain practice in the world and PwC's first Data & Analytics practice in Hong Kong. In 2018, he co-founded Blue Block Group, a digital asset research and algorithmic trading firm responsible for working with over 50 blockchain projects since 2018. | dk@nakji.network   |
| Dana Tung | Strategy & BD | ex-Stanford, ex-Blackrock, former associate at 1B Web3 VC fund | dana@nakji.network   |
| Kiyoon Ko | Product Manager | ex-Duke, ex-Microsoft | yoon@nakji.network  |
| Ross Miller | Engineering Manager | ex-Amazon | - |
| Hughie Nguyen | Software Engineer | ex-Uber | - |
| Feiran Yang| Software Engineer | - | - |
| Gabriel Jaldon | Software Engineer | - | - |
| Cenk Arioz | Software Engineer | - | - |
| Gunnar Sundberg | Software Engineer | - | - |

**Comment by alxflw** [comment]
thanks for the submission @danatung! we'll review this and get back to you soon.

**Comment by danatung** [comment]
Thank you Alex @alxflw Let me know if you have any questions or if any additional information could be helpful. Looking forward to hearing from the team.

**Comment by alxflw** [comment]
hey @danatung, we reviewed this application and it has been accepted 🚀 

I'll follow up with you via email wrt next steps

**Comment by danatung** [comment]
Thank you @alxflw for the great news! We are super excited to be part of the Flow ecosystem. Looking forward to next steps.

**Comment by Aliserag** [comment]
Looks like operations fully closed down and there were legal issues in 2023, closing this grant. Please let me know if this is mistaken!
