### ISSUE TITLE
Kickback Podcasts Grant

### ISSUE THREAD

**Issue by AlexanderBZ** [onflow/developer-grants#59]
# Kickback Podcasts

# Grant category

Please select one or more of:

- [ ] Open source maintenance
- [ ✅ ] Developer tools / services
- [ ] Educational material

# Description
Kickback is a podcast platform that leverages cryptocurrency and blockchain technology. Through a decentralized, user-owned, crypto-based network, Kickback is revolutionizing the way podcasted are shared and monetized.

At Kickback, we want to revolutionize what podcasting platforms could look like for hosts and listeners alike by adding a plethora of revolutionary features such as dynamic/auto-paid out advertising, NFT fan clubs powered by NFTs, donations, and a weekly lottery for consistent listeners.

## Problem statement
For the last three months, I've been leading the monetization team for the BanklessDAO Podcast Hatchery. While leading this team, we thought a lot about how we could create Web3 monetization options like NFT-powered fan clubs for our incubated podcasts. After creating the smart contracts and code for this, we realized just how powerful the technology was and how it could be used across the podcast industry to help fix the devastating monetization short comings - podcasts have over 500 million global listeners (on par with music), yet the industry makes 95% less than music.

## Proposed solution
As we described in our description, we believe that many of the podcast industry's monetization shortcomings are due to companies not looking at what makes podcasts unique. Podcasting a widely unique form on content in which hosts are able to create massive fan bases that have people hanging on to their every word. Yet traditional platforms have focused on advertising solely to fund creators. We believe that podcast hosts can turn their passions into a full time career by tapping into their 1000 true fans by creating fan clubs/subscriptions powered by NFT technology.

## Impact

While we believe NFT fan clubs for podcasts are massive. We can also see how the technology we're building could be used for many different things, such as sports NFT fan clubs, movie NFT fan clubs etc. Since our code is open source, we believe our technology can create NFT fan clubs across the whole ecosystem, no matter the genre.

# Milestones and funding

Month 1 - Audit the smart contracts and refine the website ($10,000)
Month 2 - Launch the NFT fan clubs with our partner DAOs ($5,000)
Month 3 - Advertise the platform and continue to build out the private fan club features ($10,000)

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Alexander | Full-Stack Engineer, Designer, & Founder | 5+ years in the audio industry, WashU CS + Business, Atlanta Inno 25 under 25, Head of monetization at the BanklessDAO Podcast Hatchery, Author of the History of Hip-Hop
 | alexander.zwerner@gmail.com |
| Grant | Product Manager | PM experience at Tinder, Inroads Scholar, WashU CS + Business
| gsolomon@wustl.edu |
| Shruti | Full-Stack Engineer | Full Stack & Web3 Experience, Open Source Developer Certified through Google
| https://twitter.com/ShrutiGavali2 |
| Aimes | Full-Stack Engineer | Full Stack & Web3 Experience, Front End Web Developer for Varscon group
 | https://twitter.com/aimes_js |

**Comment by alxflw** [comment]
thanks for the submission, @AlexanderBZ. Is this enabling developers in some form? This grant program is designed to support developers directly by providing services/tools or education. Based on the initial read, I think there's a mismatch. Correct me if I'm wrong though.
