### ISSUE TITLE
Sample app: Defi on Flow

### ISSUE THREAD

**Issue by alxflw** [onflow/developer-grants#6]
App(s) that demonstrate either one or some of the following capabilities:

- Token Launch
- Swaps
- Bridges
- Lending Protocols
- Staking

**Comment by dryruner** [comment]
[Increment](https://twitter.com/incrementfi) has built / is building some of these. Welcome more users & developers to get integrated with us!

- CFAMM-based Swap: on mainnet
    - https://swap.increment.fi,  [Docs](https://docs.increment.fi/protocols/decentralized-exchange/cfamm-based-dex)
- Lending for FTs: on testnet
    - https://test.increment.fi,  [Docs](https://docs.increment.fi/protocols/decentralized-money-market)
- Decentralized Price Feed: on testnet
    - [Docs](https://docs.increment.fi/protocols/decentralized-price-feed/overview)

**Comment by alxflw** [comment]
cool. the public repo would be help. for this grant to be complete, I think we should also provide a guide or tutorial that explains the key functionality and concepts involved. The idea behind this wishlist item was to create the equivalent of [Kitty Items](https://docs.onflow.org/kitty-items/) for a DeFi app. So, a running app, contracts, a guide, and maybe even a tutorial.

@dryruner if you'd be open to it, maybe you could submit a proposal once you're ready to go public with your code? I'd be happy to connect with you directly to hash out scope and details

**Comment by freeeta** [comment]
Hi @alxflw , is this grant application still active? I recently was reviewing my [past work for Compound Labs](https://github.com/compound-finance/gateway/tree/toni/init-flow/flow/cadence) when found this grant.

I am interested to write a couple smart contracts  + tutorials for basic Defi primitives like the pool of staked tokens https://github.com/freeeta/flow-defi
and others.
