### ISSUE TITLE
Walnut Wallet-KaiOS Flow Wallet

### ISSUE THREAD

**Issue by kaifoundry09** [onflow/developer-grants#60]
# <Walnut Wallet>

# Grant category

Please select one or more of:

- [x] Open source maintenance
- [ ] Developer tools / services
- [ ] Educational material

# Description
**What is Kaifoundry?**

We are the leading technology solution providing company working in the world of KaiOS Creating all types of Gaming, News, Social Media and Blockchain apps for the people using the KaiOS platform. We already have 5 applications deployed on KaiOS with a cumulative user base of more than half a million users.

Website: https://kaifoundry.com/

## Problem statement

A wide audience of newly onboarded Internet users don’t have access to Web 3.0, due to unavailability of dApps, building on the KaiOS Platform. We need to provide the access to Flow to the KaiOS users who are from countries like Africa, Asia and South America

**Why KaiOS?**
KaiOS brings the best of smartphones to affordable devices. Audience accessing this OS are first-time internet users from Asia, Africa, and South America. KaiOS is the third largest OS in the world with 160 million plus running devices.

## Proposed solution

We will be building a Flow wallet for KaiOS. It will help ensure the access of Flow and the ecosystem to a wide range of people using KaiOS phones.
This will be the first dApp built on the KaiOS ecosystem

## Impact

The Walnut wallet will help expand the Flow ecosystem to the KaiOS, world's third largest OS. In the next 18-24 months half a million new users will be on-boarded to Flow ecosystem.

# Milestones and funding

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1-At the grant approval | Beta version of the wallet | 12 weeks  | We have a competent and experienced team which will help in mitigating all the major identified risks | 50,000           |
| 2 - Launch of Beta Version  | Bug free and wallet with full features | 12 weeks  | We have a competent and experienced team which will help in mitigating all the major identified risks | 10,000           |
| 3 - Launch of mainnet   | Launch of wallet to general public | 8 weeks  | We have a competent and experienced team which will help in mitigating all the major identified risks | 25,000           |
| 4 - At 100K users   | 100K users of the wallet | 10 weeks  | We have a competent and experienced team which will help in mitigating all the major identified risks | 15,000           |

# Team

The team at Kaifoundry is lead by Mr. Vinayak Kalra. Through his excellent leadership, the team has developed and marketed 5 KaiOS apps in various different fields ranging from blockchain to gaming. Vinayak is a gold medalist computer science engineer. He is very popular speaker in India’s Top Engineering Institutes (IIT, NIT etc.)

Please refer to the full pitch deck: https://docs.google.com/presentation/d/1TUv9OSD7yjxD6HjkY0lHtKY2k4Xkfk_PGoIPBgFy7wA/edit?usp=sharing

**Comment by kaifoundry09** [comment]
Hi @alxflw please let me know if you have any further questions regarding the proposal.

**Comment by alxflw** [comment]
thanks @kaifoundry09 - we'll review it and get back to you soon!

**Comment by kaifoundry09** [comment]
Hi @alxflw , is there any update or development for our application? 

Please let me know if you have some questions.

**Comment by alxflw** [comment]
hey @kaifoundry09, thanks for checking in. we reviewed your proposal in detail and decided to pass because it is unclear if the impact on the Flow developer ecosystem will be high enough.

Thanks for taking the time to submit your proposal and feel free to reach me directly on Discord in case you have further questions: `alx-flw.find#6198`.

**Comment by kaifoundry09** [comment]
Hi @alxflw I sent you the friend request on discord with username Vinayak#9921. Please accept so that I can DM you.
