### ISSUE TITLE
Flowscore

### ISSUE THREAD

**Issue by proudlywashed** [onflow/developer-grants#61]
# <Flowscore>

# Grant category

Please select one or more of:

- [ ] Open source maintenance
- [X ] Developer tools / services
- [ ] Educational material

# Description
Flowscore is a ranking and rewards system for the best projects on Flow. We work directly with Projects to determine the most accurate rarity system for their community, taking into account any unique rarity tiers, boosters, or 1 of 1's. Users can then connect their Blocto, Lilico, and Dapper Wallets to see their global inventory and claim the assets they own that are listed on our Platform. Users will be rewarded based on the number of assets they own, the length of time they continue to hold those assets, and engagement within the project communities. Rewards are issued in the form of a token, which can be converted back to fiat, used to purchase digital and physical goods, and other relevant rewards. Users will also be displayed on a Global Leaderboard, which can earn them additional bragging rights and other digital and physical goods not available to the general public. The top of the leaderboard can additionally be accessed for early feedback and guaranteed purchases on upcoming projects, effectively leveraging built-in Network Effects.

## Problem statement

- Target audience
- Evidence for the need

This tool will benefit the entire ecosystem: existing Projects, new Projects, and those that are purchasing our assets. We've seen the value through our own project: SNKRHUD. Our community was thrilled when we initially launched as it gave them a new way to evaluate the collection. Its most basic function is like a Kelley Blue Book for NFT's. Users now have a means to assess the value of their assets. We immediately saw items delisted and relisted on secondary, and those not quick enough to reassess were snatched up for a steal. Our highest sale to date came 3 weeks after mint for $900, 6x our mint price! Our community continues to reference the tool for their purchases. We are confident this same value can be applied to other communities as well! And while some projects have built their own rarity tool, none are as comprehensive as ours or have the additional marketing flywheel built in through user rewards.

## Proposed solution

We are actively building Flowscore, having already onboarded one additional company, closed an agreement for the next, and are in conversation with many others. We have the wallet connect working across all three wallets and plan on pushing that out soon. Once our Leaderboard and User Profiles are live, we're working to establish various partnerships and integrations. We're talking to Web3Wear to build an embedded merch solution, including items and designs exclusive to Flowscore. Flowverse is also interested in embedding the top 3 ranked assets of every project directly into their Platform. Our goal is to onboard as many Flow Projects as absolutely possible and to grow their awareness through our product as much as we can. 

## Impact

- In what ways does this benefit the broader Flow developer ecosystem?

We estimate their are 6K-7K individuals purchasing across the various independent projects, like Ballerz, Crypto Piggos, and SNKRHUD. However, there are 600K-700K active purchasers of NBA Top Shot and NFL All Day. The more projects we can onboard, including Top Shot and All Day, means more exposure to ALL projects. The Rewards System incentivizes all purchasers to hold onto their assets, thus driving up the Floor Prices and increasing the overall value of ranked Projects. Even our Product Pages are designed as an active Landing Page for each project to make for easy accessibility and discoverability. Network Effects are baked in top to bottom.

# Milestones and funding

> Note: You can leave the USD proposal empty / "TBD". Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - MVP   | Wallet Connect & Global Inventory | 2 weeks  | Reliant on DW & Blocto |           |
| 2 - MVP   | User Profiles & Leaderboard  | 4 weeks  | Crashing with Large Portfolios |           |
| 3 - Adoption   | 5 Companies Sign Up | 4 weeks  | Co.'s are cash-strapped & worried about longterm |           |
| 4 - Adoption   | 1000 Users Connect Wallet | 4 weeks  | Need to market benefits to users |           |
| 5 - Tokenomics   | Implement Reward System & Airdrop | 3 months  | Need progressive system built for longhaul |           |
| 6 - Maintenance   | Resolving issues and fixing bugs | 3 months  | - |           |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Brandon Martinez | CEO | Founded & Sold INDMUSIC, music admin platform behind "Harlem Shake" | bmart@flowscorenft.com |
| Stefan Tauber | CXO | Creative Director, WPP Atticus Award Winner | stefan@flowscorenft.com |
| HirayaMNL | Dev Team | Built & sold largest live-gaming app in SE Asia, Paydro |  |

**Comment by alxflw** [comment]
thanks for the submission @proudlywashed. I just reviewed the description and this project seems not tailored towards developers but rather holders / users of applications. I believe this is not in alignment with the purpose of the developer grants.

Feel free to re-open with a detailed explanation if that assessment is not accurate.
