### ISSUE TITLE
Conditional Ownership of NFTs

### ISSUE THREAD

**Issue by AlexanderBZ** [onflow/developer-grants#62]
# Creating an open source protocol for the conditional ownership of NFTs on Flow

# Grant category

Please select one or more of:

- [✅ ] Open source maintenance
- [✅] Developer tools / services
- [ ] Educational material

# Description
At Kickback Podcasts, we are developing a protocol for creators to receive recurring revenue for their projects through the conditional ownership of NFTs. This will be done through things such as NFT renting, subscriptions, ticketing, and more. 

## Problem statement
Over the past five years, there have been numerous ICOs and NFT projects created for celebs and creators that have fizzled out. Creators like Tyga, Floyd Mayweather, and more have all lost interest in keeping up with their own launched projects, as many of these celebs lose interest once they see the lack of recurring revenue. We believe we can help change this by implementing many of the NFT technology stated above.

- Target audience: The Creator Economy is the initial target audience
- Evidence for the need: The laundry list of failed crypto projects by celebs, including that of T.I., The Game, Tyga, and more

## Proposed solution
We believe that by implementing conditional ownership of NFTs on Flow, we can help creators connect with their 1000 true fans and earn a recurring revenue that will keep them engaged for years to come.

## Impact

- In what ways does this benefit the broader Flow developer ecosystem?
The conditional ownership of NFTs has reach far beyond that of just the creator economy. We believe that with the open source of this protocol we can allow developers to create strong economies backed by a recurring revenue model. We've outlined some of these industries below.

**Gaming:**
- creating robust in game economies through assets that expire after usage

**Ticketing:**
- created tickets that expire after use at a concert

**NFTs:**
- The ability to rent NFTs to other people in order to get access to its community or utility

# Milestones and funding

> Note: You can leave the USD proposal empty / "TBD". Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - MVP   | Smart Contracts | 6 weeks  | Taking longer than expected | $10,000           |
| 2 - Audit   | Audit the contracts to ensure security | 3 weeks  | Costing more than expected | $7,500           |
| 3 - Onboard Devs   |  Create three different hour+ long video tutorials to walk through devs on how to create and use the contracts in React websites themselves (1 for NFT lending website, 1 for minting of time based expiration website, and 1 for minting of use-based expiration website) | 3 weeks  | Costing more than expected | $1,500        |
| 4 - Adoption   | Develop a mirco grant program to inventive developers to use the protocol | 3 months  | Developers wanting more money from the grant program | $2,500           |
| 5 - Maintenance   | Maintain and expand the smart contracts/protocol based on developer feedback | 3 months  | No real risks here | $3,000           |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Alexander | Full-Stack Engineer | Alexander is a full stack/Flow developer with 5+ years of experience in the creator/audio economy via. co-producing podcasts and writing about musicians | alexander.zwerner@gmail.com |
| Elie | Lead Engineer | Elie is a smart contract developer with a Masters in engineering and is currently working as a CTO at Citi Group | elie.hamouche@gmail.com |

**Comment by alxflw** [comment]
@AlexanderBZ can you provide us more information about: 
- the implementation and the concept of conditional ownership?
- the direct benefits that will make it easier for developers to build apps?

**Comment by AlexanderBZ** [comment]
Thanks for the questions. I'll address both below:

1. the implementation and the concept of conditional ownership?
- Web3 in 2021 was dominated by NFTs. Big projects from teams like Flow and Yuga Labs amassed massive success and changed how people look at crypto. Creators also flooded the scene, creating widely interesting projects. However, all these projects have struggled to create recurring revenue as most of the money is made when NFTs are minted. This has caused many creators to lose interest in NFT projects in the long run as they spend the initial money from the mint. We believe that by creating an open protocol for creators to time gate, rent, or use expire NFTs, they can create long-term recurring revenue, which will keep them more engaged and thus keep projects stronger long term. While we see a large use of these Flow contracts with creators, we also see a clear use for these protocols with other products like ticketing, real estate, and gaming.
 
2. the direct benefits that will make it easier for developers to build apps?
- Web3 can be confusing, to say the least. There's Cadence, Rust, Solidity, etc. All of these languages are a lot to learn. The one language arguably everyone knows, though, is Javascript. We're planning on creating a SDK that developers can import into ReactJS and NextJS sites and use the contracts to create NFT renting websites, Token gated creator websites, use-based gaming NFTs, etc. all using javascript (essentially abstracting away Cadence for coders dipping their toe into Flow). We also see a world where these open source contracts serve as a starter kit for creating utility NFTs on top of like Open Zeppelin.

Happy to expand on the proposal further!

**Comment by alxflw** [comment]
thanks for the response! two more things:

1) can you expend on the methods your contract would have?
2) you're mentioning an SDK but that doesn't seem to be included in the milestones. should it be?

**Comment by AlexanderBZ** [comment]
1. Initial contracts methods include:
- time-based expiration
- use-based expiration
- renting of NFTs

2. Yes, the SDK is a part of the adoption phase as SDKs have proven to be the easiest way of onboarding new devs from javascript.

**Comment by AlexanderBZ** [comment]
Hi @alxflw. Just wanted to check in on if this proposal were something the Flow grant community would be interested in. We also added a pure Cadence developer to our team so that we can make these conditional contracts happen!

**Comment by alxflw** [comment]
hey @AlexanderBZ we'd be in favor of approving this grant but could you make the following changes:
- add the costs for milestone 3
- add a new milestone for maintenance for 3 months

**Comment by AlexanderBZ** [comment]
@alxflw just made the necessary changes

**Comment by alxflw** [comment]
awesome, thanks! this application is now accepted 🚀 

I'll follow up with you via email with next steps!

**Comment by AlexanderBZ** [comment]
We recently created all of the NextJS websites - https://github.com/AlexanderBZ/Kickback-Projects, finished the time based contracts - https://github.com/AlexanderBZ/Flow-Time-Expiring-NFTs.git, and halfway done with the use based contracts. Making great progress 🚀

**Comment by AlexanderBZ** [comment]
We’ve just finished our MVPs of the contracts. Check them out here - https://github.com/AlexanderBZ/Flow-Conditional-NFTs

**Comment by AlexanderBZ** [comment]
We just finished all the videos to accompany our code, check them out here -> https://youtube.com/playlist?list=PLImTfrmjYO9oXdqnBzG7gtvk7QvS7kPWb

**Comment by AlexanderBZ** [comment]
Also make sure to submit a proposal to our grant program (https://docs.google.com/forms/d/e/1FAIpQLSef9xjqcggZmxY6yRaqnhAzoqZDR2HCapsiWbA4RGVTL46OXQ/viewform) to potentially win $500 to implement our contracts into a product that uses our contracts
