### ISSUE TITLE
Web3 Analytics

### ISSUE THREAD

**Issue by DannyD2021** [onflow/developer-grants#64]
# Web3 Analytics

# Grant category

Developer tools / services

# Description
Web3 Analytics provides users the ability to create databases and analytics without coding. All the data comes from the blockchain, we develop a tool to collect data from the blockchain and a tool to analyze it.

## Problem statement
When users want to analyze data related to flow, they first need to have available and easy-to-use databases to ensure that they do not need to run their own nodes to get this chain data, and do not need to spend time and effort to organize and clean it, but can quickly use existing ones (official or created by other users), or create their own databases according to their needs and quickly extract data from the chain to the Database.
Second, based on this database, users need a zero-code tool to analyze this data (by encapsulating SQL structure into a mouse-click graphical interface) instead of using SQL, which most users do not use.
Finally, the output can be quickly visualized as a corresponding chart output, and related dashboards and insights can be created according to categories or themes for your own use or to share with other users.

- Target audience
Users who have a need for analysis or validation of certain items or data in the chain.

- Evidence for the need
A simple example, after a new project on the blockchain is created, a large number of validation requirements about the project and the impact on the chain itself, because it is an innovative project, there is no suitable database and analysis model dedicated to the project, and many users interested in the project lack analysis tools because they do not have a suitable data source and do not know how to write SQL.

## Proposed solution
Data source: provide tools to create databases quickly, users create databases through the database template tool we provide, and we will collect data and import it through scripting multi-process clump flow nodes.

## Impact

- In what ways does this benefit the broader Flow developer ecosystem?
1. Richer and more multidimensional data sources for high availability and ease of use
2. More users more convenient to analyze the chain-related ecology, users can participate more deeply in the community and have higher stickiness

# Milestones and funding

> Note: You can leave the USD proposal empty / "TBD". Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - MVP   | data tools | 4 weeks  | - |          |
| 2 - Adoption   | Use our tools to serve 5 teams to create their database and analytics | 8 weeks  | - |           |
| 3 - Maintenance   | Collect 95% projects and other general data form flow | 3 months  | - |           |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Danny | Project leader | Producer at Tencent, User growth at Binance | danny@3analytics.io |
| Matthew | Producer | Product manager at Tencent | Matthew@3analytics.io |
| Star | Onchain tech-lead | Ph.D. in Large-scale Distributed File System;Published papers in Journal of Systems Architecture, IEEE Transaction, and other journals.
| Sanshi | Tech-lead | Former senior engineer at TikTok; 6 years of work experience, rich experience in data visualization.
| Kyrie | Server developer | Former senior data engineer at TikTok; 6 years of work experience
| Nic | Client developer | Former senior engineer at Tencent

**Comment by alxflw** [comment]
hi @DannyD2021 thanks for the submission. can you please tell us more about your proposal, specifically:
- what are the core features?
- how would developers use it?
- what does the envisioned architecture look like?

Can you also break down the MVP deliverables, ie what are the data tools?

**Comment by DannyD2021** [comment]
> 
We have talked with amber@DapperLabs about our project.

This project aims to provide a set of low-cost visualization and analysis solutions for on-chain data, which consists of two main cores.

1. visualized data collection tools, this is under development and we do test our MVP and would release soon
2. a low-code data analysis tool, you could see this MVP on https://www.youtube.com/watch?v=We8QP1X9j0s

The visualized data collection tool mainly solves the following problems.

1. Since different blockchains (EVM chains or non-EVM chains) do not have the same data acquisition methods, users need a high threshold to directly access data on the chain. Users not only need to run the blockchain's clients, but also need to read the blockchain's API documentation before they can extract and analyze the on-chain data. This hinders a large number of ordinary users from analyzing and mining on-chain data and reduces user engagement. In order to solve this problem, this project provides a conversion tool from on-chain data of all nodes to standardized data in the database to reduce the threshold of data collection for users in a visual way.

2. Since the data storage formats in different blockchains are not the same, how to design storage tables for on-chain data in traditional databases becomes a problem to be solved. For this reason, the project will build a basic data table for on-chain data analysis based on the structural characteristics of on-chain metadata (any user only needs to provide the contract and ABI to automatically generate the contract data table for analysis, and also supports the customization function of data table format and table header). In the future, all on-chain data analysis can be based on the basic data table, thus further reducing the threshold of data analysis for users.

The low-code data analysis tool mainly addresses the following issues.

1. To address the problem of the high entry threshold of data analysis itself, this paper provides low-code data visualization and analysis tools for ordinary users. Users do not need to master SQL, and can complete the analysis of data on the chain only by using mouse point-and-click. For advanced users, this project also provides a SQL mode that supports complex queries, which allows users to analyze data on demand.

2. In response to the demand for on-chain data analysis from project officials or a large number of users, as well as the more popular analysis indicators on the chain, the project will provide a large number of analysis codes and intermediate data tables. It is still quite difficult to extract and analyze data from the basic data table, and data analysis of a large number of users is generally based on the current popular indicators, for this reason, the project can provide intermediate tables or analysis codes on demand for users to test and analyze.

3. Own data and analysis results
Through Phala privacy service and Arweave decentralized storage, this project can encrypt and store users' own data and users' analysis results, and ensure data decryption authority through NFT credentials, so as to achieve privacy protection and confirm rights. Users can use the flow of NFT to enable the transfer of the value of that data. 
For the technical implementation of this part, you can see [link.medium.com/gKKHqLSqkpb](https://t.co/zlA1aADUqP)

Alex <notifications@github.com> 于2022年8月6日周六 04:02写道：
hi [@DannyD2021](https://github.com/DannyD2021) thanks for the submission. can you please tell us more about your proposal, specifically:

what are the core features?
how would developers use it?
what does the envisioned architecture look like?
Can you also break down the MVP deliverables, ie what are the data tools?

**Comment by DannyD2021** [comment]
We have talked with ***@***.*** about our project.

This project aims to provide a set of low-cost visualization and analysis
solutions for on-chain data, which consists of two main cores.

   1. visualized data collection tools, this is under development and we do
   test our MVP and would release soon
   2. a low-code data analysis tool, you could see this MVP on
   https://www.youtube.com/watch?v=We8QP1X9j0s

The visualized data collection tool mainly solves the following problems.

   1.

   Since different blockchains (EVM chains or non-EVM chains) do not have
   the same data acquisition methods, users need a high threshold to directly
   access data on the chain. Users not only need to run the blockchain's
   clients, but also need to read the blockchain's API documentation before
   they can extract and analyze the on-chain data. This hinders a large number
   of ordinary users from analyzing and mining on-chain data and reduces user
   engagement. In order to solve this problem, this project provides a
   conversion tool from on-chain data of all nodes to standardized data in the
   database to reduce the threshold of data collection for users in a visual
   way.
   2.

   Since the data storage formats in different blockchains are not the
   same, how to design storage tables for on-chain data in traditional
   databases becomes a problem to be solved. For this reason, the project will
   build a basic data table for on-chain data analysis based on the structural
   characteristics of on-chain metadata (any user only needs to provide the
   contract and ABI to automatically generate the contract data table for
   analysis, and also supports the customization function of data table format
   and table header). In the future, all on-chain data analysis can be based
   on the basic data table, thus further reducing the threshold of data
   analysis for users.

The low-code data analysis tool mainly addresses the following issues.

   1.

   To address the problem of the high entry threshold of data analysis
   itself, this paper provides low-code data visualization and analysis tools
   for ordinary users. Users do not need to master SQL, and can complete the
   analysis of data on the chain only by using mouse point-and-click. For
   advanced users, this project also provides a SQL mode that supports complex
   queries, which allows users to analyze data on demand.
   2.

   In response to the demand for on-chain data analysis from project
   officials or a large number of users, as well as the more popular analysis
   indicators on the chain, the project will provide a large number of
   analysis codes and intermediate data tables. It is still quite difficult to
   extract and analyze data from the basic data table, and data analysis of a
   large number of users is generally based on the current popular indicators,
   for this reason, the project can provide intermediate tables or analysis
   codes on demand for users to test and analyze.
   3.

   Own data and analysis results
   Through Phala privacy service and Arweave decentralized storage, this
   project can encrypt and store users' own data and users' analysis results,
   and ensure data decryption authority through NFT credentials, so as to
   achieve privacy protection and confirm rights. Users can use the flow of
   NFT to enable the transfer of the value of that data.
   For the technical implementation of this part, you can check
   link.medium.com/gKKHqLSqkpb <https://t.co/zlA1aADUqP>

**Comment by alxflw** [comment]
Hey @DannyD2021 - we reviewed your proposal in detail and decided to pass because it is unclear if the impact on the developer ecosystem will be high enough.

Thanks for taking the time to submit your proposal (and sharing more details). Feel free to reach me directly on Discord in case you have further questions: `alx-flw.find#6198`.
