### ISSUE TITLE
Nomis —open source credit score protocol

### ISSUE THREAD

**Issue by sxlveign** [onflow/developer-grants#65]
# Nomis

# Grant category
Developer tools / services

# Description
Nomis is an on-chain open source credit score protocol that helps developers build better DeFi products. <br />
- [Whitepaper 1.0](https://artemshtlv.notion.site/Nomis-Protocol-e859b9e3bae6412fb99d6119a8d2e5a4) <br />
- [MVP on Ethereum](https://nomis.cc) <br />
- [Pitchdeck](https://docs.google.com/presentation/d/17giV9I1EaBYhzJ7Ugei1ijMDZXCFqBpLolRd46qJNWU/edit?usp=sharing)

## Problem statement
**Over-collateralization in DeFi borrowing which is an entry- and adoption barrier for mainstream borrowers.**

Today's mainstream borrowers are either not using DeFi loans due to their unattractiveness as a financial tool comparing to banks' ones or taking over-collaterized loans with unfair collaterals (>125%) and APRs. Banks, in their turn, overcomes this problem by hiring credit scores. Such tool may also be implemented in DeFi making crypto loans more accessible for fair users, cultivating trust and reputation-culture. Moreover, credit score negatively impact the number of crypto fraud cases by disincentivizing actors to play dirty.

- Target audience: TradFi mainstram borrowers.
- Evidence for the need: TradFi global lending market is **560** bigger than TVL in DeFi lending (as of 07/05/22).

## Proposed solution
Nomis is an on-chain protocol based on a mathematical prediction and AI model enabling protocol users with a favorable on-chain credit score to borrow crypto with a fair collateral and APR on a case-by-case basis. From a developer's perspective, Nomis is an open-source protocol that helps her both to build new DeFi solutions and use cases, and to balance already existing high-TVL protocols.

## Impact
- **From the borrowers' perspective**: Nomis will crush the entry- and adoption- barriers to crypto loans by making them as attractive as today's TradFi loans.
- **From the developer's perspective**: Nomis will help them to build better DeFi products by enabling to customize their initial lending/borrowing terms on a case-by-case basis. DeFi developers will have more power over their business models and differentiation points.
- **From the blockchain/protocol's perspective**: Nomis will help blockchain/protocol to grow its TVL, # of active users (as a result of acquisition of mainstream borrowers), as well as # of active on-chain developers, and # of on-chain use cases (as a result of opportunity provided to develop new DeFi solutions on-top of the Nomis open-source protocol). Those will also result in ecosystem growth and price increase of native tokens. 
- **From the Flow ecosystem's perspective**: Besides all the benefits listed above, Nomis will help Flow to develop better DeFi ecosystem. DeFi developers who will build their solutions on-top of Flow (and Nomis) will be able to create highly customized use cases for the broadest audience ever achieved by any blockchain.

# Milestones and funding
| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Data extraction from Flow (API); Basic attribute calculation (on-chain data and transaction history) | - Code for attribute extraction;<br />- Landing with calculated attributes. | 1 month  | - | 30,000 |
| 2 - Credit score calculation via Nomis' AI-algorithm; Web3 login connection to boost UX | - Code for credit score calculation;<br />- Web-wallet integration. | 1 month  | - | 30,000 |
| 3 - API & documentation development | - API for credit score calculation;<br />- Documentation for using API;<br />- Personal area to API stats. | 1 month  | - | 30,000 |
| 4 - DST (Decentralized Score Token, non-transferable dynamic NFT which contains wallet’s current credit score) implementation | - Contracts for tokens;<br />- Web-page for token exploration. | 1 month  | - | 30,000 |
| 5 - Community building (Twitter, Discord, Telegram) — 20K total followers | - Twitter Account with ≥ 5,000 followers;<br />- Discord Account with ≥ 5,000 followers;<br />- Telegram Account with ≥ 10,000 followers. | 3 months | - | 30,000 |

# Team

The team has experience in developing of and commercializing AI- and crypto-related products such as Kickcity (web3 event/ticketing platform on Ethereum) and GoRecruit (employee scoring SaaS for HR). Moreover, our spike is 15+year experience in neural networks.

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Alex Barabash | CEO | - 5-year CTO experience; <br /> -15-year experience in neural networks;<br />-Ex. GoRecruit — employee scoring SaaS for HR. | alex@nomis.cc |
| Fedor Cherepanov | CTO | - PhD in CS;<br />-Solidity & Rust developer;<br />-8 patents’ holder (neural networks);<br />-Ex. custom L1 blockchain solution. | fedor@nomis.cc |
| Arty Shatilov | CPO | - 4-year experience of PM/UI/UX in crypto;<br /> -Ex. KickCity — web3 event dapp on Ethereum <br />; -Hack-a-Ton Winner (TheOpenStream.com)| arty@nomis.cc |

**Comment by alxflw** [comment]
thanks for the submission @sxlveign, we'll review and get back to you soon

**Comment by sxlveign** [comment]
Hey @alxflw, thanks for the heads up! Just a kind reminder.

**Comment by alxflw** [comment]
hi @sxlveign, thanks for the reminder. We appreciate that you took the time to submit the application. After careful review, we decided to pass on this application because it is unclear if the impact on the developer ecosystem would be high enough.

If you have further questions, you can find me on Discord: `alx-flw.find#6198`.
