### ISSUE TITLE
Nexera Protocol

### ISSUE THREAD

**Issue by Gleatcher512** [onflow/developer-grants#67]
# <Project name: Nexera Protocol>

# Grant category

Please select one:

- source maintenance
- **Developer tools / services**
- Educational material

# Description: What is Nexera?
We believe NFTs will become the digital representation of a person’s identity, the inventory of what they own, and the record of every action performed on-chain while maintaining privacy.

We built a fully trustless, secure and extensible protocol that leverages the uniqueness of NFT properties to create and manage a new standard of NFTs, we call them MetaNFTs.
Technically, it's an ERC-721 token with added functionalities (properties & restrictions, property managers). The Nexera MetaNFT can hold other ERC-20 tokens, NFTs and MetaNFTs. With Nexera MetaNFTs, you can design any app on top of the blockchain, from games to services & more.

Our vision is every industry will be powered by MetaNFTs in some way, shape, or form, without limiting their use to Web3 only.

Our mission is to build the infrastructure that will enable developers of all sizes to leverage the full potential of MetaNFTs, without prior Smart Contract knowledge.

This is Nexera, a platform that allows any user, from solo programmers to globally scaled teams, from startups to established companies within or outside Web3, to build on top of NFT Protocol. Nexera is the gateway to create custom MetaNFTs, their key properties and features, shape them, manage them, and deploy them into the world.

## Problem statement:
The NFT infrastructure space remains scattered, with projects building use-case specific NFT infrastructure (NFT minting & management for creators for example).
However, there are no unifying standards to build and connect different use cases with MetaNFTs (connect gaming with DeFi with compliance for example).
Nexera allows cross communication between apps and the modularity to make NFTs dynamic.

- Target audience: Big focus on B2B2C initially, with 2 key verticals: Gaming & DeFi. User audience within those verticals are:
1. A. Defi protocols / companies and power users
1. B. financial institutions with defi interest (we already speak with asset managers and private banks for certificate wrapped strategies, wrapping and fractionalisation of funds, … etc) 
2. Game developers and gamers

Our tech will allow also the bridge between DeFi and Gaming.

- Evidence for the need: The future of NFTs (beyond art & collectibles) are MetaNFTs that will power Web3 gaming and the next evolution of DeFi. Those needs will be for mutable NFTs to represent evolving game characters, bridging gaming & DeFi, having MetaNFTs representing various liquidity positions, that can be fractionalised, attached, detached, used as collateral etc. This will only be possible with the right NFT infrastructure / standard to enable this modularity. This is what Nexera is building  

## Proposed solution: 
We built a fully trustless, secure and extensible protocol that leverages the uniqueness of NFT properties to create and manage a new standard of NFTs, we call them MetaNFTs.
Technically, it's an ERC-721 token with added functionalities (properties & restrictions, property managers). The Nexera MetaNFT can hold other ERC-20 tokens, NFTs and MetaNFTs. With Nexera MetaNFTs, you can design any app on top of the blockchain, from games to services & more.

This is Nexera, a platform that allows any user, from solo programmers to globally scaled teams, from startups to established companies within or outside Web3, to build on top of NFT Protocol. Nexera is the gateway to create custom MetaNFTs, their key properties and features, shape them, manage them, and deploy them into the world.

Pitch deck: https://docs.google.com/presentation/d/1cNQRefQhehv6B4fDIa5oPtm1AEFaM8ta/edit?usp=sharing&ouid=100442600059530411881&rtpof=true&sd=true

## Impact

- In what ways does this benefit the broader Flow developer ecosystem?
Nexera is a new standard for projects leveraging NFTs on FLOW.
Devs & projects can easily build, grow & manage applications without prior smart contracts knowledge, just by leveraging our SDKs & APIs.
It also enables cross communication between those applications built on FLOW: imagine creating an index of your NFT collection in a single MetaNFT, then using it on Flowty marketplace to get a loan, issue a child NFT representing a subset of your NFT collection and moving it to another lending platform on flow and generate a yield, all within your MetaNFT.
This is only one of many applications that our MetaNFT can enable NFT collectors and protocols to generate new revenue streams and add value to the FLOW ecosystem.

# Milestones and funding page:
https://drive.google.com/file/d/1-xQY69WUPJ_QTu9IYmt0q7luWPomCt1A/view?usp=sharing

# Team page
https://drive.google.com/file/d/1-nYzdXMK6TwXxj4JtQJSifXSLfrZ4WBK/view?usp=sharing

**Comment by alxflw** [comment]
@Gleatcher512 - were you maybe looking for an ecosystem grant as opposed to a developer grants? Average amount for a dev grant is ~$50k. the support in this program is limited to FLOW token payouts and review of milestones- it isn't a partnership. If you're still looking at a dev grant, please follow the issue template and list all milestones, deliverables, timeline, and costs associated so we can review on our end. thanks!
