### ISSUE TITLE
Drizzle: Token Distribution Tool #onFlow

### ISSUE THREAD

**Issue by LanfordCai** [onflow/developer-grants#68]
# Grant category

Please select one:

- **Open source maintenance**

# Description

## Problem statement

Token distribution (Airdrop/Raffle etc) is a common need in crypto space now. A project may want to send giveaway to its community; A DAO may need to reward some contributors; A member of a Discord channel may want to distribute some tokens to other members to show appreciation or just to liven up the channel.

Over the past two years, small DAOs are blooming in Web3, and there will be more and more DAOs crowding into the Web3 world, increasing the needs for Token Distribution. But it’s hard for small communities to find experienced smart contract developers to help them to make Token Distribution Tools, and the currently available tools on Flow are not user-friendly enough:

After collecting an access-list by using FLOAT or Hype.Day, you need to run a program locally or use a centralized service to determine how much an account in the access-list should get or who are the winners(well, this is more than just tedious, it is not transparent), and eventually transfer to the eligible accounts or winners one by one, or use bulk transfer tools like [bayou](https://bayou33.app/) (FT only now, and it seems that no universal NFT bulk transfer tool exist on Flow so far）.

We need to make Token Distribution easier and more transparent to empower all the communities/DAOs on Flow.

- Target audience
    - The community operators / DAO core members #onFlow
- Evidence for the need
    - The lack of on-chain tools for token distribution on Flow

## Proposed solution

 To address these problems, I’ve made a product named Drizzle for the Flow ecosystem:

- [Drizzle](https://drizzle33.app): Drizzle is an advanced Token Distribution Tool on Flow:
    - Fungible Token Airdrop (more than 20 tokens supported)
    - NFT Raffle (3 projects supported and more to be added)
    - Multiple eligibility checking methods: host can check the user eligibility by using FLOAT / FLOAT GROUP / Whitelist, and more to be added.
    - Two Fungible Distribution modes: Identical and random distribution
    - More modes beside Airdrop and Raffle to be added
    - More information: See [Drizzle Deck](https://drive.google.com/file/d/10c8KK1z_BO-RfnTZWXZ1dudF1uKG58Tc/view?usp=sharing) and [Drizzle Walkthrough Video](https://drive.google.com/file/d/1sitLXaEgPbySn9AQsr-NUd_X70x5AbJz/view?usp=sharing)

To make Drizzle serve Flow ecosystem better, we are going to add following features:

- Support .find and .fn domain(both display and whitelist)
- Support more projects for raffling like NBATopShot / Flunks / Ballerz, etc, so that more communities can use Drizzle
- Support Merkle Drop for large-scale airdrop
- Support Fungible Token Raffle
- Support More Verifiers like Find Verifier, Flowns Verifier, Flovatar Verifier etc, so that the projects and start DROP and raffle which is limited to their holders.
- Support Score-based weighted multiple verifiers & token distributors, so that the projects can create a much more flexible DROP/Raffle
- add Group feature as the interface to other projects like DAO generators, so that the operators can have a preset whitelist for creating DROP or Raffle

## Impact

- In what ways does this benefit the broader Flow developer ecosystem?
    - These tools will make the builders and operators in the ecosystem work in a more efficient and transparent manner.
    - Drizzle itself is a good example to show the “composability” among projects #onFlow: Drizzle use FLOAT to verify eligible users, and support the Geeft Raffle, Geeft itself can have some Fungible Tokens or Flovatar or any other NFTs in it.

# Milestones and funding

> Note: You can leave the USD proposal empty / "TBD". Please consider adoption and/or maintenance milestones at the end of your project.
> 

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Support .find and .fn domain(both display and whitelist)  | Function available on website | 1 week | May need support from .find and .fn teams | 2000       |
| 2 - Support more projects for raffling like NBATopShot / Flunks / Ballerz, etc, so that more communities can use Drizzle | Support more than 10 NFT types (3 now) | 1 month  | May need support from NFT projects | 8000        |
| 3 - Support Merkle Drop for large-scale airdrop  | Function available on website | 2 weeks  | May need more time | 4000           |
| 4 - Support Fungible Token Raffle  | Function available on website | 2 weeks  | May need more time | 4000           |
| 5 - Maintenance  | Fix bugs/ Support / Cloud Service Maintenance | 1 year  |  |  6000           |
| 6 - Adaption | more than 10 communities have used Drizzle | 3 months after completion | | 5000 |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Lanford33 | Full-Stack Engineer | ... | email: lanfordcai@outlook.com <br /> discord: lanford33#2178 |

**Comment by alxflw** [comment]
thanks for the submission @LanfordCai! we're going to review this and get back to you soon

**Comment by alxflw** [comment]
@LanfordCai after first review, we'd suggest you split this up into two grant applications - one for each tool. Can you also add a USD proposal to the list? thanks!

**Comment by LanfordCai** [comment]
@alxflw Hi! I have split this into two applications, this one is for Drizzle, and https://github.com/onflow/developer-grants/issues/79 is for Bayou! Thank you!

**Comment by LanfordCai** [comment]
@alxflw Hi! Are there some feedbacks to me so that I can make necessary changes?

**Comment by alxflw** [comment]
sorry for the wait @LanfordCai - we're still gathering feedback to make a final review. please stay tuned. thanks!

**Comment by chrisackermann** [comment]
Hi @LanfordCai!  Thanks for your patience - apologies that it took a little time to review with the right folks.

The proposal looks great!  We have a few light pieces of feedback/questions for you:

>Support .find and .fn domain(both display and whitelist)
Are there any specific use cases that you already have in mind for this?

>Support more projects for raffling like NBATopShot / Flunks / Ballerz, etc, so that more communities can use Drizzle
What are the current challenges of onboarding NFT collections through Drizzle?

Lastly - can you please add a milestone that is tied to some level of adoption of the these tools?  Perhaps an adoption milestone that is triggered when you have a certain number of projects that have used them?

**Comment by LanfordCai** [comment]
Hi @chrisackermann, thank you for your feedback!

1. .find and .fn domains are very popular in Flow community, they can be used as a short name of people's Flow address, it will be make drizzle's pages more readable to users, and also make some operations more easily and convenient(e.g. add lanford33.fn to the whitelist directly rather than my Flow address)
2. Some projects haven't fully implemented the standard defined in NFTCatalog(an example is TopShot at the time this proposal created -- they didn't implement the display view so that it was impossible to get the thumbnails of the NFT), and the NFT withdrawal is hard at that time(haven't check the condition now), like Flunks, I can't withdraw them from dapper wallet to do the test. All in all, there are problems like this and that, for some problems I need the help from the NFT projects.

**Comment by chrisackermann** [comment]
Hi @LanfordCai, thanks for these replies!

In terms of the list of features, could we please scope this proposal down to the feature additions that will address the biggest pain points at the moment?  It seems like Milestones 5-8 could be longer-term improvements that we could perhaps break out into a follow-on grant after completion of this one.

Also on support - can you please propose a specific length of time for which you intend to provide support?

**Comment by LanfordCai** [comment]
Hi @chrisackermann !

I have removed Milestones 5-8 from this proposal and added the timeframe of maintenance! Thank you!

**Comment by chrisackermann** [comment]
Hi @LanfordCai, thanks for your patience!  I just wanted to let you know that we've accepted your proposal and will be following up directly via email with next steps.  Thanks!
