### ISSUE TITLE
Shopify token gate support

### ISSUE THREAD

**Issue by zxed** [onflow/developer-grants#70]
# Taco

# Developer tools / services

# Description

## Problem statement

- Target audience: ecommerce merchants and consumers who have flow nfts
- Token gated commerce is where access to products is locked to token holders, this could be early access, limited edition or nft holder only benefits. Merch stores who want to token gate their merch for nft members, have no easy way to do this with shopify.

## Impact

- In what ways does this benefit the broader Flow developer ecosystem? This adds additional utility to tokens with loyalty programs and reward/redemptions. We already have a shopify app that supports EVM; we are getting inbound interest to add flow in addition to EVM chain

# Milestones and funding

> Note: You can leave the USD proposal empty / "TBD". Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - MVP   | Smart Contract Interaction for token gate | 2 weeks  | - | TBD           |
| 2 - Adoption   | 1 large customer using this project | 4 weeks  | - | TBD           |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Zeeshan Sheikh | Full-Stack Engineer | ... | hello@taco.xyz |
| Jim O' Brien | Full-Stack Engineer | ... | hello@taco.xyz |

**Comment by alxflw** [comment]
hi @zxed. it seems like this grant is designed to add a feature to taco.xyz. Would you be open to pivot and create a general Shopify FLOW plugin that any developer could use? If not, we may suggest you [check out other project support opportunities on the ecosystem page](https://flow.com/ecosystemsupport).

**Comment by zxed** [comment]
@alxflw def open to do that in addition to adding to ours; would you happen to have a flow plugin example that I can reference - for Shopify we'd want to make sure that the plug-in we create and release is usable by other devs, in addition to marketing teams looking to use a non-dev plugin.

**Comment by alxflw** [comment]
yea, that is what we wanted to explore. I'm not too familiar with Shopify extensions and how it could be done, so would rely on your research/understanding. 

I suggest we close this issue and you open a new one for this new idea if you want to explore if further. Thanks!
