### ISSUE TITLE
Flow x CoinKit Integration

### ISSUE THREAD

**Issue by Fiftysven** [onflow/developer-grants#71]
# Flow CoinKit integration

# Developer tools / services

# Description

CoinKit is an on-chain Crypto Wallet made in Germany. It is available on iOS, Android and Web and Supports a various amount of cryptocurrencies as well as NFTs. It also provides the utility to add your Social Accounts to it and use/manage/receive/send crypto on these interfaces easily. You can already use our product at: https://app.coinkit.de/

## Problem statement

As a new user in today's crypto world, you can get overwhelmed very quickly. Assuming I want to send a small amount of cryptocurrency to a friend, I am quickly faced with a multitude of problems. Me and my friend have to choose from a variety of wallets and right after the download we face new obstacles. Entering an email address, setting a secure password, keeping the seed phrase protected (assuming I even know what a seed phrase is) and after transferring crypto to this wallet, asking for the recipient's address after he has gone through the same process.

## Proposed solution

CoinKit is a social Wallet and social media bot.

Coinkit is a social media bot born from the original idea of Bitcoin: Peer-to-peer micro transactions between individual users.

We make it easy to use cryptocurrencies with interfaces everyone is familiar with. Besides our own WebWallet and our Android and iOS Apps, users can interact with our bot through various social medias like Discord, Twitter, Telegram and WhatsApp. CoinKit allows anyone to send cryptocurrencies to everyone without a complicated regristration process. All in all CoinKit is you everyday wallet with a wide range of additional features on top.
You can do giveaways, small tips, gift codes, quiz games,monetization of tweets and even send NFTs! For an extensive list of features take a look at: https://wiki.coinkit.de/#getting-started

## Impact

Our wallet/bot makes it easy to bring aboard a lot of new users into the Flow ecosystem by lowering the barrier of entry. As you can see on our dashboard at https://app.coinkit.de/dashboard we have facilitated over 770k transactions to this date.

Additionally we would open source our JavaScript Adapters written for the integration of flow.

# Milestones and funding

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Integration   | Enabling all CoinKit functions for Flow | 2 weeks  | - | 15000           |
| 2 - Adoption   | First 10.000 tips using flow | 8 weeks  | - | 5000           |
| 3 - Maintenance   | Resolving issuing and fixing bugs | 12 months  | - | 10000           |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Oliver Ziegler | Backend developer | ... | o.ziegler@blockcurators.com |
| Sven van Gelder | Q&A | ... | s.v.gelder@blockcurators.com |
| Christian Ziegler | Backend developer | ... | c.ziegler@blockcurators.com |
| Waldemar | Frontend developer | ... | info@blockcurators.com |

**Comment by alxflw** [comment]
thanks for the submission @Fiftysven. we'll review and get back to you soon.

**Comment by alxflw** [comment]
hey @Fiftysven. Do you think you could make your wallet FCL-compatible [according to this specification](https://github.com/onflow/fcl-js/blob/master/packages/fcl/src/wallet-provider-spec/draft-v4.md)?

**Comment by Fiftysven** [comment]
Hey @alxflw , with this proposal we aim to implement FCL only to work with the transactions, interact with the Blockchain, etc. to allow custodial flow wallets within the coinkit ecosystem. This does not include functionality to interact with a dapp on the browser or on the phone for example.

In our opinion, these functionalities would go beyond the scope of the proposal. However, if desired, we could create a separate proposal for the advanced features after Flow is integrated into our ecosystem.

Let me know if you need any further information.

**Comment by alxflw** [comment]
Hi @Fiftysven, thanks for the response. We reviewed your proposal in detail - with your response in mind - and decided to pass on it because it is unclear if the anticipated developer ecosystem impact would be high enough.

Feel free to reach me directly on Discord in case you have further questions: `alx-flw.find#6198`.
