### ISSUE TITLE
FCL.Net

### ISSUE THREAD

**Issue by tyronbrand** [onflow/developer-grants#72]
# Fcl.Net

# Grant category

- Developer tools / services

# Description
My ambitious goal would be to support all the .NET offerings below.
![image](https://user-images.githubusercontent.com/44845449/185624569-8b7acbc1-0fef-4170-b3af-5b560094909d.png)

## Problem statement

- This tooling doesn't yet exist for .NET developers.

## Proposed solution

My thinking so far... 

Create a core library that will implement the FCL functionality.
This core library will need to be able to support platform-specific functionality to handle browser/iframe.

Something like the image below is what I'm thinking:
![image](https://user-images.githubusercontent.com/44845449/185624109-c6a3e6c2-d00b-461a-9a92-b230d4107f14.png)

The platform-specific packages will be very light, only containing the platform-specific code needed to launch a browser or iframe

I'm open to other ideas of course :)

## Impact

This will bring all the functionality that Flow has to offer to all the areas of .NET ecosystem!

# Milestones and funding

### FCL Core Package
| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| Authn | Support Authn services which will get user address and list of services | 1 week | - | 5000 |
| Authz | Support Authz services which allow dApp to request wallet provider to sign transaction | 3 weeks | - | 15000 |
| Utilize | Wrapper for .NET SDK, use [Query/Mutate](https://github.com/onflow/fcl-js/tree/8d356103db50a8e81415099fb64e62f7f05a1b44/packages/fcl/src/exec) | 1 week | - | 5000 |
| Proving Account | Proving Ownership of a Flow Account | 0.5 week | - | 2500 |
| Sign Messages | Ability to sign messages | 1 week | - | 5000 |
| Maintenance | Resolve bugs, issues, and maintain | 12 weeks | I can do more/less than the proposed timeline | 45000 |

### Blazor Package (IFRAME and POP support)
| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| Custom Strategy/UI implementations | Show UI based on the strategy  | 2 weeks | - | 10000 |
| Example project | Showcase FCL functionality  | 0.5 week | - | 2500 |

### MAUI Package (HTTP POST support)
| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| Custom Strategy/UI implementation | Show UI based on the strategy  | 3 weeks | - | 15000 |
| Example mobile projects android/iOS app  | Showcase FCL functionality  | 1 week |  -  | 5000 |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| [Tyron](https://github.com/tyronbrand?tab=repositories) | Full-Stack Engineer | Developer of the Flow.NET SDK | tyron.brand@gmail.com |

**Comment by alxflw** [comment]
thanks for submitting @tyronbrand - we'll take a look and get back to you soon

**Comment by alxflw** [comment]
hey @tyronbrand  - I heard you had a chance to align on the scope and potential milestones with our team? could you update the application with the details, so we can run a final review?

thanks!

**Comment by tyronbrand** [comment]
Hey @alxflw, 
I have updated the potential milestones and have arranged a meeting for next week to run through the technical details with your team so there is potential for some change, but I think I have covered it all. :crossed_fingers:

**Comment by alxflw** [comment]
great, thanks! can you also add the costs to the tables once you have a better understanding? thanks!

**Comment by tyronbrand** [comment]
@alxflw I have updated the proposal.

**Comment by chrisackermann** [comment]
Hey @tyronbrand - just wanted to let you know that we've accepted the updated proposal, thanks for your patience!  I'll follow up via email with next steps, thanks!

**Comment by chrisackermann** [comment]
This grant has been completed.

**Comment by chrisackermann** [comment]
This grant has been completed.

**Comment by chrisackermann** [comment]
This grant has been completed.
