### ISSUE TITLE
Project Toucans - DAO Fungible Token creation, management & fundraising tool

### ISSUE THREAD

**Issue by deneschonknecht** [onflow/developer-grants#74]
# Project Toucans 

# Grant category

- Open source maintenance

Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?: Yes
NOTE: This project will be led & developed by your friends at Emerald City DAO :) 

# Description
Toucans (https://toucans.app/) will be the first fungible token creation and management platform on the Flow blockchain that makes it easy for internet communities unlock the power of human-centric coordination. Toucans will allow anyone to create a DAO to fund an idea, project, or person – all via the power of web3 & the Flow blockchain.

## Problem statement(s)

**1. Lack of DAO tooling on Flow**

Unlike Ethereum which has a wealth of DAO token creation & management options, Flow currently lacks equivalent tooling. 

For example:
- if I wanted to start a DAO to fundraise for any community - I could use Juicebox https://juicebox.money/
- if I wanted to start a DAO as an investment club - I could use Syndicate https://syndicate.io/
- if I needed a full stack (albeit complicated!) DAO platform for any purpose - I could use https://colony.io/ or https://aragon.org/

**But all of these are built on Ethereum or other blockchains** - which means they a) come with the limitations & challenges of these Layer 1 blockchains AND b) are outside of the Flow ecosystem. This means that the Flow ecosystem (both projects & users) have currently have no easy-to-use DAO tooling and this has limited the formation of DAO communities on Flow.  

**2. Lack of integrated, user friendly DAO tooling & Education in general**
Today, even on other blockchains, most DAOs have to design or integrate tooling and infrastructure themselves before launch, and the bulk of these tools are overly complex and lack guidance on DAO considerations. The DAO tooling landscape is overly complex and spans a vast range of areas like reporting, treasury management, governance, payroll, communication, identity management, etc. We want to leverage the power of the Flow blockchain & ecosystem to make a one-stop platform for communities to easily fundraise & collaborate using fungible tokens. Our goal for this platform (both tooling & education) is to take DAOs mainstream in the same way Coinbase did for tokens and OpenSea did for NFTs. 

## Target Audience
We believe that Toucans will used by both existing projects on Flow as well as new communities entering the Flow ecosystem who want to utilise the power of human collaboration & tokenization in areas like:
- Art, Gaming & Music (commissioning & investing in new creative works)
- DeFi Protocols (using tokens as a voting metric to implement the protocol and financial changes)
- Investments & Fundraising (capital pooling to acquire both web3 assets like NFTs or virtual land & traditional assets like art, property, etc.)
- Social Missions (where the mission is aligned with charities, climate change, education etc.)
- Social Niches (for social interactions in communities like TopShot Collectors, P2E Gamers, Developers)

## Evidence for the need
The rise of DAO's which began in 2021 and has extended into 2022 is well documented. For example, there are almost 5000 DAOs in existance today that collectively hold $10B in their treasuries (data source: https://deepdao.io/organizations). 
Since announcing the intention to build Toucans, we have seen extremely positive responses from others wanting to utilize the platform - we have early expressions of interest from teams at:
- Animoca Brands (starting with Untamed Planet and 4 further DAO communities to follow)
- DAO EX MACHINA (who plan to launch an educational scholarship DAO)
- GENIACE (for their upcoming $GENI utility token)
- Other established projects in the Flow ecosystem like Flovatar, IncrementFi and SolarPups also have plans to launch their fungible tokens on Flow, and we are in discussions with them to use Toucans to do so. And at Emerald City we will be also be using Toucans to launch the native $EMERALD token!

We have been capturing expressions of interest in Toucans via the landing page https://toucans.app/ and have been very encouraged by the early sign-ups! 

## Proposed solution

At a high level, Toucans will: 

- Be a simple, fast and convenient token generator for fungible tokens 
- Require no smart contract programming 
- Allow the token creator to set custom token name, symbol and initial supply
- Give the creator 100% ownership of generated tokens (unless they are selling via a fundraise, in which case the contributor to the treasury will receive the tokens in proportion to their issuance rate)

At initial token creation, a DAO Token creator will need to determine if the token will be made available for purchase via a fundraising mechanism (financial token) OR if the token will initially have no economic value and be used for governance or rewards within a community (community token)

In V1 the Toucans dApp will fulfil the following core DAO functions:

- Create a DAO - Token Creation ((Allow anyone to create a token in one of 2 models - either Financial or Community Token)
- Create a DAO - Treasury Management (Set Tokenomics and manage Treasury - Financial Token only)
- Create a DAO - List & Promote a DAO (Allow anyone to create a DAO by providing full details of the goals & community)
- Invest in a DAO - DAO Discovery (Allow users to browse & discover DAOs on the Flow blockchain)
- Invest in a DAO - DAO Funding (Allow users to join a DAO by purchasing the project token - Financial Tokens only)

Some images of the Toucans UI we have already designed:

Home Page
![image](https://user-images.githubusercontent.com/100309336/185796645-e08c6557-5ab9-4bc8-93f7-66068130b91a.png)

DAO Token Creation UI flow:
![image](https://user-images.githubusercontent.com/100309336/185796957-d8d108f0-f55c-44e1-a89a-70440542d663.png)
![image](https://user-images.githubusercontent.com/100309336/185797006-2e9f0ff2-b558-4055-91f4-064f5b3a0da9.png)
![image](https://user-images.githubusercontent.com/100309336/185797032-0a040034-be06-4ef4-8927-0d6f59ce9bc5.png)
![image](https://user-images.githubusercontent.com/100309336/185797049-ed75dca2-51a8-4cc5-89e7-89b6a8f37e44.png)
![image](https://user-images.githubusercontent.com/100309336/185797061-591cb00d-79f5-4b77-a891-928f5415643a.png)

Toucans will also include beginner & advanced DAO educational content to educate creators & participants of these communities about the foundational concepts behind DAOs. This will take the form of tutorials (written & audio/video content).  

## Impact

- In what ways does this benefit the broader Flow developer ecosystem?
Toucans will fill an important gap in the Flow ecosystem - giving any project the ability to generate a fungible token for a multitude of DAO style use cases. This will attract interest from within the existing Flow community of projects & users - as well as bring new users into Flow who want to form tokenized communities & fundraising collectives. 

In addition, Toucans will aim to integrate & leverage other Flow projects & tooling - e.g. 
- Identity - .find and EmeraldID
- Foundational Treasury Management (i.e. Wallet support) - Blocto 
- Advanced Treasury Management - multi-sig wallet (being built by Dapper Collectives)
- Voting - off-chain voting (CAST built by Dapper Collectives) 
- Proof-of-Attendance - FLOATs

# Milestones and funding

> Note: You can leave the USD proposal empty / "TBD". Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Core dApp Logic Development  | Smart Contract transactions & scripts | 3 weeks  | - | 10,000           |
| 2 - UX Design  | Finalize initial designs | 2 weeks  | - | 2,500           |
| 3 - UI Development   | Front end development of the dApp | 4 weeks  | - | 20,000           |
| 4 - Integrations  | Integrate with 3rd party DeFi platform (IncrementFi) for token listings | 4 weeks  | - | 10,000           |
| 5 - 3rd Party Auditing  | Engage a trusted 3rd party to ensure core logic in token contracts | 2 weeks  | - | 10,000          |
| 6 - Go-Live!  | Complete Beta Testing & launch User Tutorials | 2 weeks  | - | 5,000          |

`NOTE: Toucans will be funded for ongoing development & maintenance beyond launch via a small % platform fee for all token sales hosted on the platform. This will be the responsibility of Emerald City.`

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Jacob Tucker | Smart Contract Engineer | Founder of Emerald City DAO| jacobtucker818@gmail.com |
| Dene Schonknecht | Product Designer | Founder of GENIACE (existing NFT marketplace on Flow) | dene@geniace.com |
| Mateo Roldos | Full-Stack Engineer | ... |  |
| Emerald City Building Guild | Various Roles | Emerald City has built FLOAT, Emerald ID & Bot etc. |  |

**Comment by deneschonknecht** [comment]
@alxflw - I'm sure you are busy & there have been a lot f grant submissions, but any chance we can get acknowledgement and some indication of the timing of the review on this? Thanks

**Comment by alxflw** [comment]
hey @deneschonknecht - thanks for the follow up. we've had a chance to review this proposal in detail and we'd love to accept it! I'll follow up with you via email with next steps!

**Comment by deneschonknecht** [comment]
Thanks so much @alxflw ! Looking forward to working with you & the team on this!

**Comment by deneschonknecht** [comment]
Hey @alxflw - we have been making some progress on the smart contracts (via @jacobtucker) and the front end too - here is a sneak peek! 
![Toucans Home Page - v1 5](https://user-images.githubusercontent.com/100309336/191092574-b782c45e-e403-4522-9ef6-f62673d50cd8.png)

**Comment by deneschonknecht** [comment]
hey @alxflw - been emailing you to get the grant documents. Just pinging you here in case you have missed my emails.

**Comment by chrisackermann** [comment]
Hi @deneschonknecht - everything is all good to go, please let us know if you need anything else!

**Comment by deneschonknecht** [comment]
A little more UI preview for you @chrisackermann https://tinyurl.com/5n7s7xd5 :)

**Comment by jacob-tucker** [comment]
Hi @chrisackermann !

Following up here after what seems like forever, but with good news: We have made tremendous progress, and actually implemented so many more cool features than what was originally intended.

We have completed the smart contract work, finalized initial designs, and completed most front end development of the app.

We have a demo link here: https://project-toucans-v2.vercel.app/

Not only do we allow for people to generate DAOs and create their own token, but we also introduced multisig treasuries. This means people can spin up their own multisig actions like withdrawing, adding new signers, etc.

I'm not sure if we are able to claim part of this bounty for the work done so far, but would be great to keep momentum going. Thank you! :D

**Comment by chrisackermann** [comment]
Hi @jacob-tucker - amazing, thanks for the update!  We'll review this deliverable against the milestones and follow up shortly.

**Comment by jacob-tucker** [comment]
Hello @chrisackermann ! We have officially completed Milestones 4, 5, and 6, concluding this bounty.

For #4, we have gotten tokens listed on Increment.Fi. The most popular example is $LOPPY, which is already trading on there.
For #5, we audited all of our contracts through Shield.
For #6, we have officially launched here: https://toucans.ecdao.org/ and have published documentation here: https://docs.ecdao.org/products/toucans

Let me know if there is anything else we can do 🙏

**Comment by alxflw** [comment]
congrats, @jacob-tucker. awesome launch! the milestones are marked as accepted and payment will be scheduled for the upcoming cycle :)
