### ISSUE TITLE
UNTAGGED gamified and tokenized application for fashion resale and digital fashion

### ISSUE THREAD

**Issue by gayleharrison** [onflow/developer-grants#75]
**Grant Category:**  
Developer tools / services

**Description:**
Development of UNTAGGED browser based digital fashion NFT marketplace to MVP with Simpleweb (our developers), utilising Open Format dApps (https://openformat.simpleweb.co.uk/https://github.com/simpleweb/open-format) and Flow.

**Problem Statement:**
The fashion industry is responsible for 10% of global CO2 emissions, we buy twice as many clothes today as we did in 2000 and wear them for half as long.  There is a desperate need to change consumer behaviour, buying a used physical item reduces its carbon footprint by 82% (ThredUp), whilst digital fashion items use 97% less CO2 to make than their physical counterparts (DressX).
 
At UNTAGGED we want to accelerate the uptake of fashion resale and digital fashion to change habits that can have a real and sustainable impact.  Our mission is to reduce the amount of new clothes people buy, by making fashion resale and digital fashion more fun and addictive than fast fashion.

**Target Audience:**
With 2.56 billion Gen Zs soon to hit the global market, digital natives are reshaping the future of shopping and digital ownership of commodities as we know it, connecting with this younger generation of consumers is crucial.  

Our target audience includes;

Gen Z:  12 million UK, 2 billion worldwide.
Conscious Fashionistas:  Diverse 18-24yr olds who love the High Street but feel guilty about shopping
Shein Haulers:  Diverse 15-18yr olds who want to access cheap clothes in volume, and copy influencer looks
Customisers:  Diverse 21-25yr old creators seeking one-off finds, to customise their clothing
Gamers:  45% of the global market are women, who are predominantly millennials and gen Z’s revealing themselves to be fashion consumers eager to spend in app. 
Digital Fashionistas + Influencers:  Diverse 18-25yr olds who see digital fashion as “greener” than traditional retail who sell digital fashion without having to send actual products.
3D Fashion Designers:  Diverse 18 - 25yr olds who create digital fashion.   

**Evidence for the need:**
Fashion resale marketplaces like Vinted and Depop are based on traditional, transactional resale marketplace models first developed by Ebay 30 years ago.  In the digital fashion space, marketplaces offering digital wearables and digital fashion NFTs are enabling unique ways for people to interact with fashion online.  DressX, The Fabricant, The Dematerialised and The Replicant have a wide set of digital clothing available, from digital-first houses, to NFTs created by IRL-first designers, and unique one-off originals. These marketplaces tend to cater towards luxury brands, and/or well-known contemporary brands, and there can be a preconception that they cater to 'niche' audiences.  UNTAGGED is a unique gamified, tokenized and social marketplace application, that offers an integrated approach to trading both physical fashion resale and digital fashion.  We offer a streamlined application to reduce friction - making it easier for our community to build their hybrid wardrobes in a sustainable, efficient and affordable way.  UNTAGGED is the ONLY integrated marketplace application, that lowers the barriers to entry, to make it easy for anyone to join in to trade physical fashion resale and digital fashion.  

**Proposed Solution:**
UNTAGGED is a gamified, social and tokenized app for fashion resale and digital fashion - with sustainability at its core.  We are using innovative technologies to create an integrated approach and experience for our community to trade both physical fashion resale and digital fashion items. UNTAGGED offers a streamlined application to reduce friction - making it easier for our community to build their hybrid wardrobes in a sustainable, efficient and affordable way.  At UNTAGGED our players complete missions, and participate and interact with a like-minded community of sustainably-minded fashionistas, to earn tokens that can be used to trade preloved fashion, or create digital fashion items in our marketplace.  These tokens can also be exchanged for redeemable discounts and coupons that we make available to our community through our brand partners.  The UNTAGGED app takes a disruptive approach to the traditional fashion resale marketplace model, by using gamification and tokenization mechanics to drive a sophisticated gamified barter system, where ‘real money’ is de-prioritised and people’s pre-loved clothing and digital fashion items become token currencies to trade and use in-app.   These mechanics create an engaging experience to drive regular usage to speed up the trading of fashion resale and digital fashion items, creating a circular and sustainable fashion resale system.  UNTAGGED lowers the barriers to entry, and makes it easy for anyone to join in to trade physical fashion resale and digital fashion items.  At UNTAGGED we are on a mission to achieve realistic and sustainable results that can have a lasting environmental impact.  

The UNTAGGED iOS app launched in Feb 2022. In three months (February - May 2022) our active and engaged community grew on average +30% month on month.   UNTAGGED is now testing and utilising blockchain technologies to develop our browser based digital fashion NFT marketplace and smart contract protocols, which will expand our overall core activities and features - and multiplatform application.  We are looking to leverage our digital audience, to bring digital fashion awareness to our existing non crypto community, to focus on affordable digital fashion items that are easily tradable both on and off platform, at minimum cost to the user.  By doing this, we are building and enabling a community to trade both physical and digital fashion items in a sustainable way to complement both physical and digital lives and hybrid wardrobes. 

We are currently developing/ testing our Digital Fashion NFT Marketplace application with [Open Format](https://openformat.simpleweb.co.uk/) - which is powered by Simpleweb (our Developers).  Open Format is a protocol which is compatible with multiple tools and frameworks. We would like to build/develop Open Format to support the Flow ecosystem, and to create a highly customisable digital fashion NFTmarketplace.  
For more information please see: 
https://openformat.simpleweb.co.uk/ https://github.com/simpleweb/open-format

**Impact**
With user adoption in mind, overall project success is based on our ambition to convert 10% of 12M UK Gen Zs wardrobes into digital fashion - representing a saving of 873k tonnes of CO2 annually.   

In addition to what we bring as a company, the open source tools that we develop with Simpleweb (Open Format) on Flow, will enable anyone to build an NFT ecosystem that is trustless, permissionless and collaborative - including, decentralised marketplaces, and ticketing and video platforms, for trading NFTs.  We see these dApps and tools as benefiting the wider Flow ecosystem and its many users, and we want to empower a community to easily develop dApps on Flow.  

**Milestones and funding**

Milestone 1: Development of digital fashion NFT marketplace (MVP-BETA)  ($125k)
Timeline: 12 weeks
Risk:  Timeframe (impacted by SimpleWeb team schedules, resolving issues, not securing adequate funding to support development).
Maintenance: (ongoing / recruitment for in house team $TBD)
Deliverables:
Planning, design and development of a digital fashion NFT marketplace MVP with Simpleweb (Open Format) and Flow.  Open Format is a protocol, which is compatible with multiple tools and frameworks. 
UI/UX:  Features to include storefront, buyer, seller, administrator panels, listing and bidding portal, search engine, filter options, built-in wallet, and customisation features.
Development of smart contracts and automated testing
Determine scalability, performance, and maintainability.
Integrate secure hosting infrastructure
Mitigating the top application security risks.
Smart wallet integration and testing.
Integrate payment API (fiat/crypto payment methods)
Troubleshooting, and testing.
Beta testing (first 100 users)
Launch event 
 
 
Milestone 2: Integrated iOS app and Digital fashion marketplace launch ($75K)
Timeline:  10 weeks
Risk:  Timeframe (impacted by team schedules, resolving issues, not securing adequate funding to support development, user adoption rate, interoperability concerns).
Maintenance: (ongoing / recruitment for in house team $TBD)
Deliverables
Improved UI/UX and customised features 
Integrated features (multiplatform)
NFT management, inventory management
Integrated brand rewards suite (onboard first 5 partners)
Ecosystem interoperability (maintain)
Troubleshooting, and testing
Define parameters and develop NFT membership.  
Ramp up users

**Team**

Our core leadership team each have over 20 years of relevant experience, covering Web3/blockchain, gaming, marketing, strategy and general management and are experts in our respective fields. We also have extensive experience in start-ups, and collectively we are deeply committed to building an innovative sustainable business, which can have a real and lasting impact on the environment.

Gayle Harrison, Founder and CEO. Gayle has 20 years' experience in general management, innovation, marketing and strategy for global consumer goods brands. She has built and grown much-loved brands around the world.
https://www.linkedin.com/in/gayle-harrison-5b39b38/
gayle@untaggedfashion.com 
Mobile:  +44 7903 560 770

Mark Panay, Co-Founder. Mark has been involved in future tech since the late 90’s. He delivered one of the first open source projects for the UK Government, has been involved in the launch of 100’s of digital products, and invested in over 30 web2 and web3 startups through Simpleweb, a venture tech agency he co-founded in 2008.
https://www.linkedin.com/in/markpanay/ (https://github.com/simpleweb/open-format; https://github.com/simpleweb/open-format-contracts)

Debra Stewardson, CTO. Debra is an XR strategist and tech focused entrepreneur building interactive and immersive experiences. She brings 20+ years of experience gained in international, and start up entertainment companies.  
https://www.linkedin.com/in/debrastewardson/

Nicola Jenkins, CMO. Nicola is an experienced CMO from the entertainment and games industry, previously at Tomy and EA Games where she led the European marketing for The Sims. More recently she has helped build consumer audiences for consumer startups.
https://www.linkedin.com/in/nicola-jenkins-55b4642/

Development Team:  Simpleweb are our dev team, who over the last year have built an in-house team specialising in Web3/blockchain technologies.   The team has successfully developed & launched dApps see here:  https://openformat.simpleweb.co.uk/# <Project name>

**Comment by gayleharrison** [comment]
Please find below the link to our lightpaper (and pitch deck):
https://drive.google.com/file/d/1qRM5jeB5aXpp_hh8wdqZO9C5_OtVcRSP/view?usp=sharing

**Comment by chrisackermann** [comment]
Hi @gayleharrison, thanks so much for your proposal!  We really appreciate the time that you put into this application - however, we have decided to pass on this proposal, since it's unclear of the impact that this project will have on the Flow developer ecosystem.  

Separately, I had followed up via email as well - please let me know if you have any further questions.
