### ISSUE TITLE
Carbon emissions reporting for FLOW

### ISSUE THREAD

**Issue by arindale** [onflow/developer-grants#76]
# Emissionless

# Grant category

- Developer tools / services

# Description

Daily electricity and carbon emissions reporting for the FLOW blockchain

## Problem statement

- In February 2022, Deloitte completed its **[Annual Energy Consumption](https://www.onflow.org/post/flow-blockchain-sustainability-energy-deloitte-report-nft)** report for the FLOW blockchain and concluded that the entire energy footprint was 180 MWh. Using industry assumptions, this would generate approximately 72 tonnes of CO2 emissions. It would conservatively cost $1,080 to offset that carbon footprint 
- Given the magnitude of the cost, Emissionless recommends that the FLOW blockchain enacts a policy to offset its entire carbon footprint to become one of the world’s first carbon neutral blockchains, rather than allow individual projects to offset their individual carbon footprint as suggested in **[Issue #16](https://github.com/onflow/developer-grants/issues/16)** 
- For FLOW to gain credibility as a carbon-neutral blockchain, its energy and carbon footprint must be monitored regularly with data available in a transparent way to the public. Emissionless proposes a solution that provides transparent daily reporting of the FLOW blockchain energy and carbon footprint for internal and external users

## Target audience

- FLOW Blockchain: “Come build #onFLOW, one of the world’s first carbon neutral blockchains”
- dApps on FLOW: “NBA Top Shot is a carbon neutral FLOW project”
- External users (e.g. NFT owners, press, academia): “The entire FLOW blockchain uses less electricity than 17 average homes in America. And 100% of its carbon footprint is offset”

## Evidence for the need

Timely, transparent, and easy-to-understand energy and carbon tracking are necessary for FLOW to gain global acceptance as a carbon-neutral blockchain. Most blockchains have an existing project that actively quantifies their carbon footprint.

- *[Cambridge Bitcoin Consumption Index](https://ccaf.io/cbeci/index)* provides daily carbon and electricity estimations for the Bitcoin blockchain
- *[Ethereum Emissions](https://kylemcdonald.github.io/ethereum-emissions/)* by Kyle McDonald provides daily carbon and electricity estimations for the Ethereum blockchain
- Polygon has quantified its carbon impact *[and has already committed to offsetting its carbon impact](https://blog.polygon.technology/polygon-is-going-carbon-negative-in-2022-with-a-20-million-pledge/)*
- Solana quantifies its energy use and *[reports it on a monthly basis](https://solana.com/news/solanas-energy-use-report-march-2022)*
- FLOW engaged Deloitte to quantify its carbon impact for the 2021 calendar year.  

## Proposed solution

Emissionless quantifies both the energy and carbon footprint for the entire FLOW blockchain on a daily basis. 
Wireframe of Emissionless’ proposal

![Co2 emissions](https://i.imgur.com/sXSiclK.jpeg )

Emissionless will go one step further and accurately estimate the carbon footprint of each dApp. Below is a sample wireframe showing NBA Top Shot’s energy and carbon impact. 

![dapps ](https://i.imgur.com/Gd1CLr1.jpeg)
## Impact

- FLOW will have an independent company (Emissionless) verifying its carbon footprint in a transparent manner
- The top 100 smart contract on FLOW will be able to clearly show that their blockchain transactions are carbon neutral via a link to the emissionless website

## In what ways does this benefit the broader Flow developer ecosystem?

- All dApps #onFLOW will be able to market their project as carbon neutral
- Top 100 dApps will have a direct link to emissionless’ website that calculates their carbon footprint

# Milestones and funding

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 – survey node operators | Survey node operators for data required to estimate their energy usage | 4 weeks  | Data required from third parties | $12,000      |
| 2 - collect data | Build a node indexer and / or an access node and pull existing FLOW transaction effort data into a database (TBD best approach) | 4 weeks | - | $12,000 |
| 3 – develop model to calculate carbon footprint | - Develop model to calculate the total energy and carbon footprint of the FLOW blockchain on a daily basis, with corresponding confidence bands <br/>  - Document methodology into a publicly accessible “Methodology” paper which outlines the framework used to calculate carbon emissions and electricity usage | 6 weeks | - | $18,000 |
| 4 - web app design | Complete Figma design for public-facing website that shows total energy consumption & carbon footprint on a daily basis, and calculates the annual carbon footprint of each of the  top 100 dApps | 2 weeks | - | $6,000 |
| 5 - web app build | Build all functionality for the web app as designed in Milestone 4 | 6 weeks | - | $18,000 |
| 6 - web app testing| Test and release web app | 1 week | - | $14,000 |
| 7 - ongoing support & maintenance | This project is intended to be ongoing in perpetuity as manual work needs to be done to evaluate new smart contracts and nodes will change over time. Ongoing support is expected to fall to 0.5 FTE. | ongoing | - | $5,000/month |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Paul Foreman| Project Lead | Carbon Accountant, CPA, Former Deloitte Auditor |paul@proimagery.com |
| Nash Prado| Carbon Data Expert | Engineer, expert in carbon modeling | nash@proimagery.com |
| Victoria Rejuso| Carbon Data Expert | Engineer, expert in carbon modeling | victoria@proimagery.com |
| Rodger R| Full stack engineer | 10+ years experience in software development |  |
| Akos E| Advisor | Engineer graduating in Germany, years in software development, technical leadership, and architecture |  |

**Comment by alxflw** [comment]
thanks for the submission @arindale - we're going to review this and follow up soon. In the meantime, could you also add the proposed USD to the milestones? thanks!

**Comment by arindale** [comment]
@alxflw thank you for getting back to us - we've added proposed USD milestones. We await your feedback, thank you!

**Comment by alxflw** [comment]
thanks @arindale!

**Comment by chrisackermann** [comment]
Hi @arindale, thanks again for this proposal!

We'd love to scope this a bit more tightly to what an MVP might look like in order to validate the solution.  Would you mind refreshing this proposal a bit more to that regard?  Thanks!

**Comment by arindale** [comment]
Thanks @chrisackermann for following up.

We would be happy to revise the scope. But to make sure we are on the same page, I would just like to clarify your expectations for the ideal MVP based on your vision.

There are 4 main steps in the original proposal:
1)	Quantify the energy & carbon footprint of the entire FLOW blockchain (Milestones 1 and 3)
2)	Allocate the energy & carbon footprint across dApps based on pro-rata share of execution effort (milestone 2 and part of milestone 3)
3)	Design, test and launch a website (Milestones 4, 5, 6)
4)	Ongoing revisions to the model as changes to nodes, dApps and the blockchain itself evolve)

The easiest way to tighten the scope would be to pull out Step 2 above (allocate the energy & carbon footprint across dApps). Doing so would drop the build time from 23 weeks to 16 weeks. The website would be much more streamlined and be focused on the top image of this proposal (FLOW Blockchain Emissions (Annualized)).

After the successful completion of the project, we could add back the allocation of energy & carbon footprint across dApps.

Thanks!

**Comment by arindale** [comment]
Apologies - misclicked :)

**Comment by chrisackermann** [comment]
Thanks so much @arindale!  Will get back to you shortly.

**Comment by chrisackermann** [comment]
Hi @arindale, thanks so much for your patience and for taking the time to share/update this proposal.  

We've reviewed in detail and have decided to pass since the direct impact on the developer ecosystem is not clear enough at this stage. 

Feel free to reach out on Discord in case you have further questions: chrisa#6592.
