### ISSUE TITLE
Closed due to lack of interest or support

### ISSUE THREAD

**Issue by justjoolz** [onflow/developer-grants#78]

**Comment by alxflw** [comment]
thanks for the submission @justjoolz. we'll review this and get back to you soon

**Comment by alxflw** [comment]
@justjoolz could you update the application to 1) set more accurate timelines and 2) add the USD proposal for each? thanks!

**Comment by justjoolz** [comment]
done

> @justjoolz could you update the application to 1) set more accurate timelines and 2) add the USD proposal for each? thanks!

Thanks for the review, I've updated the timelines and usd proposal 
thanks!
