### ISSUE TITLE
Flow NoCode Apps

### ISSUE THREAD

**Issue by iwe90** [onflow/developer-grants#80]
# <Project name>

# Grant category

Developer tools / services
( & Educational material)

# Description
We plan to create NoCode Apps for the Flow Ecosystem so that everyone (not only developers) can access, work & interact with the Flow Blockchain Ecosystem.

## Problem statement
Accessing data from the blockchain can be a complex process and pose a challenge especially to users who are not proficient coders. For instance, accessing individual transaction data is possible via individual display options, but tiresome and may not provide a useful format that non-coders can creatively and flexibly use.

## Proposed solution
In other contexts involving large-scale data queries and data management, NoCode tools have been gaining in popularity. Our plan is to build a set of NoCode modules for the Flow ecosystem. By using popular NoCode platforms such as Make or Zapier, we can create an accessible entry for both casual users and potential new developers. Overall, these NoCode modules have to potential to make Flow even more attractive to both users who are new to the blockchain technology and developers who want to generate creative solutions fast.

Demo Video: https://www.loom.com/share/7dac988f02ef4505be22a37382bc6a37

PS: Yesterday we talked to Jillian Salant from Dapper Labs who recommended we apply for this grant.

## Impact
 
The aim is to make the modules and the resulting solutions available and accessible to literally everyone in the Flow community- and to everyone interested in joining it. Every single community member will be enabled to quickly and easily build dashboards, tracking apps, tax apps, notification apps, Discord bots and much more, either for personal use or for broader use across the entire community.

# Milestones and funding

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Ecosystem Research   | List of NoCode solutions to build based on community research. | 2 weeks  | - | - |
| 2 - Platform Research   | Systematic evaluation of possible NoCode platforms to build on. | 1 week  | - | - |
| 3 - Development   | Develop selected NoCode apps, e.g., whitelist of token holders, daily commission earned through secondary sales.| 18 weeks  | - | 25,000 |
| 4 - Workflow templates   | Create templates of workflows which are useful for, e.g., the NFT community or the standard Flow user, such as easy to build custom NFT/Token dashboards, transactions export and import into tax software. | 3 weeks  | - | 5,000 |
| 5 - Optional   | Work with a Flow-based company and implement some useful workflows for them, which will later be published as templates for everyone to use. | 6 weeks  | - | TBD |
| 6 - Publication of solutions   | Once created, the apps will be made available using a public URL and will continuously be published officially on the respective NoCode platform. | continuously  | - | - |
| 7 - Educational content   |  Creation of educational content on how to use apps and workflows, e.g., blogposts or videos. | 6 weeks  | - | 15,000 |
| 8 - Maintenance   | Ongoing support for apps if underlying APIs change. | continuously  | - | - |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Ivonne | Project Lead | Ivonne is currently doing her PhD in cognitive Science and has a background in scientific programming and cross-discipline communication. | [Ivonne.weyers@gmail.com](mailto:Ivonne.weyers@gmail.com) |
| Richard | Lead Developer | Richard is a NoCode power-user who has developed several custom apps before. He recently finished his Master's degree in Finance and has been in love with DeFi since then. | [Richard.Ahrend@gmail.com](mailto:Richard.Ahrend@gmail.com) |

Together, we understand the challenges of complex new technologies and would love to make Flow more accessible to everyone.

**Comment by alxflw** [comment]
thanks for the submission @iwe90. we'll review and get back to you soon.
