### ISSUE TITLE
Dynamic NFTs

### ISSUE THREAD

**Issue by jacob-tucker** [onflow/developer-grants#82]
# Dynamic NFTs

# Grant category

Please select one:

Open source maintenance

# Description
I want to develop a smart contract that allows for dynamic updating of NFT metadata. This contract would also act as a baseline standard for all future projects to implement dynamic NFT metadata as well. 

## Problem statement

- Target audience
The target audience for this is projects who want to have dynamic updating of NFT metadata. For example, this smart contract would allow for updating metadata when a common goal is reached in a community, when a user strikes an achievement or performs some action, when a certain on-chain fundraising goal or other on-chain trigger is met, when an NFT is resold, etc.

- Evidence for the need
There are projects in need of figuring out how to solve this issue but there is no standard or common place to seek this type of behavior in a contract. Further, by moving beyond a standard NFT model with locked metadata, projects are unlocking additional potential use cases for their assets and community. 

## Proposed solution
I will design a smart contract, similar to the accepted ExampleNFT contract, that allows for dynamic updating of NFT metadata by exposing an ability to do this by an Admin in the contract.

## Impact

- In what ways does this benefit the broader Flow developer ecosystem?
It will allow entities such as Dapper/Flow to have a common way to solve this dynamic issue across their projects, as well as other Cadence developers to see how to update NFT metadata dynamically in a contract.

# Milestones and funding

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 0 - Technical | Smart Contract, Transactions, Scripts | 3 days  | - | 2500           |
| 1 - Adoption   | A GitHub repository with detailed explanation on how to adopt this standard and use it as an Admin in your community, including a step by step walkthrough of what actions you'd have to take. A blog that defines dynamic NFTs and describes their importance, with a guide explaining how to spin up a dynamic collection on Flow. | 1 week  | - | 1500           |
| 2 - Maintenance and Support | Assistance supporting implementation of smart contract, availability to answer questions regarding the contract, transactions, setup, and other relevant subjects, resolution of bug fixes | 3 months  | - | 1000           |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Jacob Tucker | Smart Contract Developer | Founder of Emerald City DAO | jacobtucker818@gmail.com |

**Comment by alxflw** [comment]
thanks for the submission @jacob-tucker. we'll review and get back to you soon

**Comment by chrisackermann** [comment]
Hey @jacob-tucker, thanks for your patience!  Just wanted to let you know that we've accepted this submission and will be following up via email with next steps.  Thanks!

**Comment by chrisackermann** [comment]
Hey @jacob-tucker, thanks for the update!  Will review the two items from Milestone 2!

In terms of Milestone 3/maintenance, please follow back up at the end of the period with an update as we're expecting that you'll continue to address issues as they arise wrt the contracts/repo.  Thanks!

**Comment by jacob-tucker** [comment]
Hey @chrisackermann! Just following up at the end of the period to claim Milestone #3

**Comment by chrisackermann** [comment]
Hey @jacob-tucker!  Marking Milestone 3 as accepted and closing out this particular grant.  Thanks so much!
