### ISSUE TITLE
BALLHUNTER

### ISSUE THREAD

**Issue by Demonopoly** [onflow/developer-grants#83]
# Ballhunter

# GAMEFI

- Developer tools / services

# Ballhunter provides game scene & marketing service for PFP NFTs through NFT recreate & play station, We aggregates high-quality NFT Holders, link more web3 projects, aiming to become the game & marketing infrastructure with most NFT holders .
First game of our playstation is 2D battle royale just like PUBG. Players battle to earn ,Spectators bet to earn，Room owner earn tcikets fee & commision.

## Problem statement
- we provide more and better games for NFT holders ，help projects marketing & increase their NFT value.

## Proposed solution
- For PFP NFT hold，we create gamefi scene to earn & boost discord activy to fun，Such as Moonbirds battle
- For game guilds，Room battle give thems more freedom to define attract guild memebers to join in the game & earn more
- For web3 projects， Data marketing based on game users profile & asset evaluation system is useful, such as targeted airdrop

## Impact
-We hope to get the support of Flow, and we are also very valuable to Flow.Because Ballhunter as a Playstation can aggregate blue chip NFT holers.It is worth to mention that our beta game has been ready，You could take a try.

# Milestones and funding
1. Complete beta by Q3 2022
2. Launch four major marketing campaigns
A. blue-chip Battle (Azuki/Moonbirds/Phantabear/Clonex)
B. public chain Battle (Aptos/Sui/PlatOn/OKX/Avax)
C. Exchange Battle (Kucion/Okex/Binance/FTX)
D. Market Battle (1000+KOL/100+Guilds)
3. Launching NFT Marketplace is related to NFTFI
4. Launch the Ballhunter Club League
5. The second game Moba type login Play Staition
6. Launch the portrait data and value evaluation data system of NFT Holder open to Web3
50000usdt

> Note: You can leave the USD proposal empty / "TBD". Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| Room Mode Launch | Top PFP NFT refresh mint | 4weeks | ----------------------- | -------------- |
| Room Mode Launch | Key PASS & BHT issue | 4weeks  | ----------------------- | -------------- |
| Room Mode Launch | Guild Cooperation | 4weeks  | ----------------------- | -------------- |
| Club League | Club League Mode launch | 3weeks  | ----------------------- | -------------- |
| Club League | Rank & Quick Mode | 3weeks  | ----------------------- | -------------- |
| Club League | DEFI & NFTFI & SWAP| 4weeks  | ----------------------- | -------------- |
| Club League | Cross-bridge | 4weeks  | ----------------------- | -------------- |
| Top WEB3.0 infrastucture | More Gamefi kickoff | 8weeks  | ----------------------- | -------------- |
| Top WEB3.0 infrastucture | PFP NFT game scene service | 8weeks  | ----------------------- | -------------- |
| Top WEB3.0 infrastucture | Web3 user profile & evaluation | 8weeks  | ----------------------- | -------------- |
| Top WEB3.0 infrastucture | Targeted airdrop marketing |4weeks  | ----------------------- | -------------- |

# Team

| Name | Role                | Bio | Contact        |
Ocean | CEO | Paypal   PM , over 8 years in software engineering,leading localization and   translation,6 years experience in dapp and blockchain.
Fruite | CTO | EAGames   Senior manager of development, over 10 years EXP on systerm scaling,smart   contract engineer.
Jiayi | CMO | Bluefocus   Web3 marketing manager, Multi Media Artist with 6 years of experience in   creative product.
Jupiter | COO | Tumblr   operation maanger, 8 years experienced functional performance,security and   blockchain QA in many fields.

**Comment by alxflw** [comment]
hi @Demonopoly - is this directly attracting developers building on Flow? Are you providing any developer tools for them? If not, I think you this is not a fit for the developer grants program. I'd suggest you check out other avenues for funding on the [Flow ecosystem support page](https://flow.com/ecosystemsupport)

**Comment by Aliserag** [comment]
We appreciate your proposal and taking the time to fill it out. Given the time since this has been submitted I'm closing this down, please reach out to me if you'd like to share what you're working on now and explore potential opportunities [ali.serag@flowfoundation.org](mailto:ali.serag@flowfoundation.org).
