### ISSUE TITLE
Univoice

### ISSUE THREAD

**Issue by zjuybx** [onflow/developer-grants#85]
# Univoice

# Grant category

Please select one:

- [ ] Open source maintenance
- [x] Developer tools / services
- [ ] Educational material

# Description

Univoice aims to develop various intelligent voice services for NFTs and Dapps on Flow.  We innovatively combines AI and NLP technology with Flow blockchain, so that Univoice can provide Flow developers with an end-to-end voice solution, such as voice transformer for SocialFi and voice over NPCs for GameFi. Univoice is a technology-oriented and to-business project. In order to adapt to the distributed computing framework, we optimize traditional algorithms like text-to-speech,   voice conversion, and voiceprint extraction as ultra light weight algorithms. Univoice publishes its developer guide as soon as possible, and serves Flow projects with APIs and SDKs.

## Problem statement

Traditional intelligent voice services exist three problems:

- **Cost**:  The implementation from purchasing data, algorithm training, and deployment, results in huge upfront costs and high user fees.
- **Emotion**: The generated voices  are seriously mechanical, lacks rich human emotions, and destroys the immersive experience.
- **Visualization**: The combination with images and do not reflect the attributes of various dimensions of voice is lacked.

In the era of Web3, new problems have emerged:

- **Privacy**: Using one's own voice in web3 socialization may cause privacy problems and destroy the freedom and security of the Metaverse.
- **Value**: The intelligent voice services of Web 2.0 deprive voice owners and creators of the value, and is unwilling to share the value of storage and computing with the ecosystem.
- **Customization**: The voice service of Web2.0 lacks user participation and cannot reflect the user's self and personality.

## Impact

Univoice will provide intelligent voice services with APIs and SDKs.

- **Film & Television**: Users can customize different voices and emotions according to their needs. Emotions, voices and texts can be inserted into film and television works with the Univoice services, so that only one person can complete the dubbing tasks of all characters.
- **SocialFi**: SocialFi operators embed Univoice voice customization and conversion services, so that users can choose, buy or customize their voice in the social ecosystem. Introducing Univoice into SocialFi softwares will cause at almost no cost on developing.
- **NFTs**: Univoice can endow PFP with language ability and show the user's personality in the voice dimension. Univoice can empower PFP issuers to achieve differentiation. In the future, we will give virtual idol NFT the ability to interact autonomously, making it a real idol in Web3.
- **GameFi**: Univoice will be embedded in GameFi in the form of SDKs or APIs, and provide voice services for games, including role dubbing, NPC interaction. In the future, we will provide more powerful interactive services to empower virtual humans in Web3.0 to assume different roles: companion, assistant, housekeeper.

# Milestones and funding

| Milestone                                                    | Deliverables                       | Timeline       | Risks | USD proposal |
| ------------------------------------------------------------ | ---------------------------------- | -------------- | ----- | ------------ |
| 1 - Website development and deployment (Art design, front-end and back-end development) | Accessible website                 | 20 man-days    | -     | 5000         |
| 2 - NLP algorithms (TTS & VC) training & deployment          | Function trial (VC and TTS) on Univoice website | 20~40 man-days | -     | 30000    |
| 3 - Link Univoice to Flow blockchain | Function trial on Univoice website on Flow | 20 man-days | - | 10000 |
| 4 - API and SDK packaging, develop guide publishing          | Available APIs or SDKs, and develop guide documents             | 20 man-days    | -     | 10000        |
| 5 - Introducing Univoice to a to-B project on Flow | First Flow project using Univoice service s | 30 man-days | - | 10000 |
| 6 - System mantainance and algorithm iteration | Website, APIs and SDKs maintenance | 6~12 months | - | 15000|

Total $80,000 

Purpose of Funds: Funds will be used for initial algorithms, software and website development. Training AI and NLP algorithms is the main part of the costs for purchasing data and computing resources. Algorithm iteration is the second main part of the costs with storing more data and train the AI models continuously.

# Team

| Name   | Role | Bio  | Contact         |
| ------ | ---- | ---- | --------------- |
| Taffin | Co-founder / CEO / Chief scientist  | PHD of Zhejiang University, HW multimedia & AI expert, having a number of patents in the field of multimedia and AI, the cumulative sales of leading products is beyond $30M | ybx90@outlook.com |
| FrankFu | Co-founder / CTO / Full Stack engineer   | Postdoctoral Fellow of Zhejiang University, Senior Researcher, Full Stack Engineer, Member of IEEE Standards Committee, Kaggle Gold Winner  | fujunwei@zju.edu.cn |
| Train | Co-founder / COO / Marketing and operating expert  | Master of Zhejiang University. He works as a Product Manager in world top 500 company, and is responsible for products with annual revenue of 15 million for 5 years. | 006l@163.com |

**Comment by zjuybx** [comment]
Hi, @chrisackermann. Thank you for your reply.
Univoice, actually is designed as a decentralized intelligent voice engine, which is composed of the AI NLP technologies and the Flow blockchain. Univoice will support Flow with NLP algorithms, like Text-to-Speech (TTS), voice conversion (VC), emotion transfer (ET), question answering (QA) and image generation (IG):

- Text-to-Speech (TTS): Converting written text in natural language to speech;
- Voice Conversion (VC): Modifying the speech of a source speaker and making their speech sound like that of another target speaker without changing the linguistic information with a voice print;
- Emotion transfer (ET): Transferring the emotion of a speech without changing the linguistic information 
- Question Answering (QA): Domain-specific tasks like community question answering and knowledge-base question answering.  
- Image Generation: Generating the images and videos from the audio, songs and music. 

All the algorithms are academically available, more work need to be done on engineering and business.

In terms of functionality, Univoice will support different Dapps on Flow:
- For the NFTs: Univoice can energize the image and music NFTs with new forms. For image and video NFTs, Univoice can generate their unique voice and audio for NFTs with TTS & VC. Similarly, Univoice can visualize the music NFTs with IG. For virtual human and idol NFTs, Univoice can give them the communication ability as real human with QA. Besides, the voice print itself is a unique personal features and a natural NFT. 
- For SocialFi: Univoice can energize the SocialFi Dapps and web3ers to customize their sounds and voices with VC and convert the text to speech of a specific target with TTS & VC.
- For DeFi: Univoice can support an online customer service robot for decentralized exchange and other financial service providers with QA.
- For GameFi: Univoice can support the voice generations in games (TTS & VC). Besides, Univoice can drive the NPCs to communicate with the gamers (QA). 
- For the metaverse:  Univoice helps to launch virtual citizens of the metaverse, who can interact with metaverse citizens from real world, learn and evolve themselves independently, and participate in the social activities and operation and maintenance of the metaverse.

With Univoice, Flow will generate Dapps of more forms and lower the thresholds of multi-media technology. for Flow Dapp developers  Univoice can help Flow to attract more users and developers.

In terms of business mode, Univoice identifies the value of voices from three aspects: voice itself, exploring voice (using our intelligent voice service) and computation (NLP algorithm computation). Univoice will share the benefits with voice owners and creators. Further, Univoice will use a distributed computing framework and a storage framework to share benefits with miners (computing and storage providers).  Therefore, more people will join in Flow to create value together.

**Comment by chrisackermann** [comment]
Hi @zjuybx, thanks for the additional details and for the time to submit this proposal.

We've reviewed in detail and have decided to pass since the impact on the developer ecosystem is not clear enough.  

Feel free to reach out on Discord in case you have further questions: chrisa#6592
