### ISSUE TITLE
Infinity Wallet

### ISSUE THREAD

**Issue by InfinityWallet** [onflow/developer-grants#86]
# Infinity Wallet

# Grant category
Developer tools / services

# Description
Infinity Wallet is the first non-browser-extension, multi-chain all-in-one non-custodial wallet ecosystem of its kind on desktop, supporting over 170,000 users within August. Providing a one-stop solution for seamless usability of DeFi and NFTs, and a gateway to the world of DApps directly within the wallet’s Web3 browser, fulfilling all a user's needs!

From day one, we have focused on enhancing and providing the best possible user experience and lowering the barrier to entry, to allow for streamlined and secure adoption of DeFi and Web3. Providing a world-class user experience with a seamless user interface, and a full spectrum of constantly growing features and services as a one-stop hub, delivering a more curated experience. Making Infinity Wallet the complete solution for all crypto users’ needs, while making adoption and usage of DeFi and Web3 easier than ever before.

Infinity Wallet is the first desktop platform to provide users with access to the entire Web3 and DApp space without needing to leave their wallet, with the first Web3 browser and DApp store directly within the platform (https://docs.infinitywallet.io/infinity-wallet/features-and-notable-advancements/browser-less-dapps-and-web3). Finally removing the need to ever use unintuitive browser extension wallets again! Providing a far superior, safer and more natural user experience, with a range of unique advantages/benefits for users, DApps and chains alike, while enabling easier adoption. Along with our unique one-stop user focused mobile wallet to come in the future https://docs.infinitywallet.io/infinity-wallet/devices/mobile-wallet-sneak-peaks 

We believe Flow will make a great addition to the Infinity Wallet and will be well received by both our and the Flow ecosystem’s users, which is why we have reached out to cooperate on this integration. As a multi-chain ecosystem we look to integrate and collaborate with chains that are innovating the space, to provide users (of Web3, DApps, DeFi, NFTs, etc.) with access to all of their crypto needs. Integrating chains across our wide range of features/services and supporting their web3 ecosystems (DApps & Tokens) is a consuming task however, hence why we can only integrate/support chains that are able to collaborate with us on supporting the integration via an integration grant.

You can learn more regarding our vision/mission here https://docs.infinitywallet.io/vision-and-mission as well as more about Infinity Wallet’s current and future features/services/protocols in the docs or information deck shared below.

![Infinity Wallet](https://i.gyazo.com/e1a68afab6f7150a2baecacb06868a88.png)

You can download the live Infinity Wallet for desktop (with mobile in the works), supporting Windows, Linux and Mac : https://infinitywallet.io/download  

Link to our information deck, which will provide further information on the Infinity Wallet and its features and future plans.[ https://infinitywallet.io/docs/Infinity%20Wallet%20Deck.pdf](https://infinitywallet.io/docs/Infinity%20Wallet%20Deck.pdf)

Link to our docs which will explain more in-depth certain features and our roadmap: https://docs.infinitywallet.io/ and mobile sneak peak https://docs.infinitywallet.io/infinity-wallet/devices/mobile-wallet-sneak-peaks 

Link to more information along with a video on Browser-less Web3, allowing users to use any DApp directly within the Infinity Wallet, allowing for easier DApp discoverability/adoption:  https://docs.infinitywallet.io/infinity-wallet/features-and-notable-advancements/browser-less-dapps-and-web3

## Problem/Solution statement
The problem today is that while wallets are the most fundamental component required for usage and adoption of a chain and its ecosystem, they are one of the least well developed applications in the crypto ecosystem. Wallets currently act mainly as an interface serving primarily as a transaction signing layer, with very limited functionality or direct features/services/protocols (users generally have to search, find, learn and interact with many different applications and services), and are generally lacking in basic UX, while providing very unprofessional, hard to use and aesthetically poor user interfaces. This has been sufficient for the early adopters in crypto, however, for the next billion users to onboard to Web3, a more curated and high quality user experience will be required.

Infinity Wallet steps in to fill this need, as a one-stop hub for all DeFi, NFT and Web3 activity. Providing a unique solution as a DeFi wallet and web3 browser, with a full spectrum of services, features and protocols in a premium platform, with a focus on delivering a seamless user experience and a user centric interface. Streamlining accessibility and lowering the barrier to entry, to allow for true adoption of DeFi & Web 3.0 globally.

You can also find problem/solution, as well as value add in our information deck on pages 4, 5, 6 and 25 here https://infinitywallet.io/docs/Infinity%20Wallet%20Deck.pdf 

## Impact
Infinity Wallet will benefit the Flow ecosystem and holders by providing a unique all-in-one wallet & ecosystem solution on Desktop (with mobile to come in the future), with a focus on premium quality. Delivering a seamless user experience and a user-centric interface, along with access to current and a wide range of constantly growing features/services. Providing Flow access to the many advancements we have, that are already bringing real value to the crypto/blockchain space.

Infinity Wallet will allow Flow and its ecosystem to be more easily adopted and used by the general public, in a unique multi-chain crypto wallet and Web3/DApp browser built for the masses, and used already by hundreds of thousands of users worldwide to access DeFi and Web3 directly within their wallet. As a one-stop platform for all users to directly access all their DeFi, Web3, NFT and crypto needs, making adoption of the Flow ecosystem as easy and intuitive as possible and boosting awareness, usage and utility.

Below are some of the key features and services that chains are already benefiting from within Infinity Wallet and that could benefit and bring value to Flow:

- Portfolio and Analytics Monitoring/Dashboard;
![Portfolio](https://i.gyazo.com/72061265ce73936f53ad623a5bd507f8.png)

- Web3 browser and DApp store (One-click Connect to DApps, with the utmost discoverability and use of a chains’ ecosystem);
![DApps Store](https://i.gyazo.com/cb3413404fdff817e25b8d56d20af49c.png)
![Web3 Browser](https://i.gyazo.com/d5160e46f6048473e971b9e458c5a981.png)

- Cross-chain swap and bridge;
![Swap](https://i.gyazo.com/a86edf9f910c3b8edc2f4e78d76f4ce4.png)

- NFT support to manage (view, send and receive) and trade NFTs;
![NFTs](https://i.gyazo.com/54988b611a034efc3e3d09ad4623446f.png)

- Advanced Transaction History and balance/value charts;
![Advanced Transactions](https://i.gyazo.com/7530eb3b49bedcf367a3ea506151954d.png)

- Custom Token Importing (Allowing any token to be imported even if not default supported);
![Import Token](https://i.gyazo.com/7233b8795e1786b00f537f6fca95a116.png)

For a more detailed look over our many current and future features/services please see our information deck available at https://infinitywallet.io/docs/Infinity%20Wallet%20Deck.pdf (pages 10-24 list core features/services and roadmap), or our docs here https://docs.infinitywallet.io/infinity-wallet/features-and-notable-advancements (detailing further information on core features/services and secondary features, as well as our roadmap)

# Milestones and funding
The goal of this grant would be the complete integration of Flow  into Infinity Wallet and its wide range of features/services for unparalleled ease of use and adoption of Flow. Providing Flow and the Flow ecosystem access to a vast user base of over 170,000 users within August and growing, bringing constant free marketing, awareness and adoption.

We would be requesting $160,000 in FLOW (or alternatively USDC/USDT) as a single milestone, deliverable after the live launch of FLOW within the Infinity Wallet. We are willing to accept an amount of FLOW on a vested linear release schedule over 1 year.

The timeline for integration/development/testing would take around 8-9 weeks with 5 full-time team members from start to live launch. While maintenance, ecosystem support (direct DApp & token integrations and ecosystem collaborations) and future developments into available features/services and platforms will be on-going.

We generally work via a single milestone, which is the complete integration and live launch of Flow in the Infinity Wallet and its features/services. This expedites the process and allows us to focus on fully completing the integration, before receiving any payment. Although we do have internal milestones, which we can provide on request.

Additionally, as part of the grant we would be waiving our usual DApp integration fee for Flow DApps/Ecosystem projects that meet our requirements. Allowing them to be freely integrated into the Infinity Wallet Web3 Browser and DApp store, driving further awareness and growth to the Flow Ecosystem. As an example 20 DApp ($5,000 per a DApp yearly) integrations would usually be $100,000 in yearly fees.

# Team
Information on our team, location, experience and goals can be found at the following link https://docs.google.com/document/d/19L9fGt241UVQlXxUtbx7BqkhCFxS6DzlFYu7svtUCi4/edit?usp=sharing 

# Contact Information
Contact Email: partner@infinitywallet.io
Telegram Contact: https://t.me/aron_infinity

**Comment by InfinityWallet** [comment]
Hello, we were wondering if there was any update regarding this proposal? Thanks

**Comment by InfinityWallet** [comment]
Hello @chrisackermann, we are following up as its been quite a while since applied and were wondering if there is anything else needed to be done? Thanks

**Comment by chrisackermann** [comment]
Hi @InfinityWallet, so sorry for the missing a response to you on this one!  

We have reviewed your proposal and are reaching out directly via email to follow-up.

**Comment by InfinityWallet** [comment]
> Hi @InfinityWallet, so sorry for the missing a response to you on this one!
> 
> We have reviewed your proposal and are reaching out directly via email to follow-up.

Hi @chrisackermann, no problem. We haven't received an email yet so we look forward to hearing from you.

**Comment by InfinityWallet** [comment]
> Hi @InfinityWallet, I'm closing this proposal out based on the discussions with our team. Please feel free to re-open or reach our directly on Discord (chrisa#6592) if you have any further questions, thanks.

Hello @chrisackermann, we have not yet received the follow-up email mentioned above, we will try to reach out to you on Discord.

**Comment by srinjoyc** [comment]
@InfinityWallet - hey guys, I believe I messaged the general partners email but it might have not gone through/missed - Let's connect on discord and schedule a quick chat. Send me a message at srinjoyc#4183 on the Flow Discord.

**Comment by InfinityWallet** [comment]
> @InfinityWallet - hey guys, I believe I messaged the general partners email but it might have not gone through/missed - Let's connect on discord and schedule a quick chat. Send me a message at srinjoyc#4183 on the Flow Discord.

Hi @srinjoyc, our team lead **Aaron | Infinity Wallet#9732** will reach out to you on Discord.

**Comment by InfinityWallet** [comment]
Hi @srinjoyc and @chrisackermann, we have tried reaching out on Discord and sent a couple of DMs, however had no luck with getting a reply. We were wondering if there is a better way to get in contact with you, such as Telegram?

**Comment by chrisackermann** [comment]
Hi @InfinityWallet!  Sorry for the delay, we've had some changes on our end.  I'm in touch with the team on Discord and we're discussing.  Thanks!
