### ISSUE TITLE
Overflow follow up grant

### ISSUE THREAD

**Issue by bjartek** [onflow/developer-grants#87]
# Overflow

# Grant category

- Open source maintenance

# Description

This is an follow up grant from https://github.com/onflow/developer-grants/issues/12, since almost all milestones there is done at this moment. Two more milestones have surfaced and then I would like to ask for a monthly grant to keep maintaining overflow and keep it bug free and up to date. 

## Continued supported. 
In the three months since the grant launched I have helped many projects convert code from old overflow syntax to the new one. I have also commited fixes to onflow core contracts to show how the new syntax could improve the readability of the tests. 

I would like to ask for a monthly fee to keep overflow a float for another 3 month period.

The last grant gave out 10k flow (valued at 5 when the grant was given) for a total of 50k USD for 3 months. So 16666 USD per month. Since the initial support period is over I think that sum is a little high so what about 10000 a month.

This will include fixing small issues in the overflow repo that are tagged with small.

## Create memory snapshots and start from them
Flow cli has support for starting the emulator from a file. I would like to create some convenience around that so it is possible to set up a project/run an overflow story and create a memory dump of that. This can be very usfull as a debugging tool. You have an issue? can you create a dump for me?

It could also be used to create a dump of a test setup to enable very quick bootstrap of tests. The .find repo has 30 contracts now and the test overhead to start up a new emulator is seconds not miliseconds as it should be. 

For this feature I would like to ask for 5000 USD
	
## Bootstrap new project and maintain it

When you start up a new project today you often want to get externally defined contracts and set up a bare bones skeleton. I propse to add features to overflow that enable it to be used to bootstrap the backend side of a flow project. 

This includes: 
 - creating a new github repo
 - get common shared code and put into project
 - set up NPM module of interactions (or work with interaction template)
 - diff the state of your local contracts with contracts on mainnet/testnet to see if your external dependencies have changed
 - offer simpler local version of some contracts on mainnet that is hard to use for testing USDC for instance

The end result is a tool that allow anybody that want to start with an NFT project using overflow to do so easy. 

For this feature I would like to ask for 10000 USD

# Milestones and funding

Only mainainance will be delivered this grant period.

> Note: You can leave the USD proposal empty / "TBD". Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Continued support   | Support | Every month  | I do not want overflow to grow unstable and want to be able to help its users. Each month for 3 months | 10000          |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Bjarte Karlsen | Code-monkey | I sling code and have fun and help some people too | bjarte@bjartek.org |

Fees can be discussed.

**Comment by chrisackermann** [comment]
Hi @bjartek - just wanted to let you know that this proposal has been accepted.  We'll follow up directly on next steps.  Thanks!
