### ISSUE TITLE
 vue3, TS, FCL scaffolding & market cases & training

### ISSUE THREAD

**Issue by 28356715** [onflow/developer-grants#88]
# <Project name>
  vue3, TS, FCL scaffolding & market cases & training
# Grant category

Please select one:

- Educational material

# Description

## Problem statement

I am a web2 senior front-end developer. After entering web3, the first smart contract development language I learned was cadence.I found that there are very few development courses in the Chinese community, and the overall content is relatively general, and the tutorial case explanation is not a complete trading market.There are many web2 colleagues around me who have urgent learning needs, but the course content is not so easy to learn.For this reason, I developed a more detailed practical development course, and built a complete DAPP trading market case, integrating the new vue3, TypeScript, and FCL scaffolding, which is more suitable for Chinese community learning;At present, I want more developers to know that I plan to promote the Chinese area. I hope the official website will give some financial support, and I will also pay a part of the funds myself.
  Just in time to complete the wishlist https://github.com/onflow/developer-grants/issues/8

   
## Proposed solution
1. The course content covers: Learn about blockchain, Learn about flow, Learn about cadence, basic grammar, core concepts, engineering development, DAPP completing the case explanation of the trading market. A total of 300 minutes of video courses.
2. Complete a vue3, TypeScript, Fcl scaffolding that is more suitable for the Chinese community.
3. Complete a complete Dapp case including mint  nft , listing, trading market, and purchasing functions.
4. I am now officially cooperating with the "2022 China Entrepreneurs Conference and Metaverse Summit", and I can promote Flow and courses through the booth. If the official needs anything at the exhibition, we can provide support. "2022 China Entrepreneurs Conference and Metaverse Summit" link address:http://10.cyz.cn/.
5. I have registered as a Chinese developer community lecturer qualification (Geek Time, 51CTO, MOOC, etc.), and I can do some course promotion in the Chinese community.
6. It has cooperated with a number of universities and can be promoted within the university.

## Course Details
course1： Learn about Flow & Cadence
1.   Learn about Block-chain 
2.   Learn about Flow
3.   Learn about Cadence
4.   Install the Flow CLI
5.   Learn about Playground
6.   Complete the First Smart Contract Development: Hello Cadence

course2：cadence basic grammar
1. Type Annotations 、Constants and Variable Declarations
2. Values and Types
3. Function
4. Control Flow
5. Composite Types

course3：cadence core concepts
1. Transactions
2. Accounts
3. References
4. Capability-based Access Control
5. Interfaces
6. Access control

course4：Engineering development configuration
1. Project initialization & environment configuration
2. Emulator
3. Generate Key Pair with the Flow CLI
4. Generate account
5. Case: contract development using simulator
6. Contract Upgrade Specifications and Standards
7. FT and NFT standards

course5：DAPP development practice 1-realize landing & NFT casting
1. Introduction to Engineering Architecture
2. Environment configuration
3. Introduction to FCL
4. Use fcl to achieve login and exit
5. Interaction with the front end: mint NFT

course6：DAPP development practice 2  -   NFT listing and trading
1. NFT listing
2. NFT trading market
3. NFT transaction

## Impact
1. Brand new scaffolding
2.Complete market case 
3. "2022 China Entrepreneurs Conference and Metaverse Summit", you can promote Flow and developer courses to Chinese entrepreneurs through the booth, and expose 10,000+
4. The course will be promoted in Chinese universities, and it is estimated that 400+ students majoring in computer science will participate in the study.
5. The course will be launched in cooperation with the Chinese developer community (such as Geek Time, 51CTO, MOOC, etc.), with an estimated number of students exceeding 400+

# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| Video Course   | 300 minute video course | The second week after the project starts  | - | 3000           |
| vue3, TypeScript, Fcl scaffolding   | A GitHub repository with content descriptions and scaffolding usage instructions.The scaffolding integrates vue3, integrates the element-plus component library, integrates TypeScript, and Fcl, which can be used as the basis for DAPP development.In the course, the scaffolding frame structure will be explained and demonstrated | The second week after the project starts | - | 2000           |
| DAPP complete case   | DApp market case based on vue3 scaffolding. Functions include: user minting NFT, Collection display, sale, transaction.In the course, the case code will be analyzed, explained and demonstrated. | The second week after the project starts  | - | 2000           |
| channel promotion   | More than 800 learners, provide data| The fifth week after the project starts  | - | 1000           |

Total funding proposed: <total USD amount>
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Kaka| Senior development engineer, lecturer | 10 years of experience in development and system architecture | kakaliu499@gmail.com |

**Comment by chrisackermann** [comment]
Hi @28356715, thanks for submitting your proposal!

We've reviewed your proposal and wanted to see if you would be open to scoping this more specifically towards Vue examples and scaffolding and more in-depth topics that are demonstrated for Vue.

In the content that you've proposed here going to be localized specifically for the Chinese market?

**Comment by 28356715** [comment]
> Hi @28356715, thanks for submitting your proposal!
> 
> We've reviewed your proposal and wanted to see if you would be open to scoping this more specifically towards Vue examples and scaffolding and more in-depth topics that are demonstrated for Vue.
> 
> In the content that you've proposed here going to be localized specifically for the Chinese market?

Hi @chrisackermann, thank you for your reply.
I'd love to take your advice and update the Milestones and Funding sections.
In the course part, 30% of the time will be spent on scaffolding, cases and demonstrations.

In the content of the proposal, it will be aimed at the Asian-Pacific Chinese community

**Comment by chrisackermann** [comment]
Hi @28356715 - one follow up question for you on your proposal:  where do you intend for the video course to live?  Where will it be accessible to the community?

**Comment by 28356715** [comment]
> Hi @28356715 - one follow up question for you on your proposal: where do you intend for the video course to live? Where will it be accessible to the community?

Hi @chrisackermann 

The community can be accessed through 51cto.com, xiaoe-tech.com, Bilibli, WeChat, and Youtube. Thanks!

**Comment by chrisackermann** [comment]
This grant is complete.
