### ISSUE TITLE
YomiSwap [ NFT AMM Protocol ]

### ISSUE THREAD

**Issue by Kazuma7** [onflow/developer-grants#89]
# YomiSwap [ NFT AMM Protocol ]
# Grant category

- Open source maintenance
- Developer tools / services

# Description

## Problem statement

- Target audience
Liquidity providers : mainly target NFT users who hold more than a few blue-chip NFTs and knowledgeable De-fi users who can set up a bonding curve
Buyers and sellers of NFT: NFT fans who usually buy and sell NFT in the market place.

- Evidence for the need
With the current structure of the NFT market place, you cannot sell immediately; even if you list, you have to wait for a buyer to appear. Therefore, liquidity is very low.

## Proposed solution
The AMM mechanism is applied to NFT trading by yomiswap. 

yomiswap allows users to do three things.

- Provide a liquidity pool
- Buy NFTs using the liquidity pool
- Sell NFTs using the liquidity pool

Liquidity pool providers have a very simple way to participate.

- Participate by offering liquidity in either NFTs or FT.
That's all there is to it. The liquidity provider is rewarded simply for staking.
You can create any number of pools, even within a single NFT collection.
Prices are determined fully automatically according to bonding curves.
Thanks to liquidity providers, you can swap FT and NFT at any time.
We decided to introduce two automations to protocol to solve the problem.

- Auto Position Change
The liquidity provider stakes an NFT, and when that NFT is sold, a buy order is automatically placed for the NFT, and the sell and buy orders are automatically repeated, and the difference between the two is the compensation.

- Auto Pool Optimization
Liquidity providers can set their own buy/sell bonding curves and create liquidity pools or stake in liquidity pools created by other users, so the liquidity pools that best fit the market will survive and others will be naturally eliminated.

## Impact

- In what ways does this benefit the broader Flow developer ecosystem?
NFTs are used in games and apps throughout the Flow ecosystem, but there are many closed NFT projects and the liquidity of NFTs is still low. If we can accelerate many NFT transactions and promote the distribution of NFTs with our protocol, NFT projects within the Flow ecosystem will be more exciting. We believe that our protocol deserves to be positioned as an infrastructure, not a service. We are confident that the existence of this protocol will boost the NFT market and make it a more liquid entity.

# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Technical Verification   | Conduct technical verification to see if NFT AMM using Bonding Curve can be realized with smart contracts. | 3 weeks  | - | 6000           |
| 2 - Smart Contract v1   | Implement the Bonding Curve for automatic price changes for NFTs with smart contracts. | 3 weeks  | - | 6000           |
| 3 - Smart Contract v2   | In v2, users can freely create liquidity pools in which NFTs are automatically priced using the bonding curves created in v1. Then, other users can freely buy and sell NFTs in the liquidity pool. | 6 weeks  | - | 12000           |
| 4 - web app   | Develop a web service that allows users to easily experience the NFT AMM protocols that have been created as an intermediary. | 4 weeks  | - | 8000           |
| 5 - Audit   | Audit the NFT AMM protocol so that users can touch it with confidence. | 2 weeks  | - | 4000           |
| 6 - Maintenance   | Regular maintenance will be performed so that users can touch the protocol in the long term. | 3 weeks  | - | 6000           |

Total funding proposed: 42000  

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Kazuma | Full-Stack Engineer | Co-Founder synschismo.inc Engaged in NFT rental protocol development | kazuma.work77@gmail.com |
| Riku | Frontend Engineer | - | suto.den.noah@gmail.com |

**Comment by Aliserag** [comment]
We appreciate your proposal and taking the time to fill it out. Given the time since this has been submitted I'm closing this down, please reach out to me if you'd like to share what you're working on now and explore potential opportunities [ali.serag@flowfoundation.org](mailto:ali.serag@flowfoundation.org).
