### ISSUE TITLE
FCL SDK: Unity

### ISSUE THREAD

**Issue by alxflw** [onflow/developer-grants#9]

**Comment by Peixer** [comment]
@alxflw since we already have a .NET SDK do we need a Unity SDK? https://github.com/tyronbrand/flow.net

**Comment by alxflw** [comment]
maybe @srinjoyc can chime in here. I'm not a domain expert on Unity, so I cannot tell if/what the delta from the .net SDK might be

**Comment by srinjoyc** [comment]
Hey! So while the .net SDK exists, it's an SDK to the Flow Access Node and not for FCL - FCL will require using the .net SDK under the hood but will need much more functionality on top to support wallet interactions (collecting signatures, authenticating, etc.)

**Comment by tyronbrand** [comment]
Hey @srinjoyc @alxflw,
Could you provide more details about the preferred authentication flow?

Some options to consider could be:
- The user is sent from the game to a browser to sign in. (Possible complexity around mobile games here)
- Load a browser within a game scene. (This will raise some security questions)

**Comment by Codie-Petersen** [comment]
Hello @srinjoyc @alxflw, is this issue still open? I thought I saw someone doing something with a Unity Flow SDK already.

**Comment by alxflw** [comment]
good question @Codie-Petersen! We currently have a Flow Unity SDK (https://developers.flow.com/tools/unity-sdk/index) but not an FCL-compatible SDK yet
