### ISSUE TITLE
ParaDAO

### ISSUE THREAD

**Issue by ParaDAO-platform** [onflow/developer-grants#90]
# <ParaDAO>

# Grant category

- Educational material

# Description
ParaDAO is a decentralized storage investment and finance data analysis platform based on DAO.

## Problem statement

- Target audience
ParaDAO is not only a VC analysis platform for investment institutions, but also a wikipedia for those who would like to search for the latest news about Web 3.0. And on top of that, we also provide a ParaFamily platform to embrace many enthusiasts to develop ParaDAO together. 

- Introduction of the tools

**ParaFamily** is an organization for DAO Memebers, who are the initiators, contributors and governors of ParaDAO. ParaFamily carries out data collection and perfection, and is responsible for the operation and BD of ParaDAO.

**ParaProtocol** includes decentralized investment management wallet protocols, decentralized IDO tools, pledge management tools, and other Defi tools.

**ParaPedia** is a big data center of web3.0 venture capital core, providing rich resources to project parties and investment institutions, and forming web3.0 Wikipedia by means of DAO management and AI technology.

- In what ways does this benefit the broader Flow developer ecosystem?
With regards to the Flow ecosystem, we will start to track Flow ecology in DAO, establish our research guild and build up our parafamily to track our member’s tasks. Besides, ParaDAO will be launched and we will establish the Flow ecological channel and start collecting ecological information about Flow. ParaDAO will also help 10 projects of Flow ecology to import through Flow ecological channel and ParaFamily (DAO organization)

# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| Milestone1 | Track flow ecology in DAO, Research Guild established and ParaFamily start to track the tasks. | 4 weeks  | - | 5000 USD           |
| Milestone2 | ParaDAO will be launched and establish the flow ecological channel and starts to collect information about the flow ecology | 4 weeks  | - | 5000 USD           |
| Milestone3 | ParaDAO helps 10 projects of flow ecology to import through flow ecological channel and ParaFamily (DAO organization) | 2 month  | - | 5000 USD           |

Total funding proposed: <total 15,000 USD amount>
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Pippo | Founder | DBA, Macau University of science and technology; Huawei based in Philippines overseas technical support; Leading investment in 50+ blockchain projects | psangparadao@gmail.com |
| Archie | Co-founder | University of Vienna; WonderfulDay Co-founder; Web3.0 Inverstor | zangbing.chen@gmail.com |
| Mike | Co-founder | University of South Carolina; Deputy CEO of MUSICFI; Head of Asia Pacific
| Dora | Co-founder | Master degree in Economics, Complutense University of Madrid; Previous Product/Marketing lead at Conflux Network; Co-founder of a15a
| Clara | Co-founder | MSAPR, Bologna University; Founder of Digital China; Base in Italy, focus on NFT and Web 3.0 investment
| DerkQiu | Co-founder   | Chairman of Japan's QE Energy; Co Director, HY Energy Co., Japan; Executive Director of Asia Economic and Cultural Revitalization Organization

**Comment by chrisackermann** [comment]
Hi @ParaDAO-platform - thanks so much taking the time to submit your proposal.  

We've reviewed in detail and have decided to pass since the impact on the developer ecosystem is not clear enough.

Feel free to reach out on Discord in case you have further questions: chrisa#6592
