### ISSUE TITLE
Bootcamp Online in Portuguese 

### ISSUE THREAD

**Issue by diegofornalha** [onflow/developer-grants#91]
# EdTech Latin America 

# Grant category

- Educational Material

# Description

## Problem statement

There are thousands of big developers in Brazil eager to get on the flow blockchain by programming in cadence, but English-only content is still a limitation.

## Proposed solution

Provide quality content to the LATAM community.

## Impact

Bringing thousands of web2 developers to the web3 world, with a focus on flow solutions. Brazil is the largest economy in Latin America and has thousands of highly talented developers. When more Brazilian developers have the tools to build innovative solutions, Flow blockchain can be used to solve different problems in Brazil such as green certification of agribusiness, environmental issues of forest devastation, better distribution of wealth and hunger.

# Content Plan

Section 0
Lesson 1 - Welcome To Flow
Lesson 2 - Whats Flow

Section 1
Lesson 1 - First Smart Contract
Lesson 2 - Setup Flow Environment
Lesson 3 - Create An NFT Contract
Lesson 4 - Make It Official
Lesson 5 - Deploy To testnet

Section 3
Lesson 1 - Setup React app
Lesson 2 - Build Wallet Connect Button
Lesson 3 - Mint NFT From App

Section 4
Lesson 1 - Wrap up

# Team

| Name | Role                           | Bio | Contact         |
| ----    | -------------------   | --- | --------------- |
| [Diego Fornalha](https://x.com/diegofornalha)    | Full-Stack Engineer | Official Ambassador at Flow  | diegofornalha@gmail.com |

**Comment by chrisackermann** [comment]
Hi @diegofornalha, thanks so much for your proposal!

We've reviewed and have a few follow-up questions/suggestions:

- Can you please share some more details about the content plan for the videos that you plan to produce?
- We suggest that the funding does not go towards paid media for the videos since it runs counter to the milestones based on adoption.
- Can you please clarify the milestones in terms of how the funding should be unlocked at each stage?  Are you suggesting that all 3 conditions (# of videos produced, total views, unique viewers) will be met for each of those milestones?  It will be helpful to be clear these are aggregate over the entire set of videos produced (as opposed to incrementally).

Thanks!

**Comment by diegofornalha** [comment]
Hi @chrisackermann , thank you very much for your reply my friend!

I follow you on linkedin, I was excited by your notes and suggestions.
I am happy to answer and to be to contribute to the in such a way that it adds value and grows in the community here in Brazil and latin america,  the requested adjustments were made andimprovement of the proposal.
With this objective to adjust the proposal for the bootcamp model.
We add the content plan by sections and lessons to the proposal.

Thanks!

**Comment by chrisackermann** [comment]
Hi @diegofornalha, thanks for the updates!

It's a little unclear as to how Milestones 3 and 4 will be evaluated.  Instead, would you consider folding them into an adoption milestone that is focused on the intended impact of the project?

For example, 'x cumulative video views' and an associated USD amount that would be unlocked when that milestone is hit.  Could look at having 2 milestones that denote different levels of consumption.

**Comment by diegofornalha** [comment]
Hi @chrisackermann , let me clarify this update for bootcamp.


We are listing a trained developer with follow-up until the end of the bootcamp at 60 USD, no longer in the previous format for views.  We will have 6 weeks to work on this delivery.

**Comment by chrisackermann** [comment]
Hi @diegofornalha, thanks for this update!  

Will the content live on anywhere publicly after the bootcamp?

**Comment by diegofornalha** [comment]
Hi @chrisackermann!

Yes, content is public on github, youtube and our website:
https://bootcamp.web3dev.com.br/

**Comment by chrisackermann** [comment]
Hi @diegofornalha!  Thanks for your patience - just wanted to let you know that we've accepted your proposal and will be following up directly on next steps.  Thanks!

**Comment by diegofornalha** [comment]
<img width="612" alt="prt 2024-01-31 at 15 54 45" src="https://github.com/onflow/developer-grants/assets/37958057/ad2fd553-fbaa-4ded-937b-e4be9c8de12b">
@Aliserag Updating on our progress, our Discord dev community has organically grown from 100 to 180 developers.

**Comment by Aliserag** [comment]
Closing this down as it's quite stale having been submitted several years ago and I believe the residency program covered similar areas.
