### ISSUE TITLE
Project FireFly

### ISSUE THREAD

**Issue by deneschonknecht** [onflow/developer-grants#92]
# Project FireFly
 
![FireFly Logo](https://user-images.githubusercontent.com/100309336/190733554-a463b899-7438-4bc7-875c-cec7eff8f038.png)

# Grant category

- Open source maintenance

Do you agree to open source all work you do on behalf of this RFP and dual-license under MIT, APACHE2, or GPL licenses?: Yes
NOTE: This project will be led & developed by your friends at Emerald City DAO :) 

# Description
**What is FireFly?**
A complete payments platform for Web3 builders & users on Flow. In short, it will be a Web3 payments platform & API which allows anyone who wants to accept Flow or FUSD on their website as a method of payment rather than debit/credit cards can use FireFly instead of a traditional payment processor like Stripe or Paypal. Our goal is to make it easy for anyone to accept, transact and integrate Flow based payments.We believe FireFly will help projects save time, sell more, increase community engagement and grow Flow’s token utility. 🚀

The 2 main components of the platform will be **Pay Streams** and **Pay Links**. These will enable a host of payment related use cases - including: Subscriptions, E-commerce style payments across the web & mobile apps, Subscription payments for recurring billing, Tipping, Paywall content gating, Discord Gating, and many more! 
(More detail on use cases below)

## Problem statement(s)

There are several issues preventing crypto payments in tokens like $FLOW & $FUSD from going mainstream outside of the current Flow ecosystem of dApps. To name a few:

**1. Flow (and web3 tokens in general) lack an easy to integrate payment platform 🤷**

Stripe enabled a generation of Web2 builders to easily integrate a credit card payment processor into their site/app. We need something similar for Flow-based payments. We make it easy for anyone to accept, transact and integrate Flow based payments. This requires a native web3 platform that enables common creator & merchant scenarios like: pre-built checkouts or embedded payments directly into a store, app, content, game or platform using $FLOW & $FUSD.

**2. Existing Payment Solutions suffer from too many intermediaries 🤯**
Web3 has the potential to dramatically improve the way payments work on the internet simply because it’s cheaper and more efficient to pay anyone, anywhere securely without the legacy intermediaries that blight Web2 payment platforms. Currently credit card payment processing on a website looks like this:
Customer → Card issuer (their bank) → Payment network (Visa) → Processor (E.g. Stripe) → Merchant (seller). 
This is too slow - and most importantly - too expensive! Both the purchaser & seller are paying a myriad of fees throughout that transaction flow. We can solve this using the power of a web3 payment processing platform built on the Flow blockchain! 

**3. Accepting Flow based payments is too cumbersome.❗**
Sure - anyone can send $FLOW or $FUSD user-to-user. Works well - but not at scale if you are a professional seller doing large volumes of transactions. Ever tried reconciling (who paid? how much? refunds? etc.) with even a moderate volume of transactions on a blockchain wallet (like Blocto)? It's a nightmare! Wouldn't it be great to have a dashboard where you can see transaction details, set up new sources, track trends, etc. We think so - and have the vision to build it!
Shopify, Wix, Woo, etc. are not fit for purpose simply because these platforms don’t support a Web3 native UX and lack relevant currency support and on-chain workflows. This means projects have to build their own merchandise payment systems.

## Target Audience & Evidence for the need
The following audiences will be able to use FireFly:
- **Any builder in the web3 ecosystem** that wants to integrate Flow based payments into their existing website for accepting payments. It could allow them to take payment for digital content that is not able to be stored on the blockchain. It could allow them to take payment for NFT related merchandise - hoodies, caps, posters, etc of your favourite NFT is a great way for holders to feel part of the community. 
- More broadly - **any brand or merchant who wants to target web3 users** in the Flow ecosystem by accepting Flow based payments for off-chain products & services (e.g. NFT, NBA, etc.)
- Any business that needs recurring payments in Flow for their business model (services or tools that want to charge monthly instead of a one-time upfront fee) 
- Any project on Flow that creates it's own Flow-based fungible token (for example, all those which will be birthed on our DAO token platform - Toucans) will be able to use our platform & API's to also accept payments in their own native token!
- Any NFT project that wants to sell access to a Allow-List for a fee 
- Any project that wants to make users pay for Discord access 
- Any creator that simply wants to accept donations or tips by simply sharing a PayLink will be able to get paid and collect supporter details (unlike today where they just see a Tx come into a wallet with no additional info - that's hard to track!)
- Any many, many more. Honestly, what we will enable will is so foundational that we are 100% certain that there are a multitude of uses cases that we haven't even thought of yet, that will emerge once people know the "Stripe of Flow" exists. 

## Proposed solution

At a high level, FireFly is a fully Web3-native and non-custodial payments platform & API which will allow users to receive their payments in any Flow token and into all compatible wallets instantly.

Breaking down the solution into more detail - there are 5 main components we need this grant to allow us to build: 

### **1. PayLinks** 
PayLinks enable one-time payments, think one-off invoices and simple e-commerce like transactions. Creators of a PayLink will be able to set the fixed price of the transaction or allow end users to set their own price - ideal for donation or tipping scenarios.

### **2. PayStreams** 
Pay Streams are recurring payments on steroids that charge & settle money by the sec/min/hour/day/week/month. Streams enable ultra-flexible subscriptions and pay-as-you-go models for digital content, utilities and more.
Creators will be able to select payment receiving options like the currency, time interval, price and Max time, which calculates the maximum amount that could be charged. End users can stop the Pay Stream at any time (from dash and in-app) and are charged for actual time used. 

**How PayStreams work**
Creators set price (e.g. 100 FLOW) --> set time interval (e.g. monthly) -> set max time  for the subscription period (e.g. 12 months). The end user then approves the max amount (e.g. 1200 FLOW) with their wallet which is held in the FireFly smart contract. 100 FLOW is then released to the creator’s wallet every month. Note: PayStreams settle into the FireFly smart contract and creators will need to withdraw the Flow payments into their wallet from the FireFly dashboard. 
The end user can stop the PayStream at any time to cancel the subscription and receive the remaining amount back. Optionally, the end user can opt for a monthly top-up payment to avoid capital lock-up - but this will require the user to sign the top up with their wallet every month, or lose access to the subscription. For PayStreams that are stopped by the end-user Flow currency settles to the creator wallet automatically. 

### **3.FireFly Dashboard** 
This will be the single-pane of glass to see all of a creator’s web3 payments, edit or set up new payments and customise the FireFly experience. 
Features will include:
- Create Payments - both PayLinks & PayStreams
- Manage Payments - Manage Payments including disable (and re-enable) edit and share of payments. 
- View Transactions - Track all incoming sales as well as a drill-down view by selecting individual transactions - including the associated receipt and all relevant customer details. Transaction details can also be exported via CSV. 
- Set Profile information - e.g. email address which is used to send & receive payment notifications

### **4.FireFly API** 
- API endpoints on both testnet and mainnet.

### **5. FireFly embedded pay functions**
- The packages and/or FireFly components required in a front-end website

### Use Cases 

- **Simple Payments** - we will allow anyone selling online to set up a Flow transacting e-commerce page in seconds using a pre-built checkout page or embed payments into their own website using our API and REACT libraries.
- **Token-gated Payments** - PayLinks will allow creators to sell exclusively to NFT holders from a specific NFT collection by requesting NFT token verification.
- **Gated Discord** - Gated Discord access is a common scenario in web3 communities. But until now, these solutions have been manual role assignment, or token based (e.g. Emerald Bot). Discord role assignment will be an option when a Creator sets up a PayLink which enables a community manager to receive payment enabling scenarios like Whitelisting, Premium Content, Raffles, Support or Pay to Promote via restricted access to specific Discord channels.
- **Pre-mint & Whitelist Sales** - PayLinks will enable NFT projects to monetise their pre-mint & WL spots because transaction details including wallet addresses, Discord ID, etc are captured at checkout and can be downloaded to CSV from the FireFly dashboard. Additionally, a PayLink creator will be able to  gate access to a Pay Link by token holding (e.g. FLOAT or other NFT);  cap quantity of sales; as well as restrict maximum sales per Pay Link.
- **Premium Content** - PayLinks will enable gating premium content, links, codes, community access, etc.
- **Tipping / Donations** - There's plenty of goodwill in the Web3 ecosystem from creators & developers who build cool stuff for free. These folks rely on tips and typically list their wallet address. But the wallet-to-wallet Tx process requires multiple steps, resulting in friction and missed conversion opportunities. By providing a simple clickable button/link, users will be able to convert supporter payments more frequently. 

## Impact

- In what ways does this benefit the broader Flow developer ecosystem?
FireFly will fill an important gap in the Flow ecosystem - giving any project the ability to accept payments in all Flow-based tokens in numerous use cases.  This will attract interest from within the existing Flow community of projects & users - as well as bring new users into Flow who want to accept native web3 currencies and expand their payment options they offer. 

**When setting up a PayLink, FireFly users will be able to choose between a pre-built checkout page or embed payments directly into their website or app using our libraries & plugins.**

We are super excited about the potential impact of this platform - and without sounding overly ambitious - let's not forget that the overall online payments opportunity is HUGE! (in the Billions) 🚀🚀🚀

In addition, FireFly like all products we are developing at Emerald City, will integrate & leverage other Flow projects & tooling - e.g. 
- Identity - .find and EmeraldID
- Wallets - Blocto, Dapper, Lilico  
- Toucans - the fungible token generator we are already building 

**In addition, we have plans for a native Shopify plug-in which will allow ANY Shopify merchant to accept Flow based payments!** 

NOTE: We will be updating this grant proposal with UI concepts over time. 

# Milestones and funding

> Note: You can leave the USD proposal empty / "TBD". Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Core dApp Development  | Smart Contract transactions & scripts | 5 weeks  | - | 20,000           |
| 2 - UX Design  | Finalize initial designs | 4 weeks  | - | 10,000           |
| 3 - UI Development   | Front end development of the platform | 6 weeks  | - | 30,000           |
| 4 - Integrations  | Integration with Toucans, Wallets, .find etc. | 2 weeks  | - | 10,000           |
| 5 - Backend Development  | Infrastructure to store user sensitive data | 6 weeks  | - | 50,000          |
| 6 - API & Library Development  | API endpoints on both testnet and mainnet. | 4 weeks  | - | 40,000          |
| 7 - Go-Live!  | Complete Beta Testing | 2 weeks  | - | 10,000          |

`NOTE: FireFly will be funded for ongoing development & maintenance beyond launch via a small % platform fee for all  transactions through the platform. This will be the responsibility of Emerald City.

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Jacob Tucker | Smart Contract Engineer | Founder of Emerald City DAO| jacobtucker818@gmail.com |
| Dene Schonknecht | Product Designer | Founder of GENIACE (existing NFT marketplace on Flow) | dene@geniace.com |
| Mateo Roldos | Full-Stack Engineer | ... |  |
| Emerald City Building Guild | Various Roles | Emerald City has built FLOAT, Emerald ID & Bot etc. |  |

**Comment by deneschonknecht** [comment]
Hi @alxflw - here is an example of the FireFly Merchant Dashboard we envisage building. Sharing it here in case it helps bring the concept to life a bit more as you evaluate this grant. 
<img width="1512" alt="FireFly Merchant Dashboard" src="https://user-images.githubusercontent.com/100309336/193652025-97f0afc4-7220-4d3c-9107-934ff35e5ac1.png">

**Comment by chrisackermann** [comment]
Hi @deneschonknecht - thanks so much for the proposal and additional context!  We're reviewing and will get back to you shortly.

**Comment by deneschonknecht** [comment]
hey @chrisackermann - any update on this review? Thanks

**Comment by chrisackermann** [comment]
Hi @deneschonknecht - sorry for the delay on this one.  Some key folks that need to take a look have been out of the office, so still awaiting some more eyes on it.  Thanks for your patience and sorry to keep you waiting!

**Comment by chrisackermann** [comment]
Hi @deneschonknecht, thanks for your patience!

This proposal is certainly exciting!  I wanted to see if you had any thoughts on how you might consider scoping this in terms of what an MVP might look like in order to get something to market sooner and get feedback/validation first.

**Comment by deneschonknecht** [comment]
hey @chrisackermann - can you check internally with Anuke on this? We are having related discussions, and it would be worth connecting the dots here. Thanks!

**Comment by chrisackermann** [comment]
@deneschonknecht, yep we're syncing up - thanks!

**Comment by chrisackermann** [comment]
We're closing this proposal out for now since the need is not immediate, but we will revisit as a further date.
