### ISSUE TITLE
OPOLO Cold Wallet Integration

### ISSUE THREAD

**Issue by faboulous1** [onflow/developer-grants#95]
# OPOLO Cold Wallet Integration

# Grant category

Please select one:

- Developer tools / services

# Description

OPOLO Cold wallet can integrate the Flow blockchain and its features into its wallet so all the users can have a secure storage for their flow coins.

## Problem statement

Secure cold wallet storage for flow coins.

- Target audience

Crypto users

- Evidence for the need

Hacks

## Proposed solution

OPOLO Cold wallet

## Impact

- In what ways does this benefit the broader Flow developer ecosystem?
It benefit not only the developers but also all the Flow users who are going to secure their flow coins.

# Milestones and funding

It depends on what features you want to be implemented in OPOLO Cold wallet.

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - MVP   | Smart Contract | 2 weeks  | - | 1000           |
| X - Adoption   | 5 team using this project | 4 weeks  | - | 1000           |
| X - Maintenance   | Resolving issuing and fixing bugs | 3 months  | - | 1000           |

Total funding proposed:  DEPENDS
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Alex | Full-Stack Engineer | ... | alex@onflow.org |

**Comment by alxflw** [comment]
hey @faboulous1 - could you fill out the details as requested in the template, missing are the milestones, team, and details about the solution.

**Comment by faboulous1** [comment]
Your team can contact us on our email for discussion and details if they are interested to integrate into OPOLO Cold Wallet www.opolo.io. thanks

**Comment by alxflw** [comment]
@faboulous1 please add all requested info to the issue if you want this proposal to be reviewed by the committee. this is purposefully a streamlined and public process. we cannot review a proposal without the details in here. 

feel free to add details and re-open the issue if you want to continue. thanks!
