### ISSUE TITLE
Advanced Governance Systems on Flow

### ISSUE THREAD

**Issue by ourflowaccount** [onflow/developer-grants#96]
# Advanced Governance Systems on Flow

# Grant category
- Developer tools/services
- Educational material

# Description
Design and implement a DAO solution and tools to manage a Decentralized Autonomous Organization effectively on the Flow Blockchain.

## Problem statement
Governance is one of the most relevant aspects of an organization as it comprehends the structure and processes of how stakeholders can control and make decisions regarding the behavior of that organization. With the advent of blockchain technology, a new type of organization was born, the Decentralized Autonomous Organization (DAO). With it came the challenge of structuring trustless governance solutions to power decision-making in this novel environment.
In our practical experience, we have encountered many technical Governance issues mainly related to the decision-making processes involved when managing resources for different projects and teams scattered throughout the world. We understand that most developers engaged with blockchain technology, like us, operate and organize in a decentralized manner. Managing decentralized operations effectively will depend on a set of tools, and this proposal covers a few.

#### Target Audience: Web3 Builders
Web3 builders need a tool to help them organize their companies' multiple departments and processes. Their needs will differ, but in general, they can be grouped as:
- DAO Setup
- Voting
- Token Management
- Finance Management
- Process Management

Besides features, we will provide a high-quality user experience and documentation. 

## Proposed solution
_This is a simplified description._

Build the technical infrastructure for a DAO to effectively operate in a fully decentralized
and autonomous way on Flow.  In this proposal, we would like to build a DAO management system covering the first three groups: Setup, Voting, and Token Management. 

This includes:
- Voting settings
  - Quorum
  - Vote duration
  - Single choice
  - Multichoice
- Voting power
  - One vote per token
  - One vote per account
- Voting outcome
  - Token Emission
  - Token Burn
  - Token Transfer
  - Update Variable
  - None

~~Note: We are considering fungible tokens only. NFTs could be used in a future release.~~
Edit: We should include NFTs in the first release.

### Deliverables
- Scope document (high-level features)
- UI Design, using Figma
- End-user website, using Next-js, with Typescript and Chakra-UI;
- Smart Contracts, with unit tests;
- Off-chain data indexer, using Kotlin or Go
  - Used to provide a better user experience.
- Documentation using GitBook;
- 4 articles on Medium, explaining the platform and how to use it.

The code will be put on GitHub.

### Not included in this proposal
- Community management

## Impact
Besides more mature projects, we understand that Flow was designed to facilitate sales to end users, making it ideal for actual companies that need profit to thrive. We think Flow can portray DAOs as profitable institutions, driving away that ‘utopic’ perception of DAOs. If we successfully make flow the perfect place for ‘companies,’ this will attract seasoned leaders and entrepreneurs.  

# Milestones and funding

| Milestone | Deliverables | Timeline | Risks | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Requirements & User research | Business Requirements, 2 Personas | 2 weeks |   | 8000 |
| 2 - UI / UX Design  | Brand guide, wireframes, UI Design.  | 6 weeks | This will need a few iterations and may delay the project  | 22000  |
| 3 - Version 0.1  | Design, Development  | 4 weeks |   | 36000  |
| 4 - Version 0.2  | Development, Documentation  | 4 weeks |   | 36000  |
| 5 - Version 1.0  | Quality Assurance, Fixes. 2 medium articles | 4 weeks |   | 18000  |
| 6 - Maintenance | Bug resolution, GitHub support | 6 months |  | Included |

Total funding proposed: U$120.000.  The project should be completed in between 3 to 6 months. 

We could add or remove features. These are the core parts of a 'professional' DAO management system. 

# Roles

| Role | Activity | 
| --------- | -------------- | 
| Product Lead | Ensure the project is successful. Understand the user, and guide the team. |
| UI/UX Lead  | Create the brand guide. Design the user experience. |
| Business Analyst | Detail requirements, support the development team | 
| Project Manager |  Support the team to deliver the project on time |
| Tech Lead  |  Architecture Design, code review, training, core development |
| Developer  | Frontend, smart contract, and backend development |
| Marketing Analyst  | English content creation and review (not docs) |
| Q.A Analyst  | Plan and test the system  |

Contact: notflowxxc@gmail.com

I prefer not to disclose the names to avoid panic in our existing community. I'll get in contact to provide this information.

**Comment by chrisackermann** [comment]
Thank you for submitting this proposal, @ourflowaccount!  We're reviewing and will get back to you shortly.

**Comment by chrisackermann** [comment]
Hi @ourflowaccount, thanks for your patience!

To confirm, your proposed solution will be a product that community managers will use directly?   Do you envision any sort of business model on this product?

**Comment by ourflowaccount** [comment]
Hello @chrisackermann ,


> To confirm, your proposed solution will be a product that community managers will use directly? 

'Yes'. It's a management tool. We should focus on the leaders/managers. 

> Do you envision any sort of business model on this product?

We have to consider the options depending on the target audience. If you/we want to focus on developers, we will likely have to work on SDKs and other dev tools. If we go after non-developer roles, we may want to deliver no-code/low-code features. In both cases, it's hard to charge for a _tool._ End users ('wallet users') are probably the best audience for a web3 product. This audience doesn't buy tools but tokens and NFTs. They are not reachable now but should be in the future.
We think that if we charge a fee for projects using it, people won't use it. Governance participation is generally unattractive, especially if there are no financial rewards. It's also worth mentioning that we can't put everything to be voted on. The voting costs can outweigh the 'voting benefits' if we do that.  

A sustainable long-term relationship is preferred, which is impossible if the project doesn't generate revenue. We can design a business model using tokens or NFTs, to grant access to features and content or give people decision-making power. Once we have an application used and approved by its users, we should have enough expertise to implement a profitable business model. This can be provided as a document or business canvas of your preference.  

At this moment, I think that we could charge royalties from NFTs generated from the system. Something like this: You create your company and mint NFTs for users and participants. When these NFTs are traded, 1% of the amount is paid as royalties. These NFTs may grant participation on voting, different vote weights, or just be a form to compensate or reward people.

**Comment by chrisackermann** [comment]
Hi @ourflowaccount, thanks for providing more context on what you're aiming to build and the intended audience - very helpful to understand how you're intending to scope this project.

I can certainly see this being a valuable solution, however we're prioritizing efforts that are focused on serving developers with this program.  I'm not sure if you've already taken a look, but it might make more sense to explore the Flow Ecosystem Fund program, which you can find more about here: https://flow.com/ecosystemsupport

I'm going to close this proposal out for now, but please feel free to re-open and/or reach out on Discord at chrisa#6592 if you'd like to discuss further.
