### ISSUE TITLE
RFP for Sample App:  DAO on Flow

### ISSUE THREAD

**Issue by Blockversity** [onflow/developer-grants#97]
# RFP for Sample App:  DAO on Flow

## **# Grant Category:** 
Education Material 

## **# Description**

From the RFP: 
The idea is to provide sample code for most basic building blocks that are used for DAOs - and show how they all come together. This would include-
<b>1) Membership token & governance token  (FT and NFT)
2) Smart contracts (incl voting)
3) Frontend with auth, token check, and voting features.</b>

<b>ENABLING DEVELOPERS TO BUILD THEIR OWN DAOs on FLOW</b>
<b>Our approach suggests giving developers the possibility to build and manage their DAOs with either NFT or fungible tokens.
However, the MVP version will use Fungible tokens only. Our team will create code samples allowing developers to use Fungible tokens for both membership and Governance, making it easy for a core team, investors, and key members to manage proposals and voting rights. We intend to support the code samples with documentation and articles that will be published on various media platforms such as medium.com, Hashnode, Github and on Flow Developers space.</b>

## **# Problem Statement**

Flow sees DAOs as the next big trend and realizes that there are little guidance and code samples for new developers to build DAOs on Flow. The only option available for now is tooling, such as provided by Emerald Green.  But when it comes to building a DAO from scratch on the Flow blockchain, there is a lack of available documentation for beginners, discouraging them from even getting started to build a DAO on this blockchain.

## **# Target Audience**

1.  Flow Developers who want to build a DAO on Flow. 
2. Anyone who is new to the Flow ecosystem and curious to learn. 

## **# Evidence for the Need**

Flow recognizes the growth of DAOs and the lack of documentation and code samples for DAOs on their blockchain. 
Supporting Flow's vision, we can find many articles mentioning the growth of DAOs; here is an example:[https://www.forbes.com/sites/davidprosser/2022/08/16/why punk master believes daos are the future/?sh=7cdef4b311b9]

Moreover, you will find here below a list of URLs (1) showing the lack of search results on top sites when looking for DAOs content built on Flow. 

Flow's objective is now to make it easy for developers to get started by providing code samples and clear documentation; they recognize the need to build top-of-mind awareness among developers who are considering building a DAO.
In brief, the objective is to communicate and demonstrate that Flow is a blockchain of choice for building a DAO. Providing code samples and detailed documentation for developers to get started will highly contribute to this goal.

----------------------
(1) Search results for DAOS on Flow

- Flowverse: Searching “DAO” on Flowverse leads us to a few existing DAOs built on Flow, but there are no articles guiding developers to create a DAO on FLow. Link: https://www.flowverse.co/search?query=DAO

- Medium: There is not a single article that talks about DAOs on Flow or How to create a DAO on Flow?
Link: https://medium.com/search?q=DAO+on+Flow

- StackOverFlow:  Searching for “DAO” on StackOverflow gives us “ We couldn't find anything for DAOs on flow blockchain” Link: https://stackoverflow.com/search?q=+DAOs+on+Flow+blockchain 

- HashNode: There is only one result, and it is about someone’s experience from participating in the Emerald Bootcamp Link: https://hashnode.com/n/flow-blockchain

## **# Proposed Solution**

We will create a public repo (open source) for developers to have access to code samples and instructions on how to create a DAO on Flow.

1. <b>Architecture:</b> Our deliverable will provide a diagram of the DAO workflow
2. <b>Membership and governance token:</b> We will create a fungible token for membership and governance which will be used by members of the DAO, core team, and investors. 

## **# Impact**

**- _In what ways does this benefit the broader Flow developer ecosystem?*_*

This will contribute to promoting Flow, positioning it as a complete ecosystem where one can develop not only tokens and smart contracts but also DAOs.
Developers will have access to clear documentation and code samples on how to build a DAO using Cadence.  As a result, it will help to onboard more developers on Flow.

## **# Milestones and Funding**
> Note: Please consider adoption and/or maintenance milestones at the end of your project.

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-9fd32d1a-7fff-2c8c-9729-9b0bbd31c906"><div dir="ltr" style="margin-left:-0.75pt;" align="left">

Milestone | Deliverables | Timeline | Risks | USD proposal
-- | -- | -- | -- | --
1- Architecture | Architecture &? Front-end with wallet login auth | 3 weeks | - | $8400
2- Governance token (FT) smart contract + Governance Token Front-end  | Issuing and distributing tokens (ICO and IDO); Create test suite and documentation | 5-6 weeks|-| $14000
3- On Chain Governance mechanisms | DAO creating proposals + voting contract, create documentation| 4-5 weeks | - | $11200
4- Front-end Governance mechanisms. | Create, view and vote on active proposals; create documentation | 4-5 weeks | -  | $11200
5- Adoption  | 5 teams | -  |- | $7500
Maintenance | Resolving issues and fixing bugs | 3 months | -| $ 10000

</div></b>
</body>
</html>
  
## # Team

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-1d3f353f-7fff-e6af-782f-f586e9b59cc2"><div dir="ltr" style="margin-left:0pt;" align="left">

Name | Role | Bio | Contact
-- | -- | -- | --
Noah Naizir | Blockchain Developer  Cadence| Frontend & backend  | itahand.naizir@gmail.com
Reyane Remache | Frontend Developer |  Frontend & Cadence Developer | reyane.a.remache@gmail.com
Emmanuel Douaud | Full stack developer | MBA, MAster Computer Science, Artificial intelligence | emmanuel.douaud@gmail.com

</div><br /></b>
</body>
</html>

**Comment by chrisackermann** [comment]
Thanks for submitting, @Blockversity!  We're reviewing your proposal and will get back to you shortly.

**Comment by Blockversity** [comment]
We are looking forward to hearing from you.  We are, of course, available if you have questions.  
Line (BlockVersity Founder)

**Comment by chrisackermann** [comment]
Hi @Blockversity, we just wanted to let you know that we've accepted your proposal.  We'll follow up directly via email on next steps.  Thanks!
